### ISSUE TITLE
[BUG-REPORT] Empty Unmasked Indices in Masked Columns Throw Numpy Error

### ISSUE THREAD

**Issue by kmcentush** [vaexio/vaex#1001]
**Description**
In some rare edge cases, line 199 of `column.py` in vaex core throws a numpy error `ValueError: zero-size array to reduction operation minimum which has no identity`. This is because the `unmasked_indices` is an empty list.

I ran into this error after attempting a join where there were no overlapping indices.

It's possible that this error is also present in other `column.py` functions, but I didn't check.

Subset of the `__getitem__` function (that contains the offending line):
```
def __getitem__(self, slice):
        start, stop, step = slice.start, slice.stop, slice.step
        start = start or 0
        stop = stop or len(self)
        assert step in [None, 1]
        indices = self.indices[start:stop]
        ar_unfiltered = self.column
        if self.masked:
            mask = indices == -1
        if isinstance(ar_unfiltered, Column):
            # TODO: this is a workaround, since we do not require yet
            # that Column classes know how to deal with indices, we get
            # the minimal slice, and get those (not the most efficient)
            if self.masked:
                unmasked_indices = indices[~mask]  # <-- can return an empty list if all indices are masked
                i1, i2 = np.min(unmasked_indices), np.max(unmasked_indices)  # <-- the offending line!
            else:
                i1, i2 = np.min(indices), np.max(indices)
            ar_unfiltered = ar_unfiltered[i1:i2+1]
            if self.masked:
                indices = indices - i1
            else:
                indices = indices - i1
            ...
```

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
```
{'vaex': '4.0.0.dev0',
 'vaex-core': '4.0.0a3',
 'vaex-viz': '0.5.0.dev0',
 'vaex-hdf5': '0.7.0a1',
 'vaex-server': '0.4.0.dev0',
 'vaex-astro': '0.8.0.dev0',
 'vaex-ui': '0.3.0',
 'vaex-jupyter': '0.6.0.dev0',
 'vaex-ml': '0.11.0a3',
 'vaex-arrow': '0.5.1',
 'vaex-graphql': '0.2.0.dev0'}
```
 - Vaex was installed via: pip
 - OS: Windows 10

**Additional information**
I've tried to create a reproducible example for over two hours now, and I still can't do it by starting with vaex.from_arrays(). However, I was able to reproduce the error by exporting my actual data to CSV, obfuscating it, and reading it into a vaex df. Please see the attached .zip with a jupyter notebook and data that illustrates the problem: [dt2.zip](https://github.com/vaexio/vaex/files/5330490/dt2.zip).

I'm starting to think that the issue may stem from some underlying dtype issue. Despite both `dt2` and `dt3` in my notebook having the same dtypes, their outputs look different. Note the apostrophes around the strings in `dt2`:
![image](https://user-images.githubusercontent.com/20652336/95139089-8a906980-0720-11eb-919b-0076dc3ddb98.png)

**Comment by kmcentush** [comment]
One hacky workaround is to do ```dt2 = vx.from_arrow_table(dt2.to_arrow_table())``` prior to joining. I presume the dtypes under the hood are different?

**Comment by sheetalakadam** [comment]
I am getting the same error when doing left or right joins. But inner join works. The dtypes seem to match too.
