### ISSUE TITLE
How to set index ? 

### ISSUE THREAD

**Issue by ttpro1995** [vaexio/vaex#1012]
df.set_index just don't work. 

How to set index ?

**Comment by JovanVeljanoski** [comment]
Hi

Vaex doesn't a dedicated index column for now. Maybe you could explain why you need an index, or a give us a minimal example.

Also please go through the tutorial on the doc page to get a sense of the basics of vaex

Thanks!

**Comment by ttpro1995** [comment]
I am converting some pandas code from other guy to vaex to speed up stuff. He use index in his code. However, I managed to make it work without index (for example: join with left_on and right_on instead of index)
