### ISSUE TITLE
[Feature request] Insert a column with constant value 

### ISSUE THREAD

**Issue by ttpro1995** [vaexio/vaex#1019]
I would like a function to add new columns with constant value.
Preferable similar to `pandas.DataFrame.insert`. However, adding a new column is enough. 

![image](https://user-images.githubusercontent.com/7196876/96822228-c717d100-1453-11eb-9a50-d530854a67ee.png)

As my current workaround in Vaex. 

```
[df_vaex = df_vaex.extract() # require if there are filter apply on df_vaex 
df_vaex["e"] = np.repeat("five", df_vaex.shape[0])
```

![image](https://user-images.githubusercontent.com/7196876/96822594-a2702900-1454-11eb-9db9-63e40614caf1.png)

The problem here is that **.extract()** give a lot of memory footprint. It is seem that whole dataframe is save on RAM. 

`df_vaex["e"] = "five"` does not work, show weird error (is it bug ? More detail #1020)

**Comment by maartenbreddels** [comment]
Yeah, I like this idea.

**Comment by JovanVeljanoski** [comment]
Yeah, we've had a discussion on it before: https://github.com/vaexio/vaex/issues/455

There are also the variables, which is perhaps why we haven't thought about a constant column much before. But I agree it would be a nice addition to have.
