### ISSUE TITLE
[BUG-REPORT] Doc suggestion - explain where a csv->hdf5 converted file is stored (answer: the same folder as you read from)

### ISSUE THREAD

**Issue by ianozsvald** [vaexio/vaex#1022]
The docs would be clearer if https://vaex.readthedocs.io/en/latest/api.html#vaex.from_csv stated that if `convert=True` the HDF5 file is stored in the same folder that you read from, if you don't specify a path. Something like "If `convert==True` then the same folder as the source data is used to write the HDF5 file`. 
I wasn't sure what would happen until I tried it!

**Comment by JovanVeljanoski** [comment]
Indeed, the documentation should improve here, you are right. 

Is it ok to close this in favor of #1023 so to keep any discussion on csv->hdf5 stuff more focused and in one place?
