### ISSUE TITLE
[BUG-REPORT] Doc suggestion - note that if a file is _already_ converted, it won't be converted again

### ISSUE THREAD

**Issue by ianozsvald** [vaexio/vaex#1023]
Here I'd assumed that if I played around with `from_csv` and changed the arguments, I'd get updated versions of the converted file: https://vaex.readthedocs.io/en/latest/api.html#vaex.from_csv

The code however checks to see if the converted result exists and if so, it silently exits without updating the file: https://github.com/vaexio/vaex/blob/master/packages/vaex-core/vaex/__init__.py#L549

For reference I'm working with a CSV file that lacks headers `df = vaex.from_csv(RAW_DATA, copy_index=False, chunk_size=None, convert=True, parse_dates=['date'], names=COLUMNS) ` so my first pass lacked the `names` column, then I couldn't understand _why_ I didn't head headers on the next pass.

I'd suggest it might be clearer in the documentation that the file is converted once and ignored on subsequent calls. I've just spent 20 mins wandering the internals of Vaex before I realised what was going on :-)

**Comment by ianozsvald** [comment]
On reflection I'll suggest that if a user calls this function twice, they'll expect their data to be reprocessed. Possibly providing a flag to avoid this is sensible or maybe raise a "File Already Exists" exception (just as `os.makedirs` does if the target folder exists), but silently exiting without telling the user that the operation was short-circuited may confuse other new users. Thoughts?

**Comment by JovanVeljanoski** [comment]
Hi @ianozsvald 

Thanks for raising this. It is a good point. I do think that both the documentation and perhaps the function itself needs to change a bit. I was made in a different time and with a specific use-case in mind a think. 

We are having an internal discussion how to proceed. Any ideas / suggestions are welcome. 

I hope to have this improved in the next stable release.

**Comment by ianozsvald** [comment]
Perhaps a "from" function should just open what's there (maybe with a warning for non-performant choices) and a "convert" function should explicitly do the conversion?
I think guiding the first-time user from "here's how you get started, it isn't optimal but it works" to "and now we can drop a converted hdf5 file next to your original data" without surprises (i.e. clearer docs and a function that doesn't contain a caching surprise) will ease new people into Vaex. 
Thanks for following up :-)

**Comment by maartenbreddels** [comment]
Hi Ian,

I agree with @JovanVeljanoski we should have better docs for this. I think thing, that if we cache, we should cache based on the argument of the functions and the mtime (time of last modification) of the file, and provide a `convert_force=True` override or something.

Regards,

Maarten

**Comment by JovanVeljanoski** [comment]
I was thinking more along the lines of adding a `overwrite=False` (default) argument. If false, and the file is already converted, it will read that, and display a info message saying "file already converted, reading from cache", something like that. 

If overwrite is True, it would force reading and exporting the CSV each time (and if a converted file is there, it will overwrite it). 

What do you think about this?

**Comment by maartenbreddels** [comment]
yes, but that doesn't change the fact that if you change the parameter of the function, that it should never use the cache.

So we should store what the used arguments of from_csv were, and if they changed, _or_ if the mtime changed, _or_ overwrite is True, we should ignore the cached hdf5 file. Does that sound right?

**Comment by maartenbreddels** [comment]
This should be fixed in #1055 and #1040, the docs now say:
https://vaex.io/docs/api.html#vaex.open
`convert – Uses dataframe.export when convert is a path. If True, convert=path+'.hdf5' The conversion is skipped if the input file or conversion argument did not change.`

Basically, we cache it when we can, if something changes (input file or argument) we will overwrite it.

**Comment by ianozsvald** [comment]
Great to see, thanks
