### ISSUE TITLE
KeyError: 'ordered_set_datetime64[s]'

### ISSUE THREAD

**Issue by psmgeelen** [vaexio/vaex#1024]
Hi there, 
I am trying to execute: `df.groupby(by=["column1", "column2", "timestamp"], agg="mean")` where column 1 and 2 are strings and the timestamp is datetime64[s]. The value is a float64. I get the following error:

`KeyError: 'ordered_set_datetime64[s]'`

#### Similar Case:
https://github.com/vaexio/vaex/issues/408

I noticed that there is something like: `vaex.BinnerTime()`. Can I use this together with other categorical variables? What would the code look like!

#### Background details:
Im running on: 
'vaex-core': '2.0.3',
 'vaex-viz': '0.4.0',
 'vaex-hdf5': '0.6.0',
 'vaex-server': '0.3.1',
 'vaex-astro': '0.7.0',
 'vaex-jupyter': '0.5.2',
 'vaex-ml': '0.9.0',
 'vaex-arrow': '0.5.1'
and the data is stored in a HDF5 file. Its large (75 GB, 1.14 billion rows). I am running this in a jupyter-notebook on Linux (Ubuntu 20.10) and installed vaex through conda. 

I am new to posting bugs, so some feedback on my reporting woud be terrific too. 

Thanks in advance!

**Comment by maartenbreddels** [comment]
Hi Pieter,

this sounds like a bug from our side. I'll look into it, I think it should be easy to fix.

Regards,

Maarten

**Comment by pjgao** [comment]
same error occured when groupby multi columns with string and datetime

**Comment by psmgeelen** [comment]
Any news?

**Comment by krishancaldwell** [comment]
Hi, I've also just run into this issue. Any word on a fix?

**Comment by maartenbreddels** [comment]
@JovanVeljanoski if you can make a test for this, I think I can fix this quite fast.
