### ISSUE TITLE
[BUG-REPORT] export_hdf5 output incorrect for all-string based dataframe

### ISSUE THREAD

**Issue by EvansYang-77** [vaexio/vaex#1025]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your problem may already be discussed or addressed.

**Description**
I did the following 4 steps: 
1. Create a data frame using Pandas with strings for all columns (see to the attached [CSV)]
[Attr.zip](https://github.com/vaexio/vaex/files/5444128/Attr.zip)
2. Convert to the vaex dataframe by using from_pandas. i.e.
vx_df=vaex.from_pandas(attr_df, copy_index=False)
3. Export the vaex dataframe by using export_hdf5. i.e.
vx_df.export_hdf5(filepath)
4. Open the hdf5 by using vaex.open. i.e.
vaex_df=vaex.open(filepath)
The result is that column of data shifted by rows. 
Correct result:
![image](https://user-images.githubusercontent.com/73524195/97280491-4dc71680-1877-11eb-8d73-495104625fe6.png)
Wrong result:
![image](https://user-images.githubusercontent.com/73524195/97280534-60415000-1877-11eb-9dc9-e524484987f2.png)

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: 
![image](https://user-images.githubusercontent.com/73524195/97280605-73ecb680-1877-11eb-8faf-6ed376c9e07f.png)
 - Vaex was installed via: pip / conda-forge / from source : via pip
 - OS: windows10

**Additional information**
Please state any supplementary information or provide additional context for the problem (e.g. screenshots, data, etc..).

**Comment by JovanVeljanoski** [comment]
Hi @EvansYang-77 

Thanks for reaching out and for providing example data. 

I am afraid I am not seeing any issue here.. in the 2nd screenshot printed lines are wrapped, but that's pretty much it?

I tried to reproduce it with the data you sent me and I can't notice any problems:
<img width="648" alt="image" src="https://user-images.githubusercontent.com/18574951/97369706-b7621780-18ad-11eb-96b6-90684e3393ac.png">

Can you maybe explain a bit better what is going wrong at your end?

Cheers, 
J.

**Comment by EvansYang-77** [comment]
hi Jovan,
Thank you very much for your quick feedback. Yes, I tried Jupyter today and get the correct result. 
![image](https://user-images.githubusercontent.com/73524195/97383378-69c6c880-1908-11eb-8d2a-8a9bbee8c468.png)
However, when I use Spyder 4.0.1. I even can't find the vaex.open function. Something is wrong there. 
![image](https://user-images.githubusercontent.com/73524195/97383431-8ebb3b80-1908-11eb-83dc-0364f076a164.png)
![image](https://user-images.githubusercontent.com/73524195/97383542-d5109a80-1908-11eb-81e6-730e7aa0af77.png)

Best regards,
Evans Yang

**Comment by JovanVeljanoski** [comment]
Hi, 

This is unrelated to vaex. Probably your IDE assume certain python environment in which vaex is not installed, or not read in correctly.

**Comment by EvansYang-77** [comment]
Hi Jovan, 

Got it. I found I have another vaex.py in the same folder. That's why the function was not working. Thanks a lot!

Best regards,
Evans Yang
