### ISSUE TITLE
[BUG-REPORT] export_arrow failure when using django-q - OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by ajstewart** [vaexio/vaex#1029]
**Software information**
 - Vaex version: {'vaex': '3.0.0',
 'vaex-core': '2.0.3',
 'vaex-viz': '0.4.0',
 'vaex-hdf5': '0.6.0',
 'vaex-server': '0.3.1',
 'vaex-astro': '0.7.0',
 'vaex-jupyter': '0.5.2',
 'vaex-ml': '0.9.0',
 'vaex-arrow': '0.5.1'}
 - Vaex was installed via: pip
 - OS: macOS 10.14.6

I'm not sure if this is a bug but rather expected behaviour. In any case I have a Django project where I'm using [Django Q](https://django-q.readthedocs.io/en/latest/) to run scheduled jobs. These jobs are sent to the Django Q cluster asynchronously. In the job I have a minor usage of vaex where it is being used to firstly read in a DataFrame from an existing pandas dataframe, and then export this to arrow, so very simply:
```
    measurements = vaex.from_pandas(measurements)
    outname = os.path.join(p_run.path, 'measurements.arrow')
    measurements.export_arrow(outname)
```
This fails when using Django Q as per the error at the end.

It runs successfully when the process is run outside of the DjangoQ queue, and from looking at the error I'm guessing something is being conflicted as I see `asyncio` is being used.

I'm wondering if there is a way around this to enable the export to work?

Error:
```
01:13:33 [Q] ERROR Failed [parallel-assoc-newmany-UI] - Processing error:
[Errno 9] Bad file descriptor : Traceback (most recent call last):
  File "/Users/adam/GitHub/vast-pipeline/vast_pipeline/management/commands/runpipeline.py", line 91, in run_pipe
    create_measurements_arrow_file(p_run)
  File "/Users/adam/GitHub/vast-pipeline/vast_pipeline/pipeline/utils.py", line 1212, in create_measurements_arrow_file
    measurements.export_arrow(outname)
  File "/Users/adam/anaconda3/envs/vast-pipeline-dev/lib/python3.6/site-packages/vaex/dataframe.py", line 5766, in export_arrow
    vaex_arrow.export.export(self, path, column_names, byteorder, shuffle, selection, progress=progress, virtual=virtual, sort=sort, ascending=ascending)
  File "/Users/adam/anaconda3/envs/vast-pipeline-dev/lib/python3.6/site-packages/vaex_arrow/export.py", line 26, in export
    table = _export_table(dataset, column_names, byteorder, shuffle, selection, progress, virtual, sort, ascending)
  File "/Users/adam/anaconda3/envs/vast-pipeline-dev/lib/python3.6/site-packages/vaex_arrow/export.py", line 89, in _export_table
    values = dataset[column_name].evaluate(selection=selection)
  File "/Users/adam/anaconda3/envs/vast-pipeline-dev/lib/python3.6/site-packages/vaex/expression.py", line 695, in evaluate
    return self.ds.evaluate(self, i1, i2, out=out, selection=selection, parallel=parallel)
  File "/Users/adam/anaconda3/envs/vast-pipeline-dev/lib/python3.6/site-packages/vaex/dataframe.py", line 2616, in evaluate
    return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, internal=internal, parallel=parallel, chunk_size=chunk_size)
  File "/Users/adam/anaconda3/envs/vast-pipeline-dev/lib/python3.6/site-packages/vaex/dataframe.py", line 5377, in _evaluate_implementation
    df.map_reduce(assign, lambda *_: None, expressions, ignore_filter=False, selection=selection, pre_filter=use_filter, info=True, to_numpy=False)
  File "/Users/adam/anaconda3/envs/vast-pipeline-dev/lib/python3.6/site-packages/vaex/dataframe.py", line 332, in map_reduce
    return self._delay(delay, task)
  File "/Users/adam/anaconda3/envs/vast-pipeline-dev/lib/python3.6/site-packages/vaex/dataframe.py", line 1463, in _delay
    self.execute()
  File "/Users/adam/anaconda3/envs/vast-pipeline-dev/lib/python3.6/site-packages/vaex/dataframe.py", line 315, in execute
    just_run(self.execute_async())
  File "/Users/adam/anaconda3/envs/vast-pipeline-dev/lib/python3.6/site-packages/vaex/asyncio.py", line 35, in just_run
    return loop.run_until_complete(coro)
  File "/Users/adam/anaconda3/envs/vast-pipeline-dev/lib/python3.6/site-packages/nest_asyncio.py", line 89, in run_until_complete
    self._run_once()
  File "/Users/adam/anaconda3/envs/vast-pipeline-dev/lib/python3.6/site-packages/nest_asyncio.py", line 113, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/adam/anaconda3/envs/vast-pipeline-dev/lib/python3.6/selectors.py", line 577, in select
    kev_list = self._kqueue.control(None, max_ev, timeout)
OSError: [Errno 9] Bad file descriptor
```

**Comment by maartenbreddels** [comment]
Hi,

thanks for the report. Can I ask why you are using Vaex for this (out of curiosity)?

Indeed, we're using asyncio, together with https://pypi.org/project/nest-asyncio/ which sometimes bites other asyncio frameworks (for tornado we have a solution). Could you make it easy for me to reproduce this?
A workaround, would be to spawn this in a new thread, so there is no existing ioloop, and we don't have to use nest-asyncio.
Something along the lines of :
```python
def vaex_task():
  df.export(...)

with concurrent.futures.ThreadPoolExecutor(1) as executor:
  await result = await loop.run_in_executor(executor, vaex_task)
```

cheers,

Maarten

**Comment by ajstewart** [comment]
Hi, thanks for the response.

> thanks for the report. Can I ask why you are using Vaex for this (out of curiosity)?

I did wonder if I should have explained that bit. The file being produced is with the direct intention of being explored later on with vaex itself, hence I ended up using vaex to export the arrow file to ensure compatibility. This was because I had encountered a few issues when trying to load/convert the data into a format that can be memory mapped by vaex.

The dataframe is originally scattered over multiple parquet files, in short the issues I had were:
* vaex taking a very long time to open multiple files (Using `open_many()`, even arrow files, say about 700 files with 3k - 5k rows each)
* vaex not supporting memory mapping parquet format which negated the advantage of using vaex
* and also the dataframe also contains datetimes which I also had problems with (for which there are already quite a few open issues on this point, I think I had datetime issues when I tried to convert the parquet to arrow using pyarrow).

There are issues open on the other points as well when I had searched.

So with all the above I took the decision to just let vaex itself do the conversion from the combined pandas dataframe (actually using dask to open all the parquets as it was faster) during the processing so I didn't have to worry about it later.

> Indeed, we're using asyncio, together with https://pypi.org/project/nest-asyncio/ which sometimes bites other asyncio frameworks (for tornado we have a solution). Could you make it easy for me to reproduce this?
> A workaround, would be to spawn this in a new thread, so there is no existing ioloop, and we don't have to use nest-asyncio.
> Something along the lines of :
> 
> ```python
> def vaex_task():
>   df.export(...)
> 
> with concurrent.futures.ThreadPoolExecutor(1) as executor:
>   await result = await loop.run_in_executor(executor, vaex_task)
> ```
> 
> cheers,
> 
> Maarten

Ok thanks I'll look to see if I can incorporate this to see if it would solve the issue. And yes apologies for the lack of reproducible information - I'll try and see if I can boil this down to a simple example.

**Comment by maartenbreddels** [comment]
You might want to try vaex-core alpha `pip install vaex-core==4.0.0a4`

> * vaex taking a very long time to open multiple files (Using `open_many()`, even arrow files, say about 700 files with 3k - 5k rows each)

This should me much improved.




> * vaex not supporting memory mapping parquet format which negated the advantage of using vaex

Parquet support is much better in the alpha (out of core), but will always be slower than arrow of hdf5, unless you have slow storage (network, or spinner drive).



> * and also the dataframe also contains datetimes which I also had problems with

Yeah, definitely something we want to focus on after the 4.0 release.

Let us know how it goes.

cheers,

Maarten

**Comment by ajstewart** [comment]
Thanks for that - it looks like the 4.0.0-alpha has addressed all these problems as you say and will let me avoid the process that I was doing that lead to this error altogether. This is great!

I noticed some of the other vaex packages had conflict issues when installing the alpha core, is there an overall alpha package? As it's alpha I guess not at this stage, maybe I'll look to see what ones I can drop.

I'll still attempt to get an example of the original problem.

**Comment by maartenbreddels** [comment]
I'm assuming the issue is solved, if not please reopen or open a new issue.
