### ISSUE TITLE
[BUG-REPORT] export_hdf5 output incorrect for a self-generated dataframe

### ISSUE THREAD

**Issue by EvansYang-77** [vaexio/vaex#1041]
**Description**
hi there, 
I found export_hdf5 can generate wrong format hdf5 file. Please try the following python code. 
[GenAttr.zip](https://github.com/vaexio/vaex/files/5486290/GenAttr.zip)
The correct data frame shall be:
![image](https://user-images.githubusercontent.com/73524195/98085260-057fa800-1eb8-11eb-9d20-562e476cac1c.png)
The output hdf5 will return to be like this:
![image](https://user-images.githubusercontent.com/73524195/98084219-74f49800-1eb6-11eb-98dc-af7636ff3248.png)

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:  
![image](https://user-images.githubusercontent.com/73524195/98085182-eb45ca00-1eb7-11eb-951d-1834321e59af.png)
 - Vaex was installed via: pip
 - OS: windows10

**Additional information**
Please state any supplementary information or provide additional context for the problem (e.g. screenshots, data, etc..).

**Comment by JovanVeljanoski** [comment]
Hi, 

I ran your code and things look fine. I can't reproduce the problem. Perhaps it is something wrong with your environment or the IDE where you are displaying the output. I tried this in an ipython terminal, vscode, and jupyter notebook, and I get the correct results. 

Please make sure that you don't have line wraps or something like that. 
You can also try things like adding `assert vaex_df.A.tolist() == vx_df.A.tolist()` at the end of your script to make sure things are the same. I would be quite surprised if they are not. 

Note: vaex for  python3.8 is still not supported for windows..

**Comment by EvansYang-77** [comment]
hi Jovan,

Thank you very much for the feedback. I'm using Python 3.8. Maybe that's the reason. Let me test it again by using Jupyter and Python3.7. 

Best regards,
Evans Yang

**Comment by JovanVeljanoski** [comment]
will close as stale. Please re-open if needed.
