### ISSUE TITLE
export_hdf5  crashes and generate not readable file

### ISSUE THREAD

**Issue by salwaen** [vaexio/vaex#1042]
Hi, 

sometime exprt_hdf5 crashes and generate not readable file [65](https://github.com/vaexio/vaex/issues/65)
````
 >>vaex_df.export_hdf5(1104_15_15.hdf5, progress=True)

  Process  finished with exit code -1073741819 (0xC0000005) 

>> df = vaex.open('1104_15_15.hdf5')
Could not open file: c:/tmp/1104_15_15.hdf5, did you install vaex-hdf5? Is the format supported?
````
 
**Software information**

#### Python: 3.6

**Comment by JovanVeljanoski** [comment]
Hi @salwaen 

That is very strange indeed. Can you perhaps try the latest alpha is possible?

Also is it possible to get some information on the data you are trying export it: what it contains (dtypes), are there missing values, how did you create it etc..

Can you try to export a smaller version of your dataframe and see if that works? If you can make/create a reproducible example with some fake (or real, if allowed) data that would help us greatly to identify the problem.

Note: exporting things like lists, dicts is currently not supported, so watch out of that one (mentioning it just in case).

Another thing to try, maybe try a brand new environment? This is well tested as far as I know, but some edge cases are of course always possible.

**Comment by salwaen** [comment]
Hi @JovanVeljanoski 

thanks for the quick reply und the great work,

i have two functions one write the data to the file
````
df =pd.read_sql_query()
df_vaex = vaex.from_pandas(dataframe, copy_index=False)
df_vaex.export_hdf5("my_file.hdf5",  progress=True)
````
another function read the file
````
   my_df = vaex.open("my_file.hdf5")

````
dtypes 

A    datetime64[ns]
B               int64
C              string

i installed vaex-core==4.0.0a5 but it doesn't help. in OS Ubuntu the code works without errors
with start debug mode in OS windows  the debugger stoped in execution.py  :
````
 async def execute_async(self):
        logger.debug("starting with execute")

        with self.lock:  # setup thread local initial values
            if not hasattr(self.local, 'executing'):
                self.local.executing = False

        # wo don't allow any thread from our thread pool to enter (a computation should never produce a new task)
        # and we explicitly disallow reentry (this usually means a bug in vaex, or bad usage)
        chunk_executor_thread = threading.current_thread() in self.thread_pool._threads
        import traceback
        trace = ''.join(traceback.format_stack())
        if chunk_executor_thread or self.local.executing:
            logger.error("nested execute call")
            raise RuntimeError("nested execute call: %r %r\nlast trace:\n%s\ncurrent trace:\n%s" % (chunk_executor_thread, self.local.executing, self.local.last_trace, trace))

````
maybe help you!

**Comment by JovanVeljanoski** [comment]
Ah so the issue is only for windows - for linux (ubuntu) you do not have the same problem - is that correct?

Interesting.. Is there more information that you can give us on the data, are there missing values in any of the columns for example? 

I do not have an access to a windows machine, but will try to look into it. Maybe @maartenbreddels can offer some insight into this.

**Comment by salwaen** [comment]
yes, it is only for windows.
instead  of  `df =pd.read_sql_query()`  i tested  this in my code 

''''
#df =pd.read_sql_query()
x = np.arange(5)
y = x**2
df = vaex.from_arrays(x=x, y=y)
df_vaex.export_hdf5("my_file.hdf5",  progress=True)

''''
the file is readable but it craches during export.

**Comment by salwaen** [comment]
Hi,

i tested again with the debugger `df_vaex.export_hdf5("my_file.hdf5",  progress=True)`  give this error
````
RuntimeError: Second simultaneous read on fileno 3436 detected.  Unless you really know what you're doing, make sure that only one greenthread can read any particular socket.  Consider using a pools.Pool. If you do know what you're doing and want to disable this error, call eventlet.debug.hub_prevent_multiple_readers(False) - MY THREAD=<function select.<locals>.on_read at 0x00000142811452F0>; THAT THREAD=FdListener('read', 3436, <function select.<locals>.on_read at 0x000001425C4976A8>, <built-in method throw of greenlet.greenlet object at 0x000001426AFB6CC0>)
2020-11-06 15:19:10,946 vaex.execution [ERROR] nested execute call

Process finished with exit code -1073741819 (0xC0000005)
````
and   `len(df_vaex)` give this error 

````
File "C:\my_folder\my_file.py", line 939, in my_def
    if len(dataframe):
  File "C:\my_folder\venv\lib\site-packages\vaex\dataframe.py", line 3836, in __len__
    self. _cached_filtered_length = int(self.count())
  File "C:\my_folder\venv\lib\site-packages\vaex\dataframe.py", line 769, in count
    return self._compute_agg('count', expression, binby, limits, shape, selection, delay, edges, progress, array_type=array_type)
  File "C:\my_folder\venv\lib\site-packages\vaex\dataframe.py", line 743, in _compute_agg
    return self._delay(delay, var)
  File "C:\my_folder\venv\lib\site-packages\vaex\dataframe.py", line 1507, in _delay
    self.execute()
  File "C:\my_folder\venv\lib\site-packages\vaex\dataframe.py", line 344, in execute
    just_run(self.execute_async())
  File "C:\my_folder\venv\lib\site-packages\vaex\asyncio.py", line 35, in just_run
    return loop.run_until_complete(coro)
  File "C:\my_folder\venv\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    self._run_once()
  File "C:\my_folder\venv\lib\site-packages\nest_asyncio.py", line 113, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\######\AppData\Local\Programs\Python\Python36\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\######\AppData\Local\Programs\Python\Python36\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
  File "C:\my_folder\venv\lib\site-packages\eventlet\green\select.py", line 76, in select
    listeners.append(hub.add(hub.READ, k, on_read, current.throw, lambda: None))
  File "C:\my_folder\venv\lib\site-packages\eventlet\hubs\hub.py", line 181, in add
    evtype, fileno, evtype, cb, bucket[fileno])
RuntimeError: Second simultaneous read on fileno 3428 detected.  Unless you really know what you're doing, make sure that only one greenthread can read any particular socket.  Consider using a pools.Pool. If you do know what you're doing and want to disable this error, call eventlet.debug.hub_prevent_multiple_readers(False) - MY THREAD=<function select.<locals>.on_read at 0x000001C5076E8D08>; THAT THREAD=FdListener('read', 3428, <function select.<locals>.on_read at 0x000001C4FC124950>, <built-in method throw of greenlet.greenlet object at 0x000001C48D135CC0>)
2020-11-06 15:48:24,774 vaex.execution [ERROR] nested execute call

````
thank you again for all your support

**Comment by JovanVeljanoski** [comment]
Hi, 

Thanks for the reports. Are you running all of this inside PyCharm btw? If so, can you please try running it in ipython or just as a python script that is not executed via PyCharm. 

We've had various random issues with PyCharm before, so just making sure that is not it.

Thanks.

**Comment by salwaen** [comment]
>   Are you running all of this inside PyCharm

Yes , and  I think the problem is in PyCharm for Windows,  my code runs in linux and docker without problems.
and i get it after update to `vaex-core==4.0.0a3`

**Comment by JovanVeljanoski** [comment]
There is a new alpha btw `vaex-core==4.0.0a5` so can also try that.

See if your code runs on Windows as well (it should) just don't run it via PyCharm. Maybe the environments are somehow mixed in PyCharm, i don't really know I've never used it.

**Comment by salwaen** [comment]
Hi @JovanVeljanoski ,

 Cleaning system cache for PyCahrm solved the issue. [https://www.jetbrains.com/help/pycharm/cleaning-system-cache.html](hier)
Thanks.
