### ISSUE TITLE
[FEATURE-REQUEST] Implementing pandas read_fwf

### ISSUE THREAD

**Issue by MordicusEtCubitus** [vaexio/vaex#1047]
Hi,

Is it possible to implement a `from_fwf` method based on pandas [read_fwf](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_fwf.html) to allow reading of fixed width fields files ?

Thanks in advance,
BTW : I've added a comment in closed question #1044 to get explanation about how updating the doc. Not sure you see it as it is closed.

**Comment by JovanVeljanoski** [comment]
Hi, 

Pandas opens a lot of different file formats. It is rather easy pass this to vaex:
```
import vaex
import pandas as pd

pdf = pd.read_fwf(...)
df = vaex.from_pandas(pdf)
```

Does this make sense?

**Comment by MordicusEtCubitus** [comment]
Indeed it will do it.

But, I was expecting a behaviour more cleaver as for `from_csv` with files that do not fit in RAM:

> If the CSV file is so large that it can not fit into RAM all at one time, one can convert the data to HDF5 simply by:
> `df = vaex.from_csv('./my_data/my_big_file.csv', convert=True, chunk_size=5_000_000)`

**Comment by JovanVeljanoski** [comment]
This is not hard to do it yourself:

```
for i, tmp_df in pd.read_fwf(... chunks=10_000):  # if this is supported in pandas, I guess it should be
    df = vaex.from_pandas(tmp_df, copy_index=False)
    df.export_hdf5(f'chunk-{i}.hdf5')

df_final = vaex.open('chunk-*.hdf5')
```

We do not have the bandwidth to do this for every single io method that pandas provides, but the above should be simple enough pattern that users should be able to do themselves without any trouble. CSV is so common that we decided to make it a bit more convenient. 

If you are happy to contribute this, that would be great! Some conversation might be needed on how to structure things with already existing code but I don't see a major blocker. Let us know!

You can also do your own [extension](https://vaex.io/docs/tutorial.html#Extending-Vaex) if this is common for your workflow.
