### ISSUE TITLE
Assertion Error when dropping columns from df

### ISSUE THREAD

**Issue by ma9az** [vaexio/vaex#1057]
The columns params of the df.drop() function is not being recognised as expression when its value is provided as a list of the column names.

**Comment by JovanVeljanoski** [comment]
Hi, 

I can not reproduce this issue (see below). Can you please provide a reproducible example?

Cheers .

<img width="809" alt="image" src="https://user-images.githubusercontent.com/18574951/99182183-b2b5b400-2733-11eb-9db9-e4126dd822f2.png">

**Comment by JovanVeljanoski** [comment]
Closed as stale.. please re-open if needed.
