### ISSUE TITLE
Save Figures, removing titles, dpi

### ISSUE THREAD

**Issue by sevamoo** [vaexio/vaex#106]
Hey, sorry for these basic questions:
1- In ds.plot_widget() is there a way to save the figures with a certain dpi?
2- in ds.plot() is there a way to remove title, colorbar at the same time? 
3- in ds.plot() is there a way to remove axes completely with no empty space? 
4- in 2d plots is there a way to have transparent backgrounds rather than black for example. I mean those areas with no data set, I see that the value is considered 0 and then black for example, but is there any way to have them as nan values?

I apologize putting several questions under one issue.

I am trying to put the saved images to a 3d webGl render. 

Thanks a lot.

**Comment by maartenbreddels** [comment]
Hi Vahid,

> I apologize putting several questions under one issue.

Not a problem.

> 1- In ds.plot_widget() is there a way to save the figures with a certain dpi?

I guess you are using the (default) bqplot backend? You can access the internal figure by sth like:
```
obj = ds.plot_widget(...)
fig = obj.backend.figure
fig.save_svg()
```
The svg is vectorized (except the image vaex put in it is of a certain resolution.



> 2- in ds.plot() is there a way to remove title, colorbar at the same time?

What do you mean at the same time? `colorbar=False` will help, for the rest I'm just calling matplotlib, so afterward you can tweak it by fiddling with matplotlib.


> 3- in ds.plot() is there a way to remove axes completely with no empty space?

Again, that is matplotlib specific.



> 4- in 2d plots is there a way to have transparent backgrounds rather than black for example. I mean those areas with no data set, I see that the value is considered 0 and then black for example, but is there any way to have them as nan values?

Yes, by default NaN's are transparant, so if you do:
```
ds.plot('x', 'y', what='count(*)', f=log)
```
You will see transparancy where the counts are zero, since log(0) gives NaN (or is it -inf?).

If you do not want log scale, you could do sth like this:
```
shape = 256
limits = ds.limits(['x', 'y'])
grid = ds.count(limits=limits, binby=['x', 'y'], shape=shape)
grid[grid==0] = np.nan
ds.plot('x', 'y', grid=grid, limits=limits) # or call plt.imshow yourself
```



> I am trying to put the saved images to a 3d webGl render.

You want to have the 2d output visualized in 3d as a plane?
Just curious, since I also work on https://github.com/maartenbreddels/ipyvolume/


Hope my answers were useful!

cheers,

Maarten

**Comment by sevamoo** [comment]
Oh! Thanks a lot for such a quick reply! 
1) Amazing to have SVG option
2) If I remove colorplot the title will appear and the other way around, while clearly title is None. 
3) I thought so, but not working or maybe I did it in a wrong way.
4) Fantastic!
5) WebGL: I am working with data set with the range of 130M to 400M. What I do as a quick solution is this: https://sevamoo.github.io/3d/ but the image resolution was an issue from here on. 
I think the best solution would be to find a proper way to serve the data from backend. We discussed this in another issue, but I didn't manage that.

Thanks a lot.
Best
Vahid

**Comment by cloudlakecho** [comment]
@maartenbreddels Thanks for showing way to save figure in file. 
I try to run your snippet:
```
obj = ds.plot_widget(...)
fig = obj.backend.figure
fig.save_svg()

**Comment by rkpradhan** [comment]
@maartenbreddels How to save a vaex plot as a file  (e.g., png)? 
For eg. I would like to save this plot as a file (.png or .pdf);
df.plot("Lz", "E",
        limits='99.7%',
        z="fe_h:-3.0,-1,4", show=True, visual=dict(row="z"),
        figsize=(12,8), f="log", wrap_columns=2);

**Comment by JovanVeljanoski** [comment]
Hi @rkpradhan 

In this case `df.plot` is just a wrapper around matplotlib. So for your case, this would work quite nicely:

```
import vaex
import pylab as plt

df = vaex.example()

fig = plt.figure(figsize=(12, 8))
df.plot("Lz", "E", limits='99.7%', 
        z="FeH:-3.0,-1,4", show=True, visual=dict(row="z"),
        figsize=(12,8), f="log", wrap_columns=2)
fig.savefig('tmp.png', dpi=200, bbox_inches=0)
```

Hope this helps!

**Comment by rkpradhan** [comment]
@JovanVeljanoski Thank you very much for sharing. This code worked perfectly.
