### ISSUE TITLE
How do I tell vaex to use multiple CPU cores?

### ISSUE THREAD

**Issue by aburkov** [vaexio/vaex#1074]
I run the following code:

```
df = vaex.open('s3://...parquet')

df = df[["original_description"]]

extractor = Extractor()# an external class that has the "match" method that extracts something from a given text inptut.

def extractor_function(input):
    return json.dumps(extractor.match(input))

df["keywords"] = df.apply(extractor_function, arguments=[df.original_description])

df.export_csv('/home/username/output_data.csv')
```

While it's running, I run the top command and observe that only one python process is running and it consumes one CPU core at 100% on a machine that has 8 CPU cores. I also don't see an increase in processing speed as compared to my previous machine that only had 2 cores.

I tried to open three parquet files using open_many, but the processing time tripled and only one CPU core was still used.

Is there a way to "tell" vaex to use multiple CPU cores?

**Comment by maartenbreddels** [comment]
If possible, vaex will use all cores. However, apply can never use more than 100% cpu, because of the GIL. I have thought of running apply in a process, possibly by using dask.
Were you expecting something like that to happen?

**Comment by aburkov** [comment]
In my case, extractor_function is called to extract keywords from each text document in the dataframe. extractor_function uses the library hyperscan. hyperscan applies regular expressions to each document in a very efficient way: it can match 100,000 regexes in a fraction of a millisecond.

If apply is not the best way to do that, how can I transform a row in a custom way (by applying some external Python module) without using apply?

**Comment by maartenbreddels** [comment]
The best way is to add a new function https://vaex.io/docs/tutorial.html#Adding-functions

instead of the apply, where each row will be fed into the Python function, this UDF will be called with an array (each thread will invoke it with a slice of the original column). If the function down the line accepts arrays (hyperscan), it should perform much better.

Let me know if you have trouble with this, happy to try this out myself. Hyperscan was on my list of libraries to use for the string regex in vaex, but we chose for PCRE instead.

If it does not accept an array, i may know of ways with numba to make that work.

**Comment by aburkov** [comment]
I implemented it this way:

```
extractor = Extractor()
@vaex.register_function()
def extractor_function(input):
    return extractor.MatchVectorized(input)

df["skills"] = df.original_description.extractor_function()
```

The method MatchVectorized of the "extractor" object takes an Arrow StringArray as input, iterates over its values, and then returns a numpy array of strings as output. I know that looping over elements in StringArray is not optimal either, but I expected to gain because multiple cores would be used in parallel.

I didn't get a parallelization effect: still, one core was used, and MatchVectorized received as input a StringArray of size     1048576. The code crashed at "return numpy.array(output)" with "MemoryError: Unable to allocate 105. GiB for an array with shape (1048576,) and data type <U26918"

where output is a list of strings of size 1048576.

I could not reduce 1048576 to anything smaller. The command df.executor.buffer_size = 10_000 doesn't give any effect.

**Comment by aburkov** [comment]
By the way, even if I modify buffer_size_default directly in execution.py like this:

`buffer_size_default = 1024 * 2  # TODO: this should not be fixed, larger means faster but also large memory usage`

That doesn't change anything. The size of 1048576 is still used because this is the value of "dataset.row_count" in line 164 of execution.py. Where does dataset.row_count come from and why this value 1048576 is used? My dataset is bigger than that, but I want it to be processed in smaller chunks than 1048576.

**Comment by maartenbreddels** [comment]
You are right, chunk_size was ignored (fixed in #1079)


> I know that looping over elements in StringArray is not optimal either, but I expected to gain because multiple cores would be used in parallel.

yeah, i checked the hyperscan python binding, and they release the GIL, so in theory that can go above 100% (and I did a small experiment to confirm it).


> I didn't get a parallelization effect: still, one core was used

I tried to make a mock version of what you want to do I think:
```python
import vaex
import pyarrow as pa
import numpy as np
import hyperscan

text = 'foafoxBAR' * 10

def do_extract(input):
    db = hyperscan.Database()
    patterns = (
        # expression,  id, flags
        (br'foa',      0,  0),
        (br'oa',       0,  0),
        (br'fo+',      0,  0),
        (br'^foobar$', 1,  hyperscan.HS_FLAG_CASELESS),
        (br'BAR',      2,  hyperscan.HS_FLAG_CASELESS
                           | hyperscan.HS_FLAG_SOM_LEFTMOST),
    )
    expressions, ids, flags = zip(*patterns)
    db.compile(
        expressions=expressions, ids=ids, elements=len(patterns), flags=flags
    )
    
    def record(expression_id, start, end, flags, context):
        records.append(text[start:end])
    results = []
    for i, text in enumerate(input.tolist()):
        records = []
        db.scan(text, record)
        results.append(records[i % len(records)])
    return pa.array(results)
    # also possible, but better to return as pyarrow string array (more mem efficient)
    # return np.array(results)


if __name__ == "__main__":
    # from multiprocessing import Pool
    # pool = Pool(5)  # in the 1gb docker, this requires too much memory, only 1 process works

    @vaex.register_function()
    def extractor_function(input):
        return do_extract(input)
        # use this to avoid the GIL
        # return pool.apply(do_extract, [input])

    df = vaex.from_arrays(original_description=pa.array([text] * 100_000, pa.string()))
    df["skills"] = df.original_description.extractor_function()


    df.executor.chunk_size = 1000
    # all exporters use the evaluate_iterator, sth like this:
    # this would return 10_000 row each time, and the executor will distribute this
    # in chunks of 1000, so it would use 10 cpu's max
    # for i1, i2, chunks in df.evaluate_iterator('skills', chunk_size=10_000):
    #     print(i1, i2)

    df.export('/tmp/test.csv', progress=True, chunk_size=10_000)
```
This gives me 220% cpu usage, because of the GIL. However, if I use the multiprocessing module, I get much higher CPU usage, but the forking of the process is costing a lot of memory.

**Comment by maartenbreddels** [comment]
I dug a bit into why I could not use multiple processes in the docker container, 2 reasons:

First, moving the memory allocation before the creation of the pool. I'm myself a bit surprised by it, since the forked processes shouldn't execute that code.

Second, it seems that the slices arrow array gets fully copied! So even though it's a small slice/view of the original large array, it gets fully serialized, causing a huge memory usage:

```python
if __name__ == "__main__":

    @vaex.register_function()
    def extractor_function(input):
        # return do_extract(input)
        # use this to avoid the GIL
        # make a copy with numpy, to avoid copying over underlying arrow buffer and cause an OOM problem
        return pool.apply(do_extract, [np.array(input)])

    print(f'{len(text)*100_000:,}')
    df = vaex.from_arrays(original_description=pa.array([text] * 100_000, pa.string()))
    df["skills"] = df.original_description.extractor_function()

    from multiprocessing import Pool
    pool = Pool(10)  # in the 1gb docker, this requires too much memory, only 1 process works

```

@JovanVeljanoski we should be thinking about implementing the multiprocessing in apply, and also write a section of mem usage and how the various chunk_size's play together.

**Comment by maartenbreddels** [comment]
This is just released, use:
```
$ pip install vaex==4.0.0a4
or for a minimal install.
$ pip install vaex-core==4.0.0a9
```
To use the `VAEX_CHUNK_SIZE` env var, or a working `df.executor.chunk_size = 1000`

**Comment by aburkov** [comment]
Thank you! I confirm that now chunk size can be reduced and I confirm that multiple instances of extractor_function, one per chunk, are running. However, CPU usage is significantly above 100% (~600%) mostly during the instantiation of the hyperscan object. Once hyperscan objects are created in each instance of the extractor_function, the CPU usage fluctuates between 100% and 120% and the chunks are processed as a sequence, one by one.

We implemented internally a temporary solution using multiprocessing.Pool and we see that it can effectively parallelize the processing between multiple cores. We see the processing speed increased roughly by the factor (1/2) x num_cores.

**Comment by maartenbreddels** [comment]
Cool, are these results with multiprocessing, or without?

**Comment by aburkov** [comment]
Our internal solution uses the multiprocessing module of Python. Vaex seems to use multithreading.

What I will try is to use vaex to generate batches for our internal multiprocessing-based solution.

**Comment by maartenbreddels** [comment]
Based on these results, I've added multiprocessing support in Vaex:
https://github.com/vaexio/vaex/pull/1080

```
import vaex
import pyarrow as pa
import numpy as np
import hyperscan

text = 'foafoxBAR' * 100


def do_extract(input):
    db = hyperscan.Database()
    patterns = (
        # expression,  id, flags
        (br'foa',      0,  0),
        (br'oa',       0,  0),
        (br'fo+',      0,  0),
        (br'^foobar$', 1,  hyperscan.HS_FLAG_CASELESS),
        (br'BAR',      2,  hyperscan.HS_FLAG_CASELESS
                            | hyperscan.HS_FLAG_SOM_LEFTMOST),
    )
    expressions, ids, flags = zip(*patterns)
    db.compile(
        expressions=expressions, ids=ids, elements=len(patterns), flags=flags
    )
    
    def record(expression_id, start, end, flags, context):
        records.append(text[start:end])
    results = []
    if isinstance(input, pa.ChunkedArray):
        input = input.to_pylist()
    else:
        input = input.tolist()
    for i, text in enumerate(input):
        records = []
        db.scan(text, record)
        results.append(records[i % len(records)])
    return pa.array(results)
    # also possible, but better to return as pyarrow string array (more mem efficient)
    # return np.array(results)


if __name__ == "__main__":

    print(f'{len(text)*100_000:,}')
    df = vaex.from_arrays(original_description=pa.array([text] * 100_000, pa.string()))
    # vectorize=True will make 1 call per chunk
    df['skills'] = df.original_description.apply(do_extract, vectorize=True, multiprocessing=True)


    df.executor.chunk_size = 100
    # all exporters use the evaluate_iterator, sth like this:
    # this would return 10_000 row each time, and the executor will distribute this
    # in chunks of 1000, so it would use 10 cpu's max
    # for i1, i2, chunks in df.evaluate_iterator('skills', chunk_size=100_000):
    #     print(i1, i2)

    df.export('/tmp/test.csv', progress=True, chunk_size=100_000)
```

Now gives me ~2200% CPU usage. 

Let me know if you're interested in testing/using this, I'll give you a ping when/if we release this.

**Comment by maartenbreddels** [comment]
apply is now parallel using multiprocessing #1080, and together with pickling #1090 gives other options as well.

apply docs: https://vaex.io/docs/tutorial.html#The-escape-hatch:-apply
