### ISSUE TITLE
[BUG-REPORT] Multiple selection filters broken in latest version

### ISSUE THREAD

**Issue by picoDoc** [vaexio/vaex#1076]
**Description**
I think I've found an issue with the new internal representation of arrays as arrow arrays.  This is in 4.0.0.dev0, so you might have a plan to fix it by the next proper release, but just flagging it anyway as it seems relatively major.

With a simple test table `data`:

```
import pandas as pd
import numpy as np
import vaex

data = pd.DataFrame({
  "A":np.array([1,2,3,4]),
  "B":["A","B","C","D"],
  "C":[np.datetime64('2019-10-07 09:00:00'),np.datetime64('2019-10-07 10:00:00'),np.datetime64('2019-10-07 11:00:00'),np.datetime64('2019-10-07 12:00:00')]
  })

vaex.from_pandas(data).export_arrow('arrow_sample.arrow')
data = vaex.open('arrow_sample.arrow')
```

Normal single clause filters work as you'd expect:

```
>>> data[(data['B'] == 'D')]
  #    A  B    C
  0    4  'D'  Timestamp('2019-10-07 12:00:00')
>>> data[(data['A'] > 2)]
  #    A  B    C
  0    3  'C'  Timestamp('2019-10-07 11:00:00')
  1    4  'D'  Timestamp('2019-10-07 12:00:00')
```

But when you combine multiple clauses the answer is wrong (this should return a single row):

```
>>> data[(data['B'] == 'D') & (data['A'] > 2)]
  #    A  B    C
  0    1  'A'  Timestamp('2019-10-07 09:00:00')
  1    2  'B'  Timestamp('2019-10-07 10:00:00')
  2    3  'C'  Timestamp('2019-10-07 11:00:00')
  3    4  'D'  Timestamp('2019-10-07 12:00:00')
```

I first noticed this using a much larger table, and in that case it seemed to cause a memory leak (process memory continually rose after the query)  I haven't been able to reliably reproduce this case though, so I'm just reporting the simple case above.  It seems likely they're the same bug with two different symptoms.  With vaex==3.0.0 the query above returns a single row as you'd expect, so I suspect maybe [this change](https://github.com/vaexio/vaex/pull/984/files) has caused the issue, although I don't know enough to say how?

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: `{'vaex': '4.0.0.dev0', 'vaex-core': '4.0.0a5', 'vaex-viz': '0.5.0.dev0', 'vaex-hdf5': '0.7.0a2', 'vaex-server': '0.4.0.dev0', 'vaex-astro': '0.8.0.dev0', 'vaex-ui': '0.3.0', 'vaex-jupyter': '0.6.0.dev0', 'vaex-ml': '0.11.0a4', 'vaex-graphql': '0.2.0.dev0'}`
 - Vaex was installed from source
 - OS: Ubuntu 18.04.4 LTS

**Comment by maartenbreddels** [comment]
Thanks for the report, indeed this was a bug in a special case for comparing strings

**Comment by maartenbreddels** [comment]
Just released this
```
try
$ pip install vaex-core==4.0.0a8
or
$ pip install vaex==4.0.0a2
```

**Comment by picoDoc** [comment]
great, thanks!
