### ISSUE TITLE
[FEATURE-REQUEST] scalable eigh computation natively in vaex

### ISSUE THREAD

**Issue by geoHeil** [vaexio/vaex#1086]
When calculating the PCA in https://github.com/vaexio/vaex/blob/5578f8a307f980651bf3390d10c8a9e0acf4315f/packages/vaex-ml/vaex/ml/transformations.py#L94 you first use https://github.com/vaexio/vaex/blob/923911f47e7324335dfd84bc58a14d4cd6eb7ee6/packages/vaex-core/vaex/dataframe.py#L1093 the vaex native scalable covariance calculation.

However, when computing the eigenvalues you resort to the default implementation of numpy:

```
eigen_values, eigen_vectors = np.linalg.eigh(C)
```

which has certain memory limitations and is crashing for me for a large matrix. Would it be possible to use `eigh` in a vaex optimized native way?

**Comment by JovanVeljanoski** [comment]
For a large matrix or for wide dataframes we recommend using `vaex.ml.PCAIncremental` which is wrapper around IncrementalPCA of scikit-learn. It works rather well with vaex. Would this help?

**Comment by JovanVeljanoski** [comment]
I will close this, please reopen if needed.
