### ISSUE TITLE
columns api ideas

### ISSUE THREAD

**Issue by xdssio** [vaexio/vaex#110]
1. columns and columns() should return a list of all columns virtual and not.
2. If you want to use column_names, then use also column_names() and in any case virtual columns should return.
3. add prefix= to the column_names() so it will be easy to get all columns from previous transformer.

**Comment by JovanVeljanoski** [comment]
Closed this as out-of-date.

Points 2 and 3 are done with with `df.get_column_names()` method which supports regex selection of columns.
