### ISSUE TITLE
[BUG-REPORT]Overflowing memory using a custom selection in df.count() in Vaex 4.0.0a5

### ISSUE THREAD

**Issue by HHKoppelman** [vaexio/vaex#1111]
Using `vaex: 4.0.0a5` I am having the issue that my memory is overflowing when I do a count of a selection that combines a `df.select()` selection with an expression. The MWE below crashes for me. The machine that I am running this on has 251G memory, reaches 100% of this and then crashes.

I am pretty sure that the bug arises from combining the named selection and the `(x>y)` expression.

```
import vaex
import numpy as np

x,y,z = np.random.normal(size=(3,10_000_000))

df = vaex.from_arrays(x=x,y=y,z=z)

df.select('x*y<z*z',name='tmp')

df.count(selection='(tmp)&(x>y)')
```

**Comment by maartenbreddels** [comment]
Thanks for the report Helper!

Note to myself for future reference. This one was tricky to track down, in docker, the OOM-killer makes it difficult to track where memory is allocated, an easier solution was to limit memory:
```
$ ulimit -Sv 100000000 
```
And then run this in a script, which gave:
```
  File "<string>", line 1, in <module>
  File "/home/maartenbreddels/github/vaexio/vaex/packages/vaex-core/vaex/arrow/numpy_dispatch.py", line 122, in operator
    result_data = op['op'](a_data, b_data)
MemoryError: Unable to allocate 1.00 MiB for an array with shape (1048576,) and data type bool
```

Where `a_data` was a bool (not an array), and op was `&`. Appearently the tmp selection (a in this case) was not wrapped, while the 
right hand side (b, or `x > y`) was wrapped. This caused NumPy to evaluate this elementwise, causing 1 million * 1 million arrays to be created!
