### ISSUE TITLE
[FEATURE REQUEST] Create dataframe from a list of lists

### ISSUE THREAD

**Issue by vertikal-andrea** [vaexio/vaex#1117]
It would be useful to have a method to create a dataframe from a list of lists.
In Pandas I would simply do: 
`pd.DataFrame([['A',1,3], ['B',2,4]])`

But in Vaex, to the extent of my knowledge, I should create intermediary Pandas dataframes or csv files or... 

In my case, having this functionality would make much easier to migrate Pandas code to Vaex. In general, I think it makes easier to use Vaex when building one owns datasets.

**Comment by JovanVeljanoski** [comment]
Hi @vertikal-andrea 

We will consider this, but I have to say that we will be likely reluctant to do this. There is already `vaex.from_dict` and `vaex.from_items`. There is also `vaex.from_arrays` where you can pass arrays or even lists.

We are reluctant to bloat up the API with too many methods that do essentially the same thing. If you do prefer creating dataframes that way, you are essentially creating them in memory so there is not problem creating a pandas dataframe and then using `vaex.from_pandas_df` to get convert the dataframe into a vaex one.

I hope this makes sense. Perhaps @maartenbreddels can comment also.

**Comment by vertikal-andrea** [comment]
Makes sense.

However, I do not see how i can use those methods to do the same thing. I am probably not mistaken, but those methods create columns from arrays/items while when I use `pd.DataFrame` I create a row for each list.
Is there an option to do that?

**Comment by JovanVeljanoski** [comment]
The easiest was is to use pandas as use `vaex.from_pandas_df()` or format reshape your data perhaps, perhaps to dict.
