### ISSUE TITLE
How to do a big groupby aggregation without running out of memory?

### ISSUE THREAD

**Issue by ManuelZ** [vaexio/vaex#1122]
I'm doing some aggregations:

    feats = train.groupby('key_value').agg(aggregations)

Where `aggregations` is a big dict full of aggregations like:

    f'{agg.__name__}_{val}_{col}={col_item}_{pkey}' : agg(val, selection=pval)

And I'm getting multiple `MemoryError`s, I guess from multiple threads. Is there a way of reducing the amount of memory consumed?

**Software information**

    {'vaex': '3.0.0', 'vaex-core': '2.0.3', 'vaex-viz': '0.4.0', 'vaex-hdf5': '0.6.0', 'vaex-server': '0.3.1', 'vaex-astro': '0.7.0', 'vaex-jupyter': '0.5.2', 'vaex-ml': '0.9.0', 'vaex-arrow': '0.5.1'}

 - Vaex installed from pip

 - OS: Windows 10 2004 build 19041

**Comment by maartenbreddels** [comment]
Hi,

thanks for the report. Could you try upgrading to the latest alpha, and give me some more information about the system, how much RAM, how many cores, how large is `aggregations` and how many unique elements are in `key_value`, and what kind of aggregations do you do.

Regards,

Maarten

**Comment by JovanVeljanoski** [comment]
Will close this as stale. Please re-open if needed. 
Also, for upcoming groupby improvements please see https://github.com/vaexio/vaex/pull/1381
