### ISSUE TITLE
[BUG-REPORT] Cannot list all dataframe columns

### ISSUE THREAD

**Issue by acubed3** [vaexio/vaex#1126]
Suppose that during calculation I create the following column:

``df[new_col] = (df[col1]-df[col2])/(df[col1]+df[col2])``

I am really surprised that when I use `list(df.columns)` I do not see `new_col`. Minimal working example:

<pre><code>arr = np.arange(1,10)
x = arr
y = x**2

df_test = vaex.from_arrays(x=x, y=y)</pre></code>

where `list(df_test.columns)` gives `['x', 'y']`. I would like to apply a transformation for all dataframe columns except hidden (as I understand, their names started from double underscore). However, I do not understand how to obtain list of columns

**Comment by JovanVeljanoski** [comment]
Hi @acubed3 

This is not a bug. Maybe it is a bit misleading, as `df.columns` has a different behaviour compared to pandas. In vaex, `df.columns` refers to the "original" or "non-virtual"  data i believe. 

If you want to get a list of column names, please use `df.column_names`. That will for sure show you all the columns. 
There is also a method called `df.get_column_names()` which also gives you options to select columns based on regex and the like.

I hope this helps. Please re-open if unclear.

**Comment by acubed3** [comment]
Thank you so much. My vague feeling that API documentation sometimes is too brief.

**Comment by JovanVeljanoski** [comment]
It is.. feel free to post suggestions and PRs! 
We appreciate it!
