### ISSUE TITLE
[BUG-REPORT] Manipulations with columns in loop

### ISSUE THREAD

**Issue by acubed3** [vaexio/vaex#1130]
It is not drastically bad but not clear. Consider the following dataframe,
<pre><code>x = np.arange(1,10)
y = x**2
df = vaex.from_arrays(x=x, y=y)</pre></code>

Then, consider that one would like to perform a manipulation in loop, for instance:
<pre><code>for col in df.column_names:
    df[col] = df[col].astype('float32')</pre></code>

The result is non-intuitive: for each iteration VaeX creates column `__col` and `df.column_names` object changes, so the loop becomes infinite.

**Comment by kmcentush** [comment]
The solution is to use `df.get_column_names()`. It returns a list at the time of execution as opposed to `df.column_names` which I assume is returning a generator
