### ISSUE TITLE
[BUG-REPORT] import vaex on Kaggle Kernel

### ISSUE THREAD

**Issue by takelushi** [vaexio/vaex#1152]
On Kaggle Kernel, import vaex was not work (without reloading pkg_resources).
If you want more people to use vaex, you should deal with this.

Not work

```py
!pip install -q --disable-pip-version-check 'vaex==3.0.0'
# Raise: ContextualVersionConflict
import vaex
print(vaex.__version__)
```

It works.

```py
!pip install -q --disable-pip-version-check 'vaex==3.0.0'

# pkg_resources detect old version of vaex dependancies.
# So pkg_resources raise `ContextualVersionConflict`.
# Resolve it with reloading pkg_resources.
import importlib
import pkg_resources
importlib.reload(pkg_resources)

import vaex
print(vaex.__version__)
```

**Comment by JovanVeljanoski** [comment]
Hi, 

Indeed thank you for letting us know. I would like to made a PR to the kaggle docker image to include vaex once we make the new vaex release, hopefully soon!

Thanks!

**Comment by JovanVeljanoski** [comment]
HI, 

we've made PR to the kaggle docker image that was recently accepted. So vaex should be in their environment when they make a new release (they once said that happens every 2 weeks or so).

Until then, `!pip install vaex` also works (it will install the latest version).
