### ISSUE TITLE
groupby on multiple columns - keeping the cartesian product output

### ISSUE THREAD

**Issue by v1gnesh** [vaexio/vaex#1173]
> Hi,
> 
> Yes you are right -  the non-existent combinations are ignored. But as you have seen in the code, vaex currently does the cartesian product, so it takes all combinations into account initially, even the non existent ones, which is where the problem with memory happens. 
> 
> We plan to improve on this in the future, but I can not speculate as to when it will happen. 
> 
> But if you have found a work-around, at least temporarily, that is great!

_Originally posted by @JovanVeljanoski in https://github.com/vaexio/vaex/issues/929#issuecomment-674574996_

Hi,

I have a requirement where it's actually good that the cartesian product is being done.
The 'Amsterdam is not in France' rows still need to be kept, but with zeros instead of any aggregation for the other columns.

Example:

```
idn_num    dow    h0  h1  h2  h3  ...  h23
5ae3g      0      20  52  ...
asfet      1      52  6246  ...
...
5ae3g      6      24  6652  ...
```

The data has millions of unique `idn_num` values, and a fixed range (`0-7` in column `dow`)... `category` for the day of week.
For all the `idn_num` values that exist, I want to have:

```
5ae3g  0  20  52  ...
5ae3g  1  0  0  ...
5ae3g  2  0  0  ...
5ae3g  3  0  0  ...
5ae3g  4  0  0  ...
5ae3g  5  0  0  ...
5ae3g  6  24  6652  ...
```

Since the referred issue & comment says that the full cartesian product is being done anyway and unnecessary combinations are dropped, perhaps an amendment can be done to it, giving the option to keep the remaining rows, and specify a fill value for them?

Depending on how much of a different approach @maartenbreddels has planned for this for v4.1, I hope this is considered.

The alternative approach would be very memory heavy because it'll basically be 
```
idn_unique = df.idn_num.unique()
dows =np.arange(7)
pd.MultiIndex.from_product([idn_unique, dows]).reset_index()
```

... and then `join` the existing df with h0 ... h23 columns to it somehow.

**EDIT:** I've just noticed [here](https://github.com/vaexio/vaex/blob/6ca53b47b76546e5b730b92b47d2cc944a00e60d/packages/vaex-core/vaex/groupby.py#L288) that an `np.meshgrid` is being used, and that `np` has the option of returning a sparse array.
That will be helpful in some use cases right, at least from a memory perspective?  
In my case at least, a `df` of shape (x00_000_000, 26) would be far smaller in memory if it were sparse, knowing that a lot of the slots will be `0`.
Can make it dense when exporting to a file... don't know if _this_ step will allocate the whole thing in memory anyway.

**Comment by maartenbreddels** [comment]
Interesting idea, @JovanVeljanoski what do you think? Note that binby might also be sth to take a look at.

I think it should be possible to do the meshgrid lazily, similar to vaex.column.ColumnVirtualRange, especially if all values will be done. Do you want to take a shot at this?

**Comment by v1gnesh** [comment]
> Do you want to take a shot at this?  

Hope you don't mean me :)   
I'm usually at that level where I can somewhat understand what's going on but can't code fast (since I don't work on it much).

**Comment by v1gnesh** [comment]
Just curious.. is this (writing the 'unneeded' combinations' rows) something that might be available in a few weeks?  
Would love to have this functionality native in vaex.  
Exploting sparse could perhaps come later.

**Comment by maartenbreddels** [comment]
I think it is simple to implement, I'm not sure how useful the feature is (@JovanVeljanoski ) and if it will bite us in the future. I may have an idea to 'hide' it for normal usage, and expose it only when we find it useful as a general feature. Also, it needs a descriptive name, for an argument, skip_missing? all_rows? Any ideas?

**Comment by v1gnesh** [comment]
How about... 
`df = df.groupby(by=[df.IDN_NUM], keep_combos={all|exist}).agg('sum')`

.. where `keep_combos=all` calls the current codepath with `np.meshgrid` while materializing all combos,
and `keep_combos=exist` calls the new codepath you're planning for in v4.1, with which only existing combos are materialized.
Also a check to state that this keyword is only applicable when grouping by more than 1 column.

I'm positive that the codebase is full of optimisation gems, and some day, this method may be useful & applicable elsewhere.  
It will be useful in cases where people are looking to fit outputs into a known grid-like structure, i.e., 24x7 or 30x12 or whatever.

**Comment by maartenbreddels** [comment]
All the binby stuff is for regular grids btw, df.binby will give you an
xarray dataset, not a data frame though. But maybe you also want to look
into that.

(from mobile phone)

**Comment by v1gnesh** [comment]
binby looks exactly like the thing I should use.
Going to take a while for me to figure out how to use this though lol.
Not a great programmer if I'm honest :)

**Comment by JovanVeljanoski** [comment]
I think this is an edge case - but it would be nice to support it if it can be done safely. I agree with @maartenbreddels, that perhaps this behavior can be chosen via some optional keyword.

@v1gnesh if you can give a short at this, that would be great :)

**Comment by JovanVeljanoski** [comment]
This is being now worked on, and can be tracked in https://github.com/vaexio/vaex/pull/1381
