### ISSUE TITLE
Conda install vaex-arrow

### ISSUE THREAD

**Issue by flekschas** [vaexio/vaex#120]
Unless I am missing something the `vaex-arrow` is currently not available as a conda package is that correct? If so, are there any plans to make that available too? :) Or is the package simply in a too early stage right now?

**Comment by maartenbreddels** [comment]
It is waiting in line here:
https://github.com/conda-forge/staged-recipes/pull/6969
feel free to ping or ask for status there.

**Comment by claforte** [comment]
Sounds like this issue can be closed.

**Comment by maartenbreddels** [comment]
Thanks, indeed
