### ISSUE TITLE
Unknown error while opening file on S3

### ISSUE THREAD

**Issue by parvathtarun** [vaexio/vaex#1201]
I've created .hdf5 from vaex & transferred it to S3. This is fine, but when I open the file then its giving an error 
OSError: Unknown error opening: s3://bucket_name/xxx/data.hdf5'

I used below to open file

df = vaex.open('s3://bucket_name/xxx/data.hdf5', fs_options={'access_key': ACCESS_KEY, 'secret_key': SECRET_KEY})

**Comment by JovanVeljanoski** [comment]
Hi @parvathtarun 

Please tell us which version of vaex you are using, your OS, etc.. those questions you skipped when opening this issue.
Cheers.

**Comment by parvathtarun** [comment]
vaex 3.0.0, windows 10 os

**Comment by JovanVeljanoski** [comment]
If possible can you the latest alpha?
```
pip install vaex-core==4.0.0a19
```
or
```
pip install vaex==4.0.0a13
```

See if that helps, otherwise please return the full stacktrace?

**Comment by JovanVeljanoski** [comment]
Will close as stale. Please re-open if needed.
