### ISSUE TITLE
[BUG-REPORT] 'DataFrameArrays' object has no attribute 'close'

### ISSUE THREAD

**Issue by flamecheng** [vaexio/vaex#1205]
x = np.arange(5)
y = x ** 2
df = vaex.from_items(('x', x), ('y', y))
df.close()

AttributeError: 'DataFrameArrays' object has no attribute 'close'

df is “DataFrameArrays”， but not DataFram？how to use ‘close’？

**Comment by flamecheng** [comment]
how to free the ram used by df？

**Comment by JovanVeljanoski** [comment]
Hi,

Your original example creates a dataset in memory. 
If you export your data to a memory mappable format like hdf5 or arrow, you can read straight from disk.

`df.close()` closes a connection to a file -> in your example you do not opena  file, but create a dataset from memory, so this method is no applicable.

Please go over the [tutorial](https://vaex.io/docs/tutorial.html) and documentation to learn more about vaex.

Thanks
