### ISSUE TITLE
 assignment of conditional values vaex dataframe. How can I replicate this?

### ISSUE THREAD

**Issue by FRP2017** [vaexio/vaex#1212]
Hello everyone.

Can you please advise me to do the following operation on a vaex dataframe?

df.loc[(df.v1>=df.v2) & (df.v1<=df.v3),'new_column'] =df.c1-df.c2 
df.loc[(df.v1<df.v2) | (df.v1>df.v3),'new_column'] =df.c2-df.c1 

This is a  pandas dataframe example.

Regards.

**Comment by JovanVeljanoski** [comment]
Hi @FRP2017 

If I understand you correctly, you can do using `where` (similar to `numpy`). 
Look at this example:

```
import vaex
df = vaex.example()
df['new_column'] = df.func.where((df.x > df.y) | (df.x > df.z), df.vx - df.vy,  df.vy - df.vx)
print(df.new_column)
print(df)
```

Is this what you want?
In general the syntax is:
`df.func.where(condition, if-condition, otherwise)`

Hope this helps,
J.

**Comment by FRP2017** [comment]
Thanks!!!

**Comment by FRP2017** [comment]
it works perfect!
