### ISSUE TITLE
[FEATURE-REQUEST] prod / skew / kurtosis aggregations

### ISSUE THREAD

**Issue by FRP2017** [vaexio/vaex#1215]
Hi everyone,

I am trying to perform the following operation:

pandas example:

df.groupy([''column1,'column2'])['column3'].prod()

vaex example:

df_vx.groupby(by=['column1','column2']).agg({'column3': ['mean', 'std','count']})   Works pefect!

I checked the documentation but I didn't find the method to multiply "prod()"  (kurtosis and skewness would be great too).

Thank you very much in advance

regards.

**Comment by JovanVeljanoski** [comment]
Hi, 

Thanks for opening an issue. Indeed these aggregators are not yet implemented. We will definitely consider them as part fo the roadmap for the next release. Thank you.

Let's keep this open until it is addressed.
