### ISSUE TITLE
[BUG-REPORT] Joining on a column with a space in the name fails

### ISSUE THREAD

**Issue by maxharlow** [vaexio/vaex#1217]
When joining two datasets, if one of the column names has a space in, I get a `SyntaxError`. For example:

```python
import vaex

ds1 = vaex.from_arrays(letter = ['a', 'b', 'c'])
ds2 = vaex.open('example.csv')

result = ds1.join(ds2, left_on='letter', right_on='Alphabet Letter')
print(result)
```

With `example.csv`:

```
Alphabet Letter
c
b
a
```

Vaex version: `{'vaex': '4.0.0a13', 'vaex-core': '4.0.0a19', 'vaex-viz': '0.5.0.dev1', 'vaex-hdf5': '0.7.0a6', 'vaex-server': '0.4.0a3', 'vaex-astro': '0.8.0a1', 'vaex-jupyter': '0.6.0.dev1', 'vaex-ml': '0.11.0a5', 'vaex-arrow': '0.5.1'}`

Installed with Pip
Python 3.8.7 on MacOS 10.15.7

**Comment by JovanVeljanoski** [comment]
This is fixed in the latest version. Thank you for the report!
