### ISSUE TITLE
Help needed: Widgets not displaying in Jupyter Notebook

### ISSUE THREAD

**Issue by Chris-hughes10** [vaexio/vaex#1222]
Hi,

I seem to be having trouble getting widgets to display in a Jupyter notebook and I'm not sure if I'm missing something, currently, when executing a widget command I get no error, but the widget does not appear in the notebook; I have verified that ipywidgets (such as `IntSlider()` work fine. 

I am running Python 3.7.9 on Linux (ubuntu 18.04), steps to reproduce are:

```
!pip install vaex==4.0.0a13

import vaex
import vaex.jupyter.model as vjm

import numpy as np
import matplotlib.pyplot as plt

df = vaex.example()
df


heatmap_xy = df.widget.heatmap(df.x, df.y, selection=[None, True])
heatmap_xy 
```
Any help here is appreciated!

Thanks,
Chris

**Comment by JovanVeljanoski** [comment]
Hi Chris,

Is there any associated error message (please also check the terminal in which you run the jupyter notebook server)? Or it is just that the widget does not appear?
Few things to try:
- another browser?
- can you display ipyvuetify widgets?

I hope we can figure it out. I just tried the alpha in a new environment and your example works ok.

**Comment by Chris-hughes10** [comment]
Hi @JovanVeljanoski, thanks for the speedy response!

Just to clarify, there is no error in the terminal, just that the widget doesn't show up.

I did try another browser (Chrome & Firefox) to no avail. I did also try running jupyter notebook locally and using Jupyterhub.

Interestingly, I am also unable to display  ipyvuetify widgets, so perhaps this is not a vaex specific issue. To try this, I did the following:

```
!jupyter nbextension enable --py --sys-prefix ipyvuetify

import ipyvuetify as v

my_select = v.Select(
    label='Fruits',
    items=['Apple', 'Pear', 'Cherry'])
my_select
```

**Comment by maartenbreddels** [comment]
Hi Chris,

Did you refresh after that? And did you do also try `jupyter nbextension install --py --symlink --sys-prefix ipyvuetify`? Is this in jupyter lab or the classic notebook (the latter should always work, without the install and enable).

Regards,

Maarten

**Comment by Chris-hughes10** [comment]
Hi Maarten,

I did refresh (and have even restarted the machine since). I have also tried `jupyter nbextension install --py --symlink --sys-prefix ipyvuetify` and still no joy unfortunately!

I am in the classic notebook. 

Thanks,
Chris

**Comment by maartenbreddels** [comment]
Which version of jupyter notebook, and how did you install? Are you using conda environments? And are you running the kernel and notebook in different environments?

**Comment by Chris-hughes10** [comment]
Hi Maarten,

I am using a conda environment. For my own sanity, I just created a new env (Python 3.8 this time) and tried again. My steps were:

```
conda create -n vaex-env python=3.8

conda activate vaex-env

conda install jupyter

pip install vaex==4.0.0a13

jupyter notebook
```

This installed :
```
jupyter                1.0.0                    
jupyter_client         6.1.7                   
jupyter_console        6.2.0                
jupyter_core           4.7.0  
jupyter_server         1.2.2
jupyterlab             3.0.5
jupyterlab_pygments    0.1.2    
jupyterlab_server      2.1.2  
jupyterlab_widgets     1.0.0 
...
vaex                      4.0.0a13                 
vaex-arrow                0.5.1                    
vaex-astro                0.8.0a1                  
vaex-core                 4.0.0a19                
vaex-hdf5                 0.7.0a6                  
vaex-jupyter              0.6.0.dev1            
vaex-ml                   0.11.0a5                 
vaex-server               0.4.0a3                 
vaex-viz                  0.5.0.dev1               
```

Once again, I ran both in the local jupyter notebook (and verified that the env used was `vaex-env`), as well as in jupyterhub running in my machine where I selected the same env.

Interestingly, this time, in addition to not seeing the widgets, I also am getting a rendering error when previewing the dataframe, I'm not sure if this is in any way related. 

![image](https://user-images.githubusercontent.com/31883449/108413363-d7359680-7222-11eb-9985-a96354d8cff4.png)

Thanks for your patience with this by the way!

**Comment by maartenbreddels** [comment]
I think you are not picking up the right jupyter, you can probably confirm that by running `which jupyter`. Deactivate and activate your environment again (or run `hash -r` or `rehash` depending on your shell), and run `which jupyter` again please, if you see the right jupyter, you'll get the right environment and it should all work :) (I hope!)

**Comment by Chris-hughes10** [comment]
Unfortunately, I am running `/anaconda/envs/vaex-env/bin/jupyter` which appears to be the right one. I deactivated and reactivated, and unfortunately still no widgets, and the strange behaviour in the # column returned! 

Perhaps this is an isolated occurrence in my environment (hopefully)! I will try spinning up a new VM tomorrow and installing everything fresh. Would you recommend a pip or conda install?

**Comment by maartenbreddels** [comment]
Try a clean environment and just pip, and check the version with
vaex.__version__, because you seem to be picking up an old vaex somehow
(installed via pip --user maybe?)

(from mobile phone)

**Comment by JovanVeljanoski** [comment]
@Chris-hughes10 actually when it comes to managing environments, I myself prefer conda but starting from miniconda rather than anaconda. In the past (this was maybe a year and a half ago), i found some strange behavior when installing vaex via anaconda, some dependency things. I couldn't look into it at the time, so don't know the real cause. 

Just saying that it could be worth installing a fresh miniconda environment, and going the conda-forge route.

**Comment by Chris-hughes10** [comment]
Hi all, an update on this. I tried a completely fresh install, in new envs, using both conda and pip. 

Using conda to install both jupyter and vaex, the widgets still do not show.

Using pip to install both Jupyter and vaex, the widgets do show!

In both cases, I still get the strange `<i style...` appearing in the `#` column though, which is odd but not a dealbreaker.

**Comment by maartenbreddels** [comment]
And you are sure this is vaex v4? Did you check `vaex.__version__`?

**Comment by Chris-hughes10** [comment]
Apologies, I had that cell at the top of my notebook from the start yesterday and I can confirm that it was `4.0.0a13` throughout. Specifically:

```
{'vaex': '4.0.0a13',
 'vaex-core': '4.0.0a19',
 'vaex-viz': '0.5.0.dev1',
 'vaex-hdf5': '0.7.0a6',
 'vaex-server': '0.4.0a3',
 'vaex-astro': '0.8.0a1',
 'vaex-jupyter': '0.6.0.dev1',
 'vaex-ml': '0.11.0a5',
 'vaex-arrow': '0.5.1'}
```

**Comment by maartenbreddels** [comment]
I just noticed https://pypi.org/project/tabulate/#history has a new release, maybe we again have an issue with rendering the HTML for that.

**Comment by JovanVeljanoski** [comment]
I believe this is fixed in the latest vaex release. Please reopen if the problem persists.

**Comment by parshvms** [comment]
I am having the same issue where the df.widget.heatmap is not showing any plot. Could you please advise on what the fix is?
