### ISSUE TITLE
Issue with byte_size() method

### ISSUE THREAD

**Issue by saffranzachary** [vaexio/vaex#1223]
**Description**
I load a dataset through vaex.from_csv(), in this case the[ Airbnb NYC 2019](https://www.kaggle.com/dgomonov/new-york-city-airbnb-open-data) dataset. I then try to get the size in bytes of the dataframe using df.byte_size(), and it throws the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/c/Users/saffr/Desktop/data_vis/dev_venv/lib/python3.7/site-packages/vaex/dataframe.py", line 1959, in byte_size
    bytes_per_row += dtype_internal.itemsize
AttributeError: type object 'str' has no attribute 'itemsize'

I got this error on every dataset that I tried it on (all of them containing at least one string column). All other vaex core functions and methods seem to be working as normal.

**Software information**
 - vaex-core==2.0.3
 - installed through pip
 - Ubuntu 20.04 on Windows 10 WSL

**Comment by maartenbreddels** [comment]
Hi Zach,

This should be solved in the latest 4.0 alpha, please try:
```
pip install vaex-core --pre
```

Regards,

Maarten
