### ISSUE TITLE
[BUG-REPORT] Loading csv with header and no rows throughs div by 0 error

### ISSUE THREAD

**Issue by foooooooooooooooobar** [vaexio/vaex#1227]
**Description**
Csv with no rows throws error when loaded via glob format. 

**Software information**
 - Vaex version `{'vaex': '3.0.0', 'vaex-core': '2.0.3', 'vaex-viz': '0.4.0', 'vaex-hdf5': '0.6.0', 'vaex-server': '0.3.1', 'vaex-astro': '0.7.0', 'vaex-jupyter': '0.5.2', 'vaex-ml': '0.9.0', 'vaex-arrow': '0.5.1'}`
 - Vaex was installed via: pip
 - OS: Mac OSX

**Additional information**
1. Create a csv with these contents
````
#    DATE|SYMBOL|SHORT VOLUME|TOTAL VOLUME|MARKET
 

````
(the two blank lines are important)
2. Read it via glob via open `vaex.open(f".tmp/short_data/NQBXshvol*.csv", sep='|', copy_index=False, skip_blank_lines=True)`
3. Throws an error
````
3838         print("self", self)
   3839         print("self", self.length_original())
-> 3840         self._active_fraction = (i2 - i1) / float(self.length_original())
   3841         # self._fraction_length = int(self._length * self._active_fraction)
   3842         self._index_start = i1

ZeroDivisionError: float division by zero
````

**Comment by JovanVeljanoski** [comment]
I believe this has been fixed in the latest alpha, can you perhaps try that:

```
pip install vaex-core==4.0.0a19
or
pip install vaex==4.0.0a13
```

**Comment by JovanVeljanoski** [comment]
This is fixed in the latest release of vaex. Please reopen if needed.
