### ISSUE TITLE
[BUG-REPORT]

### ISSUE THREAD

**Issue by keotic** [vaexio/vaex#1231]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your problem may already be discussed or addressed.

**Description**
vaex.open() can't accept list of file paths string as the documentation states, it fails in the aliases check (cant hash a list)

Code:
 `df = vaex.open(['./my_file.hdf5'])`

Error:
TypeError: unhashable type: 'list'

Code line problem:
Line 147  @__init__.py :` if path in aliases:`

Python can't use a list as a dictionary key, so we have an error

**Comment by JovanVeljanoski** [comment]
Can you please give a code example, and answer the questions that the form requires. Help us help you kind of thing. 
Also please add a meaningful title, so other people with similar issues can find this. 
Thanks.

**Comment by JovanVeljanoski** [comment]
So I think the error is clear.. `vaex.open` does not support lists... You can use glob expressions instead. If you want to pass a list of files to open, please use `vaex.open_many()`. 

Please reopen if the issue persists.

**Comment by keotic** [comment]
Yap, this is clear, but the documentation states a list of file is OK. 
So its not clear if its a bug, or wrong documentation:

> or list path (str) – local or absolute path to file, or glob string, or list of paths

**Comment by JovanVeljanoski** [comment]
Yeah, I think the docs are incorrect - or there was something that was meant to be implemented, but it is not there yet. Let's keep this open until it is fixed (documentation or implementation).
