### ISSUE TITLE
Question - Generate data points of the resulting histogram generated by plot1d

### ISSUE THREAD

**Issue by fylinhub** [vaexio/vaex#1238]
I have a question about how to get the data points of the resulting histogram after using plot1d.

Currently, I saved the histogram to a figure, but it would be convenient for other usage if the the data points of the histogram can be saved as well.

I'd appreciate your help in advance!

**Comment by JovanVeljanoski** [comment]
Hi! 

Good question. This is not hard to do actually. The `df.viz.histogram()` method is a convenience wrapper around the  `df.count()`. Same goes for the `df.viz.heatmap`. You just need to specify the `binby` argument (the axis along which to bin your data. 

The [tutorial](https://vaex.io/docs/tutorial.html#Statistics-on-N-d-grids) actually has a section on this, so you can check it out for an example and as an extra reference.

I hope this helps!
J.

**Comment by fylinhub** [comment]
Thank you @JovanVeljanoski so much for the advice! I'll try it!
