### ISSUE TITLE
[Feature Request] FlatMap/explode/unpack

### ISSUE THREAD

**Issue by RAbraham** [vaexio/vaex#1242]
Hi,
vaex is amazing! Thanks :).
I'm wondering if the following is already possible in vaex.

I have a file_name, page_number and text. I have a function `tokenize` which take the text and returns a list of tokens. I want to associate each token with the associated file_number and page_number 

E.g.
For simplicity, let's say, I split on spaces
```python
def tokenize(text: str) -> List[str]:
   return text.split()
```
My input dataframe is like:

<table>
<tr>
	<td>file</td>
	<td>page</td>
	<td>text</td>
<tr>
	<td>f1
	<td>1
	<td>Hi There
<tr>
	<td>f1
	<td>2
	<td>Hello

<tr>
	<td>f2
	<td>1
	<td>Bye Bye

</table>

How do I write a `tokenize_df` in vaex such that I can run `tokenize` on each `text` column in such a way that I get

<table>
<tr>
	<td>file
	<td>page
	<td>token
<tr>
	<td>f1
	<td>1
	<td>Hi
<tr>
	<td>f1
	<td>1
	<td>There
<tr>
	<td>f1
	<td>2
	<td>Hello
<tr>
	<td>f2
	<td>1
	<td>Bye
<tr>
	<td>f2
	<td>1
	<td>Bye
</table>

My dataset with text will be huge and will not fit all in memory. `tokenize` will be finite for each `text`

If it helps, my unoptimized pandas code is below
```python
from typing import *
import pandas as pd
text_data = [
    ["f1", 1, "Hi There"],
    ["f1", 2, "Hello"],
    ["f2", 1, "Bye Bye"],

]

incoming_df = pd.DataFrame(text_data, columns=["file", "page", "text"])

def tokenize(text: str) -> List[str]:
   return text.split()

def tokenize_df(incoming_df):
    dfs = []
    for f, p, t in zip(incoming_df["file"], incoming_df["page"], incoming_df["text"]):
        df = pd.Series(tokenize(t), name="token").to_frame()
        df["file"]= f
        df["page"] = p
        dfs.append(df)
    result = pd.concat(dfs).reset_index(drop=True) # I don't really care about index so anything works
    return result

print(tokenize_df(incoming_df))

```

Appreciate any help. Thanks!

**Comment by JovanVeljanoski** [comment]
Hi, 

I think what you are looking for is called `explode` in pandas (and I think `unpack` in some other libraries). I am afraid this is not yet possible in vaex. We would really like to have this, but it requires some work so we are looking for support for this undertaking. 

In the meantime, maybe we can help you with some hybrid approach. I think your code might run faster if you do something like:

```python
ext_data = [
    ["f1", 1, "Hi There"],
    ["f1", 2, "Hello"],
    ["f2", 1, "Bye Bye"],

]

df = pd.DataFrame(text_data, columns=["file", "page", "text"])
df['tokens'] = df.text.str.split()
df.explode('tokens', ignore_index=True)

```

So, if your actual data is too big to be handled by pandas you could try something like this (stuff below is pseudo code, but  hope you will get the idea):

```python
df = vaex.open('big_data.hdf5')
df['tokens'] = df.text.str.split()  # vaex string operations are orders of magnitude faster compared to pandas

# depending on the machine type you have, convert portions of the data to pandas, do your work, and save the data to disk:
for i1, i2, df_tmp in df[['file', 'page', 'tokens']].to_pandas(chunk_size=10_000):  # see what chunk size is appropriate for you
    df_exploded = df_tmp.explode('tokens', ignore_index=True)
    # If you are done at this point, you can save your data as csv directly from pandas, or if you need to do further analysis on the full set, pass it back to vaex and save it as hdf5/arrow/parquet (whatever you prefer, or require)
    df_exploded = vaex.from_pandas(df_exploded)
    df_exploded.export(f'exploded_data_{i1}.hdf5')
 

# At the end you can open all of the individual hdf5 files as
df_all = vaex.open('exploded_data_*.hdf5')

# From here you can again export the data as a single file for some performance benefits, or just keep using it like that, should be more or less the same
```


If your data is in csv format, it might be simpler just to read it in chunks directly with pandas and do the above without vaex.
The benefit of using vaex is that any string operations you might want to do are so much faster. Also, soon vaex will use arrow for csv reading which is also significantly faster than pandas. Finally when you explode the data you will get even more rows, so I guess it might be beneficial to store the data in a memory mappable file format like hdf5 / arrow / parquet so you can than work with your processed data further. 

I hope this helps a bit, or at least gives you some ideas on how to move forward.

**Comment by RAbraham** [comment]
Appreciate the quick response! 
Yes, I can use this approach. Thanks a lot!
