### ISSUE TITLE
[BUG-REPORT] calculate mean and then increase memory

### ISSUE THREAD

**Issue by sungreong** [vaexio/vaex#1247]
**Description**
The data I currently use is about 4GB, and what I want to do is use the minimum amount of memory.
I used the following code to calculate the average for each variable using vaex.
```
columns = ["a","b","c"]
mean_ = x.mean(columns)
```
When the above code is executed, memory is increased compared to the result value.
I would like to ask how can I get the values ​​without the memory growing anymore.

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
vaex-arrow                    0.5.1
vaex-astro                    0.7.0
vaex-core                     2.0.3
vaex-hdf5                     0.6.0
vaex-jupyter                  0.5.2
vaex-ml                       0.10.0
vaex-server                   0.3.1
vaex-ui                       0.3.0
vaex-viz                      0.4.0
 - Vaex was installed via:  conda-forge
 - OS: ubuntu 16.04

**Additional information**
Now i use the memory_profiler to check the memory.
![image](https://user-images.githubusercontent.com/22166391/110606323-6bb16a00-81cd-11eb-89ef-c1af26f09d71.png)

I just count function, memory increase 1.3MB...

![image](https://user-images.githubusercontent.com/22166391/110734565-6c004280-826b-11eb-8e6c-c648ffcd251b.png)

please help me

**Comment by maartenbreddels** [comment]
Hi,

we just released vaex 4.0, could you try upgrading?
Also, what do you use as file input, because if you use memory mapping, memory_profiler incorrectly reports memory usage. See 

Regards,

Maarten

**Comment by JovanVeljanoski** [comment]
Will  close as stale. Please re-open if needed..
