### ISSUE TITLE
[BUG-REPORT] cannot import vaex from colab

### ISSUE THREAD

**Issue by bui-thanh-lam** [vaexio/vaex#1263]
I install Vaex successfully, but fail to import it. Is there any conflict with Numpy?

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
 - Vaex was installed via: pip
 - OS: Google Colab

**Additional information**
numpy.core.multiarray failed to import
![Screenshot from 2021-03-16 15-54-00](https://user-images.githubusercontent.com/47263060/111281781-e5cf6c00-866f-11eb-9399-b7428cb53612.png)

**Comment by JovanVeljanoski** [comment]
Please restart the runtime and try again. Sometimes  a runtime-restart is required after installation.

**Comment by maartenbreddels** [comment]
Or upgrade numpy, I think this is the issue you also had Jovan, and that we're fixing in #1259

**Comment by mfouesneau** [comment]
Same issue on deepnote with fresh install of numpy and vaex via pip --upgrade
```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
```

**Comment by mfouesneau** [comment]
This seems only related to vaex 4.0. when forcing 3.0 it works.

**Comment by bui-thanh-lam** [comment]
> Please restart the runtime and try again. Sometimes a runtime-restart is required after installation.

restarting runtime doesn't work

**Comment by maartenbreddels** [comment]
> Or upgrade numpy, I think this is the issue you also had Jovan, and that we're fixing in #1259

please read my comment, I'm pretty sure think it's this.

**Comment by mfouesneau** [comment]
I believe yes if you upgrade numpy this may work. But I think the requirements should include numpy >= 1.20

Sometimes you cannot upgrade some system packages. Colab/Deepnote or if you do not control the machine yourself.

**Comment by maartenbreddels** [comment]
> we're fixing in #1259

working on it :)

**Comment by maartenbreddels** [comment]
This should be fixed in vaex/vaex-core 4.1

**Comment by maartenbreddels** [comment]
If not, please reopen, thanks for reporting!

**Comment by mfouesneau** [comment]
```vaex-arrow 0.5.1 requires vaex-core<3,>=2.0.0, but you'll have vaex-core 4.1.0 which is incompatible.```

**Comment by maartenbreddels** [comment]
you can uninstall vaex-arrow, this is now part of vaex-core.

**Comment by mfouesneau** [comment]
Sweet. Thanks. And thanks for correcting the bug this fast.

**Comment by bui-thanh-lam** [comment]
Thank guys for supporting. It all works now.
