### ISSUE TITLE
[QUESTION] How to select rows based on a list of values?

### ISSUE THREAD

**Issue by Eisbrenner** [vaexio/vaex#1274]
**How to select rows based on a list of values?**

Assuming I have a list of values of a column of a dataframe, lets say the ID's of a random selection of the rows, then how to select only those rows?

Something I could, for example, do in Pandas with `df.query("id in @randsel")` given that `id` is the column name and `randsel` is my list of ID's corresponding to my desired rows.

**Example**

```
import numpy as np
import pandas as pd

np.random.seed(0)
arrays = np.concatenate(np.array([range(10), range(10)]))
df = pd.DataFrame(np.round(np.random.rand(1,arrays.shape[0]).T, decimals=1), index=arrays, columns=["x"])
df.index.names = ["id"]

randsel = np.random.choice(list(set(arrays)), 3)
df.query("id in @randsel")
```

returns

```
     x
id 
-------
2   0.6
3   0.5
8   1.0
2   0.6
3   0.9
8   0.8
```

Best regards

**Comment by Eisbrenner** [comment]
I just can't figure it out from the docs, they never get any more complicated with selections than `df.x > y`.

**Comment by JovanVeljanoski** [comment]
You are probably looking for the `isin` method which is available in both vaex and pandas. 

So if I continue from your example, you can achieve the same thing with:

```python
vaex_df = vaex.from_pandas(df, copy_index=True)
vaex_df[vaex_df.index.isin(randsel)]
```

P.S.: Your pandas example would be much more efficient if you use `df.loc[randsel]` instead of `df.query(...)`

**Comment by Eisbrenner** [comment]
Hej thanks, That was what I was looking for!

I keep forgetting about the `isin` method...
And yes, not using `query` would be faster, but when it is performance critical I want to use `vaex` instead. And when it doesn't matter I sometimes like the expressiveness of `query` and thus remembered it first today while writing the example.
