### ISSUE TITLE
[QUESTION] How to handle dates in filters or how to use boolean arrays in select?

### ISSUE THREAD

**Issue by Eisbrenner** [vaexio/vaex#1275]
**How to handle dates in filters or how to use boolean arrays in select?**

I like to filter by a column with dates, given some date range or a boolean array. Using Pandas I'm able to use either way, however, with vaex I get back either a `NoneType` (with boolean arrays) or get an error message when directly compare vaex's date column with a date.

I think for me the option to just throw in a boolean array will be more useful, but I'm also wondering if I can use date comparison directly with vaex.

**Example**

Given a Dataframe

```
import numpy as np
import pandas as pd

np.random.seed(0)
arrays = np.concatenate(np.array([range(10), range(10)]))
df = pd.DataFrame(
    pd.date_range("20200101", freq="D", periods=arrays.shape[0]),
    index=arrays,
    columns=["date"],
)
df.index.names = ["id"]
df.head(3)
```
returns
```
       date
id
1     2020-01-01
2     2020-01-02
3     2020-01-03
```

I try to select a date range from this data, using Pandas I can do

```
pdsel = df.date < pd.Timestamp("20200103")
df.loc[pdsel]
```
returns
```
       date
id
1     2020-01-01
2     2020-01-02
```

now moving on to vaex

```
import vaex
vaex_df = vaex.from_pandas(df, copy_index=True)
```

first, just using the boolean output from `pdsel` returns `None`

```
type(vaex_df[pdsel])
```
returns
```
NoneType
```

and finally using vaex itself results in a lengthy error message

```
vaex_df[vaex_df.date < pd.Timestamp("20200103")]
```
returns (just a tiny bit of the whole error message)
```
[...]
  File "<string>", line 1
    (date < 2020-01-03 00:00:00)
                  ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers

  File "<string>", line 1
    (date < 2020-01-03 00:00:00)
                  ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[...]
```

**Comment by JovanVeljanoski** [comment]
Hi, 

Vaex is a hybrid dataframe leveraging both numpy and apache arrow. For datetime operations, i believe it is still using numpy.
So to do a simple filter as you suggest you simply need to compare to a `np.datetime64` object, i.e.

```python
vaex_df[vaex_df.date < np.datetime64('2020-01-03')]
```

> first, just using the boolean output from `pdsel` returns `None`

Please do not mix pandas and vaex. They are two complete separate technologies, only their APIs look similar. 
Vaex works with expressions, not with in memory structures like pandas does. So for example you can try creating a filter with vaex:

```python
pd_sel_vaex = vaex_df.date < np.datetime64('2020-01-03')
```

and pass that on to pandas - it will not work. However it is fairly easy to convert your dataframes back and forth between the two libraries if you need to.  

I hope this helps!

**Comment by Eisbrenner** [comment]
Hej thanks!

> I hope this helps!

Yes, very much so, I wasn't quite aware of the differences of the technologies.

---

But, I still can't really make use of it, however, for now I have a work-around; which I think will scale at least for the data size I have.

It works for your example tho, with `pd_sel_vaex = vaex_df.date < np.datetime64('2020-01-03')` but not if I try to have a slice.

So (to get a filter of the sort I wanted) I ended up introducing a dummy column, e.g.

```
t0, t1 = "2020-01-02", "2020-01-05"
npsel = (np.datetime64(t0) < vaex_df.date.values) & (vaex_df.date.values < np.datetime64(t1))
vaex_df["npsel"] = npsel
vaex_df[vaex_df["npsel"] == True]
```

---

I also tried `vaex_df[npsel]` which returns `None` and
```
vaexsel = (np.datetime64(t0) < vaex_df.date) & (vaex_df.date < np.datetime64(t1))
```
which again returns an error
```
  File "<unknown>", line 1
    (date > 2020-01-02)
                  ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```

**Comment by JovanVeljanoski** [comment]
Just try following your example (the last line)
`vaex_df[vaex_df["npsel"] == True]`

`npsel` is already a boolean expression.

**Comment by Eisbrenner** [comment]
Oh so `vaex_df[vaex_df["npsel"]]` is enought, great thanks :)
