### ISSUE TITLE
[BUG-REPORT] import vaex raises an error when unable to write to '~/.vaex'

### ISSUE THREAD

**Issue by dzanaga** [vaexio/vaex#1279]
I am running an application on an hadoop cluster with YARN and shipping a conda environment to it.

For some reason, (not clear to me yet), when [this](https://github.com/vaexio/vaex/blob/master/packages/vaex-core/vaex/utils.py#L203) is executed `~/.vaex` is expanded to `/home/.vaex` and the app fails because user doesn't have write permissions on `/home`.

Matplotlib solves this same issue by creating a [temporary folder](https://github.com/matplotlib/matplotlib/blob/d5d2b2a6caf75fc2f884c1bcde3c456db10229ec/lib/matplotlib/__init__.py#L428) and logging a warning.

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: 
 ```
{'vaex-core': '4.1.0',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.7.0',
 'vaex-server': '0.4.0',
 'vaex-astro': '0.8.0',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.11.1'}
```
 - Vaex was installed via: conda-forge
 - OS: Linux CentOS 7

**Comment by JovanVeljanoski** [comment]
I think, if you do something like in your script  / code

```python
import os
os.environ['HOME'] = '/tmp' # or path of your chosing

import vaex

# rest of script
```

Vaex will use the specified folder as the home folder.

Would this help?

**Comment by dzanaga** [comment]
That's indeed how I worked around the issue in the end, thanks for the suggestion.
