### ISSUE TITLE
Where is an up-to-date changelog?

### ISSUE THREAD

**Issue by impredicative** [vaexio/vaex#1284]
At this time the current release of [vaex on conda-forge is 4.0.0](https://anaconda.org/conda-forge/vaex). I can't seem to find an up-to-date **changelog** for it. Shouldn't the [docs](https://vaex.io/docs/index.html) be providing it? 

This repo's default branch is `master`. The [changelog](https://github.com/vaexio/vaex/blob/master/CHANGELOG.md) file in it hasn't been updated since Nov 2020. It says 4.0.0 is an unreleased version. The 4.0.0 release was in March 2021. Also, there is nothing in the file for 4.1.0.

It is a reasonable expectation that:
* The changelog file be kept up-to-date, that no release be made without it.
* The changelog be published on the **docs** site as well.

**Comment by maartenbreddels** [comment]
https://github.com/vaexio/vaex/blob/master/CHANGELOG.md should be the one and only source for this, once the pressure is off I'll make it up to date for sure.

**Comment by JovanVeljanoski** [comment]
It is now up to date
