### ISSUE TITLE
vaex 4.1.0 is not on conda-forge

### ISSUE THREAD

**Issue by impredicative** [vaexio/vaex#1285]
vaex 4.1.0 is currently on PyPI. vaex-core 4.1.0 is currently on conda-forge. The latest version of vaex on conda-forge is however 4.0.0. Why are the versions of vaex on PyPI and conda-forge different? Isn't it reasonable to expect the same version of vaex to be released to both PyPI and conda-forge on the same day?

**Comment by maartenbreddels** [comment]
I was expecting the conda forge bot to pick this up and notify me, that didn't happen, so we need to do this manually.

**Comment by maartenbreddels** [comment]
The bot never did the work, so I did this myself: https://github.com/conda-forge/vaex-feedstock/pull/29, thanks for reporting.
