### ISSUE TITLE
Displaying full integers instead of scientific notiation when printing out Vaex HDF5 data

### ISSUE THREAD

**Issue by SophieLD** [vaexio/vaex#1291]
Hi,
Can you help me:
my code:
`myfile = vaex.open('myfile.hdf5')`
`myfile['customer_id']`

output:
`Length: 4,259,376 dtype: int64 (column)`
`0   9.4618e+08`
` 1  9.43324e+08`
`  2  9.43325e+08`
`  3  9.43333e+08`
` 4  9.43333e+08`
   ...

How can get output with full integer instead of scientific notation? Thank you.

**Comment by maartenbreddels** [comment]
Thanks, totally agree, and we fixed this in #1299
