### ISSUE TITLE
[BUG-REPORT] std caculate error

### ISSUE THREAD

**Issue by gaodianzhuo** [vaexio/vaex#1293]
In [1]: import pandas as pd 
   ...: import numpy as np 
   ...: import vaex 
   ...: vaex.__version__ 
   ...:  
   ...:  
   ...: X1=pd.Series([1, 2, 3, 4, 5, 6]) 
   ...: Y1=pd.Series([0.3, 0.9, 2.7, 2, 3.5, 5]) 
   ...:  
   ...: print(X1.std()) 
   ...:  
   ...: import statistics 
   ...: print(statistics.stdev(X1)) 
   ...:  
   ...:  
   ...:  
   ...: df = pd.DataFrame({'x':X1,'y':Y1}) 
   ...: dd = vaex.from_pandas(df) 
   ...:  
   ...: print(dd.std('x')) 
   ...:  
   ...:                                                                               
1.8708286933869707
1.8708286933869707
1.707825127659933

In [2]: vaex.__version__                                                              
Out[2]: 
{'vaex': '4.1.0',
 'vaex-core': '4.1.0',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.7.0',
 'vaex-server': '0.4.0',
 'vaex-astro': '0.8.0',
 'vaex-ui': '0.3.0',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.11.1',
 'vaex-arrow': '0.5.1'}

**Comment by JovanVeljanoski** [comment]
This is not a bug.

Vaex has the behavior of numpy. Check what you will get if you pass your columns to a numpy array and calculate the same. 
You can find an explanation for example here:
https://stackoverflow.com/questions/24984178/different-std-in-pandas-vs-numpy

So in this case vaex follows the numpy convention.

**Comment by gaodianzhuo** [comment]
i see ,thanks. @JovanVeljanoski

**Comment by gaodianzhuo** [comment]
@JovanVeljanoski 
Calculate the covariance matrix,pandas and numpy is the same but vaex not.

In [7]: df.cov()                                                                   
Out[7]: 
      x      y
x  3.50  3.060
y  3.06  2.976

In [8]: np.cov(X1,Y1)                                                              
Out[8]: 
array([[3.5  , 3.06 ],
       [3.06 , 2.976]])

In [9]: ??np.cov                                                                   

In [10]: dd.cov('x','y')                                                           
Out[10]: 
array([[2.91666667, 2.55      ],
       [2.55      , 2.48      ]])

In [11]: ??dd.cov                                                                  

In [12]: df.cov()                                                                  
Out[12]: 
      x      y
x  3.50  3.060
y  3.06  2.976

**Comment by JovanVeljanoski** [comment]
can you open a new issue for this, so other can find it, now the title is misleading

**Comment by JovanVeljanoski** [comment]
but in essence is the same problem as before:

the formula in the covariance matrix is
```
COV = sum(x - mean(x)) * (y - mean(y))   / n
```

while in your case it is 

```
COV = sum(x - mean(x)) * (y - mean(y))   /  (n-1)
```

As vaex is meant to working with big data, this difference only matters for few examples. 

@maartenbreddels do you think it is worth it to change this to use `(n-1)` both here and in `std()` or make it an argument?

**Comment by gaodianzhuo** [comment]
> can you open a new issue for this, so other can find it, now the title is misleading

ok,thanks for your help,i have wrote a function to fix this.

def cov_vaex(x,y):
    # x:vaex.expression.Expression
    # y:vaex.expression.Expression
   
    cov_value = ((x - x.mean())*(y - y.mean())).sum() / (x.shape[0]-1)
    return cov_value
