### ISSUE TITLE
Expression for datetime column is inaccessible

### ISSUE THREAD

**Issue by PotatoAim101** [vaexio/vaex#1295]
Hello,
I'm having an issue with Vaex, I'm not sure if it's a bug or if it's coming from my implementation.

I have a pandas dataframe with datetimes columns. I would like to use vaex to improve the performance as it is quite a large dataset. I started by testing vaex with bokeh (the library I use for visualization) and when plotting the column A in regards to time I get an error. I tried out the same test with only the two columns in vaex and it's the same issue. This is the test I did:

```python
#df1 where time is string
df1= full_df[['time', 'A']]

#df2 where I transformed time to datetime using pandas
df2 = df1.copy()
df2['time'] = pd.to_datetime(df2['time'])

v1 = vaex.from_pandas(df1)
v2 = vaex.from_pandas(df2)
```

In both cases when I try to print what's inside time I get that the expression is df['time'] (knowing that no variable in my code is called df) when it would be just 'time' (which is the case for 'A' for example):

```error
Expression = df['48']
Length: 1,279,763 dtype: string (expression)
--------------------------------------------
      0  '2018-04-13 03:36:08.893'
      1  '2018-04-13 04:00:00.212'
      2  '2018-04-13 05:30:00.031'
               ...                
1279761  '2018-04-13 20:03:14.878'
1279762  '2018-04-13 20:33:29.350'
```

This means that it is impossible for the other library (Bokeh) to access the values because it's getting df['time'] instead of just 'time' and when I try using it I get this error:
```error
ValueError: failed to validate Circle(id='1022', ...).x: expected an element of either String, Dict(Enum('expr', 'field', 'value', 'transform'), Either(String, Instance(Transform), Instance(Expression), Float)) or Float, got Expression = df['48']
Length: 1,279,763 dtype: string (expression)
```
I also tried to transform to datetime inside vaex to see if it makes a difference using this line:
```
v1['new_time']=v1['time'].values.astype('datetime64[ns]')
```
but I get this error:
```
AttributeError: 'pyarrow.lib.ChunkedArray' object has no attribute 'astype'
```

How can I solve this issue?

**Comment by JovanVeljanoski** [comment]
Hi, 

I tried but I could not reproduce your case:
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/18574951/113150241-27494500-9234-11eb-8721-f643f2481962.png">


Can you maybe tell us which version of vaex you are using, how did you install it, and OS?

As for bokeh, i've not used it in a long long time, so I do not know if it would work directly with vaex anyway, so you might need to materialize expressions to numpy before you pass them along.

**Comment by JovanVeljanoski** [comment]
Maybe something else in your process is causing the problems you are seeing.
If you can share more of it, it might help to narrow the problem down. 

But it is mostly likely since you passing vaex stuff into bokeh, and vaex works with expressions and not directly with the actual data (like numpy, pandas etc..). So before giving data to libraries like plotly, bohek, matplotlib etc, you need to convert materialize it to numpy. 

Is it ok to close this?

**Comment by PotatoAim101** [comment]
Yes, this is very helpful. Thanks again, I will close this issue
