### ISSUE TITLE
[BUG-REPORT] vaex.open  convert issue if we use convert == True option, we don't use pandas option.

### ISSUE THREAD

**Issue by sungreong** [vaexio/vaex#1306]
Thank you for reaching out and helping us improve Vaex!

```python
data_vaex = vaex.open(data_path,convert=True,dtype=dd, usecols=dd.keys())
  File "/opt/conda/lib/python3.8/site-packages/vaex/__init__.py", line 212, in open
    return vaex.from_csv(path, fs_options=fs_options, fs=fs, convert=convert, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/vaex/__init__.py", line 531, in from_csv
    vaex.convert.convert_csv(
  File "/opt/conda/lib/python3.8/site-packages/vaex/convert.py", line 51, in convert_csv
    cached_output(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/vaex/cache.py", line 38, in call
    fp = fingerprint(vaex.file.fingerprint(path_input, fs_options_input, fs=fs_input), args, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/vaex/cache.py", line 19, in fingerprint
    return dask.base.tokenize(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dask/base.py", line 658, in tokenize
    return md5(str(tuple(map(normalize_token, args))).encode()).hexdigest()
  File "/opt/conda/lib/python3.8/site-packages/dask/utils.py", line 506, in __call__
    return meth(arg, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dask/base.py", line 669, in normalize_dict
    return normalize_token(sorted(d.items(), key=str))
  File "/opt/conda/lib/python3.8/site-packages/dask/utils.py", line 506, in __call__
    return meth(arg, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dask/base.py", line 684, in normalize_seq
    return type(seq).__name__, list(map(normalize_token, seq))
  File "/opt/conda/lib/python3.8/site-packages/dask/utils.py", line 506, in __call__
    return meth(arg, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dask/base.py", line 684, in normalize_seq
    return type(seq).__name__, list(map(normalize_token, seq))
  File "/opt/conda/lib/python3.8/site-packages/dask/utils.py", line 506, in __call__
    return meth(arg, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dask/base.py", line 702, in normalize_object
    return normalize_function(o) if callable(o) else uuid.uuid4().hex
  File "/opt/conda/lib/python3.8/site-packages/vaex/cache.py", line 17, in explain
    raise TypeError('You have passed in an object for which we cannot determine a fingerprint')
TypeError: You have passed in an object for which we cannot determine a fingerprint
```

**Description**
if we don'use convert option, it can work in csv.
but if we use convert option with pandas option, it break error.

please fix this 

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
    vaex-core                            4.1.0
   vaex-hdf5                            0.7.0
 - Vaex was installed via: pip 
 - OS: ubuntu 16.04

**Additional information**
Please state any supplementary information or provide additional context for the problem (e.g. screenshots, data, etc..).

**Comment by JovanVeljanoski** [comment]
What's inside `dd` ? What data types are you choosing?

**Comment by JovanVeljanoski** [comment]
Actually, I am not sure this is a bug.. 

You need to use it like this:

```python
data_vaex = vaex.open(data_path,convert=True,dtype=dd, usecols=list(dd.keys()))
```

So `usecols` needs to be a python list to be cached properly.

**Comment by sungreong** [comment]
you're right! thank you!

**Comment by Leo-Ji2020** [comment]
I use vaex.open(fn, usecols=[xxxxxx])，but raise an error. Please help. Here is the detail:

![image](https://user-images.githubusercontent.com/62948124/113803283-cae3a980-978e-11eb-9664-bf5cd04a9f8e.png)

**Comment by sungreong** [comment]
You use csv file
When i also try to use hdf5 and select columns, raise error

2021년 4월 7일 (수) 11:48, Leo.Ji ***@***.***>님이 작성:

**Comment by Leo-Ji2020** [comment]
So, the keyword "usecols" only can be used for csv file. Thank you for reply.

**Comment by JovanVeljanoski** [comment]
`usecols` is an argument to the pandas `read_csv` method. If you have the data in a memory mappable format like hdf5, no matter how many columns you have you "open" all of them without using any memory. So you can do simply
`vaex.open(my_file.hdf5)[usecols]`. It will not matter. 

This is different than reading a csv, due to the nature of the fileformat.

**Comment by sungreong** [comment]
I have some question. When converting and reading csv, is this code reading csv or hdf5?

```
## first convert hdf5 file
vaex.open("test.csv",convert= True)
## 
test.csv / test.csv.hdf5
## ??
vaex.open("test.csv",convert= True)
## ??
vaex.open("test.csv",convert= True, usecols = ["x1"])
```
Is this reading test.csv or test.csv.hdf5?

**Comment by JovanVeljanoski** [comment]
The first time do you it, it will convert and use the hdf5 version. 

The next time you do it, it will use the converted version. 

If any of the arguments change, it will reconvert. If the file changes (but has the same name) it will re-convert. 

At least this is the behaviour we intended (right @maartenbreddels ?)

**Comment by maartenbreddels** [comment]
Yes, this is described (in dense form) at https://vaex.io/docs/api.html#vaex.open

**Comment by sungreong** [comment]
So  for example,  i have  100gb csv file
I convert this , (i waiting many times )
And then i re open csvfile and then i add pandas argument 
So  you say reconvert meaning , csv file (100gb) convert again. So i waiting many times again??

**Comment by JovanVeljanoski** [comment]
You are waiting because reading a csv file is slow.. 
Once the file is converted, you should not really change any arguments.. or just use `vaex.open(..)` and point the converted file. in `convert` you can also specify a filename I think. 

If you add/change a pandas argument the data will be likely changed, of course you need to convert again..

**Comment by sungreong** [comment]
aha... thanks!

**Comment by achrafmasmoudi** [comment]
i had the same error "TypeError: You have passed in an object for which we cannot determine a fingerprint" when just I use fillna function with a string column and also when use str.replace function 
I'm using vaex 4.9.1
an idea ?

**Comment by JovanVeljanoski** [comment]
@achrafmasmoudi please share code.., reproducible example is best

**Comment by achrafmasmoudi** [comment]
when I checked the code more I found that I got this error after a vaex concat or vaex extract functions, so by applying those functions the data lost the fingerprint and we cannot use the data again.

sorry I can't share the code, but would you be able to explain a bit better how exactly that fingerprint works and why we lose them like that. 

Thnak you

**Comment by JovanVeljanoski** [comment]
you can create a dummy example that reproduces the issue: fake made up date, just showing the concept and making it fail. 

Difficult to communicate without code
