### ISSUE TITLE
[FEATURE-REQUEST] OHE encoder to output columns with boolean dtype

### ISSUE THREAD

**Issue by aanilpala** [vaexio/vaex#1309]
OHE currently outputs int64 cols which is highly uneconomical. It is possible to cast it to int32 or bool of course but this adds another virtual column in the df state and it makes the state transfer slower.

This is probably nothing when dealing with small amount of data but when things get bigger, it helps a lot to save some space by downcasting integer and floats.

**Comment by kmcentush** [comment]
For OHE encoding, int64 definitely seems like an overkill. I would second the idea to instead return a boolean dtype or something smaller like uint8.

**Comment by maartenbreddels** [comment]
Indeed, I agree, I can't say without digging in why it's an int64, but an int8 sounds like a good option to me. Looking forward to a PR @kmcentush !

**Comment by maartenbreddels** [comment]
This might be useful btw:
```
import numpy as np
x = np.arange(10)
np.where(x > 4, np.uint8(1), np.uint8(0))
```
