### ISSUE TITLE
[BUG-REPORT]percentile_approx, median_approx return "nan" in Win10

### ISSUE THREAD

**Issue by Leo-Ji2020** [vaexio/vaex#1318]
I have the code below in win10 to open a hdf5 data file.
It returns “nan” when I use functions: percentile_approx, median_approx. BUT the same code work well in Linux platform.

Here is the code in Jupyter notebook:

import vaex;print(vaex.__version__)
import numpy as np
##[return: {'vaex': '4.1.0', 'vaex-core': '4.1.0', 'vaex-viz': '0.5.0', 'vaex-hdf5': '0.7.0', 'vaex-server': '0.4.0', 'vaex-astro': '0.8.0', 'vaex-jupyter': '0.6.0', 'vaex-ml': '0.11.0'}]
###############
fn = r'G:\Data\test.h5'
dataset = vaex.open(fn)
dataset.describe()
## [return: 
  | ax | bx
-- | -- | --
float32 | float32
150 | 150
0 | 0
81.16666666666667 | 411.6666666666667
51.288129 | 276.370323
0.0 | 0.0
169.0 | 990.0
##############

varname = 'ax'
print(dataset.percentile_approx(dataset[varname], percentage=75, delay=False))
print(dataset.median_approx(dataset[varname]))

###############
I also try the dataset using :

 data = vaex.example()

BUT those two functions still return NAN, no matter which column I choose.
Please check. Thank you.

**Comment by kmcentush** [comment]
I'm on Windows 10. Can you provide a full-code example that uses the example dataset?

**Comment by Leo-Ji2020** [comment]
Thank you for reply. My code is as follow:

import vaex

dataset = vaex.example()

varname = 'x'
print(dataset.percentile_approx(dataset[varname], percentage=75, delay=False))
print(dataset.median_approx(dataset[varname]))


#####
The above codes return: 
nan
nan

**Comment by kmcentush** [comment]
I was not able to reproduce the issue on my machine. 
![image](https://user-images.githubusercontent.com/20652336/116841184-44539980-ab8d-11eb-917a-10af48fc3693.png)

Can you make sure that you're updated to the most recent version of vaex?

**Comment by JovanVeljanoski** [comment]
Hi, 

A while back we tracked this issue back to numpy. Can you perhaps compare numpy versions @kmcentush @Leo-Ji2020 ?

**Comment by kmcentush** [comment]
I'm on numpy 1.19.2

**Comment by Leo-Ji2020** [comment]
This problem dues to the version of numpy. I have double check the numpy versions 1.19.5 & 1.20.1 in WIN10.
Then both percentile_approx, median_approx work well with numpy1.19.5, but return "nan" with numpy 1.20.1.
I also check the numpy version under Linux. However, they can work well with numpy1.20.1 under Linux.
So, maybe the numpy1.20.1 has problem under WIN10 platform.
Thank you for all the reply.
![1 19](https://user-images.githubusercontent.com/62948124/116961160-27c27900-acd5-11eb-86c5-b0a0b46ceab3.png)
![1 20](https://user-images.githubusercontent.com/62948124/116961166-2f821d80-acd5-11eb-84e6-8c5302b1f82a.png)
![linux](https://user-images.githubusercontent.com/62948124/116961410-da92d700-acd5-11eb-8573-155a381f9294.png)

**Comment by JovanVeljanoski** [comment]
Indeed, this is a numpy issue. You can check just by using `numpy.percentile(...)` and see if that works. If it works, vaex will work too.

**Comment by heyuqi1970** [comment]
- Vaex version {'vaex': '4.8.0',
 'vaex-core': '4.8.0',
 'vaex-viz': '0.5.1',
 'vaex-hdf5': '0.12.0',
 'vaex-server': '0.8.1',
 'vaex-astro': '0.9.0',
 'vaex-jupyter': '0.7.0',
 'vaex-ml': '0.17.0'}:
 - Vaex was installed via: pip from source 
 - OS: macOS big sur

 I have same issue and numpy.percentile() works.  

```
vf = vx.from_pandas(pd.DataFrame({'x': np.arange(100)}))
vf.median_approx('x')
Out[36]: nan

a1 = vf.to_arrays()
np.percentile(a1, 50)
Out[27]: 49.5

np.__version__
Out[11]: '1.22.2'
```

**Comment by JovanVeljanoski** [comment]
This is not a vaex problem, this is a numpy problem. I think 1.19.5 worked for me. 
You can try directly with numpy, you will see the same problem (in the `percentile` method for instance)

**Comment by heyuqi1970** [comment]
@JovanVeljanoski 

Thanks for your quickly replay, numpy 1.19.5  worked.
