### ISSUE TITLE
[BUG-REPORT]

### ISSUE THREAD

**Issue by stokhos** [vaexio/vaex#1320]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your problem may already be discussed or addressed.

**Description**
Please provide a clear and concise description of the problem. This should contain all the steps needed to reproduce the problem. A minimal code example that exposes the problem is very appreciated.

Following code returns an incorrect result

```python
df=vaex.from_arrays(x=np.array([1.01,1.02,1.03]))

df.x.isin([1])
```

Expression = isin_set(x, var_isin_ordered_set)
Length: 3 dtype: bool (expression)
0 True
1 True
2 True

should be all false

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: 4.1
 - Vaex was installed via: pip / conda-forge / from source  conda-forge
 - OS: fedora 33

**Additional information**
Please state any supplementary information or provide additional context for the problem (e.g. screenshots, data, etc..).

**Comment by kmcentush** [comment]
I was able to reproduce the issue and hopefully will have a PR soon.
