### ISSUE TITLE
Vaex in Julia

### ISSUE THREAD

**Issue by lbotecur** [vaexio/vaex#1328]
Are there possibilities of a Vaex implementation in Julia? A pure Julia implementation of the Apache Arrow data standard already exists called [arrow.jl](https://github.com/JuliaData/Arrow.jl).

**Comment by JovanVeljanoski** [comment]
Hi, 

I don't see this happening any time soon. We are spread thin already trying to push forward in the python eco-system.
If somebody is willing to take up the challenge, we'd be open to giving advice etc.
