### ISSUE TITLE
[BUG-REPORT] Error when creating a swallow copy

### ISSUE THREAD

**Issue by argenisleon** [vaexio/vaex#1330]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your problem may already be discussed or addressed.

**Description**
When trying to make swallow_copy using `df.shallow_copy()` 
```
import vaex
df = vaex.read_csv("foo.csv")
df.shallow_copy()
```
I get:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-50-08977f417053> in <module>
----> 1 df.shallow_copy()

~\Anaconda3\lib\site-packages\vaex\dataframe.py in shallow_copy(self, virtual, variables)
   5305 
   5306         """
-> 5307         df = DataFrameLocal(self.name, self.path, self.column_names)
   5308         df.columns.update(self.columns)
   5309         df._length_unfiltered = self._length_unfiltered

~\Anaconda3\lib\site-packages\vaex\dataframe.py in __getattr__(self, name)
    202             return self.__hidden__[name].__get__(self)
    203         else:
--> 204             return object.__getattribute__(self, name)
    205 
    206     def _ipython_key_completions_(self):

AttributeError: 'DataFrameLocal' object has no attribute 'path'
```

**Software information**
 - Vaex version:
 {'vaex': '4.1.0',
 'vaex-core': '4.1.0',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.7.0',
 'vaex-server': '0.4.0',
 'vaex-astro': '0.8.0',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.11.1',
 'vaex-arrow': '0.4.2'}
 - Vaex was installed via: pip 
 - OS: Win10

**Comment by JovanVeljanoski** [comment]
Hi, 

Thanks for raising thins. 
`shallow_copy` is most likely going to be deprecated soon, and it should not be used. Please us `df.copy()`. 
Vaex will only ever due shallow copies, due to the nature of how vaex works.

**Comment by argenisleon** [comment]
Works great, thanks.
