### ISSUE TITLE
unable to install vaex using anaconda

### ISSUE THREAD

**Issue by elisabettabiondi** [vaexio/vaex#1349]
Hi,

I have tried to install vaex from the Anaconda Prompt using the command:
conda install -c conda-forge vaex
However, it gets stuck during Solving Environment. Actually, it says:
`Solving environment: failed with initial frozen solve. Retrying with flexible solve.`
`Solving environment:`
And then gets stuck. How can I fix this problem? 

Thank you

**Comment by maartenbreddels** [comment]
Hi,

Did you manage to fix it? You might also want to try mamba instead next time.

cheers,

Maarten

**Comment by elisabettabiondi** [comment]
Hello,

thanks fo your answer. Actually, the system downloaded vaex, and thus I
have marked thee issue as solved. But, in reality, the problem remains,
because when I use vaex I got ModuleNotFoundError: No module named 'vaex'.
I now am trying with removing vaex, andall vaex-... and do this:

conda create --name vaex_env
source activate vaex_encconda install vaex -c conda-forge

But I don't know if this would work.
Any ideas?

Thanks,
Elisabetta
----------------------------------------------------------
Elisabetta Biondi, Researcher
Ph.D. in Information engineering
MSc and BSc in Mathematics

Institute for Informatics and Telematics (IIT)
Italian National Council (CNR)
phone: +39 050 315 2195
email: ***@***.***
----------------------------------------------------------


Il giorno mer 12 mag 2021 alle ore 12:03 Maarten Breddels <
***@***.***> ha scritto:

**Comment by maartenbreddels** [comment]
that should work, what do you get if you run `which python`?

**Comment by JovanVeljanoski** [comment]
Hi @elisabettabiondi 

Also in your code snippet above (if I understand it correctly) you seem to be using two different vaex environments, maybe there is some confusion there (one `being vaex_env`, the other `vaex_encconda`)?
