### ISSUE TITLE
Error when opening vaex example

### ISSUE THREAD

**Issue by elisabettabiondi** [vaexio/vaex#1351]
Hi all,

I am trying to open vaex example, but it doesn't work. As suggested in another issue, I have delated the file 

> ".../.vaex\data\helmi-dezeeuw-2000-10p.hdf5"

But when I tried another time, I got the following message:
```
Downloading https://github.com/vaexio/vaex-datasets/raw/master/datasets/helmi-dezeeuw-2000-10p.hdf5 to C:\Users\Biondi/.vaex\data\helmi-dezeeuw-2000-10p.hdf5
wget failed, using urlretrieve
ERROR:MainThread:vaex:error opening 'C:\\Users\\Biondi/.vaex\\data\\helmi-dezeeuw-2000-10p.hdf5'
Traceback (most recent call last):

  File "<ipython-input-14-38eb1c6640d3>", line 7, in <module>
    df = vaex.example()  # this will now work

  File "C:\Users\Biondi\Anaconda3\lib\site-packages\vaex\__init__.py", line 584, in example
    return vaex.datasets.helmi_de_zeeuw_10percent.fetch()

  File "C:\Users\Biondi\Anaconda3\lib\site-packages\vaex\datasets.py", line 48, in fetch
    return vx.open(self.filename)

  File "C:\Users\Biondi\Anaconda3\lib\site-packages\vaex\__init__.py", line 222, in open
    ds = vaex.dataset.open(path, fs_options=fs_options, fs=fs, **kwargs)

  File "C:\Users\Biondi\Anaconda3\lib\site-packages\vaex\dataset.py", line 59, in open
    raise IOError(f'Cannot open {path} nobody knows how to read it.')

OSError: Cannot open C:\Users\Biondi/.vaex\data\helmi-dezeeuw-2000-10p.hdf5 nobody knows how to read it.
```

How can I do?
Thank you

**Comment by JovanVeljanoski** [comment]
Hi! 

Can you tell us a lit about how you installed vaex? Is it via anaconda? (I can see bits of it in the stacktrace you sent).
Can you send us the vaex version installed (basically all the questions that the issue template form asks..).

Can you please make sure that the vaex-hdf5 package is installed? 
You can also try opening any other hdf5 file, to make sure that is not it \
Simple case like
```python
df = vaex.from_arrays(x=[1, 2, 3])
df = vaex.export('test.hdf5')
df2 = vaex.open('test.hdf5')
```

I guess these are the first steps. 

Although I have to say (personally) I've had various issues when installing vaex via anaconda that I could not quite figure out, so I've moved fully to using either miniconda or just pip.

**Comment by elisabettabiondi** [comment]
Hi,

thank you for the help. I am using anaconda, and I have installed these versions:
```
{'vaex': '4.1.0',
 'vaex-core': '4.1.0',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.7.0',
 'vaex-server': '0.4.0',
 'vaex-astro': '0.8.0',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.11.1'}
```
I have tried the first two lines of your code, and I got this error:
`Traceback (most recent call last):

  File "<ipython-input-11-c18b6981df59>", line 1, in <module>
    df = vaex.export('test.hdf5')

AttributeError: module 'vaex' has no attribute 'export'`

**Comment by JovanVeljanoski** [comment]
Sorry I made a mistake.. 

should be 

`df.export(..)`

**Comment by elisabettabiondi** [comment]
Ok. I obtain the following message:

```
Traceback (most recent call last):

  File "<ipython-input-12-d5d0b17a6b31>", line 1, in <module>
    df.export('test.hdf5')

  File "C:\Users\Biondi\Anaconda3\lib\site-packages\vaex\dataframe.py", line 6000, in export
    self.export_hdf5(path, progress=progress, parallel=parallel)

  File "C:\Users\Biondi\Anaconda3\lib\site-packages\vaex\dataframe.py", line 6207, in export_hdf5
    from vaex.hdf5.writer import Writer

  File "C:\Users\Biondi\Anaconda3\lib\site-packages\vaex\hdf5\writer.py", line 5, in <module>
    import h5py

  File "C:\Users\Biondi\Anaconda3\lib\site-packages\h5py\__init__.py", line 33, in <module>
    from . import version

  File "C:\Users\Biondi\Anaconda3\lib\site-packages\h5py\version.py", line 15, in <module>
    from . import h5 as _h5

  File "h5py\h5.pyx", line 1, in init h5py.h5

ImportError: DLL load failed: The specified procedure could not be found.
```

**Comment by JovanVeljanoski** [comment]
Yeah ok. 

So I am not 100% sure here.. but this is what I think. 

Vaex is just not installed properly. I believe the main reason for this is that with anaconda, the environment comes with lots of pre-specidfied packages, which may or may not work with what vaex wants. 

My best suggestion would be to try a fresh installation in a new environment, preferably via miniconda or pipenv. 

Or try to find which package / dependency is causing the problem, which from the above stacktrace looks to be h5py (but I personally would not go down this road). 

Sorry I can't help more.. :S

@maartenbreddels 
We should test better how vaex behaves when installed under full anaconda - and  see if we can offer some pre-emptive suggestions. I see a bunch of issues for basic things, most of which come when people use vaex with anaconda.. 

I might try this myself as soon as I get a chance.

**Comment by elisabettabiondi** [comment]
Hello,

I have installed miniconda and spyder as well (which I use to write and run codes). Using the anaconda prompt, I have installed vaex. But, when I type on Spyder 
`import vaex`
it doesn't find the module.
`
ModuleNotFoundError: No module named 'vaex'`

I guess it's a problem that spyder is not correctly linked to anaconda... Can you help me?

Thank you

**Comment by JovanVeljanoski** [comment]
Hi, 

I've not used spyder.. but in general, if that was installed via anaconda, that is probably linked to a different environment. 
Maybe you can try installing spyder via miniconda, or make sure that the IDE you are using (Spyder, vscode, pycharm whatever) is using the right miniconda environment. I don't know how to do that with Spyder, but most editors and IDEs should have an obvious way of doing it, since it is common that one does this often (changing of python environments).

**Comment by elisabettabiondi** [comment]
Actually, I have installed spyder using the Anaconda prompt that has been installed with miniconda. In fact, it is named "Anaconda Prompt (miniconda3)", so it should work...

**Comment by JovanVeljanoski** [comment]
Is there a way you can start an ipython terminal and see if you can import vaex there?
Or see/confirm which environment the spyder IDE uses?

**Comment by elisabettabiondi** [comment]
Ok. I have opened python from the prompt. It can import vaex without errors. 
Instead of using Spyder, can you suggest me any other software? My OS is Windows

**Comment by JovanVeljanoski** [comment]
So that means that spyder is not using the right python environment. You can try to google and see how to set that up if you prefer spyder. Maybe the link that I shared the other day has some hints?

Otherwise - nowadays VSCode is very popular, and is easy to choose/which python environments with it. I know Pycharm/IntelliJ idea is also popular, but it also might require some knowledge to set up vaex/python envs on it (I am not a user of that so I don't know, just from what I see on the issue board here). 

Jupyter notebooks for interactive work, and bunch of other text/code editors like sublimetext, vim etc.. might be also popular.

**Comment by elisabettabiondi** [comment]
Ok. thank you very much for the suggestions. I'll try with one of these!
