### ISSUE TITLE
Opening multiple files with vaex.open on aws s3 fails with *.parquet

### ISSUE THREAD

**Issue by AdrianoNicolucci** [vaexio/vaex#1356]
**Description**
I am trying to open multiple parquet files on AWS S3 with 
`vaex.open('s3://s3bucket/data/file*.parquet',  fs_options=fs_options)`  and I get the error:
```
ERROR:MainThread:vaex:error opening ''s3://s3bucket/data/file_1.parquet.gz.parquet'
ERROR:MainThread:vaex:error opening 's3://s3bucket/data/file*.parquet'
OSError: When getting information for key ''s3://s3bucket/data/file_1.parquet.gz.parquet' in bucket 's3bucket': AWS Error [code 100]: No response body.
```
However, I get no error when attempting to open a single parquet file without using *. 
Is using * with files on AWS not supported? 

**Software information**
 - Vaex version: 4.1
 - Vaex was installed via: pip
 - OS: Windows 10

**Comment by maartenbreddels** [comment]
Hi,

thanks for the report. Can you check if this works for you:
```python
import vaex
vaex.open('s3://vaex/taxi/yellow*v2.parquet', fs_options={'anon': True})
```

which works for me:
![image](https://user-images.githubusercontent.com/1765949/119343120-4f827c80-bc96-11eb-9fb1-4abe81cb23c4.png)

Also, which pyarrow do you have installed?

Regards,

Maarten

**Comment by AdrianoNicolucci** [comment]
Thank you for your response maarten,

I was able to get this working after re-installing vaex and insuring that pyarrow >= 3.0.0. It looks like it did not work with pyarrow version was = 2.0.0. I'm closing this bug as I no longer think this is a bug.
