### ISSUE TITLE
 [BUG-REPORT] TypeError in shuffle while exporting

### ISSUE THREAD

**Issue by kiranscaria** [vaexio/vaex#1360]
**Description**
> df.export("shuffled", shuffle=True)
throws TypeError: export() got an unexpected keyword argument 'shuffle' 

In the example given at https://vaex.io/docs/example_ml_iris.html, the recommended way for shuffling for large datasets is given as:
>df.export("shuffled", shuffle=True)
>df = vaex.open("shuffled.hdf5)
>df_train, df_test = df.ml.train_test_split(test_size=0.2)

But adding the argument 'shuffle', throws TypeError.

The error can however be solved by shuffling while loading the dataset.
>df.export("shuffled.hdf5")
>df = vaex.open("shuffled.hdf5", shuffle=True)
>df_train, df_test = df.ml.train_test_split(test_size=0.2)

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: {'vaex': '4.1.0',
 'vaex-core': '4.1.0',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.7.0',
 'vaex-server': '0.4.0',
 'vaex-astro': '0.8.0',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.11.1'}
 
 - Vaex was installed via: pip
 - OS: ubuntu 20.10

**Additional information**
![image](https://user-images.githubusercontent.com/29411721/118909357-89731c00-b940-11eb-986c-c43730c9d176.png)

**Comment by maartenbreddels** [comment]
Hi,

thanks for the report.
In #1003 we removed the shuffle argument, and how it should be `df.shuffle().export(..)`
@JovanVeljanoski can you check why CI didn't pick this up? Do we skip running that cell, or do we not test that notebook?

@kiranscaria do you want to update the docs on this and make a PR?

Regards,

Maarten

**Comment by maartenbreddels** [comment]
Hah, Jovan was on it already in #1369 👍

**Comment by JovanVeljanoski** [comment]
Just added a PR addressing this, and few other docs things.

It is not picked up in CI, as that code is not run, but is there as an example. Updated in the PR.
