### ISSUE TITLE
[BUG-REPORT] DataFrame concatenation error with virtual columns

### ISSUE THREAD

**Issue by tgdcat** [vaexio/vaex#1361]
**Description**
Running the following code will result in an error.
It will succeed if you do not use the virtual column.
```python
import numpy as np
import vaex

col_1 = np.array([1,2])
col_2 = np.array(['test1', 'test2'])
df1 = vaex.from_arrays(a=col_1, b=col_2)
df1['new_col'] = df1.a * 3

col_3 = np.array([3,4])
col_4 = np.array(['test3', 'test4'])
df2 = vaex.from_arrays(a=col_3, c=col_4)

res_df = vaex.concat([df1, df2])

# Exception has occurred: KeyError
# "Virtual column not found: 'new_col'"
#   File "C:\work\test\verify\main.py", line 28, in <module>
#     res_df = vaex.concat([df1, df2])
```
**Software information**
 - Vaex version {
      'vaex-core': '4.1.0',
      'vaex-hdf5': '0.7.0'
  }
 - Vaex was installed via: pip 
 - OS: Windows (Version 2004, build 19041.985)
 - Python 3.8.7

**Additional information**
Adding'new_col' to df2 succeeds, but I'd like to find another idea if possible.

**Comment by maartenbreddels** [comment]
Hi, what is the expected behavior?

**Comment by tgdcat** [comment]
Hi, thank you for your reply.

The expected behavior is to 'concat' a DataFrame with virtual columns.
Currently, an error will occur if 'new_col' (virtual column) exists in df1 and 'new_col' does not exist in df2.

Specifically, I want the following result when I run the code in the first post.
```
  #    a  b        new_col    c
  0    1  'test1'  888        --
  1    2  'test2'  999        --
  2    3  --       --         'test3'
  3    4  --       --         'test4'
```

**Comment by tgdcat** [comment]
I installed Vaex 4.4.0 and tried it, and the problem was fixed.
  
Thank you for helping me.
@maartenbreddels 
@SyureNyanko
