### ISSUE TITLE
[BUG-REPORT] Error thrown when performing groupby with certain columns

### ISSUE THREAD

**Issue by sanjivyash** [vaexio/vaex#1362]
**Description**
The following code gives an error in the jupyter notebook
```python
import vaex
pokemon = vaex.from_csv("pokemon_data.csv")
pokemon.groupby(pokemon["Type 1"]).agg("count")
```
The counter part from pandas framework works perfectly
```python
import pandas as pd
pd_df = pd.read_csv("pokemon_data.csv")
pd_df.groupby("Type 1").count().head(5)
```
There are no NaN values in the column ```Type 1```

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:  
 ```
{'vaex-core': '4.1.0',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.7.0',
 'vaex-jupyter': '0.6.0',
 'vaex-arrow': '0.5.1'}
```
 - Vaex was installed via: ```pip install vaex-core vaex-viz vaex-jupyter vaex-arrow vaex-hdf5```
 - OS: Ubuntu 20.04

**Additional information**
Error Output
![image](https://user-images.githubusercontent.com/58814491/119026379-b8ca6d00-b9c2-11eb-9ca3-19e8029141ec.png)
Info of the dataframe
![image](https://user-images.githubusercontent.com/58814491/119026945-63db2680-b9c3-11eb-90c7-633a2a430b5e.png) 
The data file is [pokemon_data.csv](https://github.com/vaexio/vaex/files/6517904/pokemon_data.csv)

**Note**
This error is not produced when I use any other column for groupby except ```Type 1``` and ```Type 2```

**Comment by maartenbreddels** [comment]
Hi thanks, this should be fixed in #1362 soon.
