### ISSUE TITLE
Leave logging configuration to client code

### ISSUE THREAD

**Issue by ynouri** [vaexio/vaex#1366]
**Description**

The `import vaex` statement enforces an opinionated logging configuration. This prevents the client code to set a different logging configuration. For example:

```
import logging
import vaex

logging.basicConfig(level=logging.INFO, format="%(levelname)s --> %(message)s")
logger = logging.getLogger(__name__)

if __name__ == "__main__":
    logger.info("Logging config is usually left to client code.")
```
does output:
```
INFO:MainThread:__main__:Logging config is usually left to client code.
```
instead of:
```
INFO --> Logging config is usually left to client code.
```

**Source code responsible for this behavior**

https://github.com/vaexio/vaex/blob/master/packages/vaex-core/vaex/__init__.py#L626

**Suggested solution**

Encapsulate the logging configuration *recommended* by Vaex in a function that is not executed at module import. This leaves the user freedom to choose to use the Vaex logging config, or their own logging config.

For example:

```
import vaex
vaex.set_logging_basic_config()
```

**Thanks**

Thank you for this awesome and exciting project!

**Comment by JovanVeljanoski** [comment]
Hi, 

This is a very reasonable request and something that I agree that should be done. Would you be comfortable to taking this on and doing a PR?

Thanks!

**Comment by maartenbreddels** [comment]
I agree, we should not do that. Might be convenient to have some env vars to control this. e.g.:
```
$ VAEX_LOG=debug python myvaex.py
```
