### ISSUE TITLE
Issue in joining[in vaex]

### ISSUE THREAD

**Issue by datascientistpur** [vaexio/vaex#1370]
Hi Team,

I was trying vaex for the first time on NYC trip data and I came across some issues.

Request you to help out.

I am not sure if the following issue is a bug or I'm going wrong somewhere:
![image](https://user-images.githubusercontent.com/62737832/119356100-abafc580-bcc3-11eb-95d4-464acd0b1898.png)
1. I downloaded monthly traffic data and was trying to create some columns.To perform sample join I tried joining the column to the main base.But here the RAM consumption rose to 50+GB
2. The join seems to have some issue as The columns values are being generated for  a sample[PFB the sampe]:
![image](https://user-images.githubusercontent.com/62737832/119356725-6049e700-bcc4-11eb-900c-0d8c79e9105b.png)

However post joining I get errors:
![image](https://user-images.githubusercontent.com/62737832/119356821-79eb2e80-bcc4-11eb-9ac4-97b0d1929466.png)

What could be the issue?

**Comment by datascientistpur** [comment]
Hi Team,

Strange,restarting python resolved the issue. Closing the issue

**Comment by maartenbreddels** [comment]
Any idea what caused it?

**Comment by datascientistpur** [comment]
Nope,I wasn't able to recreate it.But only concern is join takes lot of RAM

**Comment by datascientistpur** [comment]
When joining*
