### ISSUE TITLE
Cassandra Result Set DataFrame conversion

### ISSUE THREAD

**Issue by hacker1111** [vaexio/vaex#1383]
Hi Vaex Team,

I'm working one use case and I'm using Cassandra for data retrieval and I found Cassandra Cluster Result Set. So convert it into a data frame I'm using pandas.

This is the code I use:-
cass1 = cassquery.getDataFromTableName4("DatabaseName"+'.TableName')
getDataFromTableName4 function just have Cassandra query to get the rows with provided table name and database name
So this is what I get as cass1

![image](https://user-images.githubusercontent.com/17443937/120606349-bb21d200-c46c-11eb-9246-8a0981855d2a.png)
and to convert it to our favorable data frame we use pandas as this:

df = pd.DataFrame(list(cass1))

Now the real problem begins:
cass1 line runs in 1 seconds and grabs the table data into Cassandra cluster Result Set Format as share in above image.

When we convert it to a data frame using pandas it took around 20 minutes to convert the Cassandra result set which contains 20 lakh rows. 

So is there any way to make it faster using your library because your library gives us a big hope to read large data.

*Note :
We don't want to convert the data to any format such as hdf5 or csv and read after that. We want it to convert the Cassandra cluster set into a proper data frame within seconds. 
Please Help us. We need to reduce the time

**Comment by JovanVeljanoski** [comment]
Hi, 

I am surprised that converting the data to pandas takes that long. Following your example, how long does this take:
```python
data_list = list(cass1)
```
so just listifying the data before pandas even starts touching it..  If the code above is slow, i don't think there is anything we can do about it.  Please try and let us know. 

Also - vaex shines when the data is in memory mappable format (hdf5, arrow, parquet), so for optimal performance that is recommended.

**Comment by hacker1111** [comment]
@JovanVeljanoski 
First of all thank you so much for answering my queries. We already are listifying our data. We have about 1.5 crore rows data and to listifying, it took around 20 minutes.

**Comment by JovanVeljanoski** [comment]
Hey, 

Can you please use stardard/conventional ways for the numbers, not everyone is familiar with the (
Indian numbering system (things like lakh, crore etc..). 

Anyway - so you see that converting the cassandra data into a python list is taking a lot of time - not really converting the data to pandas. So vaex would be the same. I have not used Cassandra data myself in this way, so I don't know a good way to speed this up... Maybe @maartenbreddels might have some idea.

Another thing is.. if the data is static, you can just pay the price of waiting once, and load the data in vaex, save to hdf5/arrow/parquet, and then the next time you load the data it will be instant.

**Comment by hacker1111** [comment]
@JovanVeljanoski 
1.5 crore rows means 15 million rows. The data is not static. Thank you for the answer.
@maartenbreddels If you have any idea on this thing?

**Comment by maartenbreddels** [comment]
As Jovan is saying, your problem has nothing to do with Pandas or Vaex, it's about getting the Cassandra results into arrays (NumPy or Arrow) in a fast way. I think you need to find a way not to go via lists.
