### ISSUE TITLE
How to use countplot() in plotly with VAEX data frame? 

### ISSUE THREAD

**Issue by bhargav-inthezone** [vaexio/vaex#1390]
Cell 1:
df_train = vaex.open('file')
df_train.head(10) 

Cell 2:
df_train['Census_ProcessorClass'].value_counts() # has 4 distinct integer classes

Cell 3: 
df_train['HasDetections'].value_counts() # has 2 distinct integer classes

Cell4:
fig = px.histogram(df_train , x = 'Census_ProcessorClass' , color = 'HasDetections')
fig.show()

Giving a Value Error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-32-bd025f361b36> in <module>
----> 1 fig = px.histogram(df_train, x ='Census_ProcessorClass' , color = 'HasDetections', barmode = 'relative')
      2 fig.show()

/opt/conda/lib/python3.7/site-packages/plotly/express/_chart_types.py in histogram(data_frame, x, y, color, facet_row, facet_col, facet_col_wrap, facet_row_spacing, facet_col_spacing, hover_name, hover_data, animation_frame, animation_group, category_orders, labels, color_discrete_sequence, color_discrete_map, marginal, opacity, orientation, barmode, barnorm, histnorm, log_x, log_y, range_x, range_y, histfunc, cumulative, nbins, title, template, width, height)
    454             histnorm=histnorm, histfunc=histfunc, cumulative=dict(enabled=cumulative),
    455         ),
--> 456         layout_patch=dict(barmode=barmode, barnorm=barnorm),
    457     )
    458 

/opt/conda/lib/python3.7/site-packages/plotly/express/_core.py in make_figure(args, constructor, trace_patch, layout_patch)
   1859     apply_default_cascade(args)
   1860 
-> 1861     args = build_dataframe(args, constructor)
   1862     if constructor in [go.Treemap, go.Sunburst] and args["path"] is not None:
   1863         args = process_dataframe_hierarchy(args)

/opt/conda/lib/python3.7/site-packages/plotly/express/_core.py in build_dataframe(args, constructor)
   1376 
   1377     df_output, wide_id_vars = process_args_into_dataframe(
-> 1378         args, wide_mode, var_name, value_name
   1379     )
   1380 

/opt/conda/lib/python3.7/site-packages/plotly/express/_core.py in process_args_into_dataframe(args, wide_mode, var_name, value_name)
   1181                         if argument == "index":
   1182                             err_msg += "\n To use the index, pass it in directly as `df.index`."
-> 1183                         raise ValueError(err_msg)
   1184                 elif length and len(df_input[argument]) != length:
   1185                     raise ValueError(

ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of [0] but received: Census_ProcessorClass

Someone please me the reason and solution for this error.

**Comment by JovanVeljanoski** [comment]
Hi, 

You are likely trying to use plotly express with a vaex dataframe. As far as I know, plotly express currently only works with pandas dataframes, and numpy arrays. 

This is not an issue with vaex, it should be supported on the plotly side. 

The way to use plotly with vaex at the moment, is to do your aggregation / computation with vaex, then cast the data to a format plotly (express) understands.
