### ISSUE TITLE
AttributeError: module 'pyarrow.lib' has no attribute '_Weakrefable'

### ISSUE THREAD

**Issue by bhargav-inthezone** [vaexio/vaex#1395]
Hey!,
 I'm working with kaggle notebooks for a competition. I am getting this error while importing VAEX

!pip install vaex # successfully installed

import vaex
print(vaex.__version__)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-2d4bdef9460d> in <module>
----> 1 import vaex
      2 import vaex.ml
      3 print(vaex.__version__)

/opt/conda/lib/python3.7/site-packages/vaex/__init__.py in <module>
     39 import six
     40 
---> 41 import vaex.dataframe
     42 import vaex.dataset
     43 from vaex.functions import register_function

/opt/conda/lib/python3.7/site-packages/vaex/dataframe.py in <module>
     15 import threading
     16 import six
---> 17 import vaex.utils
     18 # import vaex.image
     19 import numpy as np

/opt/conda/lib/python3.7/site-packages/vaex/utils.py in <module>
     24 
     25 from .json import VaexJsonEncoder, VaexJsonDecoder
---> 26 import vaex.file
     27 
     28 

/opt/conda/lib/python3.7/site-packages/vaex/file/__init__.py in <module>
     12 
     13 import pyarrow as pa
---> 14 import pyarrow.fs
     15 
     16 import vaex.file.cache

/opt/conda/lib/python3.7/site-packages/pyarrow/fs.py in <module>
     22 from pyarrow.util import _is_path_like, _stringify_path
     23 
---> 24 from pyarrow._fs import (  # noqa
     25     FileSelector,
     26     FileType,

/opt/conda/lib/python3.7/site-packages/pyarrow/_fs.pyx in init pyarrow._fs()

AttributeError: module 'pyarrow.lib' has no attribute '_Weakrefable'

**Comment by maartenbreddels** [comment]
Hi,

as you can see from the error message, the problem lies with pyarrow. If I google for the last error msg, I find this:
https://github.com/apache/arrow/issues/2468
Hopefully this helps.
If you fixed it, please let us know how.

Regards,

Maarten

**Comment by bhargav-inthezone** [comment]
> Hi,
> 
> as you can see from the error message, the problem lies with pyarrow. If I google for the last error msg, I find this:
> [apache/arrow#2468](https://github.com/apache/arrow/issues/2468)
> Hopefully this helps.
> If you fixed it, please let us know how.
> 
> Regards,
> 
> Maarten

Yeah I fixed it thanks!

**Comment by maartenbreddels** [comment]
> If you fixed it, please let us know how.

could you let us know how? :)
