### ISSUE TITLE
How to replace all the  strings  in a column that contain a specific word with the word?

### ISSUE THREAD

**Issue by bhargav-inthezone** [vaexio/vaex#1396]
Hi,

Please help me with the expression :

df_train['Census_InternalBatteryType'].str.title().str.replace( df_train['Census_InternalBatteryType'].str.contains('li'), 'li')

above Expression = str_replace(str_title(text), df_train['Census_InternalBatteryType'].str.contains('li'), 'li')
I thought this expression would convert all the words in the column(Census_InternalBatteryType) that contains 'li' to 'li' but I got an error.

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/vaex/scopes.py in evaluate(self, expression, out)
    105             # logger.debug("try avoid evaluating: %s", expression)
--> 106             result = self[expression]
    107         except KeyError:

/opt/conda/lib/python3.7/site-packages/vaex/scopes.py in __getitem__(self, variable)
    165             if variable not in self.values:
--> 166                 raise KeyError("Unknown variables or column: %r" % (variable,))
    167 

KeyError: 'Unknown variables or column: "str_replace(str_title(Census_InternalBatteryType), str_contains(Census_InternalBatteryType, \'li\'), \'li\')"'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/vaex/dataframe.py in data_type(self, expression, array_type, internal, axis)
   1994             try:
-> 1995                 data = self.evaluate(expression, 0, 1, filtered=False, array_type=array_type, parallel=False)
   1996             except:

/opt/conda/lib/python3.7/site-packages/vaex/dataframe.py in evaluate(self, expression, i1, i2, out, selection, filtered, array_type, parallel, chunk_size)
   2665         else:
-> 2666             return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
   2667 

/opt/conda/lib/python3.7/site-packages/vaex/dataframe.py in _evaluate_implementation(self, expression, i1, i2, out, selection, filtered, array_type, parallel, chunk_size, raw)
   5794                     scope.buffers[expression] = out
-> 5795                 value = scope.evaluate(expression)
   5796                 # if isinstance(value, ColumnString) and not internal:

/opt/conda/lib/python3.7/site-packages/vaex/scopes.py in evaluate(self, expression, out)
    111             # eval("def f(")
--> 112             result = eval(expression, expression_namespace, self)
    113             result = auto_encode(self.df, expression, result)

<string> in <module>

/opt/conda/lib/python3.7/site-packages/vaex/arrow/numpy_dispatch.py in wrapper(*args, **kwargs)
    135         kwargs = {k: unwrap(v) for k, v, in kwargs.items()}
--> 136         result = f(*args, **kwargs)
    137         return wrap(result)

/opt/conda/lib/python3.7/site-packages/vaex/functions.py in decorated(x, *args, **kwargs)
    129         else:
--> 130             return f(x, *args, **kwargs)
    131     return decorated

/opt/conda/lib/python3.7/site-packages/vaex/functions.py in str_replace(x, pat, repl, n, flags, regex)
   1769     """
-> 1770     sl = _to_string_sequence(x).replace(pat, repl, n, flags, regex)
   1771     return column.ColumnStringArrow.from_string_sequence(sl)

TypeError: replace(): incompatible function arguments. The following argument types are supported:
    1. (self: vaex.superstrings.StringSequenceBase, arg0: str, arg1: str, arg2: int, arg3: int, arg4: bool) -> vaex.superstrings.StringSequenceBase

Invoked with: <vaex.superstrings.StringList32 object at 0x7f4277fb37f0>, array([False]), 'li', -1, 0, False

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/vaex/scopes.py in evaluate(self, expression, out)
    105             # logger.debug("try avoid evaluating: %s", expression)
--> 106             result = self[expression]
    107         except KeyError:

/opt/conda/lib/python3.7/site-packages/vaex/scopes.py in __getitem__(self, variable)
    165             if variable not in self.values:
--> 166                 raise KeyError("Unknown variables or column: %r" % (variable,))
    167 

KeyError: 'Unknown variables or column: "str_replace(str_title(Census_InternalBatteryType), str_contains(Census_InternalBatteryType, \'li\'), \'li\')"'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/opt/conda/lib/python3.7/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

/opt/conda/lib/python3.7/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

/opt/conda/lib/python3.7/site-packages/vaex/expression.py in __repr__(self)
    513     if not os.environ.get('VAEX_DEBUG', ''):
    514         def __repr__(self):
--> 515             return self._repr_plain_()
    516 
    517     def _repr_plain_(self):

/opt/conda/lib/python3.7/site-packages/vaex/expression.py in _repr_plain_(self)
    543             expression = expression[:57] + '...'
    544         info = 'Expression = ' + expression + '\n'
--> 545         dtype = self.dtype
    546         if self.expression in self.ds.get_column_names(hidden=True):
    547             state = "column"

/opt/conda/lib/python3.7/site-packages/vaex/expression.py in dtype(self)
    305     @property
    306     def dtype(self):
--> 307         return self.df.data_type(self.expression)
    308 
    309     # TODO: remove this method?

/opt/conda/lib/python3.7/site-packages/vaex/dataframe.py in data_type(self, expression, array_type, internal, axis)
   1995                 data = self.evaluate(expression, 0, 1, filtered=False, array_type=array_type, parallel=False)
   1996             except:
-> 1997                 data = self.evaluate(expression, 0, 1, filtered=True, array_type=array_type, parallel=False)
   1998         if data_type is None:
   1999             # means we have to determine it from the data

/opt/conda/lib/python3.7/site-packages/vaex/dataframe.py in evaluate(self, expression, i1, i2, out, selection, filtered, array_type, parallel, chunk_size)
   2664             return self.evaluate_iterator(expression, s1=i1, s2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
   2665         else:
-> 2666             return self._evaluate_implementation(expression, i1=i1, i2=i2, out=out, selection=selection, filtered=filtered, array_type=array_type, parallel=parallel, chunk_size=chunk_size)
   2667 
   2668     def evaluate_iterator(self, expression, s1=None, s2=None, out=None, selection=None, filtered=True, array_type=None, parallel=True, chunk_size=None, prefetch=True):

/opt/conda/lib/python3.7/site-packages/vaex/dataframe.py in _evaluate_implementation(self, expression, i1, i2, out, selection, filtered, array_type, parallel, chunk_size, raw)
   5793                 if out is not None:
   5794                     scope.buffers[expression] = out
-> 5795                 value = scope.evaluate(expression)
   5796                 # if isinstance(value, ColumnString) and not internal:
   5797                 #     value = value.to_numpy()

/opt/conda/lib/python3.7/site-packages/vaex/scopes.py in evaluate(self, expression, out)
    110             # logger.debug("in eval")
    111             # eval("def f(")
--> 112             result = eval(expression, expression_namespace, self)
    113             result = auto_encode(self.df, expression, result)
    114             self.values[expression] = wrap(result)

<string> in <module>

/opt/conda/lib/python3.7/site-packages/vaex/arrow/numpy_dispatch.py in wrapper(*args, **kwargs)
    134         args = list(map(unwrap, args))
    135         kwargs = {k: unwrap(v) for k, v, in kwargs.items()}
--> 136         result = f(*args, **kwargs)
    137         return wrap(result)
    138     return wrapper

/opt/conda/lib/python3.7/site-packages/vaex/functions.py in decorated(x, *args, **kwargs)
    128             return wrapper(x)
    129         else:
--> 130             return f(x, *args, **kwargs)
    131     return decorated
    132 

/opt/conda/lib/python3.7/site-packages/vaex/functions.py in str_replace(x, pat, repl, n, flags, regex)
   1768     4         way.
   1769     """
-> 1770     sl = _to_string_sequence(x).replace(pat, repl, n, flags, regex)
   1771     return column.ColumnStringArrow.from_string_sequence(sl)
   1772 

TypeError: replace(): incompatible function arguments. The following argument types are supported:
    1. (self: vaex.superstrings.StringSequenceBase, arg0: str, arg1: str, arg2: int, arg3: int, arg4: bool) -> vaex.superstrings.StringSequenceBase

Invoked with: <vaex.superstrings.StringList32 object at 0x7f4277fb36b0>, array([False]), 'li', -1, 0, False

**Comment by JovanVeljanoski** [comment]
If I understand correctly what you are trying to do.. something like this is perhaps what you are looking for:

```python
import vaex

x = ['sometimes', Something, 'never']
df = vaex.from_arrays(x=x)

df['x_title'] = df.x.str.title()

# The condition is if "Some" appears then do stuff
cond = df.x_title.str.contains('Some')

df['x_ready'] = cond.where('replaced', df.x_title)
```

I think you were using `replace` incorrectly, check the docstring. 

Also perhaps in the future for "how to" questions it is better to use the discussion board, unless you suspect a proper bug?

Cheers!
