### ISSUE TITLE
Can Vaex Drop Rows?

### ISSUE THREAD

**Issue by Kendidi** [vaexio/vaex#1399]
Hi,

I wonder is it possible to drop rows of data read from a HDF5 file when column values meet a certain criteria (E.g. “x < 5”) and then save the data back to a different HDF5 file?

Thanks a lot in advance!

**Comment by JovanVeljanoski** [comment]
Yes of course, something like

```python
df = vaex.open('some_file.hdf5')
df_filtered = df[df.x < 5] # this creates a shallow copy so takes no memory

df_filtered.export('filtered_file.hdf5')
```

Is this what you meant?

**Comment by Kendidi** [comment]
Hi Jovan,

Yeah. Something like that. Thank you so much!!
Do I need a loop to iterate each row?  

Best Regards
Kenneth Wong

**Comment by JovanVeljanoski** [comment]
No, the filter, i.e. `df[df.x > 5]` is applied to the full dataframe. 

In general you would be hard pressed to find a legitimate reason to use any kinds of loops with vaex... 

Also, in the future for "how to" and such questions can you please use the discussion board? 
The issues is fine too if you suspect a genuine bug etc.. 

Thanks!

**Comment by Kendidi** [comment]
I see. Thank you very much for your help! Appreciate it. :)

Best Regards
Kenneth Wong
