### ISSUE TITLE
[BUG-REPORT] multiple problems with Vaex

### ISSUE THREAD

**Issue by vsraptor** [vaexio/vaex#1400]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your problem may already be discussed or addressed.

**Description**
Please provide a clear and concise description of the problem. This should contain all the steps needed to reproduce the problem. A minimal code example that exposes the problem is very appreciated.

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
 - Vaex was installed via: pip / conda-forge / from source 
 - OS:
 vaex.__version__                                                                                                                                                    
Out[14]: 
{'vaex': '4.2.0',
 'vaex-core': '4.2.0',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.7.0',
 'vaex-server': '0.4.1',
 'vaex-astro': '0.8.1',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.12.0',
 'vaex-arrow': '0.5.1'}
Linux
**Additional information**
Please state any supplementary information or provide additional context for the problem (e.g. screenshots, data, etc..).

1. read_csv() convert fails : 

Trying to load and convert a csv file to hdf5, but vaex fails !!!

        df = vaex.from_csv('./data/out/lines',convert=True)                                                                                                     

       OSError: Cannot open ./data/out/lines.hdf5 nobody knows how to read it.

its a single string field.. i see the .hdf5 file created

2. Reading csv, then saving it as .arrow and then opening the arrow file breaks my code for several reasons.

   //did this to accomodate read_csv even that i used : self.df = vaex.from_csv(file,convert=False, sep=':', dtype={'id':np.int32,'txt':str})                                                              

---> 39                         ix = int(i) 

> TypeError: int() argument must be a string, a bytes-like object or a number, not 'pyarrow.lib.Int32Scalar'

---> 40                         if ix % 10 == 0 :  ...... 

> TypeError: unsupported operand type(s) for %: 'pyarrow.lib.Int32Scalar' and 'int'

---> 41                         curr_txt = self.df[ix][1]

> TypeError: 'NoneType' object is not subscriptable

they just happen one after another ... very brittle ... btw i first made my code works with read_csv()

 I just want a reliable way to convert large csv file to some format that vaex will memory-map.
If possible w/o using alot of memory (only read_csv() does that , right ?) and w/o breaking the rest of the assumptions !! 

May be some sort of type mapping w/o losing the memmap !!

{'vaex': '4.2.0',
 'vaex-core': '4.2.0',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.7.0',
 'vaex-server': '0.4.1',
 'vaex-astro': '0.8.1',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.12.0',
 'vaex-arrow': '0.5.1'}

**Comment by maartenbreddels** [comment]
> they just happen one after another ... very brittle

this is _the_ way to convince me to spend my free time solving your issues.

If only you provided a way for me to reproduce it (like providing some data that causes the issue), I wouldn't have to guess 🤔 

I'd say, try again when you are in a better mood.
