### ISSUE TITLE
Allow creating df from SQL.

### ISSUE THREAD

**Issue by moheikal79** [vaexio/vaex#1424]
Hi,
Thanks for your efforts to create such amazing package. As a user, I'd like to see the ability to create a df from SQL query. 

Regards

**Comment by JovanVeljanoski** [comment]
This is already documented:
https://vaex.io/docs/example_io.html#In-memory-data-representations

**Comment by maartenbreddels** [comment]
@moheikal79 let us know what actions you took to find out if this was possible or not, maybe we can improve the docs from your feedback.

cheers,

Maarten

**Comment by moheikal79** [comment]
@maartenbreddels thanks for your reply, I was expecting to see it in the API page in I/O section, such API that allow direct creation from the SQL source as CSV not through a Pandas df. 

https://vaex.io/docs/api.html

**Comment by JovanVeljanoski** [comment]
`from_csv` also goes through pandas - this is just a convenience wrapper since it is such a common operation. Pandas does an excellent job of interfacing with all kinds of in memory data structures / sources. No need to re-create the wheel I don't think, unless there is some obvious gain, such as performance improvement and the like.. 

If you have any ideas on how we can improve this, i.e. what is already possible via pandas, please share them!

**Comment by moheikal79** [comment]
@JovanVeljanoski Thanks for your reply, I am new to Vaex and as I know it can manage a size of data the Pandas cannot. Also most of companies data is in a DB. So, if Vaex can directly read from DB with its unique feature of not copying data to memory, it will be a great advantage. 
Regards

**Comment by JovanVeljanoski** [comment]
Yeah I understand completely what you are asking for, and I agree it would be awesome if we could do that, but I am afraid it is not so simple..

It is true that vaex can handle data that is much larger than available ram, but to do so the data itself must be in a particular file format (HDF5 or arrow). Alternatively the data can be in-memory (if read from csv, or via pandas). You will still get some performance and memory management bonuses from vaex.

So for now, you will have to have a separate process to extract the data from a database into a vaex-friendly format, and then use vaex. If your data fits in memory, you can just go via pandas. There are some solutions/libraries that can extract data from some databases quite fast based on arrow, if you are interested in this i think @maartenbreddels can point you in the right direction.

**Comment by moheikal79** [comment]
Thanks @JovanVeljanoski, it's now clear the course of actions needed to pull data from a DB, I tried your advice and it works fine. DB>Arrow file>Vaex.
Regards

**Comment by JovanVeljanoski** [comment]
Great, I am glad it works for you!
