### ISSUE TITLE
[BUG-REPORT] pip install is broken

### ISSUE THREAD

**Issue by FrankBoermanTenneT** [vaexio/vaex#1445]
there are many other closed issues about this but it still pops up for me. If I do ```pip install vaex-core vaex-hdf5``` and then try to import vaex it it cant find ANY of the submodules. I have also tried the more general ```pip install vaex``` with same results.

I have tried everything, reinstalling multiple times, cleared pip cache etc. It just never works somehow. It used to work for me but I am on a new virtual machine and now I cant install anymore.

I am running python3.9 on latest centos. installed packages:
```
Package         Version
--------------- -----------
aplus           0.11.0
blake3          0.1.8
certifi         2021.5.30
chardet         4.0.0
cloudpickle     1.6.0
dask            2021.6.2
frozendict      2.0.3
fsspec          2021.6.1
future          0.18.2
h5py            3.3.0
idna            2.10
locket          0.2.1
nest-asyncio    1.5.1
numpy           1.21.0
pandas          1.2.5
partd           1.2.0
pip             21.1.2
progressbar2    3.53.1
pyarrow         4.0.1
python-dateutil 2.8.1
python-utils    2.5.6
pytz            2021.1
PyYAML          5.4.1
requests        2.25.1
setuptools      57.0.0
six             1.16.0
tabulate        0.8.9
toolz           0.11.1
urllib3         1.26.6
vaex-core       4.3.0.post1
vaex-hdf5       0.8.0
wheel           0.36.2
```

when I try to open a hdf5 file I get:
```
ModuleNotFoundError: No module named 'vaex.hdf5'
```

very frustrating to not get it to work :( anybody any ideas?

**Comment by maartenbreddels** [comment]
Could you try with pip `20.2.3` ? First uninstall vaex-core and vaex-hdf5, downgrade pip, and install again. Please let us know if that works.

**Comment by FrankBoermanTenneT** [comment]
hi @maartenbreddels thanks for the fast response. I have cleared my cache, removed my virtual env, remade my virtualenv downgraded the pip version inside virtualenv en installed vaex-core and vaex-hdf5. exact same problem

output of pip list:
```
Package         Version
--------------- -----------
aplus           0.11.0
blake3          0.1.8
certifi         2021.5.30
chardet         4.0.0
cloudpickle     1.6.0
dask            2021.6.2
frozendict      2.0.3
fsspec          2021.6.1
future          0.18.2
h5py            3.3.0
idna            2.10
locket          0.2.1
nest-asyncio    1.5.1
numpy           1.21.0
pandas          1.2.5
partd           1.2.0
pip             20.2.3
progressbar2    3.53.1
pyarrow         4.0.1
python-dateutil 2.8.1
python-utils    2.5.6
pytz            2021.1
PyYAML          5.4.1
requests        2.25.1
setuptools      57.0.0
six             1.16.0
tabulate        0.8.9
toolz           0.11.1
urllib3         1.26.6
vaex-core       4.3.0.post1
vaex-hdf5       0.8.0
wheel           0.36.2
WARNING: You are using pip version 20.2.3; however, version 21.1.3 is available.
```

**Comment by JovanVeljanoski** [comment]
@FrankBoermanTenneT May I also ask you to try with pip==20.0.1 please?

**Comment by FrankBoermanTenneT** [comment]
@JovanVeljanoski nope same result. pip output:
```
Package         Version    
--------------- -----------
aplus           0.11.0     
blake3          0.1.8      
certifi         2021.5.30  
chardet         4.0.0      
cloudpickle     1.6.0      
dask            2021.6.2   
frozendict      2.0.3      
fsspec          2021.6.1   
future          0.18.2     
h5py            3.3.0      
idna            2.10       
locket          0.2.1      
nest-asyncio    1.5.1      
numpy           1.21.0     
pandas          1.2.5      
partd           1.2.0      
pip             20.0.1     
progressbar2    3.53.1     
pyarrow         4.0.1      
python-dateutil 2.8.1      
python-utils    2.5.6      
pytz            2021.1     
PyYAML          5.4.1      
requests        2.25.1     
setuptools      57.0.0     
six             1.16.0     
tabulate        0.8.9      
toolz           0.11.1     
urllib3         1.26.6     
vaex-core       4.3.0.post1
vaex-hdf5       0.8.0      
wheel           0.36.2     
WARNING: You are using pip version 20.0.1; however, version 21.1.3 is available.
```
```
pip -V
pip 20.0.1 from<snip>/venv/lib/python3.9/site-packages/pip (python 3.9)
```

**Comment by JovanVeljanoski** [comment]
Ah wait, I think we misunderstood you issue.. 

Can you import vaex alright? So the problem happen when you are trying to open an hdf5 file?

Can you maybe paste a short code snippet of the stuff that is causing the problem? I thought it is an installation issue, but upon reading your OP I am thinking maybe it is something else.. 

If vaex imports ok, and you have problems reading hdf5 files, can you please try downgrading h5py to version 3.2.0?

**Comment by FrankBoermanTenneT** [comment]
@Jbollenbacher I can not open a hdf5 file because the import fails.
this works:
```
import vaex
```
this does not work:
```
import vaex.hdf5
```
this also doesnt work with the same error
```
import vaex
df = vaex.open("<path>/file.hdf5")
```
the error being:
```
ModuleNotFoundError: No module named 'vaex.hdf5'
```
downgrading the h5py version did not do anything to the problem

**Comment by FrankBoermanTenneT** [comment]
I have now also downgraded to vaex-core==4.2.0 and vaex-hdf5==0.7.0 as this is the versions of my windows install which has anaconda installed. on linux again this does not work.

**Comment by maartenbreddels** [comment]
Was this from a clean environment, or did you install vaex in some form before?

An idea
 * uninstall vaex
 * Check your site-packages for leftovers (use `python -c "import sys; print(sys.prefix)"` to find your prefix, and check if anything is left in `$PREFIX/lib/python3.9/site-packages/vaex*`
 * Remove those
 * install vaex again

**Comment by JovanVeljanoski** [comment]
That is very strange. 

In addition to what Maarten said, it might be nice to print out
```python
import vaex
print(vaex.__file__)

import site
print(site.getsitepackages())
```

To make sure the right environment is being used.

**Comment by FrankBoermanTenneT** [comment]
@maartenbreddels each of my answers was with a completely clean virtual environment. as in I do rm -rf venv

@JovanVeljanoski both of those prints point correctly to my virtual environment folder

**Comment by maartenbreddels** [comment]
Could you let us know each step, so we can try to reproduce it, or maybe even a Dockerfile if that is easy for you.

**Comment by FrankBoermanTenneT** [comment]
@maartenbreddels 

I simply do:
```
rm -rf venv
rm -rf ~/.cache/pip
virtualenv venv
pip install vaex-core vaex-hdf5
```
thats it, can you try that on your side? I am running python3.9

**Comment by JovanVeljanoski** [comment]
I just tried installing in python 3.9 in a clean environment via pip like you say, under linux. The only difference is that the environment manager is conda. Worked fine..

**Comment by FrankBoermanTenneT** [comment]
@JovanVeljanoski did you do conda install ? or with pip inside of conda? because conda install is taking ages for me....

**Comment by JovanVeljanoski** [comment]
I installed everything in pip, just the env management is code (i said this above..).

Yeah conda is slow, but mamba is super fast, so I use that when I install packages via conda(forge).

**Comment by FrankBoermanTenneT** [comment]
@JovanVeljanoski oh sorry I read past that. So I just installed with pip in my conda environment and that works! but that is really strange. the main difference I see now is that the latest conda  is python 3.8 instead of 3.9?

**Comment by JovanVeljanoski** [comment]
That is probably the default. You can just use:

```
conda create -n myenv python=3.9
```

And it will create a pythong 3.9 env.

**Comment by FrankBoermanTenneT** [comment]
@JovanVeljanoski that also worked! this is very weird that it works in p3.9 in conda but not in my "normal" virtualenv. Thanks for helping me!

**Comment by JovanVeljanoski** [comment]
Yeah, also do not understand why.. i might build a docker image and try things out, see if I can reproduce this issue. 
I know sometimes pip updates have messed around with the vaex install process, but no idea what is happening now :S

Happy you got it working!

(I've also not tried pipenv, would be curious to know if that works.. maybe you can also try? :D)

**Comment by FrankBoermanTenneT** [comment]
@JovanVeljanoski yeah something to investigate later perhaps. I am running on centos 8 stable if you want to try out the exact same setup with docker :P

**Comment by Eisbrenner** [comment]
Hi :wave: 

in case this issue evolves in a bit of a review of the versioning and packaging; here (below) the output of poetry (my personal favorite dependency manager, https://python-poetry.org/):
```
$ poetry add vaex 
Creating virtualenv mypkg in /home/mypkg/.venv
Using version ^4.3.0 for vaex

Updating dependencies
Resolving dependencies... (2.2s)

  SolverProblemError

  Because no versions of vaex match >4.3.0,<5.0.0
   and vaex (4.3.0) depends on vaex-core (>=4.3.0-post.1,<5), vaex (>=4.3.0,<5.0.0) requires vaex-core (>=4.3.0-post.1,<5).
  So, because no versions of vaex-core match >=4.3.0-post.1,<5
   and mypkg depends on vaex (^4.3.0), version solving failed.
```

I don't know if poetry is too strict or what the issue is, but I will be happy if this gets resolved either way! :grin: 

Until then, I use Conda, which works fine.

**Comment by XufengXufengXufeng** [comment]
vaex has too many dependencies, it's prone to errors when installing. docker image would be really helpful. @JovanVeljanoski

**Comment by JovanVeljanoski** [comment]
If you look in the repo, in  the `ci` folder, there are instructions to running all the tests in docker. You could modify that I guess to have a docker environment if you want. 

But we've figured that a conda env, and installing vaex either via conda-forge or pip works very well indeed. 

Also, you don't need to install the whole of vaex if you don't need it. You can just go with vaex-core and maybe vaex-hdf5. 

As for the dependencies, what do you propose we remove?

**Comment by XufengXufengXufeng** [comment]
> If you look in the repo, in the `ci` folder, there are instructions to running all the tests in docker. You could modify that I guess to have a docker environment if you want.
> 
> But we've figured that a conda env, and installing vaex either via conda-forge or pip works very well indeed.
> 
> Also, you don't need to install the whole of vaex if you don't need it. You can just go with vaex-core and maybe vaex-hdf5.
> 
> As for the dependencies, what do you propose we remove?

Thank you for your response. I had problem installing vaex with older version of miniconda, version 4.3.27. But I have installed vaex sucessfully with the latest miniconda. However, for my deploy system, the miniconda is old and offline. Updating conda is not easy, but I guess I can use the ci folder and latest miniconda to make docker images. So my problem is solved, thank you.

**Comment by maartenbreddels** [comment]
> vaex has too many dependencies

Just want to emphasize what @JovanVeljanoski said, to avoid dependency issues, vaex is a meta package that depends on all the other packages. See https://vaex.io/docs/index.html you might only need vaex-core.
