### ISSUE TITLE
[FEATURE-REQUEST]

### ISSUE THREAD

**Issue by Leo-Ji2020** [vaexio/vaex#1446]
I have a request:
    After groupby a vaex dataframe, how can I get the first row of each group to build a new vaex dataframe?
    for example:

     import numpy as np
     import vaex

     x=np.random.randint(1, 5, 20)
     df = vaex.from_arrays(x=x, y=x**2)

     dff = df.groupby(df.x)
  
     now, I want to concat the first row of each group to build a new dataframe. how to do that?

**Comment by kmcentush** [comment]
This will actually have a similar solution to https://github.com/vaexio/vaex/issues/1448, so I recommend you follow that issue in addition to this one.

**Comment by JovanVeljanoski** [comment]
Indeed, like @kmcentush  said. 

Anyway here is a belated example

```python
import vaex

df = vaex.example()
g = df.groupby('id')

dfs = []
for _, df_tmp in g:
    dfs.append(df_tmp[:1]) 

df2 = vaex.concat(dfs)
df2 = df2.trim()  # this will make things faster. 
```
