### ISSUE TITLE
How to select null/NaN?

### ISSUE THREAD

**Issue by ridlo** [vaexio/vaex#146]
I am sorry, I can not find it in the documentation, is there a simple way to select rows which has NaN/null value in a certain column?

Cheers,

**Comment by JovanVeljanoski** [comment]
Hi, 

There are a couple of ways you can do this. One simple way is to just do:
`ds.select('(x != x) ', name='nan_select')`

This takes advantage of the fact that `np.nan` is not equal to anything, not even itself. Note that you need python >2.5 for this to be reliable. 

Another way is to select the non-missing values in a column, and just take the inverse of that selection
https://docs.vaex.io/en/latest/api.html#vaex.dataset.Dataset.select_non_missing

I hope this helps!
Jovan.

**Comment by maartenbreddels** [comment]
that is a good idea. If you don't want a selection, you can create a filtered dataset like this:`dsnan = ds[ds.x != ds.x]`.

I think we should support `isnan()`, so you could do `dsnan = ds[ds.x.isnan()]`.

@ridlo if you want to make a PR, I can give you some pointers.

**Comment by ridlo** [comment]
Thank you for the solution.

@maartenbreddels  do you mean PR for this trick in the Vaex documentation? or the enhancement itself?

**Comment by maartenbreddels** [comment]
Hi Ridlo,

Ah enhancement itself, if you think you can do that?
I think it is as simple as adding isnan to the list here: https://github.com/vaexio/vaex/blob/master/packages/vaex-core/vaex/functions.py

It will be added to the Expression class by its metaclass https://github.com/vaexio/vaex/blob/805dfb2fd8d01571ffb2dfbf315ecb538ab269d9/packages/vaex-core/vaex/expression.py#L96

A sanity test in https://github.com/vaexio/vaex/tree/master/tests (functions_test.py ?) that would check if this gives the same result maybe.

Let me know, I can help you through the process, if not, no hard feelings

cheers,

Maarten

**Comment by DougRzz** [comment]
@maartenbreddels  I didn't know it was that easy to add your own functions into Vaex!   I have just got rolling mean (Pandas) and numpy.gradient to work.  This is super useful, particularly for time series analysis.  I also tried numpy.interp but it didn't work.  I was hoping somthing like `interp(channelName,[1000,2000,3000], [345,456,567])` would work. I don't think a list of numbers can be passed into an expression.

**Comment by ridlo** [comment]
I also didn't know that it was that easy!

**Comment by maartenbreddels** [comment]
I think lists are supported, numpy arrays are a bit more tricky, i'm working on that.
I think it would be good to document and give examples on how to add custom functions (globally and per dataframe).

**Comment by maartenbreddels** [comment]
we now have df.x.isnan/isna/ismissing https://docs.vaex.io/en/latest/api.html#vaex.expression.Expression.ismissing
