### ISSUE TITLE
Memory Error while trying to export data in an infitine while loop[BUG-REPORT]

### ISSUE THREAD

**Issue by bsbalkar** [vaexio/vaex#1467]
**Description**

Hello Everyone

I was running an infinite loop which was getting data from sql. I converted this sql data to pandas dataframe and finally to vaex dataframe.
After that, I had added some addition of column and merging another dataframe to the same dataframe.
Everything was running fine till now in the infinite loop. Even used memry_profiler, everything was fine till now.
But then i added the command "df.export_parquet("data.parquet",chunk_size=100000)". But the command was always ended up in memory error in the same while loop.
I tried using "df.export.hdf5("data.hdf5",chunk_size=100000)", but it also resulted in the same error.
Can anyone help.

I'm running the below function in an infinite while loop.
My PC is having 16 GB RAM.
If I'm not adding the code to export the data in hdf5 or parquet form in the end then the loop is running fine without any memory   
error. But after trying to export in the end of function i receive memory error.
I used memory_profiler and i got to know that if the the overall memory consumption before exporting data is around than 1500 MiB than it's fine. But if it's around 2000 MiB or more than it's showing Memory Error.

``` python
import os
import vaex
import pandas as pd
import numpy as np



def createFile():
    #Consider df2 as the back of my sql file
    if os.path.isfile('./testpdfile.parquet.parquet.gzip') == True:
        df2 = pd.read_parquet(r'testpdfile.parquet.gzip')
    else:
        df2 = pd.DataFrame(np.random.randint(1, 10, size=(4500000, 45)), columns=list("ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$"
                                                                                 "%^&*()123456789"))
    #I don't know sql connection here to show in example with required number of columns in the data and the data
    #I'm using can't be share here
    # After reading the df2 file i got to know how many rows I'm having right now and I'll fetch data from sql
    #starting after the last row of my back up file. Let's create a dummy data for it.

    df4 = pd.DataFrame(np.random.randint(1, 10, size=(2, 45)), columns=list("ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$"
                                                                                 "%^&*()123456789"))

    df2 = pd.concat([df2,df4])

    df2.sort_values(by='A',inplace=True)

    #I have to save this file again to create a backup for again fetching data from sql in the same way after
    # every minute

    df2.to_parquet('testpdfile.parquet.gzip', compression = 'gzip')

    df2 = vaex.from_pandas(df2)
    df2['calculatedcolumn'] = df2.A + df2.B
    df2['calculatedcolumn2'] = df2.A + df2.B / df2.D
    df2['calculatedcolumn3'] = df2.A + df2.R / df2.D

    df2.join(df1, on='A', how="left", inplace=True)
    df2.join(df3, on='B', how="left", inplace=True)

    df2.export_hdf5('testDataFile.hdf5',chunk_size=100000)
```

Thanks
Balkar Singh

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
 - {'vaex': '4.3.0',
 -  'vaex-core': '4.3.0.post1',
 -  'vaex-viz': '0.5.0',
 -  'vaex-hdf5': '0.8.0',
 -  'vaex-server': '0.5.0',
 -  'vaex-astro': '0.8.2',
 -  'vaex-jupyter': '0.6.0',
 -  'vaex-ml': '0.12.0'}
 
 - Vaex was installed via: pip / conda-forge / from source 
 - pip
 
- OS:
 - Windows 10

**Additional information**
I'm using vaex in PyCharm instead of in Jupyter Notebook, as ultimately i wanna use it with my Dash Application for doing quick calculations for my Dashboard.

**Comment by JovanVeljanoski** [comment]
Can you please answer the questions that you skipped during filling in the issue ticket? Otherwise it is quite hard for us to help you. 

Also can you include a code example of what you are trying to do, as well as the error message you are getting?
Code describes the situation much better than works!

Thanks

**Comment by bsbalkar** [comment]
Thanks @JovanVeljanoski for your quick response. Really Appreciated.
I had added as much information that i could provide in it.
Sorry for the code block, i tried my best to put it up in the code block but it's not coming up properly.

**Comment by JovanVeljanoski** [comment]
Hi,

Thanks for the info. Can you please tell us the number of column you have in the final dataframe that you are trying to export? 
If you have a large number of columns, perhaps it is worth reducing the `chunk_size` parameter in the export method. Would that work? 

The usage of the IDE should not matter if your python environment is set up properly, so that's ok, you are free to use whatever you want :).

**Comment by bsbalkar** [comment]
Hello

Reducing chunk_size is working with this example. I had reduces chunk_size to 10000. But it has also increased the time taken to save the file.
I'll test the same with my sql database too and tell you about the result.
Though i require 50 columns with 1000000 rows but my real sql data contains datetime, strings floats too that's so it was showing memory error with 1000000 rows only.
Do i have to keep reducing chunk_size if my dataframe size increases? My sql database will keep on adding upto 50000 rows every month.

**Comment by bsbalkar** [comment]
I tried using this by fetching data from my sql server and it was still showing memory error even after i reduced chunk_size.
I was using pyodbc for fetching data from mysql.
Is there anything wrong with using vaex with pyodbc

**Comment by JovanVeljanoski** [comment]
i don't know anything about pyodbc. If it can fetch data for you in a format that vaex or pandas can understand, then you can try using it for sure. 

well, you need to some memory to pull the data from the database. That is not related to vaex in any way..  

You can take a look at pandas, they have a way to connect to a sql database. See what the optimal / largest number of rows you can pull at one time, then save it locally to hdf5 or so. Then you can work with the data, and do whatever you need to.

**Comment by bsbalkar** [comment]
I'll try to replicate another example with the help of pyodbc if possible. And will share the results with you over here.

**Comment by JovanVeljanoski** [comment]
I will close this thread as inactive. Please re-open if needed, or if you have more information on this @bsbalkar
