### ISSUE TITLE
[FEATURE-REQUEST] Addition/substraction not possible on DataFrameLocal?

### ISSUE THREAD

**Issue by yohplala** [vaexio/vaex#1468]
**Description**
Hi! As said in a previous ticket and discussion, I am a newbie to vaex, and I may not have an appropriate understanding of vaex paradigm yet. Please, bare with me.

I would like to operate a basic substraction between 2 dataframes.
Starting simple, I create these 2 dataframes from pandas at the moment.
Later on, data will be from 2 different set of parquet files, sharing the same number of rows. 

I tried following code.
```python
import vaex as vx
import pandas as pd

# Dataset
diff = pd.DataFrame({'variation_1': [0.01, 0.02, 0.005, -0.02, -0.01, -0.01],
                     'variation_2': [-0.01, 0.08, 0.08, 0.01, -0.02, 0.01],
                     'variation_3': [0.005, -0.03, -0.03, 0.002, 0.025, -0.03],
                                 })
pda = 2+diff
pdb = pd.DataFrame(2, columns=diff.columns, index=range(len(diff)))

# Conversion to vaex
vda = vx.from_pandas(pda, copy_index=False)
vdb = vx.from_pandas(pdb, copy_index=False)
vdd = vda - vdb
```

I then get an error message.
```python
vdd = vda - vdb
Traceback (most recent call last):

  File "<ipython-input-33-0221a4e2578a>", line 1, in <module>
    vdd = vda - vdb

TypeError: unsupported operand type(s) for -: 'DataFrameLocal' and 'DataFrameLocal'
```

**Is your feature request related to a problem? Please describe.**
Shoud not `DataFrameLocal` be able to accept operations such as addition & substraction?
I am thinking I am not understanding the logic with vaex here.
Should I join (while renaming columns of `vdb`) to have all data in a single DataFrame, then inside this DataFrame conduct said operations?

Thanks for your feedbacks,
Bests

**Comment by JovanVeljanoski** [comment]
Hello, 

Thanks for trying out vaex and for reaching out. 

Long story short, most operations are only possible withing a single dataframe. in fact ( i might be wrong here), but the only operations that work between 2 or more dataframes are `df.join` and `vaex.concat`.  I am short on time today and I can't go into details of why this is so (for now at least). 

So if possible I would suggest you do a join of the two tables/dataframes before you do any operation between them. 
Note that you can do an  "ordered" join, by not providing any column on which to join. In this case, the dataframes will be joined just based on row numbers. 

In my mind, if you need to do operations between two dataframes they need to be linked somehow for the results to make sense, so some kind of join should be possible..

**Comment by yohplala** [comment]
> So if possible I would suggest you do a join of the two tables/dataframes before you do any operation between them.
> Note that you can do an "ordered" join, by not providing any column on which to join. In this case, the dataframes will be joined just based on row numbers.
> 
> In my mind, if you need to do operations between two dataframes they need to be linked somehow for the results to make sense, so some kind of join should be possible..

Thanks a lot for your reply!
I am guessing joining makes sense according vaex paradigm to have all data in the same 'namespace' (aka 'vaex dataframe').

Speaking about 'namespace', and because such joining is compulsory in vaex, I wonder if it has not been implemented some 'convenient handle' to 'keep track of' / 'keep a handle on' all columns of each dataframe?

I have not yet tested `vx.concat`, but maybe the following makes sense:
```python
left = vaex.DataFrame()
right = vaex.DataFrame()
left = left.join(right)
# sum left and right (assuming their column has same names)
# 'left' and 'right' would be default namespace / pointer to all columns of left (resp. right) dataframes.
left['sum'] = left.left + left.right
```

Maybe this syntactic sugar is a 'bit too much'.
I ask this last question nonetheless: how would you manage this sum? / how would you 'conveniently' keep track of columns coming from left and coming from right?

Thanks for your help!
Bests,

PS: pandas is providing such 'convenience handle' by use of multi-level column in dex, and use of [`keys` parameter in `concat`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html)

```python
import pandas as pd
s1 = pd.DataFrame({'a':[1,2], 'b':[3,4]})
s2 = pd.DataFrame({'a':[1,2], 'b':[3,4]})
npd = pd.concat([s1, s2], keys=['left', 'right'], axis=1)

npd
Out[11]: 
  left    right   
     a  b     a  b
0    1  3     1  3
1    2  4     2  4
```
Summing left and right:
```python
 npd.left + npd.right
Out[12]: 
   a  b
0  2  6
1  4  8
```

I did not see it mentionned somewhere. Does vaex manage multi-level indexing?

Thanks again for your help. Sorry for all those questions. I believe you have a great library. Learning curve is probably not very steep, but my mind is too much 'pandas oriented' yet :)

**Comment by JovanVeljanoski** [comment]
Hi, 

Vaex does not (yet?) have the concept of indexing at all. Any column can serve as index in principle. But if your point is to keep track of which column came from which dataframe originally - that is easily done by providing prefix or suffix to the left or right dataframes when doing join (or both). In fact vaex will not let you join without specifying this when joining if you have columns with incidental names (since duplicate columns are not supported).

Does this help (maybe i missed your point entirely.. ).

**Comment by yohplala** [comment]
Hi @JovanVeljanoski 
Thanks for your feedback.
Based on our exchange, I tried joining. Joining is ok, but I keep the same error message when doing the substraction, while all data is in the same dataframe.
I am very sorry to ask again for help. Please, what am I missing here?

```python
import vaex as vx
import pandas as pd
# Test data
df = pd.DataFrame({'variation_1': [0.01, 0.02, 0.005, -0.02, -0.01, -0.01],
                   'variation_2': [-0.01, 0.08, 0.08, 0.01, -0.02, 0.01],
                   'variation_3': [0.005, -0.03, -0.03, 0.002, 0.025, -0.03],
                  })
pda = 2+df
pdb = pd.DataFrame(2, columns=df.columns, index=range(len(df)))
# Swich to vaex, and gather in a single dataframe.
vda = vx.from_pandas(pda, copy_index=False)
vdb = vx.from_pandas(pdb, copy_index=False)
vdf = vda.join(vdb, lprefix='l_', rprefix='r_')
# Substract
i_col = vda.get_column_names(regex='v*')
l_col = vdf.get_column_names(regex='l_*')
r_col = vdf.get_column_names(regex='r_*') 
vdf[i_col] = vdf[l_col] - vdf[r_col]
```
This results in:
```python
Traceback (most recent call last):

  File "<ipython-input-14-ba098d6bd615>", line 9, in <module>
    vdf[i_col] = vdf[l_col] - vdf[r_col]

TypeError: unsupported operand type(s) for -: 'DataFrameLocal' and 'DataFrameLocal'
```
Thanks in advance for any help.
Bests,

**Comment by JovanVeljanoski** [comment]
You can not subtract one dataframe from another (which is what you are doing). This is what the error message tells you.
You can only subtract one expression from another expression (both of which should live in the same dataframe). 

Same goes for any arithmetic operations I think.

**Comment by yohplala** [comment]
> You can not subtract one dataframe from another (which is what you are doing). This is what the error message tells you.
> You can only subtract one expression from another expression (both of which should live in the same dataframe).
> 
> Same goes for any arithmetic operations I think.

Ok, thanks. But can I keep 3 columns in an expression?
Or directly said, how can I convert a DataFrameLocal straight into an Expression? Is this feasible or is an Expression necessarily a single column?
(sorry for the possibly dumb question)

**Comment by JovanVeljanoski** [comment]
We call a single column of a vaex dataframe an Expression, since it does not have to be a in memory column, nor a data coming from a file. 

Maybe going through the [tutorial](https://vaex.readthedocs.io/en/latest/tutorial.html#Extending-Vaex) will clear some things up. 

If I am guessing correctly from your previous code example you probably need to do something like

```python
df[ans1] = df['a1'] - df['b1']
df[ans2] = df['a2'] - df['b2']
df[ans3] = df['a3] - df['b3']
# and so on
```

**Comment by yohplala** [comment]
Ok, I think an expression is necessarily a single column. It would be what seem to say the [tutorial](https://vaex.readthedocs.io/en/latest/tutorial.html#).

_Wrapped by an expression system e.g. `df.x`, `df['x']` or `df.col.x` is an Expression;_

_Columns/expression can perform lazy computations, e.g. `df.x * np.sin(df.y)` does nothing, until the result is needed._

As I see it, I leave th ticket open.
I think, being able to handle several columns in an expression is an interesting asset:
- to handle several computations in a single line of code as illustrated above
- also to be able to supply to a ufunc an array with several columns (I am understanding that it is not possible right now, because only expression are translated into numpy array, so only single columns). So [when adding function](https://vaex.readthedocs.io/en/latest/tutorial.html#Extending-Vaex) they can only work on a static number of columns, not a dynamic number of columns

I am modifying the title of the ticket however.
Please, feel free to close if this is a dead end.

**Comment by yohplala** [comment]
> Maybe going through the [tutorial](https://vaex.readthedocs.io/en/latest/tutorial.html#Extending-Vaex) will clear some things up.

Yes, thanks, it did.

> If I am guessing correctly from your previous code example you probably need to do something like
> 
> ```python
> df[ans1] = df['a1'] - df['b1']
> df[ans2] = df['a2'] - df['b2']
> df[ans3] = df['a3'] - df['b3']
> # and so on
> ```

Yes, but this is only the 1st step.
I can have any number of rows, but I could wrap this into a for loop, no trouble.

But then, I am targetting to feed this into a ufunc that I would have registered thanks to `@vaex.register_function()`.
I did not read thoroughly enough to see that I could not supply to a registered function a DataFrame but only a fixed number of columns. So I don't see how I can move on from this point.

**Comment by JovanVeljanoski** [comment]
maybe i do not understand what you are after.. can you provide a code example, or pseudocode at least?

If you need to do custom/specialized stuff for your project, perhaps custom dataframe accessors would the way to go? In that way you can create methods that take a whole dataframe as argument and do stuff.. 

You can also write normal python functions that take vaex dataframes as arguments, and define the logic of what happens in side that function..

**Comment by yohplala** [comment]
> maybe i do not understand what you are after.. can you provide a code example, or pseudocode at least?

In present case, I want to do row-wise aggregation. Whatever the number of columns, I will apply numpy function with `axis` parameter set to 1 to extract max and min (row-wise), compare them, and return a boolean per row depending these values.

This pseudo code below is an example of the function I had in mind to register with `@vaex.register_function()`.

```python
import numpy as np
import vaex as vx

@vx.register_function()
def min_max(ar):
    max_ = np.max(ar, axis=1)
    min_ = np.min(ar, axis=1)
    ratio = max_ / min_
    return ratio >= 2

ar = np.array([[0.1, 0.5, 0.01],
               [0.9, 0.5, 0.8],
               [0.77, 0.4, 0.2]])

vd['res'] = vd.func.min_max(vd[['x', 'y', 'z']])
```
 
> If you need to do custom/specialized stuff for your project, perhaps custom dataframe accessors would the way to go? In that way you can create methods that take a whole dataframe as argument and do stuff..
> 
> You can also write normal python functions that take vaex dataframes as arguments, and define the logic of what happens in side that function..

Yes, I understand at present time, I have to break down my computation in smaller steps, managing each column independently, and manage them in a for loop.
But do you think vaex could be able to achieve row-wise computation directly, adjusting dynamically to the number of columns if the numpy functions operating the calculations are able to?

Thanks again for being so patient with this lengthy description.
Have a good day, bests,

**Comment by maartenbreddels** [comment]
For reference, a lot of this is made possible in https://github.com/vaexio/vaex/pull/415 (not merged, not ready)

**Comment by yohplala** [comment]
Hi @JovanVeljanoski, hi @maartenbreddels,
Thanks a lot for your feedbacks both of you!
Ok, I could take time this evening to write what I think is 'appropriate vaex code' for my 'mysterious row-wise function'.
For reference (and also because I still have a tiny demand about it), please find it below with test data.
I could check that results are as expected.

The 'tiny' demand relates to the creation of a new column, initialized to '-1'.
`    data['gte'] = -1*np.ones(len(data), dtype=int)`
I would ideally have it taking no memory, and I would gladly accept any advice to have it as a virtual column if possible?

This is a 'tiny' demand because already, if I have only a single column in memory, memory efficience is much improved over the pandas scenario when `left` and `right` dataframes are both read from files and stored in memory.

Again, thanks a lot!

```python
import vaex as vx
from vaex.dataframe import DataFrameLocal
import numpy as np
import pandas as pd

# Implementation in pure vaex
def gte_by_row_vx(left: DataFrameLocal, right: DataFrameLocal,
                  thresh: float) -> DataFrameLocal:
    """
    Compare all 'variation_*' columns between 'left' and 'right', row per row.
    Return per row `True` if difference between row in 'left' and row in
    'right' is larger than or equal to 'thresh', except if difference is lower
    than or equal to '-thresh' for a preceding column.
    Return 'False' otherwise (i.e. when difference is in-between 'thresh' and
    '-thresh' whatever the column).

    Parameters:
        left (vx.DataFrameLocal):
            Left DataFrame.
        right (vx.DataFrameLocal):
            Right DataFrame
        thresh (float64):
            Threshold above which comparison returns `True` if no difference is
            lower than or equal to '-thresh' before.

    Returns:
        data (vx.DataFrameLocal):
            Vaex dataframe with boolean results in 'gte' column.

    """

    data = left.join(right, lprefix='l_', rprefix='r_')
    l_cols = data.get_column_names(regex='l_v*')
    r_cols = data.get_column_names(regex='r_v*')
    # Create column 'gte' initialized to '-1'.
    data['gte'] = -1*np.ones(len(data), dtype=int)
    for l_col, r_col in zip(l_cols, r_cols):
        data[l_col] = data[l_col] - data[r_col]
        data['gte'] = data.func.where(
                      (data.gte == -1) & (data[l_col] >= thresh), 1, data.gte)
        data['gte'] = data.func.where(
                      (data.gte == -1) & (data[l_col] <= -thresh), 0, data.gte)
    # Setting to 'False' rows that are still initialized to '-1'.
    data['gte'] = data.func.where(data.gte == -1, 0, data.gte)
    data['gte'] = data['gte'].astype('bool')
    
    return data.drop(l_cols + r_cols)

# Test data
threshold=0.02       #2%
df = pd.DataFrame({'variation_1': [0.01, 0.02, 0.005, -0.02, -0.01, -0.01],
                   'variation_2': [-0.01, 0.08, 0.08, 0.01, -0.02, 0.01],
                   'variation_3': [0.005, -0.03, -0.03, 0.002, 0.025, -0.03],
                  })
pda = 2+df
pdb = pd.DataFrame(2, columns=df.columns, index=range(len(df)))
vda = vx.from_pandas(pda, copy_index=False)
vdb = vx.from_pandas(pdb, copy_index=False)

# Test
res = gte_by_row_vx(vda, vdb, threshold)
```
Results.
```python
res
Out[17]: 
  #  gte
  0  False
  1  True
  2  True
  3  False
  4  False
  5  False
```

**Comment by JovanVeljanoski** [comment]
Hey, 

I don't have time at the moment to look at this at the moment, but a simple trick to get a virtual column of constant value is to do something like `df["some_numeric_column"] * 0 - 1` :D

But I agree we should have a method that does this, also for strings @maartenbreddels 

For the rest I'll try to have a better look as soon as I can

**Comment by JovanVeljanoski** [comment]
Hi, I had a look.. maybe i misunderstand something, but what is not working here? I think what you wrote should work?

If you want any comments about the code then DataFrameLocal is an internal thing, better to just used DataFrame. 
Also we no longer import vaex as vx, that has not been the case for years (vaex is short enough).

**Comment by yohplala** [comment]
> Hi, I had a look.. maybe i misunderstand something, but what is not working here? I think what you wrote should work?
> 
> If you want any comments about the code then DataFrameLocal is an internal thing, better to just used DataFrame.
> Also we no longer import vaex as vx, that has not been the case for years (vaex is short enough).

Hi @JovanVeljanoski 
Yes it works. (I wrote: 'I could check that results are as expected.')
I pasted the code so that someone that would get over this ticket as the final code.
And i do accept your feebdacks :) of for `DataFrame` instead of `DataFrameLocal` and `import vaex` :)
Thanks again, closing the ticket then.

**Comment by JovanVeljanoski** [comment]
cool!  Yeah sorry about that, I am conditioned to think that if there is something in the issues, that there is a problem with it :)
