### ISSUE TITLE
Please add support for Streaming plots and analysis to determine and handle data inconsistencies

### ISSUE THREAD

**Issue by AVINASH-T619** [vaexio/vaex#1474]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your request may already be discussed or addressed.

**Description**
Please add support for streaming plots and cross library support like pandas and vaex and add more functionalities to handle various missingness in the data/data inconsistencies like forward fill backward fill , data imputations etc.

**Is your feature request related to a problem? Please describe.**
Please describe the type of use-cases the proposed feature will address.

**Additional context**
Please state any supplementary information or provide additional context for the proposed functionality (e.g. workarounds, alternatives you have considered, etc..).

**Comment by JovanVeljanoski** [comment]
This kind of issue, more like a wishlist is not very helpful. We know there are many features we would still like to have, and are working on the things we think have the most impact and are possible to implement right now without scarifying what vaex is all about. 

- streaming plots: i don't know what this is. please give a detailed description on a pointer to some place that uses/explains that
- one can already read data from pandas, and export data as a pandas dataframe. 
- we already have `isna`, `ismissing` ,`isnan` which is more what most dataframe libraries implement actually. You are being quite vague on what you are requesting.  Same for their `fill` counterparts, regarding your data imputations.
- regarding forward/backwards fill, this is in the pipeline, we hope to get to it soon. It  was requested and is tracked in the another issues. 

Based on what you wrote, i'd kindly ask you to go over the docs, especially the tutorial and the notebook examples.
