### ISSUE TITLE
[BUG-REPORT] TypeError export_hdf5 keyword mode

### ISSUE THREAD

**Issue by arjen-hiemstra** [vaexio/vaex#1484]
**Description**
When trying to run the snippit from https://vaex.io/docs/example_io.html  under Exporting binary file formats:
```
import vaex

df1 = vaex.from_arrays(x=[1, 2, 3], y=[-0.5, 0, 0.5])
df2 = vaex.from_arrays(s1=['Apple', 'Orange', 'Peach'], s2=['potato', 'carrot', 'cucumber'])

df1.export_hdf5('C:\\output_hdf5_file_with_multiple_groups.hdf5', mode='w', group='/numbers')
df2.export_hdf5('C:\\output_hdf5_file_with_multiple_groups.hdf5', mode='a', group='/food')
```
I get the error:
```
TypeError: export_hdf5() got an unexpected keyword argument 'mode'
```
What am I missing?

**Software information**
 {'vaex': '4.3.0',
 'vaex-core': '4.3.0.post1',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.8.0',
 'vaex-server': '0.5.0',
 'vaex-astro': '0.8.2',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.12.0'}
 - Vaex was installed via: pip
 - OS: Windows 10

**Comment by JovanVeljanoski** [comment]
I guess the docs are following the latest master branch rather than the released version. 
So that feature is in, but it is not released yet. If you install from source it will work. 
Otherwise just remove those `mode` and `group` arguments.

**Comment by arjen-hiemstra** [comment]
@JovanVeljanoski Installing from source gave me the same error. It is the group argument I'm interested in. So removing it isn't an option.

**Comment by JovanVeljanoski** [comment]
Are you sure you are using the installation from source? Perhaps you are still picking up the old installation (this is a common occurrence, for my too..).  Can can do: 

```python
import vaex
vaex.__file__
```
to see which installation you are picking up. Maybe try in a clean/new environment?

This is implemented in the master branch - you can see the source. You can also try running the tests (or the specific parts of it), if you installed vaex from source. Let me know if you run into more issues!

**Comment by arjen-hiemstra** [comment]
It seems my install from source is going wrong. I tried installing in a clean venv from both windows 10 and ubuntu(WSL) both times I get the error: 
```
src/strings.cpp:7:10: fatal error: pybind11/pybind11.h: No such file or directory 

/vaex-master/setup.py", line 31, in run
        raise RuntimeError(f'Oops, failed to install {package}')
    RuntimeError: Oops, failed to install vaex-core
```
Suggestions?

**Comment by JovanVeljanoski** [comment]
Yeah you are missing the submodules. 
Please follow the instructions in the docs:
https://vaex.io/docs/installing.html#for-developers

**Comment by arjen-hiemstra** [comment]
@JovanVeljanoski  Correct. I got it working now.
