### ISSUE TITLE
Unable to install via PIP

### ISSUE THREAD

**Issue by fonty422** [vaexio/vaex#1497]
**Description**
Tried to install via pip and it failed with many errors.
**Software information**
 - pip: version: 21.2.3
 - Vaex install attempt via: pip
 - OS: Windows 10

**Additional information**

Attempted a full install vie `pip install vaex` and it failed with too many errors to put in here.
I also tried just to install the `vaex-core` part, which also failed as below:

`ERROR: Could not build wheels for vaex-core, pyarrow which use PEP 517 and cannot be installed directly`

Let me know if you need the full trace.

Note I do have full administrator rights.

**Comment by ashvinmanoj** [comment]
I just tried and it worked for me in a new virtual environment. 
Did you tried to install it in a new virtual environment?

**Comment by fonty422** [comment]
No, just trying to install on my local machine

**Comment by ashvinmanoj** [comment]
May be [this ](https://docs.anaconda.com/anaconda/navigator/tutorials/manage-environments/)helps to create a virtual environment. Its better to create a virtual environment for your projects so that you dont disturb other packages.

**Comment by maartenbreddels** [comment]
Hi,

> `ERROR: Could not build wheels for vaex-core, pyarrow which use PEP 517 and cannot be installed directly`

it's a problem with installing pyarrow it seems, can you try installing that first? That should trigger this issue.

cheers,

Maarten

**Comment by JovanVeljanoski** [comment]
Closing as stale. Please reopen if needed
