### ISSUE TITLE
[BUG-REPORT] Groupby misbehaves when one of the grouping columns contains missing values

### ISSUE THREAD

**Issue by humcasma** [vaexio/vaex#1500]
**Description**
If we try to group by one column that contains missing values, the result is erratic. 

Running
```
df1 = vaex.from_pandas(pd.DataFrame([1,2,3], columns=['idx']))
df2 = vaex.from_pandas(pd.DataFrame({'idx':[1,6,7], 'a': [0,0,0], 'b': [1,2,3]}))
df3 = df1.join(df2, how='left', on='idx')
df3.groupby(['idx', 'a']).agg({'b': 'sum'})
```
throws an exception:
`TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

However, if we save to Arrow and read back, the behavior is different. Sometimes a different exception is thrown:
`ArrowIndexError: Index -1 out of bounds`

Other times it does not fail and gives back a wrong result, which is really worrying:
```
df3.export('test.arrow')
z = vaex.open('test.arrow')
y = z.groupby(['idx', 'a']).agg({'b': 'sum'})
```
results in
```
z:
#	idx	a	b
0	1	0	1
1	2	--	--
2	3	--	--

and

y:
#	idx	a	b
0	1	0	1
1	2	0	0

```

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: {'vaex-core': '4.3.0.post1', 'vaex-hdf5': '0.8.0', 'vaex-ml': '0.12.0'}
 - Vaex was installed via: pip 
 - OS: Linux

**Comment by maartenbreddels** [comment]
Thanks for the report, I can confirm this is still an issue. I have an refactor planned that will also affect this part, I'll make sure it will also solve this.

**Comment by maartenbreddels** [comment]
@parinavcodes I just read that you were interested in this, but I worked on this in #1637

If there is anything else you want to contribute, let us know, or join our slack (see main README.md) to get up to speed.
