### ISSUE TITLE
[BIG THANK YOU]

### ISSUE THREAD

**Issue by Artyrm** [vaexio/vaex#1506]
25 000 000 strings.

Loaded from HDF5 in 300ms.

Joined by "MAC-address" field in 3s.

What can I say? Only "Big thank you" :) Sorry for using issues for that, it was the only way I found.

![image](https://user-images.githubusercontent.com/21180686/129058700-ef593c16-15bb-4114-b389-911691ee320f.png)

**Comment by maartenbreddels** [comment]
Hi, thanks for letting us know, and no need to excuse yourself for abusing issues for this :) Thanks!
