### ISSUE TITLE
[BUG-REPORT] RobustScaler is currenty broken

### ISSUE THREAD

**Issue by danielgafni** [vaexio/vaex#1511]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your problem may already be discussed or addressed.

**Description**
`vaex.ml.RobustScaler` is broken

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
     {'vaex-core': '4.3.0.post1',
     'vaex-viz': '0.5.0',
     'vaex-hdf5': '0.8.0',
     'vaex-jupyter': '0.6.0',
     'vaex-ml': '0.12.0'}

 - Vaex was installed via: pip (poetry)
 - OS: Ubuntu 20.04.2 LTS

**Additional information**
![image](https://user-images.githubusercontent.com/49863538/129332783-e5dd8d42-f588-4de2-9631-80a404b5ea98.png)

**Comment by JovanVeljanoski** [comment]
Hi, 

It is not a problem with RobustTransformer (or with `percentile_approx` thart the RobustTransformer uses), but with numpy.. Which numpy version do you have? Can you try numpy==1.19.5 ?

**Comment by JovanVeljanoski** [comment]
This should also work for numpy larger than 1.21.x on non windows OSes.
