### ISSUE TITLE
pip install fails on python 3.7.1 (gcc error)

### ISSUE THREAD

**Issue by nbecker** [vaexio/vaex#152]
compile fails with many errors like this:

```
    src/wcs.c: In function ‘__Pyx_ExceptionSave’:
    src/wcs.c:31410:21: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
         *type = tstate->exc_type;
                         ^~~~~~~~
                         curexc_type
```

**Comment by maartenbreddels** [comment]
Ah, that is a dependency of vaex-astro (kapteyn package) that needs porting to py37.
For the moment, you could install instead of the vaex metapackage (which is just a dependency package), install the packages you need:
```
$ pip install vaex-core vaex-hdf5 vaex-arrow vaex-viz
```

**Comment by maartenbreddels** [comment]
I'll mark it as a bug so we don't lose track, thanks ndbecker!

**Comment by nbecker** [comment]
Yes, the above install command completed OK.

May want to update the docs to show this as the suggested install.
