### ISSUE TITLE
[BUG-REPORT] fillna not work

### ISSUE THREAD

**Issue by gaodianzhuo** [vaexio/vaex#1534]
In [11]: df['ff']=df['ff'].fillmissing('missing')

In [12]: df.ff
Out[12]: 
Expression = ff
Length: 14 dtype: string (column)
---------------------------------
 0   a
 1
 2
 3   b
 4   c
 ...  
 9   a
10  Aa
11  BB
12  BB
13  BB

In [13]: df = df.fillna(value='missing', column_names=['ff'])

In [14]: df.ff
Out[14]: 
Expression = ff
Length: 14 dtype: string (column)
---------------------------------
 0   a
 1
 2
 3   b
 4   c
 ...  
 9   a
10  Aa
11  BB
12  BB
13  BB

In [15]: vaex.__version__
Out[15]: 
{'vaex': '4.4.0',
 'vaex-core': '4.4.0',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.9.0',
 'vaex-server': '0.6.0',
 'vaex-astro': '0.8.3',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.13.0'}

**Comment by JovanVeljanoski** [comment]
Can you please create a reproducible example?

**Comment by gaodianzhuo** [comment]
In [2]: df = vaex.open('dee.csv.parquet')

In [3]: df
Out[3]: 
#    a     b      bb     c     d      tt    label    中文    ff    g    gg    mynull
0    603   0.603  0.603  -217  0.36   a     0                a     a    c     --
1    183   0.183  0.183  32    0.175  a     0                      a    c     --
2    -103  0.103  0.103  34    0.33   b     0        是            a    c     --
3    63    0.063  0.063  11    0.175  b     0        是      b     a    c     --
4    48    0.048  0.048  6     0.125  c     0        是      c     a    c     --
...  ...   ...    ...    ...   ...    ...   ...      ...     ...   ...  ...   ...
9    6     0.063  0.063  34    0.175  a     1        是      a     b    d     --
10   6     0.063  0.063  34    0.175  Aa    1        是      Aa    b    d     --
11   10    0.063  0.063  34    0.175  BB    1        否      BB    b    d     --
12   10    0.063  0.063  34    0.175  BB    1        否      BB    b    d     --
13   10    0.063  0.063  34    0.175  BB    1        否      BB    b    d     --

**Comment by gaodianzhuo** [comment]
> Can you please create a reproducible example?
> 
> And perhaps format your post so we can read it more easily?
parquet File format

**Comment by JovanVeljanoski** [comment]
So, I will take a blind shot at this:

1) Fillna works fine, you can try this example:

```python
import vaex.ml
df = vaex.ml.datasets.load_titanic()
df['cabin'] = df.cabin.fillna('unknown')
print(df)
```

If this does not work, please report the error, or provide a reproducible example

2) Guess from your example, is that `fillna` works, but you think it is not imputing the "missing" values. 
Are you sure those "missing values" are not just empty strings, i.e. `''`. In this case those are valid samples, not missing, or N/A, so will not be imputed. If you want to change them, you need to use `where`, for example:

```python
df['x'] =  df.func.where(df.x == '', 'new_value', df.x)
```
This means that where df.x is an empty string (`''`),  then "new_value" will be put in its place, else keep the same value of x.

I hope this helps.
