### ISSUE TITLE
Removes column when cell is empty when using vaex.open('s3-path', convert='path')

### ISSUE THREAD

**Issue by juanr2001** [vaexio/vaex#1543]
Your issue content here.

My csv looks like this:

|----------------|
columnA
|----------------|
true
|----------------|
false
|----------------|
<[empty]>
|----------------|
true
|----------------|

When I call `vaex.open('s3_file.csv', convert='file.htf5')`

The error I get is:
`Object dtype dtype('O') has no native HDF5 equivalent`

vaex returns the table without `columnA`. 

I am using as a work around:
df = vaex.open(file_location, convert='tmp/' + name + '.hdf5', **{'na_filter': False})

Seems like it works, but this `na_filter` spikes memory a bit.

Is there an option I need to pass  thru `arg` or `kwargs` ex:
`vaex.open('s3 path', convert='file.htf5', ignore_na=False)`

FYI:
when I DO NOT use `convert` option vaex does NOT remove column.

**Comment by JovanVeljanoski** [comment]
Closing as inactive - please reopen if needed.
