### ISSUE TITLE
Travis-CI not working (and AppVeyor)

### ISSUE THREAD

**Issue by maartenbreddels** [vaexio/vaex#155]
#154 did not trigger travis, still an issue with the repo move. Also a good time to get appveyor up again, see #139

**Comment by rpfk** [comment]
I cannot recover the page, but I saw Travis being triggered by my pull request. From the pull request, I was able to visit the page on Travis CI and there I saw it was passing the tests for a number of Python versions, the others were still running. I'm not sure if it is of any help, but I thought it would be a good thing to share the experience I had with #154.

**Comment by maartenbreddels** [comment]
Yes, travis does get triggered, but the status is not visible on GitHub. Thanks!

**Comment by maartenbreddels** [comment]
fixed
