### ISSUE TITLE
'Open_many' does not fully support inconsistent columns names between hdf5 files

### ISSUE THREAD

**Issue by DougRzz** [vaexio/vaex#156]
I  would like to combine several hdf5 files into a Vaex dataset but where the column names and/or number of columns may be inconsistent.  The `open_many` command or the `open` command using the * wildcard does not support this.  See example code below which produces error.

Error message:
> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> ~\AppData\Local\Continuum\miniconda3b\lib\site-packages\vaex\scopes.py in evaluate(self, expression, out)
>      85             # logger.debug("try avoid evaluating: %s", expression)
> ---> 86             result = self[expression]
>      87         except:
> 
> ~\AppData\Local\Continuum\miniconda3b\lib\site-packages\vaex\scopes.py in __getitem__(self, variable)
>     130             if variable not in self.values:
> --> 131                 raise KeyError("Unknown variables or column: %r" % (variable,))
>     132 
> 
> KeyError: "Unknown variables or column: 'Channel2'"
> 

```python
import numpy as np
import vaex
import pandas as pd
import os

#cwd = os.getcwd() # Change this to your directory for path to save hdf
cwd = r'C:\Dougs\vaexNotebooks' # Write files to this directory.  Use a fast SSD for fast read calculations in Dask/Vaex

### Create random data
size = 20000 # number of rows
scale = 1.
scaleLocal = 20
np.random.seed(0)
y_data = np.cumsum(np.random.randn(size)  * scale) + np.random.randn(size) * scaleLocal

np.random.seed(1)
scaleLocal2 = 3
size2 = 30000 # number of rows
y_data2 = np.cumsum(np.random.randn(size2)  * scale) + np.random.randn(size2) * scaleLocal2


#Create 2x Pandas dataframes, same 1st channel, but different 2nd channel.
df1 = pd.DataFrame({'Channel1' : y_data,'Channel2' : y_data})
df2 = pd.DataFrame({'Channel1' : y_data2,'Channel3' : y_data2})

# Create a Vaex dataset from pandas and then export to hdf5
dataVX = vaex.from_pandas(df1)
dataVX.export_hdf5(os.path.join(cwd, 'randomData1.hdf'))

# Creat a Vaex dataset from pandas and then export to hdf5
dataVX2 = vaex.from_pandas(df2)
dataVX2.export_hdf5(os.path.join(cwd, 'randomData2.hdf'))

# Open both hdf files in Vaex using the wildcard *
# ds = vaex.open(os.path.join(cwd, 'randomData*.hdf'))
ds = vaex.open_many([os.path.join(cwd, 'randomData1.hdf'),os.path.join(cwd, 'randomData2.hdf')])

print(ds.count('Channel1')) ~ OK. 50000 count

print(ds.count('Channel2')) # Error output on this line, Expect to see a count of 30000

print(dataVX2.count('Channel3'))
```

**Comment by DougRzz** [comment]
Actually, it is not just hdf5.  Here is a more succinct example using vaex.concat. 

```python
import numpy as np
import vaex

size = 20000 # number of rows

ds1 = vaex.from_arrays(x=np.arange(size), y=np.arange(size))
ds2 = vaex.from_arrays(x=np.arange(size), z=np.arange(size))

ds = vaex.concat((ds1,ds2))

print(ds.count('x'))  # this give 40000. This is correct
print(ds.count('y'))  # error on this command. I would expect 20000. 
```

**Comment by maartenbreddels** [comment]
Ah, so you want to them to be replaced by missing values?

**Comment by DougRzz** [comment]
Hi @maartenbreddels Has this issue been flagged by anyone else?   I noticed you have recently been working on other vaex.concat / vaex.open_many issues so I thought I would bump this issue.  My current interim solution to this issue to write a column of NaNs to the hdf5 file if there is a missing column.  But this is difficult to manage and increases my disk space requirements.  The example below is the simplest way to describe the problem.

```python
import numpy as np
import vaex

size = 20000 # number of rows

ds1 = vaex.from_arrays(x=np.arange(size), y=np.arange(size))
ds2 = vaex.from_arrays(x=np.arange(size), z=np.arange(size))

ds = vaex.concat((ds1,ds2))

print(ds.count('x'))  # this give 40000. This is correct
print(ds.count('y'))  # error on this command. I would expect 20000. 
```

**Comment by maartenbreddels** [comment]
@JovanVeljanoski and I were talked about that today. He wants to have the same. I'm thinking about how to implement is.

**Comment by maartenbreddels** [comment]
This is fixed in https://github.com/vaexio/vaex/pull/1009 and the first alpha release that makes this possible https://pypi.org/project/vaex-core/4.0.0a4/
