### ISSUE TITLE
[BUG-REPORT] Is conda package up to date?

### ISSUE THREAD

**Issue by yohplala** [vaexio/vaex#1585]
Hi,
when installing vaex using anaconda
`conda install -c conda-forge vaex`

vaex-core 2.0.3 gets installed.
I am fighting with conda remove/install to remove it (ok) and ionstall last version that seems to be able ton conda-forge (4.5.1), but so far, my installation is not 'converging'

```bash
conda install -c conda-forge vaex-core=4.5.1
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving envrionment: -
```
and the last row runs for hours...

I saw a post in which @maartenbreddels you advise using mamba. I will give a try.

**Comment by yohplala** [comment]
omg!!!!
mamba is another world, love it!!! I lost I don't know how many hours that anaconda tried to 'solve the environment', and mamba did it in 10 seconds...
`mamba install vaex-core=4.5.1 -c conda-forge`
crazy...
ok, at least, I have vaex-core 4.5.1 now.
I leave the ticket open so that the package vaex in anaconda gets updated maybe?

bests,
Pierre

**Comment by yohplala** [comment]
trying to install each package separately, it seems vaex-arrow is creating troubles. It requires vaex-core to be downgraded from 4.5.0 to 2.0.3
![Screenshot from 2021-09-23 21-42-25](https://user-images.githubusercontent.com/13206058/134573363-41c2eab2-1916-4676-bc48-f13e425cbce8.png)

**Comment by maartenbreddels** [comment]
Weird, vaex arrow is deprecated, it should not be installed

**Comment by yohplala** [comment]
> Weird, vaex arrow is deprecated, it should not be installed

ok, thanks, I was reading the install doc and tried to install listed packages one by one.
https://vaex.io/docs/installing.html
`pip install vaex-core vaex-viz vaex-jupyter vaex-arrow vaex-server vaex-ui vaex-hdf5 vaex-astro`

Maybe the install doc should be updated.
And maybe the `vaex` module in conda-forge has not been updated, so it lists vaex-arrow?
Could this be possible?

**Comment by maartenbreddels** [comment]
https://github.com/conda-forge/vaex-feedstock/blob/master/recipe/meta.yaml
seems fine, do you want to open a PR to change the docs?

(from mobile phone)

**Comment by yohplala** [comment]
> do you want to open a PR to change the docs? (from mobile phone)

@maartenbreddels 
sure, see #1586

As said in the PR, I amde 3 changes, please review and confirm it is ok:
- adding `vaex-ml`
- removing `vaex-arrow`
- removing `vaex-ui`
(as per content of `meta.yaml`)

**Comment by yohplala** [comment]
Doc is updated
