### ISSUE TITLE
Problem installing with conda

### ISSUE THREAD

**Issue by andreyferriyan** [vaexio/vaex#159]
So I try to install vaex with conda, with this command:   

> conda install -c conda-forge vaex

Everything was fine but after I try to import. The vaex didn't work and show errors saying that "kapteyn" distribution was not found.    

> import vaex
ERROR:MainThread:vaex:issue loading astro
Traceback (most recent call last):
  File "D:\program\Anaconda3\envs\vaexenv\lib\site-packages\vaex\__init__.py", line 556, in <module>
    add_namespace = entry.load()
  File "D:\program\Anaconda3\envs\vaexenv\lib\site-packages\pkg_resources\__init__.py", line 2345, in load
    self.require(*args, **kwargs)
  File "D:\program\Anaconda3\envs\vaexenv\lib\site-packages\pkg_resources\__init__.py", line 2368, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "D:\program\Anaconda3\envs\vaexenv\lib\site-packages\pkg_resources\__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'kapteyn' distribution was not found and is required by the application   

I try to install the "kapteyn" distribution but it doesn't exist in the conda library. Is there anyone know how to resolve this ?

**Comment by maartenbreddels** [comment]
Strange that is still managed to get into conda-forge. I assume this is Python37? 

vaex is a meta-package that has as a dependency allmost all the other packages, one of them being vaex-astro (for astronomy, which has kapteyn as a dependency).
There are two things you can do:
 * use Python36
 * install what you need, `conda install -c conda-forge vaex-core vaex-hdf5 vaex-arrow vaex-viz`

**Comment by andreyferriyan** [comment]
Thank you for your fast response @maartenbreddels 

Unfortunately, still doesn't work. I'm using python 3.6.6.

> Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 11:48:23) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by maartenbreddels** [comment]
Could you elaborate on "doesn't work"?

**Comment by andreyferriyan** [comment]
I'm sorry, what I mean is same issue with "kapteyn" distribution was not found   

> import vaex
ERROR:MainThread:vaex:issue loading astro
Traceback (most recent call last):
  File "D:\program\Anaconda3\envs\vaexenv\lib\site-packages\vaex\__init__.py", line 556, in <module>
    add_namespace = entry.load()
  File "D:\program\Anaconda3\envs\vaexenv\lib\site-packages\pkg_resources\__init__.py", line 2345, in load
    self.require(*args, **kwargs)
  File "D:\program\Anaconda3\envs\vaexenv\lib\site-packages\pkg_resources\__init__.py", line 2368, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "D:\program\Anaconda3\envs\vaexenv\lib\site-packages\pkg_resources\__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'kapteyn' distribution was not found and is required by the application

**Comment by maartenbreddels** [comment]
Ah, I misread your initial report, my bad.

Try uninstalling vaex-astro:
```$ conda uninstall vaex-astro```

**Comment by andreyferriyan** [comment]
Great !, it works now !. I don't know why. But by uninstalling the vaex-astro I can import vaex now. It's weird because if we install with:   

> conda install -c conda-forge vaex   

I think vaex-astro will automatically install. Thank you @maartenbreddels for your help.

**Comment by maartenbreddels** [comment]
I'll keep this open until I know if it is a fluke or really an issue, thanks for reporting!

**Comment by rancdg** [comment]
Hi,
encountered the same thing, it happens on my windows system and not on my ubuntu system.
haven't explicitly uninstalled vaex-astro, but i used the conda forge command with vaex-astro excluded:
conda install -c conda-forge vaex-core vaex-viz vaex-server vaex-ui vaex-hdf5 vaex-distributed.
it didn't help.

**Comment by andreysfc** [comment]
As @maartenbreddels said, you can uninstall vaex-astro. I'm using Windows by the way and not GNU/Linux Ubuntu. @rancdg

**Comment by maartenbreddels** [comment]
kapteyn package is no longer a dependency, so this should not be a problem, if so, please open an issue with a good error msg, thanks!
