### ISSUE TITLE
[BUG-REPORT] vaex runs forever after a join operation

### ISSUE THREAD

**Issue by yohplala** [vaexio/vaex#1591]
**Description**
I have implemented a custom scaling, that operates each row independently, over a selection of columns.
The code works on a vaex Dataframe created from scratch with `from_arrays`.
(if you have any idea how to boost the exectuion time, I am of course interested, but this is not the main point of this ticket, clearly).

Now, the real targeted use case is to apply this custom scaling on a vaex Dataframe created from multiple joined DataFrames.
Ideally, these Dataframes would come from Parquet files, but I have the trouble already starting from vaex DataFrames created from scratch and then joined: the custom scaling runs forever on this joined DataFrame.
Please, why is that so?

Here is a Minimal Reproducible Example.

Custom scaling function, dealing with each row independently.
```python
# 'jit_numba()' is commented as it raises an error when used.

import numpy as np
from vaex import register_function

@register_function(on_expression=False)
def min_row_wise(*args):
    """
    Extract min row-wise, not taking into account null values.
    """
    # Create mask array as view.
    masked = np.ma.masked_equal(np.stack(args, axis=1), 0.0, copy=False)
    return masked.min(axis=1).filled(fill_value=0.0)

@register_function(on_expression=False)
def max_row_wise(*args):
    """
    Extract max row-wise.
    """
    return np.max(np.stack(args, axis=1), axis=1)

def scaling_minmax_by_row(vdf, columns: list, lower: float, upper: float):
    """
    Scale row per row, in-place, over defined list of columns.
    Null values are not modified.

    Parameters:
        df (vaex.DataFrame): Input DataFrame, modified in-place.
        columns (list): List of columns overwhich scaling the data.
        lower (float): Min value after scaling (not taking into account null values).
        upper (float): Max value after scaling.
    """
    vdf['min_row'] = vdf.func.min_row_wise(*[vdf[col] for col in columns])
#                      .jit_numba()
    vdf['max_row'] = vdf.func.max_row_wise(*[vdf[col] for col in columns])
#                      .jit_numba()
    for col in columns:
        # Scale if value is not null.
        vdf[col] = vdf.func.where(vdf[col] != 0.0,
                                ((upper-lower)*(vdf[col] - vdf['min_row']) /
                                 (vdf['max_row'] - vdf['min_row']) + lower),
                                vdf[col])
    vdf.drop(columns=['min_row', 'max_row'], inplace=True)
```
Now the example with a single vaex DataFrame created from scratch.
Scaling is made on 144 columns (total number of columns in the DataFrame is 864).
This code works ok on my machine.
It allows checking that custom scaling function works (apparently).
```python
# Minmax scaling / single dataframe.
import numpy as np
import vaex as vx

n_df = 48
n_cols = 6*3*n_df
n_rows = 6

# Generate test data: a list of vaex DataFrames, for joining in a 2nd step.
index = np.arange(n_rows)
x = np.ones(n_rows)
vdf = vx.from_arrays(**{f'x_{i}': x*i+1 for i in range(n_cols)},
                     timestamp=index)
# Scale
cols = list(vdf.get_column_names(regex='^(?!timestamp)'))[:n_cols:6]
print(cols)
print(len(cols))
scaling_minmax_by_row(vdf, cols, 0.1, 1.0)
```
Now, when applied on a vaex Dataframe obtained from joining 48 vaex DataFrames, the custom scaling runs forever (maybe at some point, it finally ends, but I have not been patient enough to find out).
```python
# Minmax scaling / several dataframes.
import numpy as np
import vaex as vx

n_df = 48
n_cols = 6*3
n_rows = 6

# Generate test data: a list of vaex DataFrames, for joining in a 2nd step.
index = np.arange(n_rows)
x = np.ones(n_rows)
vdfs = []
for k in range(1,n_df+1):
    vdf = vx.from_arrays(**{f'x_{i}': x*i+1 for i in range(n_cols)},
                         timestamp=index)
    vdfs.append(vdf)

# Join with vaex.
left = None
for i, vdf in enumerate(vdfs):
    rprefix = f'vdf_{i}_'
    try:
        left = left.join(vdf, on='timestamp', rprefix=rprefix, how='inner')\
                   .drop(rprefix+'timestamp')
    except AttributeError:
        left = vdf
        for col in left.get_column_names(regex='^(?!timestamp)'):
            left.rename(col, rprefix+col)
# Scale
cols = list(list(left.get_column_names(regex='^(?!timestamp)'))[:n_cols*n_df:6])
print(cols)
print(len(cols))
scaling_minmax_by_row(left, cols, 0.1, 1.0)
```

Size of both DataFrame (from the example that works, and from the example that does not work, are the same: same number of columns, same number of rows).
Please, is there a bug somewhere to correct?

I thank you for your help.
I have not identified any workaround so far, and would greatly appreciate any advice.
Bests

**Software information**
 - Vaex version: `{'vaex-core': '4.5.1', 'vaex-hdf5': '0.10.0', 'vaex-ml': '0.14.0'}`
 - Vaex was installed via: conda-forge + mamba !!!!!! :) 
 - OS: ubuntu 20.04

**Additional information**
I am lost, please, help! :)

**Comment by maartenbreddels** [comment]
So, vaex tries to save memory, and does not make memory copies of your data, which can mean it will do random access into the data from the dataframes you have joined.
A common strategy, for performance, would be to first export your dataframe to a single hdf5 file, open it, and continue working with that dataframe instead. This way it's memory mapped, will not waste any memory, and memory access will not be random acces.

Let us know if that works for you.

Regards,

Maarten

**Comment by yohplala** [comment]
Closing following discussion in #1726
