### ISSUE TITLE
Filtering using multiple conditions on the same column

### ISSUE THREAD

**Issue by SyureNyanko** [vaexio/vaex#1601]
Hi, I want to filter on multiple conditions about the same column, but looks like the conditions don't apply correctly.

The reproducible script is as follows.

```python
import vaex
import pandas as pd

pandas_df = pd.DataFrame(
    data=[{
        'a': 1,
        'b': 2,
    }, {
        'a': 3,
        'b': 4,
    }, {
        'a': 5,
        'b': 6,
    }])

vaex_df = vaex.from_pandas(df=pandas_df, copy_index=False)
vaex_df[3 < vaex_df.a and vaex_df.a < 6]
```
result :
```
#	a	b
0	1	2
1	3	4
2	5	6
```

I expected,
```
#	a	b
0	5	6
```

**Software information**
 - Vaex version : {'vaex': '4.5.0', 'vaex-core': '4.5.1', 'vaex-viz': '0.5.0', 'vaex-hdf5': '0.10.0', 'vaex-server': '0.6.1', 'vaex-astro': '0.9.0', 'vaex-jupyter': '0.6.0', 'vaex-ml': '0.14.0'}
 - Vaex was installed via pip 
 - OS: MacOS Catatlina (Intel)

**Comment by SyureNyanko** [comment]
Sorry, I misunderstood the specifications.
This can be achieved by writing the following.

```python
import vaex
import pandas as pd

pandas_df = pd.DataFrame(
    data=[{
        'a': 1,
        'b': 2,
    }, {
        'a': 3,
        'b': 4,
    }, {
        'a': 5,
        'b': 6,
    }])

vaex_df = vaex.from_pandas(df=pandas_df, copy_index=False)
vaex_df[(3 < vaex_df.a) & (vaex_df.a < 6)]
```

**Comment by maartenbreddels** [comment]
Thanks for opening the issue and reporting back,.glad you solved it yourself!
