### ISSUE TITLE
[BUG-REPORT] DataFrameLocal filter operation does not work as expected for multiple values

### ISSUE THREAD

**Issue by Ben-Epstein** [vaexio/vaex#1618]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your problem may already be discussed or addressed.

**Description**
The filter operation does not have the expected behavior when you apply it to many values

```
import numpy as np
import vaex

n=1000
label = np.random.randint(0, 20, size=n)
pred = np.random.randint(0,20,size=n)

data = {'label': label, 'pred': pred}
df = vaex.from_arrays(**data)

df[df['label'] == 5] # Works as expected
df[df['label'] == 5 or df['label'] == 2] # Only returns rows with label=2
df[df['label'] in [5,6,7]] # Returns a list of a single row
```

Is there a way to filter on multiple values? Thanks!

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
```
{'vaex': '4.5.0',
'vaex-core': '4.5.1',
'vaex-viz': '0.5.0',
'vaex-hdf5': '0.10.0',
'vaex-server': '0.6.1',
'vaex-astro': '0.9.0',
'vaex-jupyter': '0.6.0',
'vaex-ml': '0.14.0'}
```
 - Vaex was installed via: pip / conda-forge / from source : pip
 - OS: Mac os big sur

**Comment by Ben-Epstein** [comment]
@JovanVeljanoski would you be able to take a look at this by chance?

**Comment by JovanVeljanoski** [comment]
Hey @Ben-Epstein 

So looks like you figured it out :).

Going back to your original example, you need to use binary operators, so like this

```python
df[(df['label'] == 5) | (df['label'] == 2)] # Only returns rows with label=2
```

If you want to check if a value in an expression is contained within some external list, indeed `df.x.isin(list_of_values)` is the way to go, and should be quite fast. `isin` can be found in the API docs, i just checked.. Or did you mean the main tutorial?

**Comment by Ben-Epstein** [comment]
Yea I think that would help a lot! RIght [here](https://vaex.io/docs/tutorial.html#Selections-and-filtering) in Selections and Filtering I now see the `isin` in the api docs, but I had no way to know that, unfortunately. I also think that the ability to do `df[df.id in [1,2,3]]` is cool as a feature, but certainly not necessary if this one is well known.
