### ISSUE TITLE
Set a user functions path

### ISSUE THREAD

**Issue by DougRzz** [vaexio/vaex#162]
I would like the users of my Vaex based app to be able to create their own NumPy/Pandas type functions similar to functions.py.  To enable this,  I would like to be able to specify a list of paths which contain these additional functions.  

Maybe the api could be something like this:
```python
vaex.userFunctionPaths = [r'C:\Dougs\vaexFunctions\DougsFunctions.py',  r'X:\team\functions\extraFunctions.py']
```

**Comment by maartenbreddels** [comment]
I guess you mean something that runs when you import vaex?
It does currently https://github.com/vaexio/vaex/blob/master/packages/vaex-core/vaex/__init__.py#L550
But it's a bit of a leftover artifact, but does it suit your needs?

**Comment by DougRzz** [comment]
Something similar to that would work maybe.   I would like the user to be able to write and save their own functions and then add them to the `expression_namespace` without having to modify functions.py in the Vaex code base.

**Comment by DougRzz** [comment]
This PR fulfils this issue.
https://github.com/vaexio/vaex/pull/188
:)
