### ISSUE TITLE
How to select rows from a dataset that are exist in other dataset (e.g. using id/name column) ? 

### ISSUE THREAD

**Issue by ridlo** [vaexio/vaex#163]
I want to ask again, I can not find it in the documentation, is there a simple way to select rows from a dataset that exists in another dataset (e.g. using id/name column)? or rows that do not exist in other datasets?

I think in sql it is easier.

Cheers,

**Comment by JovanVeljanoski** [comment]
Hi, 

If there is a common column, you can simply use `.join` to joint the two datasets. No memory copy is done. Then on the joined dataset, you can use standard techniques to select the rows that you need.

**Comment by maartenbreddels** [comment]
I admit vaex is not very 'row' friendly, we used it more often for large datasets where we just aggregate, not inspect individual rows.
Do you have any suggestions for an API?
I kind of like xarray's method of passing a dict, sth like (although xarray uses `ar.loc[]`)
```
df[{'name': 'maarten}]
```

**Comment by maartenbreddels** [comment]
I guess the join was the solution
