### ISSUE TITLE
[FEATURE-REQUEST] Ability to encode string column to category?

### ISSUE THREAD

**Issue by yohplala** [vaexio/vaex#1649]
**Description**
I tried to use `categorize` to set type of a string column to category the following way, but I got following error message.
`TypeError: Only integer columns can be marked as categorical, status is large_string`

Please, could string be supported?

**Is your feature request related to a problem? Please describe.**
Here is the complete data I used.

```python
import vaex as vx

vdf = vx.from_dict({'status':['unconfirmed', 'unconfirmed', 'unconfirmed']})
vdf.categorize('status', labels=['unconfirmed'], inplace=True)
```

**Additional context**
I was thinking that a syntax similar to pandas would work as well, but unfortunately not.
`vdf['status'] = vdf['status'].astype('category')`

**Comment by JovanVeljanoski** [comment]
Hi, 

Yeah we are doing some work in this area. So currently in vaex version 4.x, `df.categorize` works only on ints. If you want to encode strings you need to use `df.ordinal_encode`. This will work on strings, but will replace the column with an int column. 

This behavior will change in vaex 5.x. Then we plan on using arrow dictionaries to still display the string values of the original columns when you print them and inspect them, but to use the encoded int values under the hood for faster processing. 
This is available as a preview, and you can try it like this:

```
df = vaex.from_dict({'status':['unconfirmed', 'unconfirmed', 'unconfirmed']})
df = df._future()  # Enables v5 preview features. 
df = df.ordinal_encode(column='status')
print(df)
print(df.status.values)
```

Of course, the v5 preview features come without any guarantee and may be subject to change without any notice. Just a taste of what is coming. You can achieve similar things with v4 if you poke around the API around (e.g. using `df._categories` to make a dictionary and then do mapping). 

Anyway, i hope this helps a bit.

**Comment by yohplala** [comment]
Thanks a lot for the quick reply @JovanVeljanoski , much appreciated!
