### ISSUE TITLE
[BUG-REPORT] - `to_numpy` corrupts numpy array

### ISSUE THREAD

**Issue by Ben-Epstein** [vaexio/vaex#1655]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your problem may already be discussed or addressed.

**Description**
Please provide a clear and concise description of the problem. This should contain all the steps needed to reproduce the problem. A minimal code example that exposes the problem is very appreciated.

When you have a column whose values are a pyarrow Arrays, and you try to convert that to numpy, it corrupts the numpy array and it cannot be worked with directly. 

```
NUM_SAMPLES = 100
WIDTH = 20

vals = [pa.array([random() for _ in range(WIDTH)]) for _ in range(NUM_SAMPLES)]
ids = list(range(NUM_SAMPLES))
data = {
    'vals': vals,
    'id': ids
}
df = vaex.from_pandas(pd.DataFrame(data))

bad = df['vals'].to_numpy() # np.array of type Object, cannot become a (NUM_SAMPLES,WIDTH) matrix
good = np.array(vals) # (NUM_SAMPLES,WIDTH) matrix
```

In the example above, good is a numpy matrix that you'd expect. But bad is a numpy array of pyarrow arrays. Numpy, for some reason, cannot convert it to a numpy matrix, it thinks the object is of unequal length. The only way to do it is either to
1. Cast it to a list, then back to numpy
2. Convert each pa.array to a numpy array first, then call the `np.array` constructor

Both of those are very slow. Do you have a suggestion for a way to get around this? Thanks!

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
```
{'vaex': '4.5.0',
 'vaex-core': '4.5.1',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.10.0',
 'vaex-server': '0.6.1',
 'vaex-astro': '0.9.0',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.14.0'}
```
 - Vaex was installed via: pip / conda-forge / from source : pip
 - OS: MacOS big sur

**Additional information**
Please state any supplementary information or provide additional context for the problem (e.g. screenshots, data, etc..).

**Comment by Ben-Epstein** [comment]
@JovanVeljanoski could you point me to about where in the code that support would live? Is that in the C++ implementation or Python wrapper?

**Comment by Ben-Epstein** [comment]
@JovanVeljanoski 

I figured out a pretty clean solution that works for all types i've tried. Vaex can natively handle ChunkedArrays, and ChunkedArrays seem to be able to handle everything i've thrown at them. This function has been a lifesaver for me, maybe worth adding into the codebase as a builtin Expression?

It's really fast, 300ms for 1M records, each with a (1,20) array


```
import pyarrow as pa
import pandas as pd
import numpy as np
import vaex
from random import random

@vaex.register_function()
def as_numpy(arr):
    return pa.chunked_array(arr).to_numpy().reshape(-1, len(arr[0]))


NUM_SAMPLES = 100_000
WIDTH = 20

pa_vals = [pa.array([random() for _ in range(WIDTH)]) for _ in range(NUM_SAMPLES)]
np_vals = [np.array([random() for _ in range(WIDTH)]) for _ in range(NUM_SAMPLES)]
vals = [[random() for _ in range(WIDTH)] for _ in range(NUM_SAMPLES)]

ids = list(range(NUM_SAMPLES))
data = {
    'vals': vals,
    'np_vals': np_vals,
    'pa_vals': pa_vals,
    'id': ids
}
df = vaex.from_pandas(pd.DataFrame(data))

v = df.vals.as_numpy().to_numpy()
np_v = df.np_vals.as_numpy().to_numpy()
pa_v = df.pa_vals.as_numpy().to_numpy()


assert v.shape == (NUM_SAMPLES,WIDTH)
assert np_v.shape == (NUM_SAMPLES,WIDTH)
assert pa_v.shape == (NUM_SAMPLES,WIDTH)

assert (v==np.array(vals)).all()
assert (np_v==np.array(np_vals)).all()
assert (pa_v==np.array(pa_vals)).all()
```

**Comment by maartenbreddels** [comment]
> The column `val` is of a pyarrow DoubleArray type, which is not supported by vaex.

We do, but we don't really work well with a list of DoubleArray.

I'm not sure why you want to use arrow here, this can be solved using numpy:
```
import vaex
from random import random
import numpy as np

NUM_SAMPLES = 100
WIDTH = 20
vals = np.array([np.array([random() for _ in range(WIDTH)]) for _ in range(NUM_SAMPLES)])
ids = np.arange(NUM_SAMPLES)
data = {
    'vals': vals,
    'id': ids
}
df = vaex.from_arrays(vals=np.array(vals))
print(df)
print(df.vals.shape)

```

I'm not sure where arrow is when multid arrays, but we currently don't support them, so you'd have to use numpy for that. Hope that helps!

**Comment by Ben-Epstein** [comment]
If you use my function, though, it'll be handled properly
```
@vaex.register_function()
def as_numpy(arr: Union[pa.ChunkedArray, np.ndarray]) -> np.ndarray:
    """Converts a vaex column of arrays into properly formatted numpy ndarrays.

    Assumes that all rows in the column have a list of the exact same length.
    """
    # Base case: if we already have a numpy array, return it
    if isinstance(arr, np.ndarray) and arr.ndim > 1:
        return arr

    if isinstance(arr[0], pa.Array):
        tmp = pa.chunked_array(arr)
    elif isinstance(arr, pa.lib.ListArray):
        tmp = arr.flatten()
    elif isinstance(arr, pa.ChunkedArray):
        tmp = arr.combine_chunks().flatten()
    else:
        tmp = pa.array(arr).flatten()
    return tmp.to_numpy().reshape(-1, len(arr[0]))


df1.vals.as_numpy().to_numpy() # a proper ndarray of shape (100000,20)
```

**Comment by Ben-Epstein** [comment]
It is certainly a tricky case. Your example above is in fact a bug, though. The shape, `(100000,)` is incorrect. This should be `(100000,20)` because this is a 10000X20 matrix. Something from vaex is telling numpy that the data cannot be put into a matrix. See the different in this example

![image](https://user-images.githubusercontent.com/22605641/138002842-5d25f21c-fdc9-4b6b-9586-1b74e8671e32.png)

See how after using the `as_numpy` custom function I added above, the numpy ndarray is properlly formatted and understood?

**Comment by Ben-Epstein** [comment]
Yup that does work, but i'm curious why the previous example you showed gives the output it does. Numpy would create an ndarray matrix if it could... Something is telling it that it cannot..

See this example. Same as before...
![image](https://user-images.githubusercontent.com/22605641/138004661-94ec8923-fe49-4c9f-9f2e-4348f89e76f1.png)

but if we simply copy that data manually, you'll see that numpy automatically puts it into a matrix
![image](https://user-images.githubusercontent.com/22605641/138004706-bae9e408-8e4f-412e-a397-f55a7a1df17b.png)


More technically, if we take that original data, convert it to a list (take it out of the numpy space), and then put it back into numpy, it'll again go to a matrix

![image](https://user-images.githubusercontent.com/22605641/138004777-74696008-5ff2-4927-9329-f0b8d4355a11.png)


The question (and bug) is, why when going from vaex to numpy in the first image, does numpy believe that this object cannot be a matrix?

**Comment by maartenbreddels** [comment]
Again, thanks for sharing your code/example/results!
