### ISSUE TITLE
[BUG-REPORT] Cannot add virtual column that is output of different dataframe

### ISSUE THREAD

**Issue by Ben-Epstein** [vaexio/vaex#1661]
Thank you for reaching out and helping us improve Vaex!

**Description**
If I have 2 dataframes, `df1` and `df2` and I want the output of an expression of `df1` to be applied to `df2`, I currently cannot.

```
import vaex
import numpy as np

ids = list(range(100))
data1 = {
    'a': np.random.random(100),
    'id': ids
}
df1 = vaex.from_arrays(**data1)

data2 = {
    'b': np.random.random(100),
    'id': ids
}
df2 = vaex.from_arrays(**data2)

@vaex.register_function()
def add1(v):
    return v+1


df2.add_virtual_column('c',df1.a.add1())
df2.c.to_numpy(). # NameError: name 'a' is not defined
```

If I run the same thing but change that second to last line to 
```
df2.c = df1.a.add1())
```
this works but not as expected. Upon an export, the resulting value is gone, and a print of `df2.virtual_columns` is empty. I think it's attaching it as a simple python attribute, not an actual vaex column.

I also tried something like 
```
df1['c'] = df1.a.add1()
df2.add_virtual_column('c',df1['c'])
df2
```
but that gave me a massive stack trace ending in
```
RecursionError: maximum recursion depth exceeded
```

same with 
```
df2.add_virtual_column('a',df1['a'])
df2['c'] = df2['a'].add1()
df2
```

The only solution I can think to do for now is something like 
```
df2['c'] = df1['a'].add1().to_numpy() 
```
which is of course not ideal.

Do you have any suggestions/workarounds? 

Thanks!

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
```
{'vaex': '4.5.0',
 'vaex-core': '4.5.1',
 'vaex-viz': '0.5.0',
 'vaex-hdf5': '0.10.0',
 'vaex-server': '0.6.1',
 'vaex-astro': '0.9.0',
 'vaex-jupyter': '0.6.0',
 'vaex-ml': '0.14.0'}
```
 - Vaex was installed via: pip / conda-forge / from source `pip`
 - OS: MacOS big sur

**Comment by yohplala** [comment]
Hi,

To mix 2 distinct data from 2 vaex DataFrames, you have 1st to join them.
"_DataFrames_" is in my opinion, and somehow, misleading the user in vaex world, or so I think.
You should see vaex "_DataFrames_" as a list of pending commands to be run 'when it will be time'.
These 'commands' are "_Expression_".
An "_Expression_" is only relative to one "_DataFrame_". It has no meaning in other "_DataFrame_".

And as stated in `add_virtual_column()`, the 2nd expected parameter is an "_Expression_".

So before anything.
`df2 = df2.join(df1)`  

Bests,
