### ISSUE TITLE
Feature request: support for string datatype

### ISSUE THREAD

**Issue by tkowalcz** [vaexio/vaex#167]
I have a dataset of up to 2TB containing about 40 columns. This data is a log of web traffic from advertising exchange. Initially I wanted to do some simple aggregations and statistics. I could use Spark or something similar but the task seemed simple enough that some sane tool (with mechanical sympathy) should handle it easily. That's why I was quite happy to find Vaex. Unfortunately it does not support all datatypes present in the data.

This data is in our proprietary format that I can export to ORC or Arrow and can tweak export process to better match tools that will process the data (such as Vaex).

Column types are:
- Minority of the columns are of type integer/floating point. 
- A lot of them are UUIDs that I encoded as strings (e.g. "e7b3dc38-8518-46bf-96c0-650422648a9e"). 
- Some are actual strings (e.g. referrer, operating system, browser). 
- Some are boolean.

Turns out that during import of Arrow files into Vaex strings and booleans are not supported.
Example query that I would like to do is to get distinct referrers from all the data or group numeric columns by referrer.

My notebook code that uses Pandas and will not work on large data looks like this:

```python
import pyarrow as pa
import pandas as pd

mmap = pa.memory_map('/media/ephemeral1/30.arrow')
reader = pa.open_stream(mmap)
df = reader.read_pandas(zero_copy_only=True)
df = df.groupby('REFERRER').aggregate('sum').sort_values(by='FOO', ascending=False)
```

Please let me know if I can help.

**Comment by maartenbreddels** [comment]
Hi Thomasz,

FYI: string support is getting in via #186

cheers,

Maarten

**Comment by maartenbreddels** [comment]
Together with https://github.com/vaexio/vaex/pull/200 should be solved, please reopen if not.
