### ISSUE TITLE
Vaex's `from_pandas` doesn't work well with String?

### ISSUE THREAD

**Issue by dyngts** [vaexio/vaex#168]
Dear @maartenbreddels,

I'm trying to convert pandas dataframe into vaex dataframe. Turns out, one of my data contains special character (ñ), `&#10003;Onoñ`. As the result, it throw error like this

>UnicodeEncodeError: 'ascii' codec can't encode character '\xf1' in position 11: ordinal not in range(128)

After some searches, i read following line of your code which trying to force string conversion using `astype("S")`
https://github.com/vaexio/vaex/blob/master/packages/vaex-core/vaex/__init__.py#L359

What i don't understand is why you're trying to convert it using "S" argument? I found the error can be resolved by change it into "str". Looking for your advice.

To reproduce:
```python
import pandas as pd
x = "&#10003;Onoñ"
df_test = pd.DataFrame({"some_str": [x, x]})
df_test.some_str.astype("S") # throw error
df_test.some_str.astype("str") # run well
```

P.S.: I'm using Python 3.6.7 and Vaex 1.0.0-beta.6

**Comment by maartenbreddels** [comment]
Hi,

thanks for your feedback. We plan to improve string support, and when doing this I'll check this as well!

cheers,

Maarten

**Comment by dyngts** [comment]
Got it @maartenbreddels, thanks for confirming. Can't wait for this.

Anyway, just to be sure, I observe Vaex currently will convert all string data into byte. is it true?

**Comment by maartenbreddels** [comment]
yes, for py27 that is the same, but we want to change that behavior, it is confusing.

**Comment by dyngts** [comment]
>yes, for py27 that is the same, but we want to change that behavior, it is confusing.

**Comment by maartenbreddels** [comment]
FYI, some changes are happening in #186, to have better string support

**Comment by maartenbreddels** [comment]
String support is merged, assuming this is resolved
(note that df_test.some_str.astype("S") will give a encoding error, which is valid, since it cannot be cast to unicode)

**Comment by dyngts** [comment]
Awesome @maartenbreddels ,

I'll spend some time to explore this feature.
