### ISSUE TITLE
Join errors with ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by Code4SAFrankie** [vaexio/vaex#1683]
**Description**
Trying to perform a join with selections, but since it does not seem to support selections I am using filter instead. However it throws an error.

```
import vaex
is_a = vaex.open(r'D:\Downloads\WikipediaENLatest\is_a.hdf5')
yfacts = vaex.open(r'D:\Downloads\Wikipedia\Yago\yagoFacts.hdf5')
yfacts.select(yfacts.statement=='<isCitizenOf>', name='yfacts')
is_a.select(is_a.attr_root.isin(['case', 'decision', 'trial', 'relations']), name='is_a')
yfacts.filter('yfacts').join(is_a.filter('is_a'), left_on='class2', right_on='subject', allow_duplication=True)
```

throws error:
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\dataframe.py", line 6311, in join
    return vaex.join.join(**kwargs)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\join.py", line 212, in join
    left = left.concat(left.take(lookup_left))
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\vaex\dataframe.py", line 4204, in take
    max_index = indices.max()
  File "E:\WPy64-3771\python-3.7.7.amd64\lib\site-packages\numpy\core\_methods.py", line 30, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
```

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: `{'vaex': '3.0.0', 'vaex-core': '4.5.1', 'vaex-viz': '0.5.0', 'vaex-hdf5': '0.10.0', 'vaex-server': '0.6.1', 'vaex-astro': '0.9.0', 'vaex-jupyter': '0.6.0', 'vaex-ml': '0.14.0', 'vaex-arrow': '0.5.1'}`
 - Vaex was installed via: pip 
 - OS: Windows 10

**Additional information**
First of many joins to come. Need to join with `is_a` again without filter.

SQL would be:
```
select ia1.attr_root type1, ia2.attr_root type2, ia1.subject, ia2.subject, yf.statement, yf. class2, ia1.attr_full, ia1.title, ia1.the_text, ia2.attr_full, ia2.title, ia2.the_text
from   yago_facts yf,
       is_a       ia1,
       is_a       ia2
where  yf.statement in ('<isCitizenOf>')
and    ia1.subject = yf.class1
and    ia2.subject = yf.class2
and    ia2.attr_root in ('case', 'decision', 'trial', 'relations')
```

**Comment by JovanVeljanoski** [comment]
Can you please make an example that we can reproduce locally? 

Also, is it possible to just join the dataframes, and do filtering afterwards?

Also, selections are meant to work on a single dataframe. So if you do use them, it will be post-join.

**Comment by Code4SAFrankie** [comment]
Not likely. It's 2.7GB worth of data.

But your suggestion to join without filtering seems to get around the issue. Thanks

**Comment by maartenbreddels** [comment]
If you can find the time to make a reproducible issue, that would be nice, I don't know how to fix this now, since I cannot reproduce it. (You could generate fake data).
