### ISSUE TITLE
issue in reading data from s3

### ISSUE THREAD

**Issue by beeramnikhil** [vaexio/vaex#1688]
Error1: I do read a .hdf5 file from s3 to  a VM everyday for further use cases, however even after deleting the file from s3 am still able to read the file with complete data.
does Vaex cache the data onto VM ?

**Comment by Ben-Epstein** [comment]
@beeramnikhil you can set cache to false to stop vaex from doing that 

```
import vaex
options = {'cache':False}
df = vaex.open(<url>, fs_options=options)
```

**Comment by JovanVeljanoski** [comment]
Hey @beeramnikhil 

Yes, vaex caches the data by default if you call the file with the same arguments. That is how you can use the data locally in a fast way. So it is smart way of downloading it (only what is needed/used is downloaded not the full file). 

By default the caching is done `~./vaex/data` if you want to remove it manually.

**Comment by maartenbreddels** [comment]
Thanks for the question, this is documented at https://vaex.io/docs/example_io.html#Cloud-Support
