### ISSUE TITLE
[Locking] When converting tsv files, it would be nice to specify the directory where the vaex lock files go

### ISSUE THREAD

**Issue by mwang87** [vaexio/vaex#1689]
**Description**
When converting tsv files, it would be nice to specify the directory where the vaex lock files go. If we could create an option for example: 

```
vx.from_csv(path_to_file, lock_folder="/tmp")
```

that could make this clutter a bit better also, sometimes the current working directory is read only even though the location for the HDF5 and tsv files are writeable. 

**Is your feature request related to a problem? Please describe.**
Currently its in the active working directory which might clutter things and is not actually cleaned up.

**Comment by maartenbreddels** [comment]
I agree, I initially though that lock files would be removed, but due to possible race conditions on Unix systems they cannot. I think /tmp/vaex is a good default for that

**Comment by maartenbreddels** [comment]
See https://github.com/vaexio/vaex/pull/1797

**Comment by mwang87** [comment]
Thanks @maartenbreddels this is great, can't wait til next release!
