### ISSUE TITLE
[BUG-REPORT] Open_many with different columns

### ISSUE THREAD

**Issue by JcGKitten** [vaexio/vaex#1696]
Hello vaex-Team,
first of all thank you for the great work.
I didn't find a similar request or a solution so I hope you can help me here.
I'm really new to vaex and big data, so maybe there is a simple way to do it, I couldn't figure out yet :)
Maybe it's connected with [https://github.com/vaexio/vaex/issues/1491](https://github.com/vaexio/vaex/issues/1491)

**Description**
I want to load hdf5 files with `vaex.open_many()`, but they might have some different column names. This works so far but when I want to get the values of a column which wasn't in all files with `df["col_name"].values` it doesn't return an array as expected but `<pyarrow.lib.ChunkedArray object at 0x7fbbb9210860>` and some nested array sturucture I don't understand. This even happens when I use `df.dropmissing(column_names = ["col_name"])` before.

Thanks for your help and best wishes 
Max

**Software information**
 - Vaex version :
` {'vaex': '4.5.0', 'vaex-core': '4.5.1', 'vaex-viz': '0.5.0', 'vaex-hdf5': '0.10.0', 'vaex-server': '0.6.1', 'vaex-astro': '0.9.0', 'vaex-jupyter': '0.6.0', 'vaex-ml': '0.14.0'}`
 - Vaex was installed via: pip
 - OS: Ubuntu 20.04.3 LTS

**Additional information**
I hope this screenshots explain the problem:
![image](https://user-images.githubusercontent.com/46611597/141482827-77e9133c-fcd0-4428-aa6c-7f2f17365994.png) ![image](https://user-images.githubusercontent.com/46611597/141482921-b95f88d5-c201-4cfc-b6fe-7fd00da4a128.png)
![image](https://user-images.githubusercontent.com/46611597/141483143-f2770aff-8854-466b-aff7-04dc89c2be50.png)

And after using `df_dropped = df.dropmissing(["CCR7"])`:
![image](https://user-images.githubusercontent.com/46611597/141483552-830316b3-4c69-49fd-8b32-09700ae3f4aa.png) ![image](https://user-images.githubusercontent.com/46611597/141483665-cf6492ed-1442-478a-95f7-97ad7a6ff3a7.png)
![image](https://user-images.githubusercontent.com/46611597/141483785-d6499b86-1003-46d1-bed9-235644427cdd.png)

**Comment by JovanVeljanoski** [comment]
Hi, 

So `.values` exposes the "raw" data. In your case, the data is stored as an arrow chunked array. You were probably expecting a numpy array. In that case, you should do `df['column_name'].to_numpy()` and the data will be cast to numpy on the fly. 

Note that this will consume memory (same as `values`).

**Comment by JcGKitten** [comment]
@JovanVeljanoski thx for the super fast answer and explanation. I wasn't aware that `.to_numpy()` could get me the data as i expect it.
