### ISSUE TITLE
[FEATURE-REQUEST]

### ISSUE THREAD

**Issue by karan-doshi** [vaexio/vaex#1722]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your request may already be discussed or addressed.

**Description**
Could you please explain how would be get the co-efficients of the variables/features used in sklearn regression models? The sklearn has a function called model.coef_ which gives us the coefficients of the variables used in the linear models. Is there something similar in vaex? I could not find any information about it in the documentation. I used dir(model) to look for any explanation.

**Is your feature request related to a problem? Please describe.**
Could you please explain how would be get the co-efficients of the variables/features used in sklearn regression models? The sklearn has a function called model.coef_ which gives us the coefficients of the variables used in the linear models. Is there something similar in vaex? I could not find any information about it in the documentation. I used dir(model) to look for any explanation.

**Additional context**
Please state any supplementary information or provide additional context for the proposed functionality (e.g. workarounds, alternatives you have considered, etc..).

**Comment by JovanVeljanoski** [comment]
This is possible via the `model` attribute of a vaex model wrapper. Consider this simple example

```python
import vaex
import vaex.ml
from vaex.ml.sklearn import Predictor
from sklearn.linear_model import LinearRegression

df = vaex.example()
features = ['x', 'y', 'z', 'vx', 'vy', 'vz']
target = 'FeH'

vaex_model = Predictor(model=LinearRegression(), features=features, target=target)
vaex_model.fit(df)

# The original sklearn model is the model attribute.
# Accessing the coefficients
print(vaex_model.model.coef_)
```

The same is for any other wrapper that vaex-ml offers, those for the the boosted tree  model, `IncrementalPredictor` etc. 
All of them have a `.model` attribute which contains the original (in this case) scikit-learn model, which you can use as you would normally. 

I hope this helps

**Comment by karan-doshi** [comment]
@JovanVeljanoski - Thank you very much for your reply. This really helps. Exactly what I was looking for. Thank you again!

**Comment by karan-doshi** [comment]
Hi @JovanVeljanoski - Could you please help me as to how can I get the p-values for the features/variables. I do not think vaex has the OLS estimator yet which is used in sklearn. Is there an alternative way to find the p-value of the variables/features?

**Comment by JovanVeljanoski** [comment]
Vaex does re-implement any estimator from scikit-learn. You are using it directly from them. 
Whatever estimator you are using from scikit-learn (or any other library that uses the scikit-learn fit/predict structure) will work with the `Predictor` wrapper in the example above (but you are putting the data in memory in this case).

**Comment by karan-doshi** [comment]
Hi @JovanVeljanoski - Thank you for your reply. Do you mean to say that everytime we use the 'Predictor' wrapper, we will be putting data into memory?

**Comment by JovanVeljanoski** [comment]
Yes, this is all explain in the documentation - please read the docstrings. For large datasets you can use incremental models (there are some in scikit-learn) and that is why `IncrementalPredictor` exists. You can also look at [river](https://github.com/online-ml/river/), and we also have wrapper for them. For boosted trees, if you look at catboost they have a way of averaging models, and the vaex-ml wrapper supports. There are many ways to get around the problem :)
