### ISSUE TITLE
ImportError: cannot import name 'Task'

### ISSUE THREAD

**Issue by mfouesneau** [vaexio/vaex#173]
https://github.com/vaexio/vaex/blob/f654e895e48a1c5080ad9f84df9a2c31c7add64a/packages/vaex-ui/vaex/ui/layers.py#L2740

Sorry but this version does not find Task in `vaex.dataset`. Should this be imported from tasks instead?

**Comment by maartenbreddels** [comment]
Hi Morgan,

again, thanks for the report. I don't often run the ui tests (since they are not as solid, may block when error occur), so this slipped by. Hope the referenced fix/PR works.

cheers,

Maarten
