### ISSUE TITLE
[BUG-REPORT] error with layout() and new progressbar

### ISSUE THREAD

**Issue by erwanp** [vaexio/vaex#1748]
I'm getting this error in [our CI](https://app.travis-ci.com/github/radis/radis/jobs/549862691#L2911)

```
    @docsubst
    def export_hdf5(self, path, byteorder="=", progress=None, chunk_size=default_chunk_size, parallel=True, column_count=1, writer_threads=0, group='/table', mode='w'):
        """Exports the DataFrame to a vaex hdf5 file
    
        :param str path: path for file
        :param str byteorder: = for native, < for little endian and > for big endian
        :param progress: {progress}
        :param bool parallel: {evaluate_parallel}
        :param int column_count: How many columns to evaluate and export in parallel (>1 requires fast random access, like and SSD drive).
        :param int writer_threads: Use threads for writing or not, only useful when column_count > 1.
        :param str group: Write the data into a custom group in the hdf5 file.
        :param str mode: If set to "w" (write), an existing file will be overwritten. If set to "a", one can append additional data to the hdf5 file, but it needs to be in a different group.
        :return:
        """
        from vaex.hdf5.writer import Writer
        progressbar = vaex.utils.progressbars(progress, title="export(hdf5)")
        progressbar_layout = progressbar.add("layout file structure")
        progressbar_write = progressbar.add("write data")
        with Writer(path=path, group=group, mode=mode, byteorder=byteorder) as writer:
>           writer.layout(self, progress=progressbar_layout)
E           TypeError: layout() got an unexpected keyword argument 'progress'
```

It could be be due to the recent changes in progressbar (https://github.com/vaexio/vaex/commit/3d5c2fb71417c12a195e046900e4beda5fb5fc5c) 

Versions : 
- vaex 4.5.0
- vaex-core-4.6.0

**Comment by maartenbreddels** [comment]
If you restart CI it will probably pick up the new vaex-hdf5, which is compatble with the new Vaex-core 4.6. To avoid this in the future we're gonna make vaex (the metapackage) more strict on future version.

**Comment by maartenbreddels** [comment]
And thanks for your quick reports!

**Comment by zoken01** [comment]
Is there any easy fix for this?

**Comment by JovanVeljanoski** [comment]
Nothing was broken.. you just need to update to the latest version of vaex. (vaex-hdf5 should be updated if you update vaex-core)

**Comment by aohma** [comment]
I am still seeing this error after updating using conda (vaex 4.5.0, vaex-core 4.6.0 and vaex-hdf5 0.10.0). Any suggestions?

**Comment by xeladsn** [comment]
Try using vaex-hdf5 0.11.0 as it is the last vaex-hdf5 version. Installing this package solved the issue for me.

**Comment by aohma** [comment]
Thank you, solved the issue for me as well! Note that I was not able to do this using conda, I had to use pip to get the newest version of vaex-hdf5

**Comment by maartenbreddels** [comment]
That should be available now on conda forge I hope!

(from mobile phone)

Op di 30 nov. 2021 22:34 schreef aohma ***@***.***>:
