### ISSUE TITLE
Thanks for the report, could you try to isolate the issue? Maybe generate some fake data to trigger this, so it's easy for us to replicate? If so, could you open a new issue for this?

### ISSUE THREAD

**Issue by KrzysztofPrzygodzki** [vaexio/vaex#1749]
Thanks for the report, could you try to isolate the issue? Maybe generate some fake data to trigger this, so it's easy for us to replicate? If so, could you open a new issue for this?

_Originally posted by @maartenbreddels in https://github.com/vaexio/vaex/issues/746#issuecomment-980075133_

**Comment by KrzysztofPrzygodzki** [comment]
Sorry, for this. This was created by accident. Can I delete it?

**Comment by maartenbreddels** [comment]
it's closed, this is fine.
