### ISSUE TITLE
[BUG-REPORT] import fails after installation

### ISSUE THREAD

**Issue by regCode** [vaexio/vaex#1779]
Hi, I recently installed the library, but when I try to import it (`import vaex`), I always get the same exception:

`
ModuleNotFoundError: No module named 'vaex.server.settings'`

I have tried it on different machines and the same thing always happens.

**Comment by JovanVeljanoski** [comment]
can you pls answer all the questions that were on the issue template? 
like version number, os et..

**Comment by regCode** [comment]
Sorry my mistake:

**Description**
Library import fails after installation.
1. Install the library: `pip install vaex` 
2. import the library: `import vaex`
3. An exception appears: `ModuleNotFoundError: No module named 'vaex.server.settings'`

**Software information**
- Vaex version: I tried with the last 2 versions `4.6.0` and `4.5.0`
- Vaex was installed via: `pip`
- OS: I tried over `Ubuntu 20.04.2 LTS` and `MacOS Monterey 12.0.1`
- python version: 3.8.10

**Additional information**
I have a cron job that instantiates a cluster every hour. The problem started yesterday. I also tried to install the library manually on 2 different machines.

**Comment by aqqwvfbukn** [comment]
I also encountered the same problem in a clean virtual environment on Windows 10.

**Comment by JovanVeljanoski** [comment]
In a new virtual environment, can you please try `pip install vaex-core==4.7` ?

**Comment by regCode** [comment]
Yes, In a new virtual environment `pip install vaex-core==4.7` solves the issue.

**Comment by regCode** [comment]
But when you try to use it with the other components such as `vaex-hdf5 ` it fails again.

**Comment by JovanVeljanoski** [comment]
So `vaex==4.7` was released yesterday, and it looks like `vaex` meta package is not on pip for whatever reason. So for now (till monday or so), either install `vaex-core` and all the packages you need manually one by one, or perhaps use explicitly `vaex==4.6`, should be fine. 

Sorry about that.

Let's keep this open until fixed.  

(Don't deploy on Fridays :P @maartenbreddels 🤣 )

**Comment by regCode** [comment]
No problem, thanks for the quick reply 😁👍

**Comment by JovanVeljanoski** [comment]
Should be fixed now! Thanks!

**Comment by maartenbreddels** [comment]
The problem was that vaex had the upper limits for Vaex-core <5, so it picked up Vaex-core 4.7, but it was still limited to the old vaex-server. We now from vaex 4.7 on put the upper limit 1 minor version higher, so this shouldn't occur anymore.
Thanks for reporting!
And indeed, vaex 4.7 (the meta package) is released now.
