### ISSUE TITLE
[FEATURE-REQUEST] Have `return_index` in `unique()`

### ISSUE THREAD

**Issue by yohplala** [vaexio/vaex#1780]
Hello,

[`vaex.unique()`](https://vaex.io/docs/_modules/vaex/dataframe.html#DataFrame.unique) has `return_inverse`, but does not have `return_index` like numpy equivalent [`unique()`](https://numpy.org/doc/stable/reference/generated/numpy.unique.html).
Do you think this could this be considered?

Thanks for the great work!
Bests

**Comment by JovanVeljanoski** [comment]
Vaex does not (yet) have the concept of indices, so it makes no sense to return this (while this is the case).

What is it that you are trying to achieve?

**Comment by yohplala** [comment]
> Vaex does not (yet) have the concept of indices, so it makes no sense to return this (while this is the case).
> What is it that you are trying to achieve?

It seems to me it has. I am currently assessing indices (or as you say _trying to_ actually ;)) on how to chunk a dataframe, as per discussion #1782 .
`vdf[start:end]`.

`return index` is not directly the indexes I am using, I further process them to have my `start` and `end`, but it is one of the 1st step. I would like the 1st steps to be conducted in vaex if possible as it will reduce the size of the 1d array (column), and then on the resulting array, finish the index calculation in numpy (last part of the calculations require `np.digitize()`)

The basic need is that I want to yield chunks of dataframe with indexes for the chunks that do not fall right in the middle of duplicates values. So from a list of chunk indexes, I am offsetting them as required.

I am currently working out this algorithm in numpy. Maybe there can be alternative way.
So, a bit more formalized, here is what I have in mind:
- 1st steps of calculations, in vaex on a column with vaex equivalents:
     - for `np.unique(return_index=True)` : vaex does not have `return_index`
     - for `np.diff` : vaex already has
     - extract results larger than 1     (reduction step)
     - switch to numpy to finalize the work on indices
- 2nd steps of calculations, in numpy this time
     - use of `np.digitize`

**Comment by JovanVeljanoski** [comment]
[Is this SO issue related?](https://stackoverflow.com/questions/70405390/splitting-an-array-according-input-offset-values-but-leaving-duplicated-in-a-sa).

Vaex know about row numbers. But does not have indices like pandas does  (it has kind of the `iloc`, row index, but not the `loc` index).

As for the rest.. i tried but i really can't understand what you are trying to do .. maybe someone else can help.

**Comment by yohplala** [comment]
> [Is this SO issue related?](https://stackoverflow.com/questions/70405390/splitting-an-array-according-input-offset-values-but-leaving-duplicated-in-a-sa).

My god, it is, I feel tracked now ;)

> Vaex know about row numbers. But does not have indices like pandas does (it has kind of the `iloc`, row index, but not the `loc` index).

Yes, it is what I have in mind. I mean my understanding is that vaex has same indexing than numpy, based on row number.
It is inline with my initial question. `np.unique()` is a numpy function. `return_index` is a parameter of this function so the index is the row number.

> As for the rest.. i tried but i really can't understand what you are trying to do .. maybe someone else can help.

Rephrasing the title of the ticket, my question here is:
  _Can `vaex.unique()` support `return_index` as `numpy.unique()` does?_
But yes, it is kind of an open question, I think I should investigate my own need further and assess possible alternative algorithms for my need before resorting to vaex specifically on this one.

**Comment by JovanVeljanoski** [comment]
I would ask @maartenbreddels  @xdssio , what do you think about this (unique returning row indices). 

Also, just for your understanding @yohplala, the `unique` in vaex  does not simply call `numpy.unique` in the background :).
