### ISSUE TITLE
GUI ignores keyboard layout

### ISSUE THREAD

**Issue by jhidding** [vaexio/vaex#18]
This may be PyQt related. Vaex gives me Qwerty input, but my keyboard is set on Dvorak.

**Comment by maartenbreddels** [comment]
Are you on linux, of so it might be this: https://bugreports.qt.io/browse/QTBUG-32322 :(

**Comment by maartenbreddels** [comment]
Although, looking at the data, it's pretty old. Do you know of another Qt that you can test? Spyder maybe?

**Comment by maartenbreddels** [comment]
stale
