### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by JamieSlome** [vaexio/vaex#1816]
Hey there!

I belong to an open source security research community, and a member (@srikanthprathi) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by maartenbreddels** [comment]
Hi,

thanks for reaching out, I've added a a simple https://github.com/vaexio/vaex/blob/master/SECURITY.md
Let take if from there, hope to hear from you soon.

Regards,

Maarten

**Comment by JamieSlome** [comment]
@maartenbreddels - you should have received an e-mail, otherwise you can view the report here:

https://huntr.dev/bounties/9014d7cf-ef2f-413b-822c-57a8c5aae408/

**Comment by JovanVeljanoski** [comment]
This issue has been resolved,  and a security policy has been since added when that one can review when creating a new issue.
