### ISSUE TITLE
AttributeError: module 'vaex' has no attribute 'DataFrame'

### ISSUE THREAD

**Issue by jgh2i** [vaexio/vaex#1838]
**Description**
** trying to initialize empty dataframe
 df = vaex.DataFrame()
AttributeError: module 'vaex' has no attribute 'DataFrame'

**Software information**
vaex                                                  4.7.0
vaex-astro                                        0.9.0
vaex-core                                         4.7.0.post1
vaex-hdf5                                         0.11.1
vaex-jupyter                                      0.7.0
vaex-ml                                             0.16.0
vaex-server                                       0.8.0
vaex-viz                                            0.5.1
virtualenv                                         20.2.2

 - OS:
ProductName:	macOS BigSur
ProductVersion:	11.6.2
BuildVersion:	20G314

**Comment by JovanVeljanoski** [comment]
You can't and should not initialize an empty dataframe. Please refer to the [tutorial](https://vaex.io/docs/tutorials.html) for information on how to use vaex.

**Comment by maartenbreddels** [comment]
I don't think that is happening, but indeed you shouldn't do that.

you shouldn't construct a dataframe via the constructor, please go over the tutorial.
