### ISSUE TITLE
'pip install vaex' fails on python 3

### ISSUE THREAD

**Issue by rieder** [vaexio/vaex#184]
It fails with the following error:

>   Using cached https://files.pythonhosted.org/packages/0d/e0/0c495ed2162406832894f93b06ce8d7c1e331ff4b859e5a048417408f3bb/vaex-0.3.10.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/p0/3kksqsgd2ll_9xn3yh7m75c00000gn/T/pip-install-32jpg29k/vaex/setup.py", line 18
>         print "Executing: ", cmd
>                           ^
>     SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Executing: ", cmd)?

I can't find this line though. Maybe it's a remnant of an older version?

**Comment by maartenbreddels** [comment]
Hi Steven,

thanks for the report, yes, use `pip install --pre vaex` for now, until we do a new release based on calver #178.

cheers,

Maarten
