### ISSUE TITLE
[BUG-REPORT]

### ISSUE THREAD

**Issue by derrickcchow** [vaexio/vaex#1844]
**Description**
Not really a bug but I was wondering if there was a function still called fillmissing? There is documentation on the function still but when i try to use the function i get an attribute error 

**Software information**
 - Vaex version (`import vaex; vaex.4.7.0)`:
 - Vaex was installed via: pip
 - OS: windows 10

**Additional information**
 __getattr__
[2022-01-18 12:28:47,582] ERROR in config.py (fn:write ln:74): return object.__getattribute__(self, name)
[2022-01-18 12:28:47,582] ERROR in config.py (fn:write ln:74): AttributeError
[2022-01-18 12:28:47,582] ERROR in config.py (fn:write ln:74): :
[2022-01-18 12:28:47,582] ERROR in config.py (fn:write ln:74): 'DataFrameLocal' object has no attribute 'fillmissing'

**Comment by JovanVeljanoski** [comment]
Yes there is. 

Can you perhaps do a minimal example exposing this ? Now we can't see why you are seing what you are seeing..

**Comment by derrickcchow** [comment]
Yes, I can provide an example. 
what i am trying to do is create a dataframe with columns that are string and turn them into a float datatype so that i can fill the blank values with a Nan value so i can manipulate it later to fill in the blank values with different time period.
example code is 
`df['Week of Event'] = df['Week of Event'].astype('float64')
        df['Fiscal Year of Event'] = df['Fiscal Year of Event'].astype('float64')
        df['Fiscal Quarter'] = df['Fiscal Quarter'].astype('float64')
        df['Fiscal Month of Event'] = df['Fiscal Month of Event'].astype('float64')
        df['Fiscal Week of Event'] = df['Fiscal Week of Event'].astype('float64')
        df['Julian Day'] = df['Julian Day'].astype('float64')
        df['Activity Event Id'] = df['Activity Event Id'].astype('float64')
        df['Measure Value'] = df['Measure Value'].astype('float64')
        df.fillmissing(value=np.nan,column_names=['Week of Event', 'Fiscal Year of Event', 'Fiscal Quarter',
                                                  'Fiscal Month of Event', 'Fiscal Week of Event', 'Julian Day',
                                                  'Activity Event Id', 'Measure Value'])`

**Comment by JovanVeljanoski** [comment]
Oh can  you format it properly please? Quite hard to read as it is..

Also I meant an example that we can run..  maybe with some fake data just to expose the badness..

**Comment by derrickcchow** [comment]
here it formated properly:
df['Week of Event'] = df['Week of Event'].astype('float64') 
df['Fiscal Year of Event'] = df['Fiscal Year of Event'].astype('float64') 
df['Fiscal Quarter'] = df['Fiscal Quarter'].astype('float64') 
df['Fiscal Month of Event'] = df['Fiscal Month of Event'].astype('float64') 
df['Fiscal Week of Event'] = df['Fiscal Week of Event'].astype('float64') 
df['Julian Day'] = df['Julian Day'].astype('float64')
 df['Activity Event Id'] = df['Activity Event Id'].astype('float64')
 df['Measure Value'] = df['Measure Value'].astype('float64') 

df.fillmissing(value=np.nan,column_names=['Week of Event', 'Fiscal Year of Event', 'Fiscal Quarter', 'Fiscal Month of Event', 'Fiscal Week of Event', 'Julian Day', 'Activity Event Id', 'Measure Value']) 

Will try to get you something that you can run

**Comment by JovanVeljanoski** [comment]
Ah I see the problem now:
`fillmissing` is a method on an expression, not on a dataframe. Only `fillna` is a method on a dataframe. 

So you need to do something like:
```python
df['x_filled'] = df.x.fillmissing(value=y)  # overwriting the original expression is also ok
```

**Comment by derrickcchow** [comment]
okay thanks, there's not a lot of documentation on it so I didn't full understand how to implement the method.
I will give this a go thanks for the help Jovan
