### ISSUE TITLE
Access and update values in vaex df

### ISSUE THREAD

**Issue by MarcoAbbatangelo** [vaexio/vaex#1849]
Hi,
I was wondering if there is a way to do the following operation from pandas in vaex.

``
df.values[list_row_index, list_column_index] += 1
``

Thanks

**Comment by JovanVeljanoski** [comment]
I believe that command is directly modifying the data in memory. 
In vaex you need to write a new expression for any changes you are doing (you can overwrite an expression). 

So you will need to do something like this for example (for every column you wanna change) 

```python
df['new_column'] = df.func.where(df['column'] > 5, value_if_true, value_otherwise) 
```

or simply


```python
df['new_column'] = df['column'] + 1
```

**Comment by MarcoAbbatangelo** [comment]
Thank you Jovan

**Comment by maartenbreddels** [comment]
And if you want to do this on row number, you can add a `df['row_number'] = vaex.vrange(0, len(df))` column quite cheaply

**Comment by MarcoAbbatangelo** [comment]
And if I want to do something like that:
``
df2 = vaex.from_arrays(x=x)
df2['new_column'] = df1.func.where(df1['column'] > 5, value_if_true, value_otherwise) 
``
I should do first ``df1.func.where(df1['column'] > 5, value_if_true, value_otherwise).evaluate()`` and then assign the values to df2 with from_array? O there is a fastest way? 

Thanks.

**Comment by maartenbreddels** [comment]
If you call evaluate, it will copy the data, which is probably what you want here because df1 and df2 life in different 'worlds'.
