### ISSUE TITLE
Error while converting pyarrow table to vaex dataframe

### ISSUE THREAD

**Issue by ashutosh2211** [vaexio/vaex#185]
Hi,

We recently ran into an issue while using `vaex.from_arrow_table` to convert a pyarrow table to vaex dataframe. The error seems to be in the buffer objects returned from the arrow_array.

![image](https://user-images.githubusercontent.com/4144295/53643512-2811e600-3c2c-11e9-86ad-7b3bc1100326.png)

The `arrow_array.buffers()` returns 3 buffer objects instead of 2 when we checked.

We are reading a parquet data file 
```
import pyarrow.parquet as pq
import vaex

p_dataset = pq.ParquetDataset("<filePathToTheParquetFile'>)
df = p_dataset.read()
df_vaex = vaex.from_arrow_table(df)
```
The parquet file is also encoded with the snappy encoder.
We can read the file to the pyarrow table without any issues.

It would be real;ly helpful to find some context or help on this issue as we are trying to use vaex for some data exploration tasks and this is one key blocker for it.
Thanks.

**Comment by maartenbreddels** [comment]
Hi Ashutosh,

Great timing, that is most likely a string column. I'm working at this right now. Could you confirm that it is a string column?

thanks for the report.

**Comment by andreeaPascu** [comment]
Hi Maarten,

Yes indeed. The error happens on string columns.

**Comment by maartenbreddels** [comment]
Hi Andreea,

thanks for letting me know.
#186 is the start of supporting this, would be great if you could test it.

cheers,

Maarten

**Comment by maartenbreddels** [comment]
Together with https://github.com/vaexio/vaex/pull/200 should be solved, otherwise please reopen.
