### ISSUE TITLE
Issue on page /index.html

### ISSUE THREAD

**Issue by DataExplorerUser** [vaexio/vaex#1872]
On page https://vaex.io/docs/index.html, at the bottom of the page, there is a link to examples that refers to https://vaex.io/docs/examples.rst. That page does not exist.

**Comment by JovanVeljanoski** [comment]
Thank you! I'll try to fix it.

**Comment by bandit-masked** [comment]
That was quick! Thanks. Vaex looks like an excellent library -- impressive performance!

**Comment by JovanVeljanoski** [comment]
Thank you :)
