### ISSUE TITLE
Configuration settings don't seem to "know" path_lock or "listen" to .env or other configuration settings

### ISSUE THREAD

**Issue by tdeboer-ilmn** [vaexio/vaex#1876]
I am using vaex to convert some CSV file on the fly, but my working directory gets swamped with .lock files that seem to stick around and don't seem to be removed.

Looking at https://vaex.io/docs/conf.html it seems there is an configuration option to set VAEX_LOCK or vaex.setting.main.path_lock to some directory to store the lock files in (it also seems to suggest that the default is ${VAEX_HOME}/lock/ but clearly that is not correct since it is using the CWD.

I tried setting the various forms of the configuraiton option, but vaex continues to use the WD...

It also seems that the configuraiton page uses 'setting' rather than 'settings', so a lot of the examples are wrong there.

I also tried this
`VAEX_LOCK='/data/.vaex/lock' vaex settings yaml`
`aliases: {}
async: nest
home: /data/.vaex
mmap: true
process_count: 64
thread_count: 64
thread_count_io: 65
chunk:
  size: null
  size_min: 1024
  size_max: 1048576
display:
  max_columns: 200
  max_rows: 10
fs:
  path: /data/.vaex/file-cache
server:
  add_example: true
  graphql: false
  files: {}
cache:
  type: null
  disk_size_limit: 10GB
  memory_size_limit: 1GB
  path: /data/.vaex/cache
data:
  path: /data/.vaex/data
memory_tracker:
  type: default
  max: null
task_tracker:
  type: ''`

But the output does not contain the expected path_lock value so it seems configuration is not working correctly?
Also tried the .env route to no avail and also using $VAEX_PATH_HOME/.vaex/main.yaml did not change anything.

Is there some other configuration file that I need to set (the JSON version?) that is the file that describes all the configuraiton options?

**Comment by JovanVeljanoski** [comment]
Closed via #2101 . Please re-open if needed.
