### ISSUE TITLE
[FEATURE-REQUEST] Extract out multi-level cache into a package

### ISSUE THREAD

**Issue by davidbrochart** [vaexio/vaex#1890]
**Description**

It looks like the [multi-level cache](https://github.com/vaexio/vaex/blob/069dc5f305925ba96011477b30fcef440236789e/packages/vaex-core/vaex/cache.py#L110) could be useful for other projects as well. Any plan to make a package of its own?

**Additional context**

[akernel](https://github.com/davidbrochart/akernel) could have an execution mode where cell execution would be cached. It could use such a multi-level cache.

**Comment by maartenbreddels** [comment]
I'm not planning to do so myself (at this moment), feel free to do so, and please take a look at df20365e6ce4390d46a6e3705c72ddd44aa146ee so you also capture the tests.

**Comment by davidbrochart** [comment]
Thanks!
