### ISSUE TITLE
[FR] Is it possible to load `zarr` files?

### ISSUE THREAD

**Issue by NightMachinery** [vaexio/vaex#1895]
Is it possible to load [`zarr`](https://zarr.readthedocs.io/) files?

**Comment by maartenbreddels** [comment]
Hi,

i think so, but not directly. If you pass the arrays to Vaex, using `vaex.from_arrays(...)` we will not copy them. But note that Vaex is about dataframes, so mostly a collection of 1d arrays of the same length, while zarr is about nd arrays, with often n>1.

Regards,

Maarten

**Comment by JovanVeljanoski** [comment]
I will close this as stale. Please re-open if needed.
