### ISSUE TITLE
[FEATURE-REQUEST] How to use dt.days in vaex

### ISSUE THREAD

**Issue by hacker1111** [vaexio/vaex#1896]
I subtracted two datetime64 columns and stored into a new column. Now I want to get the number of days from that column.
For example:
  #          datetime_1                     datetime_2                  delta                 
  0  2021-01-11 04:05:43  2011-01-11 04:05:43  -3653 days +00:00:00  
  1  2009-03-22 00:54:37  2019-03-22 00:54:37    3652 days 00:00:00    
  2  2017-12-22 14:46:27  2037-12-22 14:46:27    7305 days 00:00:00
How should I get no of days in delta column rather than this "3653 days +00:00:00" format.

Thanks & Regards

**Comment by JovanVeljanoski** [comment]
Hey did you figure this out or did you close it by mistake?

**Comment by ashsharma96** [comment]
@JovanVeljanoski Yeah while I was going through more issues I found the same and got the answer. So i closed it.
