### ISSUE TITLE
How to Filter on String on a virtual column

### ISSUE THREAD

**Issue by jgzga** [vaexio/vaex#1897]
Hello. 
I applied on my dataframe the next command

```
df['seccion'] = df.pagePath.str.split('/').apply(lambda x: x[1])
```

And this created the column 'seccion'

|pagePath	                                      |   seccion |
|-----------------------------------|----------------------|
|'/empresas/2021/10/22/tiendas-no-participan-buen'|	empresas |
|'/finanzas-personales/2021/10/22/pueden-cobrar-c|	finanzas-personales |
|'/finanzas-personales/2021/10/01/autos-mas-vendidos|	finanzas-personales |

Now I want to left only the values that contain some value. For example 'finanzas-personales'.
I know that in Vaex column "seccion" is a virtual column. So I tried something like

```
df['seccion'] = df.pagePath.str.split('/').apply(lambda x: x[1])
df2 = df.extract()
df2 = df2[df2['seccion']=='empresas']
```

But this doesn't work

I also tried:

```
df2.select(df2.seccion == 'empresas')
df2.evaluate(df2.seccion, selection=True)
```

This also doesn't work

Expected output once dateframe is filtered 

|pagePath	                                      |   seccion |
|-----------------------------------|----------------------|
|'/finanzas-personales/2021/10/22/pueden-cobrar-c|	finanzas-personales |
|'/finanzas-personales/2021/10/01/autos-mas-vendidos|	finanzas-personales |

Any suggestions you have will be greatly appreciated

**Comment by maartenbreddels** [comment]
Hi,

> But this doesn't work

Can you be more precise about what you mean?
`df2 = df[df["seccion"] == "empresas"]` should give you the expected results, what does df2 give you?

Regards,

Maarten

**Comment by JovanVeljanoski** [comment]
What do you mean when you say 
> But this doesn't work

Do you get an error, or a result that you do not expect?

Also the output of the code you are showing would not match the expected output you are showing at the end.

**Comment by jgzga** [comment]
Sorry. I think is there's an issue with the instalation or something on my machine. 

What I was trying to achieve is to filter my Dataframe 


```
df_urls[df_urls.seccion == 'finanzas-personales']
```

I ran this command in Google Colab and works fine and gives me the expected output. 

I will close the issue

Many thanks to both of you!

**Comment by JovanVeljanoski** [comment]
Would also be fair if you show the answer in your stackoverflow post, so other people may benefit.
