### ISSUE TITLE
head() method not displaying result after doing a replace() with regex

### ISSUE THREAD

**Issue by omonmaxi** [vaexio/vaex#1938]
**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: 4.7.0
 - Vaex was installed via: pip / conda-forge / from source : Vaex installed through conda-forge
 - OS: macOS
 - Conda  4.10.3

**Additional information**
Please state any supplementary information or provide additional context for the problem (e.g. screenshots, data, etc..).

Thanks for this great package. I'm not sure if this is a bug or how to classify it but I thought it was just unusual . So I ran the following code to do a replace on all empty strings in my data. The code ran quite well and fast without any error but when I run a head()  method to view the result, the process runs indefinitely. I figured it's because of the volume of data  (8 million + rows) but then I repeated the task on smaller data (5 rows) but the same thing occurred. However, trying this task on a pandas dataframe gave me the result I wanted and I was able to view the result. Thanks

```
%time var = sample.get_column_names() 

for i in var:
    if i == 'ibe8579_8579' or i == 'ibe8592_8592' or i == 'raw_create_timestamp' or i == 'raw_load_date':
        sample[i]
    else:
        sample[i] = sample[i].str.replace(pat = r'^\s*$', repl = 'empty', regex = True)


head(2)
```

**Comment by JovanVeljanoski** [comment]
Hi, can you make a reproducible example? Small with fake data will do. Thanks

**Comment by JovanVeljanoski** [comment]
This example works for me  (on latest master)

```python
import vaex

x = ['asad', 'asf adf ', '', '', 'asfasf']
df = vaex.from_arrays(x=x)
df['x'] = df['x'].str.replace(pat = r'^\s*$', repl = 'empty', regex = True)
print(df)
```

**Comment by JovanVeljanoski** [comment]
Ok I think I can reproduce it. I will make tests, thanks!

**Comment by JovanVeljanoski** [comment]
Ok, as a workaround you can try using `str_pandas`:

```python
sample[i] = sample[i].str_pandas.replace(pat = r'^\s*$', repl = 'empty', regex = True)
```

This will not be as performant, but it should work until we fix the issue. The issue only happens if you have an empty string in the 1st element. So in principle you can adjust your loop to check for this, and if true, use `str_pandas.replace`, otherwise use `str.replace` for performance. 

Thanks for reporting this. Let's keep this open until solved.

**Comment by JovanVeljanoski** [comment]
How to reproduce the issue @maartenbreddels :

```python
import vaex
x = ['', '', 'please']
df = vaex.from_arrays(x=x,)
df['x_fill'] = df.x.str.replace(pat = r'^\s*$', repl = 'empty', regex = True)
```

**Comment by omonmaxi** [comment]
Sorry for my late response. I'm not allowed to share such info. I'm not sure if I mentioned this before or if it's relevant but my data contains 8+ million rows and 417 columns hence the reason for the for loop. You mentioned that this happens when some of the columns has empty strings as the first value, this is true for my data. That being said, I'm not sure how to modify my code to work according to your suggestion. I'd appreciate it if you could help me with that. Thanks

**Comment by omonmaxi** [comment]
Not sure if this is what you mean?


`%time var = sample.get_column_names() 

for i in var:
    if i == 'ibe8579_8579' or i == 'ibe8592_8592' or i == 'raw_create_timestamp' or i == 'raw_load_date':
        sample[i]
        
    elif data[i][0] == '' or data[i][0] == ' ' or data[i][0] == '  ' or data[i][0] == '   ':
        sample[i] = sample[i].str_pd.replace(to_replace = r'^\s*$', value = 'empty', regex = True)
        
    else:
        sample[i] = sample[i].str.replace(pat = r'^\s*$', repl = 'empty', regex = True)

`

**Comment by omonmaxi** [comment]
I tried using the where statement but it unfortunately couldn't catch all the variation of empty strings in the data , I was left with some stubborn ones but I was able to run the head() method, that was why I resulted to using regex but couldn't view the data with the head() method after running the aforementioned code. Nonetheless, I will try your suggestion. Thanks for responding so swiftly.

**Comment by omonmaxi** [comment]
Goodnews!!! It worked like a charm. I didn't know I could use pandas methods with Vaex arguments on a Vaex dataframe.  I'm shocked or am I missing something? Just incase anyone might need this, this is how I modified my code. A huge THANKS to you. 



`%time var = bge.get_column_names()  # Ben

for i in var:
    if i == 'ibe8579_8579' or i == 'ibe8592_8592' or i == 'raw_create_timestamp' or i == 'raw_load_date':
        bge[i]
    else:
        bge[i] = bge[i].str_pandas.replace(pat = r'^\s*$', repl = 'empty',  n = -1, regex = True)`
