### ISSUE TITLE
[BUG-REPORT] Unable to run KMeans clustering with more than five features in dataset

### ISSUE THREAD

**Issue by ninabina921** [vaexio/vaex#1952]
**Description**

Unable to cluster my sample dataset with more than five features. Below is the code I used
`df_test = vaex.read_csv(filepath, convert=True, chunk_size=chunk_size)`
 ` features = df_test.get_column_names()`
  `cls = [vaex.ml](http://vaex.ml/).cluster.KMeans(n_clusters=3, features=features, init='random')`
 ` cls.fit(df_test)`
 ` df_test = cls.transform(df_test)`
When i try to cluster using all columns in my dataset, I get the following error:
![Screen Shot 2022-02-23 at 7 20 47 PM](https://user-images.githubusercontent.com/15370123/156221203-ad261ee5-4af4-4720-ad03-dc2f5f802405.png)

If I change `features` to only five columns in my dataset, the KMeans function executes fine. 

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: 4.8.0
 - Vaex was installed via: pip 
 - OS: Mac Mojave 10.14.6

**Comment by JovanVeljanoski** [comment]
I can't reproduce it, look at this example:

```python
import vaex.ml.cluster

df = vaex.example()
features = df.column_names[1: 9]

train, test = df.ml.train_test_split()

cls = vaex.ml.cluster.KMeans(features=features, n_cluster=10)
cls.fit(train)
cls.transform(test)

```

Can you check if there is something strange with your data, such as missing values, inf, etc..

**Comment by JovanVeljanoski** [comment]
Actually, what could be happening.. can you make sure that all of your input features are of type float? 
(or float64 to be more exact).

**Comment by ninabina921** [comment]
I am using float64 but I can try float32 like the example vaex data

**Comment by JovanVeljanoski** [comment]
i just tried it with 100M rows on 8 features and it works fine (all features float64, numpy)

**Comment by ninabina921** [comment]
I found the issue. It seems to be a problem caused by using `column.names` and `get_column_names()`. When I converted all columns to `float64` using `get_column_names()`, it added duplicate column name in my array. I tried using column.names to change the column dtypes first then used `get_column_names()` for the features array. Thank You
