### ISSUE TITLE
[BUG-REPORT] Dataframes are corrupted after filters (only on linux)

### ISSUE THREAD

**Issue by Ben-Epstein** [vaexio/vaex#1972]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your problem may already be discussed or addressed.

**Description**
Please provide a clear and concise description of the problem. This should contain all the steps needed to reproduce the problem. A minimal code example that exposes the problem is very appreciated.

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: `{'vaex-core': '4.8.0', 'vaex-hdf5': '0.12.0'}`
 - Vaex was installed via: pip / conda-forge / from source `pip`
 - OS: 
```
[ec2-user@ip-172-31-33-173 ~]$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Additional information**
Code to reproduce

```
import vaex

df_right = vaex.open("output.hdf5")
df_left = vaex.open("output.hdf5")
df_right = vaex.open("input.arrow")
df_right_split = df_right[df_right["split"]=="training"]
df_left.join(df_right_split, on="id", how="inner", lsuffix="_L", rsuffix="_R")
```

For some reason I cannot upload a zip file (only 34MB), but here is the link for the zip. It contains 1 hdf5 file and 1 arrow file (named as above). https://drive.google.com/file/d/11lCcXrx0FDLWJg2WgNfxdy8nuKjqnhWg/view?usp=sharing

EDIT: Note that the following works:
```
import vaex

df_right = vaex.open("output.hdf5")
df_left = vaex.open("output.hdf5")
df_right = vaex.open("input.arrow")
df_right_split = df_right[df_right["split"]=="training"]
df_right_split = df_right_split.extract()
df_right_split["id"] = df_right_split["id"].values  # This is required!
df_left.join(df_right_split, on="id", how="inner", lsuffix="_L", rsuffix="_R")
```

calling only `extract` alone won't work. You need the `id.values` line as well, materializing the column.

**Comment by JovanVeljanoski** [comment]
Hey @Ben-Epstein !

I can't reproduce your issue with the data you provided. Your code example works the way I'd expect. 

I see when creating this issue you've used a but of older version of vaex (from current point of view), maybe you can check if updating helps. 

Cheers, 
J.

<img width="954" alt="image" src="https://user-images.githubusercontent.com/18574951/187280051-56fa80e4-b37a-43ef-b400-cf339a5a9272.png">

**Comment by Ben-Epstein** [comment]
Hi @JovanVeljanoski yes this seems to be gone with 4.10. Thanks!
