### ISSUE TITLE
[BUG-REPORT] Vaex.open() not including 'profile' option when opening files from S3

### ISSUE THREAD

**Issue by krishancaldwell** [vaexio/vaex#1983]
**Description**
When attempting to pull `parquet` files from an S3 bucket using `vaex.open()`, I'm passing `fs_options={'profile': 'myProfile'}`. However, in the logs I can see that Vaex is attempting to use the default profile and hence failing to download the file from the following warning
```
WARNING - /home/***/.local/lib/python3.9/site-packages/vaex/file/s3.py:19 UserWarning: Reading key/secret from ~/.aws/credentials using profile: /home/***/.aws/credentials
```

**Software information**
 - Vaex version 4.8.0:
 - Vaex was installed via: pip
 - OS: Debian Buster (Airflow Docker Image - `apache/airflow:2.2.4-python3.9`)

**Additional information**
Code to reproduce below.

```python 
df = vaex.open("s3://my-bucket/path/to/snappy/parquet/files/*", fs_options={"cache": False, "profile": "myProfile"})
```

Which fails to open the file with the following error
```
WARNING - /home/***/.local/lib/python3.9/site-packages/vaex/file/s3.py:19 UserWarning: Reading key/secret from ~/.aws/credentials using profile: /home/***/.aws/credentials
ERROR - error opening 's3://my-bucket/path/to/snappy/parquet/files/*'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/vaex/__init__.py", line 212, in open
    raise IOError(f'File pattern did not match anything {path}')
OSError: File pattern did not match anything s3://my-bucket/path/to/snappy/parquet/files/*
```

**Comment by Hasham04** [comment]
this is not an issue with the profile option. Try opening your files with this.

``df = vaex.open("s3://my-bucket/path/to/snappy/parquet/files/*.parquet", fs_options={"cache": False, "profile": "myProfile"}).
``
Make sure you have named your profile correctly in ~/.aws/credentials.

**Comment by krishancaldwell** [comment]
Thanks @Hasham04.

I gave your suggestion a go, but still ran into the same problem.

I'm fairly sure it's the `profile` option, as when I use the default AWS profile (ie `"profile": "default"`), the files are fetched correctly.

**Comment by maartenbreddels** [comment]
We don't support profile directly, because arrow does not support that. However, if you explicitly use fs=... (use s3f filesystem) or use:
```
df = vaex.open("fsspec+s3://my-bucket/path/to/snappy/parquet/files/*", fs_options={"cache": False, "profile": "myProfile"})
```

it should use s3fs, which supports this option
