### ISSUE TITLE
[BUG-REPORT] parsing a pandas.DataFrame with a column named `"col"` causes `RecursionError`

### ISSUE THREAD

**Issue by raphaelquast** [vaexio/vaex#1992]
Hey, I just opened up another issue, but since this one came up as well I thought I report it also...

**Description**
It seems that `"col"` is somehow used internally by vaex but `pandas` allows `"col"` as a column-name....

```python
import pandas as pd
import vaex

pandas_df = pd.DataFrame(dict(col=[3, 4, 5]), index=[1,2,3])
vaex.from_pandas(pandas_df)
```

```python
...
...
  File "D:\miniconda\envs\rt1\lib\site-packages\vaex\dataframe.py", line 2098, in col
    expression = getattr(self, name, None)

  File "D:\miniconda\envs\rt1\lib\site-packages\vaex\dataframe.py", line 2098, in col
    expression = getattr(self, name, None)

  File "D:\miniconda\envs\rt1\lib\site-packages\vaex\dataframe.py", line 2094, in col
    class ColumnList(object):

RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
 - {'vaex-core': '4.8.0',
 'vaex-viz': '0.5.1',
 'vaex-hdf5': '0.12.0',
 'vaex-server': '0.8.1',
 'vaex-astro': '0.9.0',
 'vaex-jupyter': '0.7.0',
 'vaex-ml': '0.17.0'}
 - Vaex was installed via:  conda-forge
 - OS: Windows

**Comment by JovanVeljanoski** [comment]
Thanks for the report! I can confirm this is a bug

**Comment by maartenbreddels** [comment]
Fixed in vaex-core 4.9

**Comment by maartenbreddels** [comment]
And thanks for the report indeed!

**Comment by raphaelquast** [comment]
awesome! thanks for the nice library!
