### ISSUE TITLE
[BUG-REPORT] Issue Importing Vaex due to Contextual Version Conflict

### ISSUE THREAD

**Issue by msbeeman** [vaexio/vaex#2014]
**Description**
Good morning, after freshly re-installing Anaconda, and subsequently Vaex, I was unable to import vaex in a jupyter notebook using `import vaex`. I received two errors, both stating there was a contextual version conflict with pydantic. Per the error, I visited pydantics site to find the most recent version (1.9.0) and upgraded to it by running:
- `conda install pydantic=1.9.0`

This seemed to allow me to begin importing vaex.

![image](https://user-images.githubusercontent.com/59752826/162766198-5ccdf76c-9876-403c-8b7d-431658cab43a.png)

**Software Information**
**Vaex Installation:** Vaex was installed via conda-forge using the following commands [from the docs](https://vaex.io/docs/installing.html): `conda install -c conda-forge vaex-core vaex-viz vaex-jupyter vaex-server vaex-hdf5 vaex-astro vaex-ml`
**OS:** macOS Monterey
**Anaconda Version:** 2021.11
**Vaex Versions:**```{
‘vaex-core’: ‘4.8.0’,
 ‘vaex-viz’: ‘0.5.1’,
 ‘vaex-hdf5’: ‘0.12.0’,
 ‘vaex-server’: ‘0.8.1’,
 ‘vaex-astro’: ‘0.9.0’,
 ‘vaex-jupyter’: ‘0.7.0’,
 ‘vaex-ml’: ‘0.17.0’
}```

**Comment by maartenbreddels** [comment]
Thanks for reporting this, this will be fixed in Vaex 4.9.1 on conda-forge:
 * https://github.com/conda-forge/vaex-core-feedstock/pull/80

**Comment by JovanVeljanoski** [comment]
Will close this as we consider it solved. Please re-open if needed.
