### ISSUE TITLE
Safe to remove cmake from vaex-core/pyproject.toml ?

### ISSUE THREAD

**Issue by Haiz14** [vaexio/vaex#2026]
I was trying to install vaex on termux, but while installing python module  cmake a dependency for vaex-core i was facing lots of difficulties.

So, one guy suggested to remove cmake and ninja from pyproject.toml of vaex-core since it's not used at all.( https://github.com/termux/termux-packages/issues/10065#issuecomment-1105651104 )

Would it be safe if i remove cmake from vaex-core pyproject.toml ?

**Comment by Haiz14** [comment]
Solved, i just created a dummy cmake, that doesn't even work but i got passed the requirement of not having cmake.

**Comment by maartenbreddels** [comment]
I'm ok with that.
