### ISSUE TITLE
Optional dependency [FEATURE-REQUEST]

### ISSUE THREAD

**Issue by Haiz14** [vaexio/vaex#2028]
**Description**

Can certain dependency like pyarrow and libllvmlite be made optional like in dark

**Is your feature request related to a problem? Please describe.**

I was trying to install vaex but i wasn't able to install it cause i am missing these two packages
``Failed to build pyarrow llvmlite``
I tried installing them but it's really problematic.

**Additional context**

While dask also needs pyarrow they list it as optional and i can successfully install it. Can this same feature be executed here.

Thks

**Comment by Haiz14** [comment]
Finally installed pyarrow just llvmlit is left, finding llvm version 11.x.x is tough, gotta build it myself. I have llvm 14.x.x though.

**Comment by Haiz14** [comment]
np i installed ``pyarrow`` just lacking `libllvmlite`

**Comment by maartenbreddels** [comment]
ok, that should be fixed by cherry-picking only what you need, `vaex-core`, `vaex-hdf5` etc
