### ISSUE TITLE
Conversion of virtual column to a real column

### ISSUE THREAD

**Issue by ashsharma96** [vaexio/vaex#2050]
Hey @JovanVeljanoski,
I want to know one thing that how to convert a virtual column to a actual column. For example I'll share one dataframe information below:
![image](https://user-images.githubusercontent.com/17443937/167994517-998473b2-8bf7-458a-835d-52942ac5104d.png)
the last column store_recency is a virtual column with some expressions on it. I want to be store_recency column as int64 with no expressions on it. For example
![image](https://user-images.githubusercontent.com/17443937/167994914-5911c146-7806-4783-b156-bdab7893c168.png)
I've tried extract function but that doesn't help me. Have you any idea how can I do this?
In detail, my dataframe name is df_rec which has 3 columns mentioned in above pictures.

**Comment by JovanVeljanoski** [comment]
Use `df.materialize(...)`

**Comment by ashsharma96** [comment]
@JovanVeljanoski  Thank you so much. Its working. I'll close this one.
