### ISSUE TITLE
[FEATURE-REQUEST] drop duplicates in vaex

### ISSUE THREAD

**Issue by ashsharma96** [vaexio/vaex#2051]
Hey @JovanVeljanoski  
How we can easily do drop duplicates in vaex dataframe? Is there any particular function for this one?

**Comment by JovanVeljanoski** [comment]
Please search the issue / pr boards before posting. 

Check this out:
https://github.com/vaexio/vaex/issues/746
https://github.com/vaexio/vaex/pull/1623

There is no proper implementation yet, but maybe this will serve as an inspiration for you.
