### ISSUE TITLE
[FEATURE-REQUEST] Make HDF5 output configurable

### ISSUE THREAD

**Issue by Darktex** [vaexio/vaex#2061]
**Description**
Vaex has an excellent hdf5 [exporter](https://github.com/vaexio/vaex/blob/master/packages/vaex-hdf5/vaex/hdf5/export.py), but the structure of the file it generates is currently static: it will always write each column under the `/table` group, under `/table/columns`.

It would be great if we could make this output configurable, and if we could also allow for custom `attributes` in the HDF5 file, so that Vaex can be used upstream of packages that require a fixed HDF5 file structure.

**Is your feature request related to a problem? Please describe.**
My current use case is about using Vaex together with [PyTorch-BigGraph](https://torchbiggraph.readthedocs.io/en/latest/index.html). BigGraph requires that edges be put in a HDF5 file with a fixed structure (see their [docs](https://torchbiggraph.readthedocs.io/en/latest/input_output.html#edges)), which prevents me from using Vaex directly.

**Comment by JovanVeljanoski** [comment]
Hi, 

`df.export_hdf5` does accept the `group` argument and you can use it to specify the path here the data is stored within the hdf5 file. 

Check out the [docs](https://vaex.io/docs/example_io.html#Exporting-binary-file-formats) for more instructions. 

Does this help, or did you mean something completely different?

**Comment by JovanVeljanoski** [comment]
Closing as stale. Please re-open if needed.
