### ISSUE TITLE
Unable to open gzipped CSV's [BUG-REPORT]

### ISSUE THREAD

**Issue by jaredbgo** [vaexio/vaex#2070]
I am trying to use `vaex.open()` on a gzipped CSV.

Getting this error:

`OSError: Cannot open ./folder/filename.csv.gz nobody knows how to read it.`

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: 4.9
 - Vaex was installed via: pip

**Additional information**
Pandas is able to read in gzipped CSV's without issue. Do you plan on adding support at any point? Also a more descriptive error for this use case could be helpful, 'nobody knows how to read it' is a little vague although I understand you guys are likely using this as an umbrella error for many unsupported formats. 

This same issue arises when using `vaex.open_many()`. Opening using `vaex.from_csv` and specifying `compression='GZIP'` was successful however.

**Comment by maartenbreddels** [comment]
I think we need to explore the option mentioned in https://github.com/vaexio/vaex/issues/1879#issuecomment-1033691134 first

**Comment by JovanVeljanoski** [comment]
I believe this is now possible in the new release, thanks to @maartenbreddels .

Please re-open if needed.
