### ISSUE TITLE
[FEATURE-REQUEST] Maintain a CIRCULAR MEMORY BUFFER using vaex - Simultaneous write and read HDF5

### ISSUE THREAD

**Issue by nithintito** [vaexio/vaex#2078]
**USER CASE**
   Data acquisition from sensor and post-processing real time

**DESCRIPTION**
1. Sensor data are logged using a data acquisition system
2. Latest 1 million data is required for post-processing in real time
3. Since the buffer in the data acquisition system is only a few MegaBytes. The data has to be transferred to host PC and stored till 1 million data is collected and then processed.
4. Once one set of 1 million data is processed, the next 1 million data has to be transferred from the data acquisition system to PC.

**Single Writer Multiple Reader** ([SWMR](https://docs.h5py.org/en/stable/swmr.html)) implementation to read and write in the **same HDF5 file with a fixed size as a circular buffer** is the preferred feature for data handling in this problem

**Comment by nithintito** [comment]
Hi Maarten,

   Appreciate your prompt help. The solution you had suggested rightly meets the requirement.

Do we need to add exception handling to prevent the same memory from being assessed by WRITER and READER at the same time?  How does vaex handle such a scenario?

I will be implementing [DATA PRODUCER(write) CONSUMER(read) architecture](https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z0000019WvuSAE&l=en-IN) using multi threading. So WRITER and READER can access the same memory map at same time, should this be avoided.

Here is my code snippet

** CREATE CIRCULAR BUFFER**

```
import vaex
import vaex.hdf5.writer as w
h5_filename = '/path/to/cbuf.hdf5'

def CreateVaexCircularBuffer(h5_filename):   # Create HDF5 file in disk to store circular buffer
    try:
        os.remove(h5_filename)
    except OSError as e:  ## if failed, report it back to the user ##
        print("Error: %s - %s." % (e.filename, e.strerror))

    N = 1000000
    # dummy dataframe for laying out the hdf5 file
    df_layout = vaex.from_arrays(
        id=vaex.vrange(0, N),
        x=vaex.vconstant(0, N, dtype='int64'),
        y=vaex.vconstant(0, N, dtype='float32')
    )
    
    
    with w.Writer(h5_filename) as writer:
        writer.layout(df_layout)
```

**Thread for writing data to circular buffer** 
   
```
def WriteToVaexCircularBuffer(h5_filename,index_write_begin,index_write_end): # Thread to write data to Circular Buffer
    df_write = vaex.open(h5_filename, write=True)
    with vaex.cache.off():
        df_write.x.values[index_write_begin:index_write_end] = 42  # write  directly in the mmapped numpy array
```
**Thread for reading and processing data stored in circular buffer**    
```
def ReadFromVaexCircularBuffer(h5_filename,index_read_begin,index_read_end): # Thread to read data from Circular Buffer
    df_read = vaex.open(h5_filename)
    with vaex.cache.off():
        df_linear = vaex.concat([df_read[index_read_begin:], df_read[:index_read_end]])
    # df_read.execute() or # .get() # https://vaex.readthedocs.io/en/latest/example_async.html
    #  Should concat operation be force executed 
    
    # Some arithmetic operation to follow after reading
    print(df_linear.x.values[:])
```

**Comment by maartenbreddels** [comment]
> Do we need to add exception handling to prevent the same memory from being assessed by WRITER and READER at the same time? How does vaex handle such a scenario?

It's memory, so basically, the last one wins. 
If you use multithreading, you may want to protect some codes with a mutex (e.g. threading.Lock). I can't go into the details of concurrent programming, that's a whole new topic :)
