### ISSUE TITLE
[FEATURE-REQUEST]: Expose `vaex.DataFrame` for type hinting

### ISSUE THREAD

**Issue by NickCrews** [vaexio/vaex#2086]
I would like to add type annotations to my code. Currently I can do `from vaex.dataframe import DataFrame`, but it would be nice if  the DataFrame was exposed at the top level so I could just do `import vaex` and then `df: vaex.DataFrame = ...`

I like being able to namespace it like this to differentiate between other DataFrames, eg `import pandas as pd` and then `pdf: pd.DataFrame = ...`

I can submit a PR if you want. Thank you for this awesome library, I'm excited to get started with it! Better string processing is a big requirement of mine and this is 💯

**Comment by NickCrews** [comment]
@JovanVeljanoski any thoughts on this?

**Comment by JovanVeljanoski** [comment]
I have no strong opinion on this. @maartenbreddels if you have no objections, we can just do this.  Should we proceed?

**Comment by NickCrews** [comment]
Linked to a PR above. Also exposed Expression, because I often want to type that as well. We didn't discuss that, so leave it out if it's a problem.
