### ISSUE TITLE
[BUG-REPORT] Storing an array of strings

### ISSUE THREAD

**Issue by thebhsu** [vaexio/vaex#2087]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your problem may already be discussed or addressed.

**Description**

This succeeds:

```python
data = {"A": [1], "B": [[1, 2, 3]]}
vx.from_dict(data)
```

|   | A | B |
|-- | -- | -- |
| 0 | 1 | array([1, 2, 3]) |

and this fails:

```python
data = {"A": [1], "B": [["a", "b", "c"]]}
vx.from_dict(data)

"""
Error
pyarrow.lib.ArrowInvalid: only handle                           
                             1-dimensional arrays 
"""
```

is this a limitation of pyarrow or vaex? any simple workarounds.

**Software information**

```python
vx.__version__

{'vaex': '4.9.2',
 'vaex-core': '4.9.2',
 'vaex-viz': '0.5.2',
 'vaex-hdf5': '0.12.2',
 'vaex-server': '0.8.1',
 'vaex-astro': '0.9.1',
 'vaex-jupyter': '0.8.0',
 'vaex-ml': '0.17.0'}
```

**Additional information**
Please state any supplementary information or provide additional context for the problem (e.g. screenshots, data, etc..).

**Comment by JovanVeljanoski** [comment]
I believe it is a quirk with arrow.. 

There are a couple of simply ways to go around this:

```python
import vaex
import pyarrow as pa

# the best option  - cast things to arrow beforehand
data = {"A": [1], "B": pa.array([["a", "b", "c"]])}
df = vaex.from_dict(data)

# easiest option - go via pandas (but check how data types are propagated)
import pandas as pd
data = {"A": [1], "B": [["a", "b", "c"]]}
df = vaex.from_pandas(pd.Dataframe(data))
```

I hope this helps.

**Comment by thebhsu** [comment]
Thanks for the quick feedback.

Unfortunately, if a user wanted to export the vaex dataframes (`df.export_hdf5`) with the above approaches, they would be met a `TypeError: Cannot export column of type: ...`. I think you eluded to this in the second solution but is there another workaround that allows for exporting.

**Comment by JovanVeljanoski** [comment]
In that case you should use `df.export_arrow`.

**Comment by JovanVeljanoski** [comment]
This is now explained on this (https://github.com/vaexio/vaex/pull/2088)

**Comment by JovanVeljanoski** [comment]
Well it should not crash.. can you open a separate issue for that please?
