### ISSUE TITLE
Equal aspect without square figure?

### ISSUE THREAD

**Issue by rieder** [vaexio/vaex#21]
Is it possible to have equal aspect axes in the GUI, without having a square image?
In this case, an x axis ranging from 0-1 and an y axis ranging from 0-2 with equal aspect would result in a rectangular figure (e.g. with similar x/y ratio as in the figure without equal aspect).

**Comment by maartenbreddels** [comment]
Not now, but I think this should be possible, just that this was easier to implement, but I understand the use case.

**Comment by maartenbreddels** [comment]
Will not implement this I think, focussing on jupyter.
