### ISSUE TITLE
Needing append functionality

### ISSUE THREAD

**Issue by RuanPutka** [vaexio/vaex#211]
I couldn't find a way to append data to my vaex dataframe. I need something like pandas.DataFrame append method:

**DataFrame.append(other, ignore_index=False, verify_integrity=False, sort=None)[**
> Append rows of other to the end of caller, returning a new object.
> Columns in other that are not in the caller are added as new columns.

Anyone willing to help me with this?

[]'s

**Comment by JovanVeljanoski** [comment]
Hi, 

I think if you do 
`df  = df_1.concat(df_2)`
you will get close to what you need.  

The only thing is that `df` will have only the columns that are common between `df_1` and `df_2` ( i think, not 100% on this).

**Comment by RuanPutka** [comment]
Yes, it worked! Thank you very much. But just out of curiosity, why this functionality isn't described in the documentation?

**Comment by maartenbreddels** [comment]
Hi Ruan,

It's on the API docs:
https://docs.vaex.io/en/latest/api.html#vaex.dataframe.DataFrameLocal.concat
But not in the tutorial. The tutorial needs a bit more coverage on this topic, adding/removing columns etc.
Would it have helped if it was there, or would you expect an append method?

cheers,

Maarten

**Comment by RuanPutka** [comment]
I wouldn't necessary expect an append method, but I would expect to find a section for grouping functions / methods. I tried searching for terms like join, merge and append but got nowhere near finding *concat*. 

Anyways, thanks! Now I have what I need haha, :+1: 

[]'s
