### ISSUE TITLE
[BUG-REPORT] empty filtered dataframe cannot be sliced

### ISSUE THREAD

**Issue by Ben-Epstein** [vaexio/vaex#2123]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your problem may already be discussed or addressed.

**Description**
Please provide a clear and concise description of the problem. This should contain all the steps needed to reproduce the problem. A minimal code example that exposes the problem is very appreciated.

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: 4.10
 - Vaex was installed via: pip / conda-forge / from source  pip
 - OS: mac/linux

**Additional information**
```
import vaex

df = vaex.example()
df_empty = df[df.x==4]
df_empty[:3]  # RuntimeError: end index should be larger or equal to start index
```

**Comment by JovanVeljanoski** [comment]
What would you expect to get? Since the dataframe you are slicing is empty..

**Comment by Ben-Epstein** [comment]
@JovanVeljanoski I'd expect an empty dataframe. 

At least a helpful error if not, but I think it's reasonable to get an empty df

**Comment by maartenbreddels** [comment]
Yes, good point! 
Do you want to open a PR with a test in `tests/slice_test.py`?
Then I'm happy to fix it! Do you agree @JovanVeljanoski ?

**Comment by JovanVeljanoski** [comment]
Agreed. Unit-test made
