### ISSUE TITLE
[BUG-REPORT] setup uses hardcoded name for python

### ISSUE THREAD

**Issue by arunpersaud** [vaexio/vaex#2126]
Setup.py currently uses
` os.system('python -m pip install --upgrade .')`
but this should be 
` os.system(f'{sys.executable} -m pip install --upgrade .')`

Using just 'python' can create problems when several pythons are installed, e.g. python3.10 and python3.9 and the default system python is linked to python3.10. In this case one can start the install using `python3.9 -m pip install .`, but python3.10 will be called from within setup.py. Happy to supply a pull request for this (I only found 3 locations where this should be changed in the top setup.py file)

**Comment by JovanVeljanoski** [comment]
Closed via https://github.com/vaexio/vaex/pull/2144/files
