### ISSUE TITLE
[BUG-REPORT] vaex.viz.histogram data transposed

### ISSUE THREAD

**Issue by cega-000** [vaexio/vaex#2142]
**Description**
vaex.viz.histogram has an issue where the data appears to become transposed when choosing a list of selections.

**Example Code**
import vaex as vx
df = vx.example()
df.viz.histogram("x", selection=[None,None], shape = 10)
df.viz.histogram("x", selection=None, shape = 10)

**Software information**
 - Vaex version: 'vaex': '4.11.1', 'vaex-core': '4.11.1', 'vaex-viz': '0.5.2', 'vaex-hdf5': '0.12.3', 'vaex-server': '0.8.1', 'vaex-astro': '0.9.1', 'vaex-jupyter': '0.8.0', 'vaex-ml': '0.18.0'
 - Vaex was installed via: pip 
 - OS: mac

**Comment by JovanVeljanoski** [comment]
Hey! 

Strange.. I am not sure if the intent was to only ever have one selection.. but I attempted to add support for this as you requested. I do want @maartenbreddels to take a look at it just in case before merging.  Feel free to experiment with the pull-request branch and provide feedback / improvements if you want! 

Thank you!

**Comment by arunpersaud** [comment]
Hi

it would be great to have this supported. The documentation (guides-> [plotting selection](https://vaex.io/docs/guides/advanced_plotting.html#Plotting-selections)) show an example where multiple selections are used for a heatmap and I could also use it for 1D histograms. It seems to be already working when using df.count, which is what I am doing now.
I see if I can try out the branch too

Thanks.

**Comment by arunpersaud** [comment]
I have some issues building from source, so I just downloaded the new mpl.py file from your branch and just replaced it in site-packages and it seems to work well! Would be great to get this merged... Already looking forward to the release which includes this :)

Thanks for the quick fix.

**Comment by JovanVeljanoski** [comment]
Hey, i just merged the fix -  so you can install  from master if you'd like that. 
For a release.. sometime 2nd half of august.. as we are on holidays :)
