### ISSUE TITLE
Not working with tensorflow

### ISSUE THREAD

**Issue by JuliaJ99** [vaexio/vaex#2166]
This is the error I got:
![image](https://user-images.githubusercontent.com/91378218/184421347-ca8bee58-a63c-4684-90d4-7e5077a4c513.png)

when I called the fit method while I was trying to run a neural network model using tensorflow. I largely followed the docs example here except I didn't scale my data, added more layers, changed activation functions, and used different optimizer, metrics for compiling. https://vaex.readthedocs.io/en/latest/tutorial_ml.html#Keras-example 

and it shouldn't hopefully be a package issue as vaex-ml is there
![image](https://user-images.githubusercontent.com/91378218/184422733-84c2d790-ccf5-4b8d-8cef-e18f64c19ebf.png)

Any idea?

**Software information**
 - Vaex was installed via: pip 
 - OS: windows

**Comment by JovanVeljanoski** [comment]
Can you share your code..?

From where error it looks like you are using a dataframe somewhere where a string or an expression is exptected

**Comment by JuliaJ99** [comment]
https://nbviewer.org/github/JuliaJ99/Kaggle-projects/blob/ad5500762054ea650ff917a6cef0f4d15aaf7851/NB1.ipynb

If that's easier to read or I just posted it on github https://github.com/JuliaJ99/Kaggle-projects/blob/ad5500762054ea650ff917a6cef0f4d15aaf7851/NB1.ipynb

**Comment by JovanVeljanoski** [comment]
So as the error says... in your case `target` appears to be a dataframe. It should be an expression, one that which exists in the training (and validation) data

**Comment by JuliaJ99** [comment]
I am a bit confused, what do you mean by expression? I had added the target by means of a join, that can't work?

I did check and yes the target exists in both training and validation sets
![image](https://user-images.githubusercontent.com/91378218/184432917-a98ab8b4-b58a-4d9b-ac1e-cf5c2d33e01e.png)

**Comment by JovanVeljanoski** [comment]
You use the _variable_  target in 

```python
gen_train = df_train.ml.tensorflow.to_keras_generator(features=cols_use, target=target, batch_size=512)
```

while you should use the column or expression name:

```python
gen_train = df_train.ml.tensorflow.to_keras_generator(features=cols_use, target='target' batch_size=512)
```

if the name of that target column is "target".

Maybe if would help you to go through the tutorial to learn how vaex actually works.

**Comment by JuliaJ99** [comment]
I feel so dumb🤦‍♀️, should have named the data frame  differently from the vaex column. 
Thank you so much.

**Comment by JovanVeljanoski** [comment]
Sure, glad to help!
