### ISSUE TITLE
UI invalid expression for field weight

### ISSUE THREAD

**Issue by mfouesneau** [vaexio/vaex#218]
I just updated Vaex and now I cannot use the UI which throws an error 
```
Invalid expression for field weight: ValueError("expected an expression got a <class list>,)
```

**Comment by maartenbreddels** [comment]
Hi Morgan,

is this for master or the last release?

cheers,

Maarten

**Comment by maartenbreddels** [comment]
focussing on jupyter more, labeling as wontfix

**Comment by mfouesneau** [comment]
Sad, because I think such an interface is not available anywhere else to explore big data. Or do you have something in Jupyter, like bokeh or plotly for interactive explorations? (the lasso selections etc are so useful)

**Comment by JovanVeljanoski** [comment]
Hi @mfouesneau 

Can you please provide some info on your environment? Like OS, python version, and how you installed vaex. On my side (installation from source, macOS, py37), the UI works quite well.

**Comment by mfouesneau** [comment]
macOs py36 pip
linux     py37 pip
google collab   py37 pip  (not using UI there of course)
