### ISSUE TITLE
[BUG-REPORT] nunique Aggregation differs in result with the datatype of the column.

### ISSUE THREAD

**Issue by vignesh-bungee** [vaexio/vaex#2197]
Hi Vaex Team,
I have a column as source_sku_upc, (dtype : string) and another column source_sku_upc_id (dtype : int64).
source_sku_upc_id  is nothing but an id column  of the source_sku_upc. Doing nunique on the source_sku_upc returns correct result, but doing unique on source_sku_upc_id  columns returns a number which is always correct result +1 for each group. On Inspecting it seems that 0 is also included from somewhere. It seems to be a bug, can you please confirm ?

**Software information**
 - Vaex version 4.9.0
 - Vaex was installed via: pip 
 - OS: Linux

**Additional information**
Jupyter notebook and sample data attached
![image](https://user-images.githubusercontent.com/99238709/187906274-449b832b-dff0-4eca-a260-e2e1d5d11449.png)

**Comment by vignesh-bungee** [comment]
[ErrorSampleData.csv](https://github.com/vaexio/vaex/files/9469488/ErrorSampleData.csv)

**Comment by JovanVeljanoski** [comment]
Hi! 

Thanks for reporting this. It looks like a bug to me. Let me see if I can create an elegant test for this and so we can fix it quickly hopefully. 

Cheers, 
J.
