### ISSUE TITLE
Feature request: support for periodic boundaries

### ISSUE THREAD

**Issue by rieder** [vaexio/vaex#22]
Low priority, but it would be nice for visualising cosmological simulations.

**Comment by maartenbreddels** [comment]
Excellent idea for the gui, also for spherical coordinates this can be useful. A workaround now is, to shift the 'center' is to use for instance:
`(l + 180) % 360 - 180`
To go from a range `[0, 360)` to `[-180, 180)`

**Comment by rieder** [comment]
Thanks, that certainly works for now!

**Comment by rieder** [comment]
Is there also a way to add a "ghost" region - e.g. a periodic box ranging from [-0.5, 1.5) where the box' "real" values run from [0,1)? 
Application would be for vectors that cross the boundary and are now missed.

**Comment by maartenbreddels** [comment]
The only dirty way would be, say from the notebook, to copy the data multiple times with this offset, and add them together using ds.concat. If you then want to use it from the gui, you'd have to export it.. using ds.export_hdf5... as I said, quite dirty :)

**Comment by rieder** [comment]
ugh...

**Comment by maartenbreddels** [comment]
A more clean solution is explained in #76
