### ISSUE TITLE
[FEATURE-REQUEST] Support Google Colab installation without runtime restart

### ISSUE THREAD

**Issue by franz101** [vaexio/vaex#2211]
**Description**
When running `pip install vaex`, the runtime of the colab is needed to restarted (see attachments)

**Is your feature request related to a problem? Please describe.**
The problem is some dependencies update matplotlib to larger then 3.22 (which runs on Google Colab)
**Additional context**
[Here is a Google Colab that shows the problem and a workaround](https://colab.research.google.com/drive/19O8H2n947R4g5PEMKrOHvIb7pvec3VPg?usp=sharing)

Example of runtime restart needed:
<img width="1197" alt="Screenshot 2022-09-20 at 15 27 03" src="https://user-images.githubusercontent.com/18228395/191348197-88ec9c97-d03f-4eb5-b612-2aa3522aa1c7.png">

Example of installing the packages in a way matplotlib is not updated:
<img width="1547" alt="Screenshot 2022-09-20 at 15 27 56" src="https://user-images.githubusercontent.com/18228395/191348378-4da6ee8a-1eb5-4b33-b920-6df407a55052.png">

**Comment by franz101** [comment]
@maartenbreddels

**Comment by JovanVeljanoski** [comment]
I don't think we can do anything about that. It is their environment. 

If somebody has an idea on how to fix this - please get in touch.

**Comment by maartenbreddels** [comment]
Strange issue, thanks for letting us know.

Maybe by using the solution here https://github.com/geoalchemy/geoalchemy2/pull/392 in vaex (instead of the slow pkg_resources) we can make this faster and also working on colab without requiring a restart.

I think this could be a good first issue for someone.

**Comment by franz101** [comment]
Hey @maartenbreddels ,

thanks for the input. I have forked vaex and am experimenting with the different version implementation:
https://github.com/franz101/vaex-colab/blob/f70f4a4e2ef6c4d2902239e183f5d7abd4bcc4d3/packages/vaex-core/vaex/version.py

But running the installation it fails during the vaex-meta setup:
https://colab.research.google.com/drive/1WC-ROEunPKaxHD50b_vqxHS_3FT9METM#scrollTo=apSprOWRQ2qy

is this related to python 3.7 and not a venv?

**Comment by franz101** [comment]
Running setup.py develop for vaex-meta
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/content/vaex-colab/setup.py'"'"'; __file__='"'"'/content/vaex-colab/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by maartenbreddels** [comment]
Yeah, we could improve there by giving a hint if the git submodules are empty.
