### ISSUE TITLE
Deletion of a (virtual) column shows up in autocomplete (jupyter, ipython)

### ISSUE THREAD

**Issue by JovanVeljanoski** [vaexio/vaex#222]
I am not 100% sure if this is the correct way we want to "delete" in-memory columns, in this example:
```
import vaex
ds = vaex.example()
del ds['x']
```
in Jupyter and IPython one still gets `ds.x` to show up via the auto-complete, while of course, the "x" column is no longer accessible.

(Note to anyone reading this: `del ds['x']` does not modify the original hdf5/arrow/csv file on disk. Well not unless one exports the `ds` and overwrites the original file. )

**Comment by maartenbreddels** [comment]
I wouldn't say in memory, any column. I'll see if I can fix it.
