### ISSUE TITLE
[BUG-REPORT] materialize do not support column name length greater than 1

### ISSUE THREAD

**Issue by cgjosephlee** [vaexio/vaex#2247]
**Description**
Good
```
x = np.arange(1,4)
y = np.arange(2,5)
df = vx.from_arrays(x=x, y=y)
df['r'] = (df.x**2 + df.y**2)**0.5 # 'r' is a virtual column (computed on the fly)
df = df.materialize('r')  # now 'r' is a 'real' column (i.e. a numpy array)
```
Fail
```
x = np.arange(1,4)
y = np.arange(2,5)
df = vx.from_arrays(x=x, y=y)
df['pqr'] = (df.x**2 + df.y**2)**0.5 # 'r' is a virtual column (computed on the fly)
df = df.materialize('pqr')  # now 'r' is a 'real' column (i.e. a numpy array)

# NameError: p is not a column or virtual column
```

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: 4.14.0
 - Vaex was installed via: pip
 - OS: Debian 10

**Additional information**
Please state any supplementary information or provide additional context for the problem (e.g. screenshots, data, etc..).

**Comment by JovanVeljanoski** [comment]
Thanks for the report. I thought we improved this but maybe I misremember. Anyway I just open a PR with the fix.
As a workaround, just pass a list of columns/expressions in `materialize`. So your example will be:
`df = df.materialize(['pqr'])` and this should work just fine.

**Comment by cgjosephlee** [comment]
Thanks. Put into a list do solve the problem for now.
