### ISSUE TITLE
[BUG-REPORT] unexpected behavior of `agg={"count": vaex.agg.count()}`

### ISSUE THREAD

**Issue by cgjosephlee** [vaexio/vaex#2248]
**Description**
`count` seems to cause some kind of conflict, not sure if this is a bug.
![截圖 2022-10-26 上午11 58 03](https://user-images.githubusercontent.com/12654602/197931421-5d4a26b3-ea32-4e2b-a6a0-74aaccec9887.png)

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: 4.14.0
 - Vaex was installed via: pip 
 - OS: Debian 10

**Additional information**
Please state any supplementary information or provide additional context for the problem (e.g. screenshots, data, etc..).

**Comment by JovanVeljanoski** [comment]
It's not a bug. I think you are confusing the method `count` and the column name `"count"`. If you use the dot notation, `df.count` will refer to the method by default.

**Comment by cgjosephlee** [comment]
Indeed, thanks for clarifying.
