### ISSUE TITLE
Pandas vs. Vaex quartile differences

### ISSUE THREAD

**Issue by DougRzz** [vaexio/vaex#227]
Hi,

I have noticed some significant differences between the quantile/percentile results between Vaex and Pandas.  Is the Pandas and Vaex commands below comparable? 

```python
import numpy as np
import pandas as pd
import vaex as vx

binbyChannelx = 'x'
yChannel = 'y'
samplePoints = 50
start = 0
end = samplePoints
selectionName = None

# Create sample data in Pandas
x = np.repeat(np.arange(samplePoints), 5)+.5
y = np.random.rand(samplePoints*5)
pandas_df = pd.DataFrame()
pandas_df[binbyChannelx] = x
pandas_df[yChannel] = y

grpby = pandas_df.groupby(binbyChannelx)
output_df = grpby[yChannel].quantile([0.25, 0.75]).unstack()

vaex_df = vx.from_pandas(pandas_df)
output_df['vaex_percentile25']  = vaex_df.percentile_approx(yChannel, percentage=25.0 , binby=binbyChannelx, selection = selectionName, shape=(samplePoints,), limits=[start,end])
output_df['vaex_percentile75'] = vaex_df.percentile_approx(yChannel, percentage=75.0 , binby=binbyChannelx, selection = selectionName, shape=(samplePoints,), limits=[start,end])
```

**Comment by maartenbreddels** [comment]
Hi Doug,

thanks for letting us know. As mentioned in #208 this part needs a refactor, I'll take this into account as well. After #197 is merged it will be easier to add new aggregation algorithms as we.

cheers,

Maarten

**Comment by DougRzz** [comment]
@maartenbreddels   Sorry.  I should have spotted that other issue.  I'll close this issue and I'll post an updated example on the other issue just in case you need a few test cases.
