### ISSUE TITLE
[BUG-REPORT] Failed to build vaex-core (pybind11 issue?)

### ISSUE THREAD

**Issue by mfouesneau** [vaexio/vaex#2366]
**Description**
`pip install vaex`
```
... 
      19 warnings and 4 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
```
possible error linked to pybind11
```
vendor/pybind11/include/pybind11/cast.h:445:26: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
                  frame = frame->f_back;
```
Currently pip cannot install vaex because of this issue.

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:  `pip install vaex`
 - Vaex was installed via: pip
 - OS: Mac OS 10.15.7
 - Python 3.11

**Comment by ddelange** [comment]
python 3.11 support in https://github.com/vaexio/vaex/pull/2331
