### ISSUE TITLE
Peek into Expressions like Dataframes

### ISSUE THREAD

**Issue by xdssio** [vaexio/vaex#241]
Examples:
```
data.Age[0]
data.Age[:10]
data.Age.head(3)
data.Age.tail(3)
```

This is working:
```
data[['Age']][0:]
data[['Age']][:10]
data[['Age']].head()
data[['Age']].tail()
```
So only need to wrap it when the Expression is called

**Comment by JovanVeljanoski** [comment]
This is a duplication of #238 so I will close it. Any further discussion should be before to that thread.
