### ISSUE TITLE
Memory-mapped writes/appends/saves?

### ISSUE THREAD

**Issue by claforte** [vaexio/vaex#246]
Hi, thanks for creating Vaex, it's impressive. I'm trying to integrate it in my project. I especially like the expression system that should save me lots of memory and time!

I was able to open/export arrow and HDF5 files and now I'm trying to understand if the following is supported. I hope this isn't a newbie mistake although I read almost the entire tutorials and API documentation, and skimmed the Github issues, the unit tests and source code.

**Does Vaex support saving a large file (e.g. 100GB) progressively? e.g. concatenating lots of rows, adding new columns based on evaluating expressions?** Otherwise said, is is possible to open a memory-mapped file in read/write/append mode? If so, can you give a quick example?

... or is the recommended workflow to only write or read for any given file? e.g.
1. Export lots of smaller Arrow files during data collection, then
2. Use vaex.open_many() to load the results of step 1, and export in separate file(s) the evaluated expressions, new rows, etc?

Thank you very much!

**Comment by JovanVeljanoski** [comment]
Hi Christian, 

Thank you for your kind words. 

Actually, if you have many smaller hdf5 or arrow files, as you correctly pointed out, you have use `vaex.open_many()`. The resulting DataFrame from the user side will be the same as if you opened a single massive file. If you prefer to work with a single massive file (i do..) then you can just export that DataFrame. 

Adding columns is easy. You can use `df.materialize()` to convert from a virtual expression to an in-memory column. In fact, you don't even need to do that, if you want to export to disk some virtual columns you have added, just specify `virtual=True` or specify a list of columns to be exported (virtual or in-memory). 

The same works for concatenated DataFrames I believe. 

I hope this helps.

**Comment by claforte** [comment]
Great, thanks Jovan! I'll try that out!

**Comment by maartenbreddels** [comment]
Hi Christian,

indeed, thanks for you kind words!

> Does Vaex support saving a large file (e.g. 100GB) progressively?

Exporting hdf5 is the most efficient, it creates 1 huge file, mmaps it and fills in the chunks. So using hdf5, the chunks in memory have nothing to do with the chunks on disk (which is a good idea). For arrow, I am not sure how to export large datasets without having it all in memory, of write it out in multiple chunks. However, chunks for arrow are not supported yet.

**Comment by claforte** [comment]
> Exporting hdf5 is the most efficient, it creates 1 huge file...

Very good to know. I think it would be helpful for such information to be in the docs. I think I can spare some time improving the docs (fixing typos, adding a few paragraphs here and there, etc) if you'd like. Do you have a preference on how to proceed? Should I just fork and PR?

**Comment by maartenbreddels** [comment]
That would be great. To give you some info for our planning. We plan to have a few more things on the short term (I think a faster and possible lazy join, and get vaex-ml in this repo) before the next big release. After that we plan to focus more on polishing, docs, docstrings, and some medium articles. 
PR's are welcome, also suggestions or contributed medium articles!
