### ISSUE TITLE
Error when exporting object type column to hdf5

### ISSUE THREAD

**Issue by JovanVeljanoski** [vaexio/vaex#257]
There is an issue appearing, probably some edge case, when exporting a particular column of an object type that also contains `nans`. I was unable to create a specific unit test with synthetic data, but I attach a small file (5 rows) from the original dataset that produces the issue.

```
import vaex
df = vaex.read_csv('./test_file.csv', copy_index=False)
cols = ['CancellationCode']
df = vaex.read_csv('./test_file.csv.zip', copy_index=False, compression='zip')
```

[test_file.csv.zip](https://github.com/vaexio/vaex/files/3182848/test_file.csv.zip)

**Comment by maartenbreddels** [comment]
This one is tricky... if a column of dtype=object is being passed, you never know what the user wants right? Should it be seen as string or not?
Maybe we can define a rule for this, if the types are string type, None type and NaN's, we consider it strings?
