### ISSUE TITLE
reading s3 file from sagemaker jupyter notebook

### ISSUE THREAD

**Issue by slashtea** [vaexio/vaex#258]
I have a use case where I need to read from a dataset from an s3 bucket with vaex, now using **vaex.open()** seems to search for the file within the instance. It work with **read_csv()**.

I'm not sure if anyone experienced this before.

Error message:
OSError: Could not open file: s3://vaex.datasets/sudeste.csv.hdf5, it does not exist

**Comment by maartenbreddels** [comment]
It seems there is [hdf5 s3 support](https://github.com/h5s3/h5s3), I may actually need that tomorrow and will take a quick look.

**Comment by maartenbreddels** [comment]
#267 implements this, at least for reading, if you want to try it out.

**Comment by slashtea** [comment]
Yes sure, I'll give it a try !
Reading is enough for me right now, thanks Maarten.
