### ISSUE TITLE
Custom functions

### ISSUE THREAD

**Issue by melovv** [vaexio/vaex#265]
Hello!

I'm trying to develop a very simple function but it is not working properly.
The idea is to check a value before applying a function. For instance,
suppose the following safe_log function:

```
def safe_log(x):

    if x > 1. :

         return np.log(x)

    else:

         return 0.
```

First thing is that x is supposed to be a column, not a scalar. Therefore, the function
above won't work properly.

I intend to use this function inside an expression such as x**2 + safe_log(x). 
An option is running x**2 + log(x) and then using fillna to replace the values after all calculation is done. However, the calculation will fail the log returns nan. I don't want
it to fail.

I managed to make it work with the following code:

```
def safe_log(x):

    data = np.log(x)

    data = data.fillna(0.)

    return data    
```

But jit_numba does not compile:

```
anaconda3/envs/py36/lib/python3.6/site-packages/vaex/functions.py:112: RuntimeWarning: invalid value encountered in log
  return function(*args, **kwargs)
ERROR:MainThread:vaex:error evaluating: slog_jit at rows 0-10
Traceback (most recent call last):
  File "/home/vvmelo/anaconda3/envs/py36/lib/python3.6/site-packages/vaex/scopes.py", line 86, in evaluate
    result = self[expression]
  File "/home/vvmelo/anaconda3/envs/py36/lib/python3.6/site-packages/vaex/scopes.py", line 133, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: '_jit(x)'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vvmelo/anaconda3/envs/py36/lib/python3.6/site-packages/vaex/dataframe.py", line 3376, in table_part
    values[name] = self.evaluate(name, i1=k1, i2=k2)
  File "/home/vvmelo/anaconda3/envs/py36/lib/python3.6/site-packages/vaex/dataframe.py", line 4713, in evaluate
    value = scope.evaluate(expression)
  File "/home/vvmelo/anaconda3/envs/py36/lib/python3.6/site-packages/vaex/scopes.py", line 86, in evaluate
    result = self[expression]
  File "/home/vvmelo/anaconda3/envs/py36/lib/python3.6/site-packages/vaex/scopes.py", line 128, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/home/vvmelo/anaconda3/envs/py36/lib/python3.6/site-packages/vaex/scopes.py", line 92, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/home/vvmelo/anaconda3/envs/py36/lib/python3.6/site-packages/vaex/expression.py", line 562, in __call__
    return self.f(*args, **kwargs)
NameError: global name 'fillna' is not defined
ERROR:MainThread:vaex:error evaluating: slog_jit at rows 0-10
Traceback (most recent call last):
  File "/home/vvmelo/anaconda3/envs/py36/lib/python3.6/site-packages/vaex/scopes.py", line 86, in evaluate
    result = self[expression]
  File "/home/vvmelo/anaconda3/envs/py36/lib/python3.6/site-packages/vaex/scopes.py", line 133, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: '_jit(x)'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vvmelo/anaconda3/envs/py36/lib/python3.6/site-packages/vaex/dataframe.py", line 3376, in table_part
    values[name] = self.evaluate(name, i1=k1, i2=k2)
  File "/home/vvmelo/anaconda3/envs/py36/lib/python3.6/site-packages/vaex/dataframe.py", line 4713, in evaluate
    value = scope.evaluate(expression)
  File "/home/vvmelo/anaconda3/envs/py36/lib/python3.6/site-packages/vaex/scopes.py", line 86, in evaluate
    result = self[expression]
  File "/home/vvmelo/anaconda3/envs/py36/lib/python3.6/site-packages/vaex/scopes.py", line 128, in __getitem__
    self.values[variable] = self.evaluate(expression)  # , out=self.buffers[variable])
  File "/home/vvmelo/anaconda3/envs/py36/lib/python3.6/site-packages/vaex/scopes.py", line 92, in evaluate
    result = eval(expression, expression_namespace, self)
  File "<string>", line 1, in <module>
  File "/home/vvmelo/anaconda3/envs/py36/lib/python3.6/site-packages/vaex/expression.py", line 562, in __call__
    return self.f(*args, **kwargs)
NameError: global name 'fillna' is not defined
```

Any help here?

Cheers,

Vinícius.

**Comment by DougRzz** [comment]
Does it have to be in a function? Could you do this expression instead? ```where(x > 1, log(x), 0)```

**Comment by melovv** [comment]
Hi, DougRzz.

It has to be a function because I want to apply a function over it, for instance: abs(max(log(x))-2.5).

**Comment by JovanVeljanoski** [comment]
Hey @melovv 

Depending on the size of your dataset, you may consider using `apply`. If your dataset is reasonably small (<1M samples) and the function is not computationally expensive, it maybe be a solution. 

Something like this

```
import vaex

def save_log(x):
    if x>1.:
        return np.log(x)
    else:
        return 0.

df = vaex.example()
df['log_x'] = df.x.apply(save_log)

df.describe()
```

If your dataset is larger, we are working on a solution that will hopefully be out soon.

**Comment by melovv** [comment]
Hey @JovanVeljanoski ,

thanks for the reply.

Unfortunately, your suggestion is not what I need.
It has to be a function because I want to apply a function over it, 
for instance: abs(max(log(x))-2.5).

I'll wait for another solution because I need something faster than pandas.
Otherwise, I'll have to implement my code in Cython.

Cheers,

Vinícius.

**Comment by maartenbreddels** [comment]
Hi Vinicius,

great question. The way vaex works together with numpy is based on an old method, that does not catch all ufuncs, and therefore it does not like `np.where(<vaex expression>)`, we're already talking about improving that, because as you see, it can lead to issues.
An escape hatch is to use `mat.func.where(mat.x > 0, np.log10(mat.x), 0)`. where mat.func is a convenience object that gives tab completion on all known functions. This bypasses numpy, and directly constructs a vaex expression. I did notice it does not jit compile using numba for me, and my Pythran seems broken. I doubt the jitting will improve performance a lot though.
Does this help you?
Vaex is using c++ using pybind11 to add functions written in c++ btw, I thought of creating an example project/cookiecutter on how that would work, would you be interested in that, or would you like to help set that up?

cheers,

Maarten

I'll keep this issue open to track the following:
NOTES/TODO:
 - [ ] test/improve vaex-numpy support, make abs/where work
 - [ ] document the usage of custom functions, and df.func maybe?
 - [ ] Investigate why jitting the above does not work with numba.

**Comment by maartenbreddels** [comment]
Btw, the proper way to do this is:
`(mat.x<0).where(0, np.log(mat.x))` or `mat.func.where(mat.x < 0, 0, np.log(mat.x))`

The problem here is that `np.where(df.x)` does not call vaex', so that I can turn it into an expression. The workaround is to call `df.func.where` or `expression.where`, see https://docs.vaex.io/en/latest/tutorial.html#Extending-vaex for some background.

**Comment by CWen001** [comment]
Sorry to have a question about custom function here, as `apply` method is not documented. In addition to `df.x.apply(custom_func)` above, is it possible to use apply on a data frame? Like `df.apply(custom_func, axis=1)` in Pandas or in Dask.

```python
import vaex
df = vaex.example()
df.apply??

### Is it possible:
df.apply(lambda df: cumstom_func(df.x, df.y), axis=1)
```

My real use case is to call `networkx.shortest_path_length` function, and each source-target node pair is stored in one row of a dataframe. There are millions of rows as paths.

**Comment by maartenbreddels** [comment]
Hi, would you mind opening a new issue for this, that makes it easier for people to find answers. thanks!
