### ISSUE TITLE
Can't install package from source

### ISSUE THREAD

**Issue by slashtea** [vaexio/vaex#271]
I'm trying to install package from source, I get a bunch of errors. When import vaex, I get the following error " ImportError: cannot import name 's3' ". Checking I see that there is no s3.py in file directory. 

 I don't know what am I doing wrong here ?

**Comment by maartenbreddels** [comment]
Did you pull this repo? And which python version?

**Comment by slashtea** [comment]
Yes I pulled this repo (pip install git+https://github.com/vaexio/vaex.git) , python 3.6.

**Comment by maartenbreddels** [comment]
Strange, it is in master: https://github.com/vaexio/vaex/blob/master/packages/vaex-core/vaex/file/s3.py

Can you give me the full stack trace?

**Comment by slashtea** [comment]
I got this tracebac when installing, probably the root cause of what's happening.

 Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-l4gdt8dc/setup.py", line 74, in <module>
      'develop': DevelopCmd,
    File "/home/shannon/Python_projects/Envs/myvenv/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/shannon/Python_projects/Envs/myvenv/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 244, in run
      self.egg2dist(self.egginfo_dir, distinfo_dir)
    File "/home/shannon/Python_projects/Envs/myvenv/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 341, in egg2dist
      raise ValueError(err)
  ValueError: Egg metadata expected at build/bdist.linux-x86_64/wheel/vaex_meta-0.1.0-py3.6.egg-info but not found
  ----------------------------------------
  ERROR: Failed building wheel for vaex-meta

**Comment by maartenbreddels** [comment]
My guess is you did a `pip install .` from the root. Vaex has 'fake' setup.py in its root, that actually installs all of the subpackages in the packages directory.
I've seen this happening with `pip install .` before, and don't know the solution yet, however, `pip install -e .` (dev code) always seems to work, could you try that.

**Comment by slashtea** [comment]
I'm late to respond, sorry !

Well I tried **pip install -e .** in root directory and got an error
 
`symlinking /home/shannon/Python_projects/vaex_poc/vaex/packages/vaex-viz/vaex/viz viz ../../vaex-viz/vaex/viz
    error: [Errno 2] No such file or directory: 'viz`

reading setup.py I see a comment about adding a symlink to make dev install work, do I have to add something ?

**Comment by maartenbreddels** [comment]
No problem. Did you pull again? I think I just fixed that!

**Comment by slashtea** [comment]
It works, but it installs only vaex-meta.

**Comment by maartenbreddels** [comment]
I'm not sure what you mean, could you try the following:
 * update pip/setuptools: `pip install --upgrade pip setuptools`
 * `pip list | grep vaex | awk '{ print $1 }' | xargs pip uninstall` # uninstalls all vaex packages
 * run from repo root: `pip install -v -e .`
 * If you get error, could you paste the logs here?

**Comment by slashtea** [comment]
`x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/shannon/Python_projects/Envs/vaex_venv/lib/python3.6/site-packages/numpy/core/include -Ivendor/pybind11/include -Ivendor/pybind11/include -Ivendor/string-view-lite/include -Ivendor/boost -I/home/shannon/Python_projects/Envs/vaex_venv/include -I/home/shannon/Python_projects/Envs/vaex_venv/Library/include -I/usr/include/python3.6m -I/home/shannon/Python_projects/Envs/vaex_venv/include/python3.6m -c src/strings.cpp -o build/temp.linux-x86_64-3.6/src/strings.o -std=c++11 -mfpmath=sse -O3 -funroll-loops -g
        src/strings.cpp:7:10: fatal error: pybind11/pybind11.h: No such file or directory
         #include <pybind11/pybind11.h>
                  ^~~~~~~~~~~~~~~~~~~~~
        compilation terminated.
        error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
        ----------------------------------------
      ERROR: Can't roll back vaex-core; was not uninstalled
    ERROR: Command "/home/shannon/Python_projects/Envs/vaex_venv/bin/python -c 'import setuptools, tokenize;__file__='"'"'/home/shannon/Python_projects/vaex_poc/vaex/packages/vaex-core/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps" failed with error code 1 in /home/shannon/Python_projects/vaex_poc/vaex/packages/vaex-core/
Successfully installed vaex-meta
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-8eaxs132'`

**Comment by maartenbreddels** [comment]
Aaaah, I should have a warning for that! `$ git submodule update --init --recursive` then try again :)

**Comment by slashtea** [comment]
It works !!

Thanks Maarten for your help.

**Comment by maartenbreddels** [comment]
Great, glad I could help!

**Comment by astrofrog** [comment]
Ran into this too and checking out submodules manually works :)

**Comment by slashtea** [comment]
Glad I posted that !
