### ISSUE TITLE
Fresh install on Colab raises issues with vaex-viz

### ISSUE THREAD

**Issue by mfouesneau** [vaexio/vaex#283]
https://github.com/vaexio/vaex/blob/7043df824cd8915b2cca773854023bb10b5ef538/packages/vaex-core/vaex/dataframe.py#L62

I do not know where the issue comes from, but I do `pip install vaex` or `pip install vaex --pre`
And I get issues with compatible packages.

Installing individual packages also does not work. I don't see an obvious error message.

**Comment by JovanVeljanoski** [comment]
Hey!

I just tried installing vaex google Colab (I've never tried installing vaex there before), and it worked out of the box.

Just did `pip install vaex` in an empty cell. 

![image](https://user-images.githubusercontent.com/18574951/60264656-07a91e00-98e4-11e9-84e7-4a602fd72ea8.png)

I think there was at least one new release since this issue was open, so please try again and report back? 

Cheers!

**Comment by JovanVeljanoski** [comment]
Things work as usual after the install 

![image](https://user-images.githubusercontent.com/18574951/60264758-4b038c80-98e4-11e9-90b0-62d9983c697a.png)

**Comment by mfouesneau** [comment]
Try to plot something, please. This is where the vaex-viz link does not always work.

**Comment by JovanVeljanoski** [comment]
Sure here are some examples using the `vaex.example()` dataset

![image](https://user-images.githubusercontent.com/18574951/60265646-869f5600-98e6-11e9-955b-db4b4193bc3a.png)

**Comment by JovanVeljanoski** [comment]
Also, `df.scatter()`, which is just a wrapper around `pylab.scatter` i think also work ok:

![image](https://user-images.githubusercontent.com/18574951/60268134-ffed7780-98eb-11e9-9769-c43f313c558f.png)

**Comment by maartenbreddels** [comment]
It seems that if it happens, you need to restart the runtime/kernel, not sure why.

**Comment by samuelsoc** [comment]
Hi @maartenbreddels , i did like @JovanVeljanoski  and i see this message 
![imagen](https://user-images.githubusercontent.com/5819631/105355360-cb799480-5bd0-11eb-9c48-8d5ada3f2d07.png)

Then with import vaex 
![imagen](https://user-images.githubusercontent.com/5819631/105355418-e3511880-5bd0-11eb-8249-a0bedb5b0f94.png)

**Comment by JovanVeljanoski** [comment]
You need to restart the runtime after finish the installation. I just checked, it works. 

this is my 1st cell of the test notebook for collab:
```
!pip install vaex
!pip install --upgrade ipython
```

**Comment by JovanVeljanoski** [comment]
It also works with the latest alpha version.

**Comment by samuelsoc** [comment]
thanks! its works!
