### ISSUE TITLE
new release of jupyter-sphinx

### ISSUE THREAD

**Issue by akhmerov** [vaexio/vaex#286]
This project lists `jupyter-sphinx` in its sphinx configuration or requirements file, but does not appear to use this extension directly anymore.
We have just rewritten `jupyter-sphinx` from scratch, and fully changed the interface.
Therefore we would like to give you a heads up, in case you find the new version useful.

Now all code execution is done via a single `jupyter-execute` sphinx directive, instead of the previous `ipywidgets-setup`/`ipywidgets-embed`.
The new version is also much more flexible: it allows to embed any output recognized by jupyter in sphinx documentation. See the [project documentation](https://jupyter-sphinx.readthedocs.io) for details.

We have released 0.2.0rc1 on pip, please give it a shot using `pip install 0.2.0rc1 --pre` — we would love to hear your feedback.
Please also let us know by responding here or in https://github.com/jupyter-widgets/jupyter-sphinx/issues/33 if the new release disrupts your workflow.

**Comment by maartenbreddels** [comment]
Thanks for the report!
I'm not using it directly, but it makes widgets render in notebooks since the extension injects the proper JS on the pages.
