### ISSUE TITLE
vaex-ml techniques

### ISSUE THREAD

**Issue by melovv** [vaexio/vaex#301]
Hello, guys!

Any plans in the roadmap to add more techniques to vaex-ml?
I was hoping to get a super-fast Multiple Linear Regression via OLS, Lasso, Ridge, etc.
Given you already have PCA, maybe these techniques could be easily added.

Thanks!

**Comment by JovanVeljanoski** [comment]
Hi, 

Yeah, we plan on adding many more things to `vaex-ml`. If you see #254 , it has support for `scikit-learn` estimators, which I think do have `Lasso` and `Ridge` implementations. 

It would help us a lot if you point us to any other particularly good implementation of the models you find useful, and of course you are welcome to submit PRs :)

Cheers, 
Jovan.
