### ISSUE TITLE
When installing from source individually, sub packages clobber the install of the parent package and each other

### ISSUE THREAD

**Issue by timkpaine** [vaexio/vaex#322]
Discussed a while back on gitter, will do a PR by this can be fixed following this: https://stackoverflow.com/questions/26528178/right-way-to-set-python-package-with-sub-packages

**Comment by timkpaine** [comment]
closing as this might be a py2.7 or a pip issue, I can't repro on py3.7 with pip 19.0.3

**Comment by maartenbreddels** [comment]
What I've also noticed is that using
```
pip install --target <path> vaex-core vaex-hdf5
```
works, while two successive commands:
```
pip install --target <path> vaex-core
pip install --target <path> vaex-hdf5
```
Might not.

**Comment by timkpaine** [comment]
Ah this is almost definitely what i was seeing
