### ISSUE TITLE
Feature Request: support for datetime data

### ISSUE THREAD

**Issue by jjisnow** [vaexio/vaex#33]
It would be great if there could be support for numpy.datetime64 objects in a data series and axis scale as I regularly get time data quoted in this format and charted using matplotlib. The data is getting large, so I would ideally like to be able to scatter plot this using vaex.

**Comment by maartenbreddels** [comment]
Hi, there is some support for it in storing and reading the data, but not yet in the plotting part. Could you point me to some good documentation/tutorials on this, or give some pointers/ideas on how this should work, that would be great!

**Comment by jjisnow** [comment]
Good question! I am thinking of the way matplotlib handles datetime fields. Not exactly sure how it resolves the date fields to an axis, but it seems standard for financial charting of  data

**Comment by maartenbreddels** [comment]
Because if you pass mpl datatime64 data, maybe it will automatically detect it, but I will basically draw an image and need to configure the axis to show datetimes.

**Comment by RAJAT8878** [comment]
Is there any support in vaex for datetime columns so that we can set the datetime columns to the particular format. for e.g. '%Y-%m-%d %H:%M:%S'

**Comment by maartenbreddels** [comment]
Would you mind opening your own issue, that makes tracking easier :) Thanks!

**Comment by JovanVeljanoski** [comment]
Closed as stale. The main purpose of the issue was resolved. Vaex supports numpy.datetime64 elements.
