### ISSUE TITLE
creating larger than memory file from csvs

### ISSUE THREAD

**Issue by quazzuk** [vaexio/vaex#355]
Hi

After seeing your impressive presentation at PyData London I was keen to try! Unfortunately, I seem to be falling at first hurdle...

I have a set of *csv.gz organised by date I would like to build a single file (either hdf5 or arrow) and use vaex for analysis. The csvs contain a mixture of ints, floats and variable length strings. 

So far I tried the following:

1. Python example [here](https://vaex.readthedocs.io/en/latest/getting_data_in_vaex.html?highlight=hdf5) - doesn't support strings and needs extending to multiple files
2. Reverse engineering vaex-hdf5 export - appears to write a compatible file but fails with 

```
--> 254         self.nbytes = self.bytes.nbytes + self.indices.nbytes
    255         self.null_bitmap = null_bitmap
    256         if string_sequence is None:

AttributeError: 'ColumnNumpyLike' object has no attribute 'nbytes'
```
3. ```vaex.open('*.csv', 'mybigfile.hdf5')``` fails with either ```RuntimeError: byte buffer too small``` or ```too many files open```
4. building a parquet file as per https://stackoverflow.com/questions/47113813/using-pyarrow-how-do-you-append-to-parquet-file with the aim to load and export as arrow. Fails with error  ```array is of length %s, while the length of the DataFrame is %s```

At this point I've run out of ideas . Any suggestions?

Thanks
AJ

**Comment by JovanVeljanoski** [comment]
Hi AJ, 

Thanks for trying out vaex. I think point number 3. gives me the most hints. I have gotten that `too many files open` error a bunch of times, and I believe is a simply limitation of OS (assuming you are using a Mac). One way of getting around this potentially is to run `$ ulimit -n 2048` at a terminal and try again (also restart any Jupyter sessions beforehand if you are using that). 

An alternative method would be to make a loop opening one csv file at a time and converting it to arrow or hdf5. You can use the `vaex.read_csv` or `veax.from_csv` which uses the `pandas` method of reading csv files. Then, you can use `vaex.open_many(*.arrow)` and the result will be a single DataFrame object. You could continue to use that, or you can make another export if you would prefer to have a single file on disk. 

Of course, the underlying assumption here (for the moment) is that the data type of each column does not change between the different csv files.  

We are actively working on getting the batch opening & converting of multiple csv files more robust. 

I hope this helps, 
Jovan.

**Comment by quazzuk** [comment]
Hi Jovan

Thanks for the quick response. I finally managed to get it to work by:

1.  upping the ulimit (as suggested)
2. using open/convert to convert the csvs to hdf5 (although the operation failed due to ```byte buffer too small``` it correctly wrote out the hdf5 variant of the csvs
3. ```df = vaex.open_many(glob(*.hdf5))```
4. ```df.export('all_data.hdf5')```

The final step didn't work using arrow - for the full dataset I got a memory error on a 64GB machine, for a subset I got ```array is of length %s, while the length of the DataFrame is %s``` (as above).

Anyway ```df = vaex.open('all_data.hdf5')``` appears to work now and I've tested with a handful of commands and all appears to be well.

Thanks for your help!

AJ

**Comment by JovanVeljanoski** [comment]
Hi, 

I am glad that it (eventually) worked! Yes, exporting to `arrow` unfortunately is not supported currently  for datasets that are larger than the memory of the machine used. This is a limitation of arrow I believe (for now I hope). You can still use arrow the format if you export to smaller files, and than use the `open_many` method.  Note that you can simply use `vaex.open_many("*.hdf5")` (so no need to use `glob` there).

I am curious about the `byte buffer too small` error/warning you are getting.. I have not encountered it before. I would be very grateful if you could check which kind of column type causes this, so we can make the method more robust. We test for the export of all standard types I believe on Linux and OSX.

Thank you!
Jovan.

**Comment by quazzuk** [comment]
I'll reproduce the byte buffer error and send you the details. 

Thanks for the ```open_many``` tip! I left out that I call ```sorted``` on the list returned by glob. Is any ordering applied to ```open_many``` patterns?

**Comment by JovanVeljanoski** [comment]
Ups, I have given you wrong info.. sorry about that..  for `open_many` you do need to use `glob` for instance as it expects a list of files. I got confused with `read_csv_and_convert` in which you can pass something like `*csv` without specifying a list yourself (and there no sorting of the files is applied).

Perhaps we should also support the same in `open_many` and apply alphabetical sorting.. 
@maartenbreddels ?

**Comment by maartenbreddels** [comment]
@quazzuk :
> I'll reproduce the byte buffer error and send you the details.

Would really love to hear about that!

> open_many

No, sometimes ordering matters, so lets keep it in the order the user passed.

**Comment by JovanVeljanoski** [comment]
I will mark this as closed since it is stale.  Please re-open if needed, or open a separate issue if another cause arises. 

For reference, our current suggested method to convert large CSV files to HDF5 is outline on [our docs page](https://docs.vaex.io/en/latest/faq.html).

We are actively working to improve this process. Cheers
