### ISSUE TITLE
concatenate ascii files or data-frames?

### ISSUE THREAD

**Issue by fprada** [vaexio/vaex#372]
Hi again,

  I am reading the ascii files as you suggested, 

   df1 = vaex.read_csv('somefile1.csv', delim_whitespace=True, comment='#', header=None, names=names, copy_index=False)

  But now a have a bunch of them ... I have splitted the original huge ascii file.

  I don't think I can use open_many, isn't? Should I read each separately and then concatenate the data-frames: df1, df2 ... df8? 

 What do you recommend in this case?

Thank you!

**Comment by maartenbreddels** [comment]
https://docs.vaex.io/en/latest/api.html#vaex.dataframe.DataFrameLocal.concat

can do it, I just noticed `vaex.concat` is not in the API docs:
```
df = vaex.concat([df1, df2, df3])
```
But I recommend to write them first to hdf5, and then open it like this:
```
df = vaex.open('somefile*.hdf5')
```

`open_many` is also an option, but this should work

**Comment by maartenbreddels** [comment]
The advantage of first writing them to disk, and then opening it, is that the hdf5 can memory map the data, freeing up the memory.

**Comment by fprada** [comment]
Great, thanks Maarten! I'll follow your advise. 

Cheers.
