### ISSUE TITLE
How to do interactive 2D scatter plot zoom / point selection in Vaex?

### ISSUE THREAD

**Issue by cirosantilli** [vaexio/vaex#374]
I have asked a detailed question at: https://stackoverflow.com/questions/57323126/how-to-do-interactive-2d-scatter-plot-zoom-point-selection-in-vaex feel free to close this issue once you stumble upon it. Cheers!

**Comment by cirosantilli** [comment]
Thanks for the reply, problem solved as per answers.

**Comment by maartenbreddels** [comment]
Thank you!

(from mobile phone)
