### ISSUE TITLE
edge case for LabelEncoder

### ISSUE THREAD

**Issue by xdssio** [vaexio/vaex#380]
If you use prefix='' and run fit_transform a few times, it crashes.
I think we should we should either prevent it, or fix it, but the crash forces you to restart your python session.

```
import vaex
from vaex.ml import LabelEncoder
df = vaex.from_dict({'A':['a','b','c']})
le = LabelEncoder(features=['A'], prefix='')
df = le.fit_transform(df)
df = le.fit_transform(df)
```

**Comment by JovanVeljanoski** [comment]
This has been since fixed. Please re-open if the issue repeats.
