### ISSUE TITLE
Allow file-like input to read_text

### ISSUE THREAD

**Issue by ARF1** [vaexio/vaex#392]
It would be nice if the following was possible:
```
df = vaex.from_ascii(
    StringIO(str(result)),
    sep="|",
)
```

This is particularly useful in the case, where XML data is transformed to in-memory CSV which is then to be read into a dataframe.

The `StringIO` object currently raises an error as a path is expected. However, the "only" thing that is done with the path is that the file is opened. Thus, the effort to accept `StringIO` or othe file-like objects should me very small.

Pandas allows in all(?) cases where a path can be specified to alternatively provide a file-like object, which gives the user a tremendous amount of flexibility regarding data sources. E.g. streamed data over network sockets, etc.

**Comment by maartenbreddels** [comment]
Good point, but on the other hand, vaex' focus is on large dataframes, where ascii does not really play a role. I would say, in most cases is the source is ascii I would go for a workflow like this:
 * open file with pandas
 * convert pandas df to vaex df: `df = vaex.from_pandas(df)`
 * export to hdf5: `df.export('foo.hdf5')`
* Open it memory mapped: `df = vaex.open('foo.hdf5')

If there are many files files, you can do this many times and concatenate them using `vaex.concat`.

Does that make sense?

**Comment by ARF1** [comment]
@maartenbreddels I take your point. Many thanks.
