### ISSUE TITLE
Adding a new column from a 1D numpy array of numpy arrays

### ISSUE THREAD

**Issue by kushalkolar** [vaexio/vaex#410]
Adding a new DataFrame column from a 1D numpy array of numpy array raises exceptions.  Currently this seems to put the data into the actual dataframe but exceptions are raised from the array comparison in the DataFrame.add_column() method.

This illustrates the current behavior:
https://nbviewer.jupyter.org/github/kushalkolar/vaex/blob/numpy-fix/numpy_fix_info/current_behavior.ipynb

Naively changing the array comparison doesn't results in exceptions and the dataframe can be printed:

https://github.com/kushalkolar/vaex/commit/2afd71be1482e4963ad86c6f22f9602c76dc2230

https://nbviewer.jupyter.org/github/kushalkolar/vaex/blob/numpy-fix/numpy_fix_info/numpy-fix.ipynb

However this breaks normal functionality:
https://nbviewer.jupyter.org/github/kushalkolar/vaex/blob/numpy-fix/numpy_fix_info/breaks_stuff.ipynb

**Comment by maartenbreddels** [comment]
Hi Kushal,

thanks for opening the issue!
that line tries to find all types in a column, apart from nan (that's why the k == k) and None values/types. This is done to check if a column is actually a string type. I think that np.all(k == k) will do the trick.

You could open a PR if you'd like.

cheers,

Maarten

**Comment by JovanVeljanoski** [comment]
Hi @kushalkolar 

Thank you for the issue and the PR! 
Just a word of warning: a `vaex` column should really only be a 1d array, and not nested or nd array. There is no official support for arrays or lists being elements of a column at the moment, especially if the length of those lists is not identical for all rows (like in your example). You may run into various unpredictable issues with that usage. 

Support for this may be added down the line (@maartenbreddels might answer this better), but unlikely to come in the immediate future. 

In addition, I would avoid using columns of `dtype=`O`` whenever possible. 

Happy vaexing :)

**Comment by kushalkolar** [comment]
@JovanVeljanoski Thanks for the warning, I'll so how far I can integrate this into our stuff!

**Comment by JovanVeljanoski** [comment]
Closed via #411
