### ISSUE TITLE
Why does df.count return wrong value?

### ISSUE THREAD

**Issue by qo4on** [vaexio/vaex#419]
![image](https://user-images.githubusercontent.com/35609308/64979095-69b86480-d8d0-11e9-8288-616c8b77f59e.png)

**Comment by JovanVeljanoski** [comment]
Hi, 

By default it clips outliers during the binning process.

Try:

```sum(df.count(binby=df.x, shape=700, limits='minmax'))```

**Comment by maartenbreddels** [comment]
Hi,

Even with minmax, you will probably get `len(df)-1`, since the bins are half-open, i.e, >= min, < max. You can pass edges=True to get the counts outside the edges, but this is currently only used internally/undocumented afaik, in any case, counts[0] would be the nans, counts[1] those with < min, and counts[-1] those with >=max.

cheers,

Maarten

**Comment by qo4on** [comment]
Thank you! This means if I'd like to get real values (not estimation) for full range of data with`df.count, mean, std, median_approx, minmax...` I have to add `limits='minmax'` to all them too. Am I right?

**Comment by maartenbreddels** [comment]
You're welcome!

They are no estimations, but you did not give the limits/bounds for the bins of count, so it will be determined for you, which by defaults means a 95% percentile approximation. Within those bins, the results are exact though. Manually you can do:
```python
df.count(binby=df.x, limits=[0,10], shape=10)
df.count(binby=df.x, limits=df.x.minmax(), shape=10)
```

etc. Does that make sense?

**Comment by qo4on** [comment]
Yes, thank you very much, Maarten.

**Comment by qo4on** [comment]
I tried what you suggested and can confirm
'sum(df.count(binby=df.x, shape=700, limits='minmax'))'
returns `len(df)-1`
![image](https://user-images.githubusercontent.com/35609308/64984934-3defab80-d8dd-11e9-83af-83f61315d0c0.png)
and
`sum(df.count(binby=df.x, shape=700, limits='minmax', edges=True))`
returns with borders
![image](https://user-images.githubusercontent.com/35609308/64985583-9e331d00-d8de-11e9-8b76-67325a760258.png)

**Comment by maartenbreddels** [comment]
Thanks for confirming!
