### ISSUE TITLE
Acknowledgement 

### ISSUE THREAD

**Issue by mfouesneau** [vaexio/vaex#42]
Is there an official acknowledgement text somewhere to give credit to Vaex and your work in publications?

**Comment by maartenbreddels** [comment]
Hi Morgan,

thanks for asking this, I'm working on a paper, but until that gets our I suggest you cite:
http://adsabs.harvard.edu/abs/2017IAUS..325..299B

cheers,

Maarten

**Comment by maartenbreddels** [comment]
For the record, this is the paper that can be cited:
http://adsabs.harvard.edu/abs/2018A%26A...618A..13B
