### ISSUE TITLE
AttributeError: module 'vaex.ml.xgboost' has no attribute 'XGBModel'

### ISSUE THREAD

**Issue by edgarduartecoelho** [vaexio/vaex#436]
Hello,

While following the docs (https://docs.vaex.io/en/latest/ml.html), I've encountered the error stated in the title while trying the code in cell [7].

Responsible line:
`xgmodel = vaex.ml.xgboost.XGBModel(features=features, num_round=10, param=param)`

**Comment by JovanVeljanoski** [comment]
Hi @edgarduartecoelho 

Thanks for trying out Vaex and for pointing that out. I am afraid the docs on that part are a bit out of date. I am attaching an example screenshot of the current API. Maybe you would like to submit a PR updating this part of the docs, in the spirit of [Hacktober](https://hacktoberfest.digitalocean.com/) :)

Thanks!
 
![image](https://user-images.githubusercontent.com/18574951/66113371-ea63aa00-e5cc-11e9-9aeb-1b8f311a6f23.png)

**Comment by JovanVeljanoski** [comment]
The docs have since been updated.
