### ISSUE TITLE
How to use apply on the dataframe

### ISSUE THREAD

**Issue by CWen001** [vaexio/vaex#442]
Hello. I have a question about custom function here, as apply method is not documented.
 ```python
import vaex
df = vaex.example()
df.apply??
```
I saw the example from #265 that apply can be used on a (virtual) column.
```python
def save_log(x):
    if x>1.:
        return np.log(x)
    else:
        return 0.

df['log_x'] = df.x.apply(save_log)
```

In addition to `df.x.apply(custom_func)` above, is it possible to use apply on a data frame? Like `df.apply(custom_func, axis=1)` in Pandas or in Dask.

```python
### Is it possible:
df.apply(lambda df: cumstom_func(df.x, df.y), axis=1)
```
My real use case is to call `networkx.shortest_path_length` function, and each source-target node pair is stored in one row of a dataframe. There are millions of rows as paths.

**Comment by maartenbreddels** [comment]
Hi,

good question, and we should add a docstring there (cc @JovanVeljanoski ).
Vaex wants to know in advance what the arguments are because it will only compute what is needed. Example:
```python
df = vaex.example()['x', 'y']
def myfunc(a, b):
    return a+b
df['q'] = df.apply(myfunc, [df.x, df.y])
```
Note that apply is probably really slow, since it will not be done parallel/vectorized.
You can materialize the column, so it takes up memory, but is only computed once:
```python
dfm = df.materialize('q')
```
I hope that answers your question.

Regards,

Maarten Breddels

**Comment by CWen001** [comment]
Thanks for the instruction. I have tested `.apply` method on some of my data using several packages (pandas, dask, and vaex). Indeed, since applying a pyfunc cannot be parallel/vectorized, computing is not very fast. The three packages perform almost identically. However, on my computer vaex is the fastest for other vectorized calculations or aggregations. I really like the presentation design, and the virtual columns always make me believe the results are already there. 

Thank you very much for your work. Closing the issue as the question answered.

**Comment by maartenbreddels** [comment]
Thanks for the feedback!

@JovanVeljanoski added the docstring in #444

**Comment by CWen001** [comment]
Thank you very much for the update. I have done some very simple tests about `.apply` on different packages using Colab. I'm still curious the potential of vaex for a custom function.

```python
!export MODIN_ENGINE=ray

import vaex as vx
import modin.pandas as md
import pandas as pd
import dask.dataframe as dd
import math
from dask.distributed import Client
from multiprocessing import cpu_count

df_vx = vx.example()

df_pd = df_vx.to_pandas_df()

# cpu_count() is 2 on my Colab environment
df_dd = dd.from_pandas(df_pd, npartitions=4 * cpu_count())

df_pd.to_csv('file.csv')
df_modin = md.read_csv('file.csv')

# define a pyfunc
def custom_func(x, y):
    return math.cos(x ** 2 + y)
```
Measure the time one by one. First Pandas:
```python
%%time
res_pd = df.apply(lambda df: custom_func(df.x, df.y), axis=1)
res_pd

# CPU times: user 9.63 s, sys: 133 ms, total: 9.76 s
# Wall time: 9.87 s
```
Then vaex:
```python
%%time
res_vx = df_vx.apply(custom_func, arguments=[df_vx.x, df_vx.y] ,vectorize=False)
res_vx = res_vx.evaluate()
# For a fair comparison, transforming to an array.

# CPU times: user 940 ms, sys: 13 ms, total: 953 ms
# Wall time: 952 ms
```
Dask. A distributed scheduler is activated before. `client = Client()`
```python
%%time
res_dd = df_dd.apply(lambda df: custom_func(df.x, df.y), axis=1, meta=('float64'))
res_dd = res_dd.compute()

# CPU times: user 1.06 s, sys: 192 ms, total: 1.25 s
# Wall time: 11 s
```
Last, Modin[Ray]. But the documentation says the apply method is still under development.
```python
%%time
res_md = df_modin.apply(lambda df: custom_func(df.x, df.y), axis=1)
res_md

# UserWarning: User-defined function verification is still under development in Modin. The function # provided is not verified.
# CPU times: user 537 ms, sys: 111 ms, total: 647 ms
# Wall time: 9.26 s
```
Although my use case of `networkx.shortest_path_length` didn't show much performance difference among packages, the simple tests here are impressive. My question is, is there any internal optimization under the hood of `vaex`? It is so fast. Actually, Dask's [documentation](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.apply) on `.apply` explicitly states that it is Parallel version of pandas.DataFrame.apply. Is vaex also the case? Does vaex have some future plan on further accelerating custom functions, which is heavily used by many users?

Thank you very much for your thoughts. Hope this package can be used by more people.
Chen

**Comment by JovanVeljanoski** [comment]
Hi @CWen001, 

Thanks for trying and testing out vaex. To be honest, as far as I know, the `apply` function is meant to be used "as a last resort" in case all other options fail. It is for very custom functions. I am not aware that we are doing anything special under the hood, apart from creating a lazy function and evaluating on the "need to have" basis. 

If you can write you functions using `numpy` and add them as virtual columns, their evaluation will be super fast, parallel and out-of-core. To speed things up even further, one can use jitting, via numba (`jit_numba()`), pythran (`jit_pythran()`), and if you happen to have NVIDIA GPU you can even used that (`jit_cuda()`). This will pre-compile the expressions, and their executions will be much faster. This is our preferred method for doing computations. Of course, in some cases you have to use very custom functions is which `apply` seems to be the only choice..

For examples on how to use the jitting you can check out this notebook:
https://nbviewer.jupyter.org/github/vaexio/vaex-talks/blob/master/2019-pydata-london/PyData-London-2019-vaex-EDA-ML.ipynb

As for your question about speeding up particular computations... do you have something particular in mind?

Oh, btw, if you want to do some other benchmarks, and would like to force vaex to do the full operations, you can use the `nop()` method to do so. For you example this would be like:
```
res_vx.nop()
```

Cheers!
Jovan.

**Comment by CWen001** [comment]
Thanks for the response. Yes, users often have to use some domain-specific libraries, like `networkx`. The scalar functions of them cannot be easily accelerated or rewritten. On the user side, maybe the best we can do is to find tools to make the full use of the computer, for example, using the parallel and all cores. Anyway, the open-source world is evolving, excellent new tools will always come to stage. Cheers.
