### ISSUE TITLE
Re-enable support for half precision floats

### ISSUE THREAD

**Issue by DougRzz** [vaexio/vaex#452]
Vaex used to support half precision floats.  I'm not sure when or where Vaex stopped working with half precision.  I recently downgraded to vaex-core 0.9.2 and it was working again for a while but now that version is no longer working too. 

```python
import numpy as np
import pandas as pd
import vaex as vx

df = pd.DataFrame(data = np.ones(13), columns = ['ones']).astype(np.float16)
ds = vx.from_pandas(df)
ds.count('ones')
```

Traceback....
______________________________________________________________

error Could not find a class (AggCount_float16), seems float16 is not supported
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-26-10e4e47d934c> in <module>
      1 df = pd.DataFrame(data = np.ones(13), columns = ['ones']).astype(np.float16)
      2 ds = vx.from_pandas(df)
----> 3 ds.count('ones')

~\AppData\Local\Continuum\miniconda3_37_2\lib\site-packages\vaex\dataframe.py in count(self, expression, binby, limits, shape, selection, delay, edges, progress)
    610         :return: {return_stat_scalar}
    611         """
--> 612         return self._compute_agg('count', expression, binby, limits, shape, selection, delay, edges, progress)
    613 
    614     @delayed

~\AppData\Local\Continuum\miniconda3_37_2\lib\site-packages\vaex\dataframe.py in _compute_agg(self, name, expression, binby, limits, shape, selection, delay, edges, progress, extra_expressions)
    585         stats = [compute(expression, grid, selection=selection, edges=edges, progressbar=progressbar) for expression in expressions]
    586         var = finish(*stats)
--> 587         return self._delay(delay, var)
    588 
    589     @docsubst

~\AppData\Local\Continuum\miniconda3_37_2\lib\site-packages\vaex\dataframe.py in _delay(self, delay, task, progressbar)
   1325             return task
   1326         else:
-> 1327             self.execute()
   1328             return task.get()
   1329 

~\AppData\Local\Continuum\miniconda3_37_2\lib\site-packages\vaex\dataframe.py in execute(self)
    277     def execute(self):
    278         '''Execute all delayed jobs.'''
--> 279         self.executor.execute()
    280         self._task_aggs.clear()
    281 

~\AppData\Local\Continuum\miniconda3_37_2\lib\site-packages\vaex\execution.py in execute(self)
    187                                                         progress=lambda p: all(self.signal_progress.emit(p)) and
    188                                                         all([all(task.signal_progress.emit(p)) for task in task_queue]),
--> 189                                                         cancel=cancel, unpack=True):
    190                         pass  # just eat all element
    191                     self._is_executing = False

~\AppData\Local\Continuum\miniconda3_37_2\lib\site-packages\vaex\multithreading.py in map(self, callable, iterator, on_error, progress, cancel, unpack)
     51         time_last = time.time() - 100
     52         min_delta_t = 1. / 100  # max 100 per second
---> 53         for i, value in enumerate(super(ThreadPoolIndex, self).map(wrapped, values)):
     54             progress_value = (i + 1) / N
     55             time_now = time.time()

~\AppData\Local\Continuum\miniconda3_37_2\lib\concurrent\futures\_base.py in result_iterator()
    584                     # Careful not to keep a reference to the popped future
    585                     if timeout is None:
--> 586                         yield fs.pop().result()
    587                     else:
    588                         yield fs.pop().result(end_time - time.monotonic())

~\AppData\Local\Continuum\miniconda3_37_2\lib\concurrent\futures\_base.py in result(self, timeout)
    423                 raise CancelledError()
    424             elif self._state == FINISHED:
--> 425                 return self.__get_result()
    426 
    427             self._condition.wait(timeout)

~\AppData\Local\Continuum\miniconda3_37_2\lib\concurrent\futures\_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

~\AppData\Local\Continuum\miniconda3_37_2\lib\concurrent\futures\thread.py in run(self)
     55 
     56         try:
---> 57             result = self.fn(*self.args, **self.kwargs)
     58         except BaseException as exc:
     59             self.future.set_exception(exc)

~\AppData\Local\Continuum\miniconda3_37_2\lib\site-packages\vaex\multithreading.py in wrapped(*args, **kwargs)
     45                 if unpack:
     46                     args = args[0]  # it's passed as a tuple.. not sure why
---> 47                 callable(self.local.index, *args, **kwargs)
     48         # convert to list so we can count
     49         values = list(iterator)

~\AppData\Local\Continuum\miniconda3_37_2\lib\site-packages\vaex\execution.py in process(thread_index, i1, i2)
    173                                 blocks = [block_dict[expression] for expression in task.expressions_all]
    174                                 if not cancelled[0]:
--> 175                                     task._results.append(task.map(thread_index, i1, i2, *blocks))
    176                                 # don't call directly, since ui's don't like being updated from a different thread
    177                                 # self.thread_mover(task.signal_progress, float(i2)/length)

~\AppData\Local\Continuum\miniconda3_37_2\lib\site-packages\vaex\tasks.py in map(self, thread_index, i1, i2, *blocks)
    502     def map(self, thread_index, i1, i2, *blocks):
    503         if not self.aggregations:
--> 504             raise RuntimeError('Aggregation tasks started but nothing to do, maybe adding operations failed?')
    505         grid = self.grids[thread_index]
    506         def check_array(x, dtype):

RuntimeError: Aggregation tasks started but nothing to do, maybe adding operations failed?

**Comment by maartenbreddels** [comment]
I didn't answer this for some reason. I am not so sure about half float support in C/C++. What you can do is to upcast it to float32, e.g. `df['x'] = df.x.astype('float32')`. We could do this ourselves in vaex, would that work for you?
This means that the casting is done for each chunk, it will not copy the whole dataframe.

**Comment by DougRzz** [comment]
Thanks for the reply 2 years ago!!  I downgraded vaex-core to v0.7.1 for a while.  I have just upgraded Vaex to the latest version and cast my number types to float32 as you suggested.  This works well thanks.   Now I need to catch up with some of the latest developments with Vaex since 0.7.1!
