### ISSUE TITLE
New column with constant value, applied to longer dataframe

### ISSUE THREAD

**Issue by asavv** [vaexio/vaex#455]
Is there a way to add a new column with a constant value (string or numeric) to a dataframe, save the state and apply it to a longer dataframe?

The following example demonstrates what I am trying to achieve.

When I run the following,
```
import vaex
import numpy as np

# Initial dataframe
text = ['Something', 'very pretty', 'is coming', 'our', 'way.']
x = np.arange(5)
df = vaex.from_arrays(col1=x, col2=text)
df.head()

# Add new column as a string
df['col3'] = "'hello'"
df.head()
# NOT: the string value is spanned across the available rows (!!!), instead of having an entry 'hello' per row.
```

I would like my dataframe to be
```
  #    col1  col2            col3
  0       0   Something  hello
  1       1    very pretty  hello
  2       2   is coming    hello
  3       3   our              hello
  4       4   way.            hello
```

Which would then allow me to apply the state to a longer dataframe:
```
text2 = ['Something', 'very pretty','and', 'longer', 'than', 'the', 'original', 'text'] 
x2 = np.arange(8) 
# create a new dataframe
df2 = vaex.from_arrays(col1=x2, col2=text2) 
# save the state from the 1st df above 
saved_state = df.state_get() 
# load the state to the new df we just created, this should allow VAEX to replay everything so we have the same DF
df2.state_set(saved_state) 
# display 
df2.head()
# NOTE: the error "IndexError: string index out of range" happens
```

in order to get the following df2:
```
  #    col1  col2             col3
  0       0   Something  hello
  1       1    very pretty  hello
  2       2   and              hello
  3       3   longer         hello
  4       4   than            hello
  5       5   the              hello
  6       6   original       hello
  7       7   text  hello
```

**Comment by JovanVeljanoski** [comment]
Hey Ana, 

Thank you for trying out Vaex. 

I do not know your use-case for this.. but perhaps using variables will help you out. In Vaex you can define `variables`, which you can use them as constants in the expressions you will be creating. They are also state transferable.  

There are some already defined, try `print(df.variables)`.

Maybe this example, which is a small revision of yours, will help you understand what I am talking about:

```
# Initial dataframe
text = ['Something', 'very pretty', 'is coming', 'our', 'way.']
x = np.arange(5)
df = vaex.from_arrays(col1=x, col2=text)

# Add a variable
df.variables['my_var'] = 'hello'
df['col3'] = df.col2 + ' ' +  df.variables['my_var']
df
```

Then you can do a state transfer

```
text2 = ['Something', 'very pretty','and', 'longer', 'than', 'the', 'original', 'text'] 
x2 = np.arange(8) 
# create a new dataframe
df2 = vaex.from_arrays(col1=x2, col2=text2) 
# save the state from the 1st df above 
saved_state = df.state_get() 
# load the state to the new df we just created, this should allow VAEX to replay everything so we have the same DF
df2.state_set(saved_state) 
# display 
df2
```

I hope this helps, 
Jovan.

**Comment by JovanVeljanoski** [comment]
Hi Ana, 

Ah ok, i thought the main point was the state transfer thingy. If you just want to add a new column that you have defined yourself (for instance, all elements being equal), you can just do it similarly as in pandas, but you will need to use RAM for it. Just create a numpy array, and add it to the dataframe:

```
import vaex
import numpy as np

df = vaex.example()

new_column = np.ones(len(df), dtype=np.bool)
df['is_new_user'] = new_column
```

If you can't afford to waste any additional RAM on this, you can do a virtual column type of thing, for example if you have any other numerical column, do something like

```
df['is_new_user_virtual']  = (df.x+1) > df.x.min()
```
Then, when you export to disk, make sure you specify which columns you want exported, or have the `virtual=True` flag turned on so that the virtual columns are exported as well.  Note that in this case, the state of the dataframe is also modified, but if your purpose is to just transform data before saving them to disk, it should not matter.

I expect the 1st approach to be faster/simpler if you can afford the RAM. 

I hope this helps, 
Jovan.

**Comment by asavv** [comment]
Hi Jovan, 

My question actually relates to both angles (I am sorry if it wasn't clear before).

So, my query is on: 
(a) what is the vaex equivalent for pandas' `df['is_new_user'] = True`,
(b) so that I can save the df state and consequently apply it to a different dataframe. 
Note: The length of the dataframes can vary too.

From what I can understand, the approach of a virtual column
```
df['is_new_user']  = (df.x+1) > df.x.min()
```
will work if we want to store boolean values in the state and apply them to a different dataframe.

For other data types (e.g., string, numerics), something like:
```
df['is_new_user_2']  = df.x.apply(lambda x: 'bla' if x+1 == x else 'my important data')
```
also works.

Is this correct or are there other simpler/more correct ways to do it in vaex?

Thank you in advance for your reply,
Ana Sofia

**Comment by JovanVeljanoski** [comment]
Hi Ana, 

Ok, I perhaps have a slightly better understanding on your usecase, but it is still quite fuzzy.. 

in short:
a) the vaex way of doing it would be:
`df['is_new_user'] = np.ones(len(df), dtype=np.bool)`
which is what pandas is doing behind the scenes I believe, just casting the single element to a Series and adds it the the dataframe. In vaex you should need to define your array yourself, making sure it matches the length of the dataframe. 

b) If you want to store for example textual data, I would do a "hack" like this:
```
# Initial dataframe
text = ['Something', 'very pretty', 'is coming', 'our', 'way.']
x = np.arange(5)
df = vaex.from_arrays(col1=x, col2=text)

# "Hack" to get a virtual column going on
df['new_user'] = df.col2.str.slice(0, 0) + 'placeholder_text'

ext2 = ['Something', 'very pretty','and', 'longer', 'than', 'the', 'original', 'text'] 
x2 = np.arange(8) 
# create a new dataframe
df2 = vaex.from_arrays(col1=x2, col2=text2) 
# save the state from the 1st df above 
saved_state = df.state_get() 
# load the state to the new df we just created, this should allow VAEX to replay everything so we have the same DF
df2.state_set(saved_state) 
# display 
df2
```

In the above example, I am taking a string column, slicing but getting nothing (to get an empty string), then to that I add whatever needs to be added. Such an operation will be stored in the state, so you can transfer it safely. 

As a side-note, i would avoid using the `apply` method, and use it only as a matter of last resort. 

I hope this helps, 
Jovan.

**Comment by asavv** [comment]
Hi Jovan,

Thank you for your prompt replies.

I think for our use case, we need to go with the "hack" solution, as we are really interested on using the state transfer. 
As there been more interest from the community to have a less "hacky" solution for this? 
Just for me to know if I should keep my eyes open on the next few releases. :)

Out of curiosity, why should `apply` be avoided? Is it because the case above shouldn't rely on an if clause?
(These questions may deserve a new thread...)
I am asking because I have another situation where I need to apply an if clause in order to determine the value of a column. For example,
`df['region'] = df.filename.apply(lambda x: 'emea' if 'emea' in x else 'usa')`
and I assumed that this was the best way to do it. Is there another way I should be considering?
As before, the solution should work when transferring the state.

Thanks again,
Ana Sofia

**Comment by JovanVeljanoski** [comment]
Hi Ana, 

Well.. you should pay attention to vaex anyway, some very exciting stuff are coming up soon! :). 

As far as I remember you are the only one yet to bring the topic of a column with a unique value. Maybe we can think about it more if it is a recurrent issue. 
You may also want to check out the discussion here #265 for inspiration on custom expressions for selections filtering. 

Regarding `apply`,  you can read through this thread #442. So if you find a way to achieve what you need without apply, you will get considerable performance boost. 

If you are happy with this for now you can close this issue. For any other questions or problems please open another one, as to not go off the original topic :)

Thanks!
Jovan.

**Comment by asavv** [comment]
Hi Jovan,

Thank you for the links and for your (multiple) replies.
I will close this one, then.

Have a nice weekend,
Ana Sofia
