### ISSUE TITLE
hdf5 file with groups

### ISSUE THREAD

**Issue by wgnu6** [vaexio/vaex#460]
Hello,
I'm trying to load a hdf5 file with groups, and it can't seem to load it in. I'm using
```
import vaex as vx

df = vx.open("../SingletDM.hdf5")
```
Can vaex load hdf5 files with groups?

Thanks.

**Comment by JovanVeljanoski** [comment]
Yes, since recently we support opening of hdf5 files that have groups. You can find some information about this in [the I/O examples page](https://vaex.io/docs/example_io.html#Opening-binary-file-formats).

Thanks.
