### ISSUE TITLE
Bug in concatenating String columns

### ISSUE THREAD

**Issue by mfouesneau** [vaexio/vaex#461]
There seems to be a bug in the manner `vaex.column.ColumnStringArrow` are built during concatenation.

Individual files work fine, but all string values are set to None (fill value I suppose) when extracting values from `vaex.dataframe.DataFrameConcatenated`

Other bug:
```
~/anaconda/lib/python3.6/site-packages/vaex/column.py in tolist(self)
     14 class Column(object):
     15     def tolist(self):
---> 16         return self.to_numpy().tolist()
     17 
     18 

AttributeError: 'ColumnConcatenatedLazy' object has no attribute 'to_numpy'
```

In addition missing imports:
```python
~/anaconda/lib/python3.6/site-packages/vaex/dataset_mmap.py in _map_array(self, offset, length, dtype, stride, filename, array, name)
    163                 if offset is None:
    164                     print("offset is None")
--> 165                     sys.exit(0)
    166 
    167                 file = self.file_map[filename]

NameError: name 'sys' is not defined
```

**Comment by JovanVeljanoski** [comment]
Hi @mfouesneau 

I am having trouble reproducing this issue.. can you please share a minimal example of the code that leads to these issues?

I tried this, and it seems to work:
![image](https://user-images.githubusercontent.com/18574951/68774123-e8a9ef00-062c-11ea-95b1-1269fe732575.png)

Cheers!
J.

**Comment by mfouesneau** [comment]
Your example works. Could this be an encoding issue with older vaex files?
Again single file opens fine, but concatenating does not on the string columns.

**Comment by JovanVeljanoski** [comment]
Oh that could very well be the case.. especially if your files are more than 1 year old. 

Maybe you can try importing and exporting (at least a small portion), and see if that works. Or maybe if you can send me small example files that would help a lot, since I can not peproduce the issue on my side..
