### ISSUE TITLE
vaex.ml: catboost does not allow read-only numpy arrays in v0.20

### ISSUE THREAD

**Issue by JovanVeljanoski** [vaexio/vaex#481]
This issue is due to a recent new release of [`catboost`](https://github.com/catboost/catboost), which appears to have problems with the usage of read-only `numpy` arrays.

One can track this issue on the `catboost` side [here](https://github.com/catboost/catboost/issues/1101).

In the meantime, we will revert to `catboost < 0.20` until the problem is resolved. 

This is meant as a reminder to help us keep track.

**Comment by maartenbreddels** [comment]
v0.20.1 is out, we should test this out on CI

**Comment by JovanVeljanoski** [comment]
Closed via #525
