### ISSUE TITLE
why it is so slow to read a big .csv file via vaex.from_csv()?

### ISSUE THREAD

**Issue by CNFeffery** [vaexio/vaex#484]

**Comment by JovanVeljanoski** [comment]
Hi, 

The speed of reading a .csv file primarily depends on your hardware, i.e. on the read-speed of your hard or solid-state disk. `vaex.from_csv()` essentially uses `pandas.read_csv()` so it is as fast (or as slow) as pandas is (which is pretty fast in my experience). 

If you know of a better / faster .csv parser please let us know, and you are always welcome to submit a PR :). 

Cheers, 
Jovan.
