### ISSUE TITLE
Unable to open hdf5 file

### ISSUE THREAD

**Issue by nitin194** [vaexio/vaex#485]
Hi Team,

I am struggling to open a hdf5 file using vaex.open(path+'test.hdf5')

OSError: Could not open file: D:/<some-path>/test.hdf5, did you install vaex-hdf5? Is the format supported?

Please help, my vaex installation is upto the mark and intact in anaconda env

**Comment by JovanVeljanoski** [comment]
Hi, 

Thanks for trying out vaex.

As a quick test, could you simply try:

```
import vaex
df = vaex.example()
```

Does that work for you?

**Comment by nitin194** [comment]
Thank you for the prompt response. 

No, that didn't work. I received below error

ERROR:MainThread:vaex.file:could not open file as hdf5
Traceback (most recent call last):
  File "C:\Users\nitin.garg\AppData\Local\Continuum\Anaconda3\lib\site-packages\vaex\hdf5\dataset.py", line 161, in can_open
    h5file = h5py.File(f, "r")
  File "C:\Users\nitin.garg\AppData\Local\Continuum\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 394, in __init__
    swmr=swmr)
  File "C:\Users\nitin.garg\AppData\Local\Continuum\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 5447680, sblock->base_addr = 0, stored_eof = 29276864)
ERROR:MainThread:vaex:error opening 'C:\\Users\\nitin.garg/.vaex\\data\\helmi-dezeeuw-2000-10p.hdf5'

AND finally in the output window below info

OSError: Could not open file: C:\Users\nitin.garg/.vaex\data\helmi-dezeeuw-2000-10p.hdf5, did you install vaex-hdf5? Is the format supported?

**Comment by maartenbreddels** [comment]
Odd, could you try deleting this file:

> C:\Users\nitin.garg/.vaex\data\helmi-dezeeuw-2000-10p.hdf5

And try again?

**Comment by nitin194** [comment]
Now, it's working and I can see the df dataframe now. But I still can't open my hdf5 file which I converted from a CSV file. I am using below code to convert to hdf5 from csv

hdf_filename = path+'test.hdf5'
hdf_key = 'hdf_key'
df_cols_to_index = ['id', 'vendor_id', 'pickup_datetime', 'dropoff_datetime',
       'passenger_count', 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'store_and_fwd_flag',
       'trip_duration'] # list of columns (labels) that should be indexed
store = pd.HDFStore(hdf_filename)

for chunk in pd.read_csv(path+"train.csv", chunksize=500000):
    # don't index data columns in each iteration - we'll do it later ...
    store.append(hdf_key, chunk, data_columns=df_cols_to_index, index=False)
    # index data columns in HDFStore

store.create_table_index(hdf_key, columns=df_cols_to_index, optlevel=9, kind='full')
store.close()

**Comment by JovanVeljanoski** [comment]
Hi, 

I can't see the (latest) error message so I don't know if the issue is the same or different. 

In any case, if the way pandas stores HDF5 files is different and currently incompatible with vaex.

To be safe: 
use `vaex.read_csv` which essentially uses `pandas.read_csv` to read in the csv file in memory. You can use the same keywords like you do in pandas. 

After it is in memory, simply do:

`df.export_hdf5(path)`.

For a more detailed example you can also take a look at [this notebook.](https://github.com/vaexio/vaex-examples/blob/master/medium-airline-data-eda/airline-original-data-conversion.ipynb)

I hope this helps.
J.

**Comment by nitin194** [comment]
Thank you for the response. The error which I was getting was same i.e. OSError: Could not open file: D:/................./test.hdf5, did you install vaex-hdf5? Is the format supported?

Also, the whole purpose of reading the file without loading it into memory will fail if I have to read it in memory first and then export it into an hdf5 file. 

I needed a way where I can convert a large csv or any other input file to HDF5 or vaex compatible format without loading into the memory and then open it via Vaex to explore the dataset.

I looked at this [method](https://nbviewer.jupyter.org/github/vaexio/vaex-examples/blob/master/medium-airline-data-eda/airline-original-data-conversion.ipynb) you suggested for conversion but that seemed to be quite complex. That's why I used a simpler way to convert the file in small batches. 

please suggest

**Comment by JovanVeljanoski** [comment]
Right now this is the recommended method. 

You can also look at [this post](https://github.com/vaexio/vaex/issues/369#issuecomment-516818612) for an additional explanation on how to do this.

It is not complex at all.. a simple loop :). 

Aside: on your earlier post, you are in fact using HDF not HDF5.

Hope this works.

**Comment by nitin194** [comment]
Hi @Jovan,

Thanks for pointing out that I might be using the wrong format.

Could you please help me to use the correct format i.e. HDF5 instead of HDF? Where exactly I am using wrong code

**Comment by JovanVeljanoski** [comment]
@nitin194 

Please look at the two examples I send you earlier. That should be more than enough information to get you started. The process is similar no matter what kind of data you are using.

To summarize:
1. read a chuck of the CSV data with `pandas.read_csv` or `vaex.read_csv`.
1.5 if you read it with pandas, convert the data frame with `df = vaex.from_pandas_df(pandas=df)`
2. Export that chunk to HDF5 by `df.export_hdf5(path)`

After this, you will have bunch of hdf5 files. To use them, you can:
a) use `df = vaex.open_many(list_of_filenames)` to open the all as a _single dataframe_, so it would behave just as if you opened one big file.
b) use `df = vaex.open_many(list_of_filenames)`  to open the files as a single dataframe, which you can than export again, to get a single large hdf5 file (might give you a small performance boost).

I hope this helps, there is really nothing more to it. 

Cheers, 
Jovan.

**Comment by nitin194** [comment]
Hi @JovanVeljanoski 

Thank you for all the help. Here is my code to convert CSV file to single HDF5 file based on the batch count. Please suggest if the loop over CSV can be improved?

```
def csv2hdf5(filepath, filename, rownum):
    
    # Delete existing HDF5 files
    del_hdf5(filepath)
    
    # Initialize the counters
    count = 0
    i=0
    
    # Count the number of rows in the csv file
    with open(filepath+filename+'.csv') as fp:
        for _ in fp:
            count += 1
            
    # Loop to convert csv to HDF5 file
    while count - rownum > rownum:
        df = pd.read_csv(filepath+filename+'.csv', nrows=rownum) 
        df = vaex.from_pandas(df) # Convert to vaex format
        df.export_hdf5(filepath+str(i)+filename+'.hdf5') # Export in HDF5 format
        count -= rownum
        i += 1
    else:
        df = pd.read_csv(filepath+filename+'.csv', nrows=count)
        df = vaex.from_pandas(df)
        df.export_hdf5(filepath+str(i)+filename+'.hdf5')
        
    # Return the list of HDF5 file
    hdf5_list = glob.glob(filepath+'*.hdf5')
    hdf5_list.sort(key=alphanum_key)
    hdf5_list = np.array(hdf5_list)
    
    # Open all HDF5 files into dataframe
    master_df = vaex.open_many(hdf5_list)
    
    # Export dataframe into one file with HDF extension
    master_df.export_hdf5(filepath+filename+'.hdf', progress=True)
    
    # Close open file handles
    for df in master_df.dfs:
        df.close_files()
    
    # Delete all file with HDF5 extension
    del_hdf5(filepath)
    
    # Correct the master DF extension
    os.rename(filepath+filename+'.hdf', filepath+filename+'.hdf5')
    
    return filename+'.hdf5'
```

`file = csv2hdf5(path,'train',10000)`
