### ISSUE TITLE
Unable to close open file handles with vaex

### ISSUE THREAD

**Issue by nitin194** [vaexio/vaex#486]
Hi Team,

I want to close the files opened by vaex so that I can delete them after exporting as a single file.

So in details, I am doing this
 ```
    # Open all HDF5 files into dataframe
    master_df = vaex.open_many(hdf5_list)
    
    # Export dataframe into one file with HDF extension
    master_df.export_hdf5(filepath+filename+'.hdf', progress=True)
    
    # Close any possible open file handles
    vaex.close_files(hdf5_list)
```

But I am getting an error as

`AttributeError: module 'vaex' has no attribute 'close_files'`

Please help me close file handles so that I can delete them after exporting.

**Comment by JovanVeljanoski** [comment]
There is no need to close anything.. vaex opens files in read-only mode. 

After you export your big file, just do a quick check and see if the file has the right number of rows and columns, then you are free to delete anything you want. 

Also note, looking from your code example: hdf and hdf5 are _different_ file formats. Vaex uses hdf5. So you probably want to fix that extension, or you might find it confusing sometime down the line, if you forget these details.

**Comment by nitin194** [comment]
oops sorry for that ... here are more deatils for your reference

```
def del_hdf5(filepath):
    files = glob.glob(filepath+'*.hdf5')
    for f in files:
        os.remove(f)

```
```
 # Open all HDF5 files into dataframe
    master_df = vaex.open_many(hdf5_list)
    
    # Export dataframe into one file with HDF extension
    master_df.export_hdf5(filepath+filename+'.hdf', progress=True)
    
    # Close any possible open file handles
    vaex.close_files()
    
    # Delete all file with HDF5 extension
    del_hdf5(filepath)
    
    # Correct the master DF extension
    os.rename(filename+'.hdf', filename+'.hdf5')
```

So the del_hdf5 function is throwing below error

`PermissionError: [WinError 32] The process cannot access the file because it is being used by another process`

**Comment by maartenbreddels** [comment]
> There is no need to close anything.. vaex opens files in read-only mode.

You need to if you want to remove the fil.



>  Close any possible open file handles
>    vaex.close_files(hdf5_list)

You are looking for:
```python
df.close_files()
```

In this, case, master_df has a list of dfs:
```
for df in master_df.dfs:
  df.close_files()
```
Should work, I think it would be nicer if `master_df.close_files()` would do this for you.

Let me know if this works.

**Comment by nitin194** [comment]
Thanks, @maartenbreddels 

You got it right. I will wait for your solution on `master_df.close_files()`  it would help to close it in one go

**Comment by maartenbreddels** [comment]
Does this solution work?

Yes, lets keep this open until we fixed/implemented this.

**Comment by nitin194** [comment]
Yes, that worked for me. Please check my solution [here](https://github.com/vaexio/vaex/issues/485#issuecomment-563163922).

**Comment by MMF3775** [comment]
I have this problem. I want to close vaex dataframe and open it with other process. I saw in vaex document to use df.close() to close vaex file. When I used it ,nothing happened and i had this error:
"The process cannot access the file because it is being used by another process."
I got this error when I use vaex.close_file()
"module 'vaex' has no attribute 'close_files'".
