### ISSUE TITLE
Support for substring search in selection

### ISSUE THREAD

**Issue by tboch** [vaexio/vaex#49]
I'd like to be able to perform a selection by searching for a substring in a given field of my dataset.
Something like this:
```python
t = vaex.open('simbad.fits')
t.select("object_type.find('galax')>=0")
```

For the record: in numpy, you can use this syntax for this use case:
```python
foo = np.array(['star', 'galaxy', 'quasar', 'cluster of galaxies'])
np.where(np.char.find(foo,  'gal') > -1)
```

**Comment by maartenbreddels** [comment]
Now that strings are supported, this should fully work:
```
t.select(t.object_type.str.contains('galax'))
```
Please reopen if it does not work.
