### ISSUE TITLE
Feature request for Datetime Format

### ISSUE THREAD

**Issue by RAJAT8878** [vaexio/vaex#490]
Is there any support in vaex for datetime columns so that we can set the datetime columns to the particular format. for e.g. '%Y-%m-%d %H:%M:%S'

**Comment by maartenbreddels** [comment]
I think @JovanVeljanoski worked on this a while ago, but it was quite manual work. I think this is a good feature to have and will make sense to put into the C++ code for good performance.

**Comment by RAJAT8878** [comment]
Thanks @maartenbreddels

**Comment by qiruoqiqi** [comment]
Have you realized this function now?

**Comment by qiruoqiqi** [comment]
Have you realized this function now?

**Comment by JovanVeljanoski** [comment]
This is possible indeed:

```python
import vaex
import pandas as pd

t = pd.date_range('2020-10-01', '2021-02-02', freq='D').values
x = np.arange(len(t))
df = vaex.from_arrays(x=x, t=t)
df.t.dt.strftime('%Y-%m-%d %H:%M:%S')
```

I will close this. Any improvements can go to a separate issue.
