### ISSUE TITLE
how to pyspark.sql.DataFrame  convert to vaex.df?

### ISSUE THREAD

**Issue by zangruirui** [vaexio/vaex#498]
i often use spark.sql("select * from XXXX").toPandas() ,but how use vaex in pyspark spark.sql?

**Comment by maartenbreddels** [comment]
Hi,

from a pandas dataframe, you can easily go to a vaex dataframe:
https://docs.vaex.io/en/latest/api.html#vaex.from_pandas
So that would be:
```python
import vaex
df = vaex.from_pandas(spark.sql("select * from XXXX").toPandas(), copy_index=False) # assuming you don't care about the index, which i think spark also does not have by default
```
Does that help?

**Comment by zangruirui** [comment]
> Hi,
> 
> from a pandas dataframe, you can easily go to a vaex dataframe:
> https://docs.vaex.io/en/latest/api.html#vaex.from_pandas
> So that would be:
> 
> ```python
> import vaex
> df = vaex.from_pandas(spark.sql("select * from XXXX").toPandas(), copy_index=False) # assuming you don't care about the index, which i think spark also does not have by default
> ```
> 
> Does that help?

no，because my data is too much to canvert pandas.df 。 so，i want convert spark.df to vaex.df directly

**Comment by maartenbreddels** [comment]
That is actually an interesting problem, we don't work so much with Spark.

The general approach is, export to hdf5 files:
```python
for i in range(chunks):
  pandas_df = load_chunk(i) # your function to load a piece that does fit into memory
  pandas_df.export(f'chunk_{i}.hdf5)
```

Then you have two options, either work with a concatenated dataframe, or combine them in 1 big hdf5 file:
```
df = vaex.open('chunk_*.hdf5) # concatenated dataframe
df = vaex.open('chunk_*.hdf5', convert='big.hdf5') # will convert to 1 file if it does not exist
```
Does that help?

**Comment by zangruirui** [comment]
> That is actually an interesting problem, we don't work so much with Spark.
> 
> The general approach is, export to hdf5 files:
> 
> ```python
> for i in range(chunks):
>   pandas_df = load_chunk(i) # your function to load a piece that does fit into memory
>   pandas_df.export(f'chunk_{i}.hdf5)
> ```
> 
> Then you have two options, either work with a concatenated dataframe, or combine them in 1 big hdf5 file:
> 
> ```
> df = vaex.open('chunk_*.hdf5) # concatenated dataframe
> df = vaex.open('chunk_*.hdf5', convert='big.hdf5') # will convert to 1 file if it does not exist
> ```
> 
> Does that help?

en, i cannot convert pyspark.sql.df data to hdf5  directly.

**Comment by maartenbreddels** [comment]
I don't think so. I would not worry too much, these steps you only do every now and then. Also, I doubt a more efficient way to convert them would speed it up by much (at most a factor 2 I'd guess).

**Comment by JovanVeljanoski** [comment]
Will close as stale - please reopen if needed.

**Comment by ttpro1995** [comment]
I have issue again. 
Vaex is said to work with BIG, very big data. 
I would like to do EDA, chart on data load from spark/hdfs (.parquet). 
However, due to system config, only sprak.read.parquet(path) can read from Hadoop from jupyter notebook, vaex.open( ) cannot. I can manually download the dataset to my computer, however, the data is bigger than my hard disk. 

I would like a solution to work with Vaex without: download .parquet to my PC, convert to pandas and save as hdf5 to my PC. Because the data is so big (hundres gb). Preferable the method that does not include running computing on whole dataset.

**Comment by BenLBurke** [comment]
I 2nd what @ttpro1995 has said. 

I have a 1T worth of data I'd like to plot but the data is saved in a delta table. Downloading the data to Pandas takes a long time, is there a more efficient way to take the data from delta (parquet files) and import into a Vaex DF?

**Comment by maartenbreddels** [comment]
> Is there a more efficient way to take the data from delta (parquet files) and import into a Vaex DF?

Yes, vaex directly supports parquet, so you probably don't need to go via the pandas route.
