### ISSUE TITLE
vaex in python3 install Ok  ,import error

### ISSUE THREAD

**Issue by zerolugithub** [vaexio/vaex#503]
[root@worker ~]# python3
Python 3.6.8 (default, Aug  7 2019, 17:28:10)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vaex
ERROR:MainThread:vaex:issue loading plot
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/vaex/__init__.py", line 720, in <module>
    add_namespace = entry.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'vaex.viz'
ERROR:MainThread:vaex:issue loading astro
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/vaex/__init__.py", line 720, in <module>
    add_namespace = entry.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'vaex.astro'
>>>

**Comment by maartenbreddels** [comment]
How did you install vaex?

A solution could be to upgrade pip and setuptools, and try reinstalling.

**Comment by zerolugithub** [comment]
pip3 install vaex

**Comment by zerolugithub** [comment]
[root@worker ~]# pip3 --version
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
[root@worker ~]#

**Comment by zerolugithub** [comment]
yum install python3-pip 
install pip3

**Comment by JovanVeljanoski** [comment]
@zerolugithub 

You can read through [this thread](https://github.com/vaexio/vaex/issues/464) and see if the suggestions that may help you.

**Comment by maartenbreddels** [comment]
I recommend not using your system python, but install anaconda, or create a virtual environment and use `$ pip install --upgrade pip setuptools`.

**Comment by zerolugithub** [comment]
OK ,i'm try

**Comment by zerolugithub** [comment]
hi, Thank you @maartenbreddels @JovanVeljanoski 
I  install vaex ,OK
Thank you  again!!!

**Comment by JovanVeljanoski** [comment]
You are welcome! Good luck.

**Comment by grantbelford** [comment]
Thank you Jovan.
Tried pip every which way today but your suggestion for new environment/conda forge works great!
Best Regards,
Grant
