### ISSUE TITLE
Improvement(s) to the progressbar

### ISSUE THREAD

**Issue by JovanVeljanoski** [vaexio/vaex#508]
`Vaex` already has support for a couple of progress bars: 
 - the classic progressbar2
 - progressbar from `ipywidgets`

The progressbar2 works very well, but looks a bit dated in a notebook environment. 

The `ipywidgets` one looks much better, but lacks the extra information that the classic progressbar2 has (time elapsed and estimated time left, where in the loop one is etc..). 

I propose: 
 - keep progressbar2 as it is.
 - update the ipywidgets progress bar to display the same information that the classic progressbar also displays
- optionally add support for `tqdm.notebook` although that might be just the `ipywidgets` progressbar
- support for `ipyvuetify` progressbar, since we are using this in `vaex-jupyter`.

**Comment by maartenbreddels** [comment]
Would #545 close this, or should we have more?

**Comment by JovanVeljanoski** [comment]
Indeed, we can mark this as closed via #545 

I have other ideas about progressbars.. but that can wait, and be handled separately when the time comes.
