### ISSUE TITLE
ml: Wrap IncrementalTrees

### ISSUE THREAD

**Issue by maartenbreddels** [vaexio/vaex#519]
With #516 and #497 merged, we should take a look at:
https://github.com/garethjns/IncrementalTrees
Having out of core xgboost/lightgbm/catboost/sklearn-pygbm seems very interesting.

**Comment by JovanVeljanoski** [comment]
The Implementation of IncrementalTrees for scikit-learn Random Forrest and ExtraTrees works out of the box `IncrementalPredictor` in `vaex.ml.sklearn`.

You can check out this notebooks (zipped, no external data is needed) for reference:
[IncrementalTrees-trial.ipynb.zip](https://github.com/vaexio/vaex/files/3992349/IncrementalTrees-trial.ipynb.zip)

I guess we can put something similar to disk in the docs somewhere.

Is there anything else that is needed for this PR @maartenbreddels ?

**Comment by maartenbreddels** [comment]
Hmm, you are right! Cool. Does it serialise to disk?

(from mobile phone)

**Comment by JovanVeljanoski** [comment]
Yes it does! 

Would be very nice if this package (IncrementalTrees) could be merged into scikit-learn, or at least into their experimental stuff. Right now it can only be installed from source.
