### ISSUE TITLE
Left (or Right) Outer joins on string fields yields an error on missing values (on left or right dataframes)

### ISSUE THREAD

**Issue by nageshdanturti** [vaexio/vaex#528]
Hi, 

I get a **non-fatal** error when I join two dataframes where the joining keys on both dataframes are string fields. The error happens when I perform an outer join (left or right) when I know one of the 2 dataframes contains fewer rows than the other. I am looking for a SQL-like outer join output where the resulting dataframe should show empty values for non-existing rows (instead it shows **error** in the output).  

Example:

df1 = 800K rows (4 fields all strings datatypes, joining (string) key = part_number)
df2= 1Million rows (5 fields all string datatypes, joining (string) key = prd_part_number)

syntax:

`
df1 = vaex.open(write_directory + 'ERPPartNumbers.parquet')
print("ERP Part Numbers = ", df1.count())

df2 = vaex.open(write_directory + 'ProductItems.parquet')
print("Product Items = ", df2.count())

df3=df1.join(df2, left_on='part_number', right_on='part_number', rprefix='cedi_', how='right', inplace=False)

print("Join between ERP and Product Items = ", df3.count())
df3
`

The error is as follows:

_ERROR:MainThread:vaex:error evaluating: part_number at rows 0-5
Traceback (most recent call last):
  File "/Applications/Anaconda/anaconda3/envs/eriks/lib/python3.7/site-packages/vaex/dataframe.py", line 3467, in table_part
    values[name] = df.evaluate(name)
  File "/Applications/Anaconda/anaconda3/envs/eriks/lib/python3.7/site-packages/vaex/dataframe.py", line 5038, in evaluate
    dtype = dtypes[expression] = self.dtype(expression, internal=False)
  File "/Applications/Anaconda/anaconda3/envs/eriks/lib/python3.7/site-packages/vaex/dataframe.py", line 2002, in dtype
    data = column[0:1]
  File "/Applications/Anaconda/anaconda3/envs/eriks/lib/python3.7/site-packages/vaex/column.py", line 124, in __getitem__
    ar = ar_unfiltered[indices]
  File "/Applications/Anaconda/anaconda3/envs/eriks/lib/python3.7/site-packages/vaex/column.py", line 398, in __getitem__
    return type(self).from_string_sequence(self.string_sequence.index(slice))
TypeError: index(): incompatible function arguments. The following argument types are supported:
    1. (self: vaex.superstrings.StringSequenceBase, arg0: numpy.ndarray[bool]) -> vaex.superstrings.StringSequenceBase
    2. (self: vaex.superstrings.StringSequenceBase, arg0: numpy.ndarray[int32]) -> vaex.superstrings.StringSequenceBase
    3. (self: vaex.superstrings.StringSequenceBase, arg0: numpy.ndarray[int64]) -> vaex.superstrings.StringSequenceBase
    4. (self: vaex.superstrings.StringSequenceBase, arg0: numpy.ndarray[uint32]) -> vaex.superstrings.StringSequenceBase
    5. (self: vaex.superstrings.StringSequenceBase, arg0: numpy.ndarray[uint64]) -> vaex.superstrings.StringSequenceBase_

**Comment by nageshdanturti** [comment]
I do realize that you mentioned in the docs that outer joins are not yet supported. I raised it anyway to help contribute to your longer-term vision

**Comment by JovanVeljanoski** [comment]
Hi @nageshdanturti ,

Thank you for making us aware of this. We will try our best to handle it.

Cheers, 
Jovan.

**Comment by maartenbreddels** [comment]
I think #530 fixed it, which is now merged. Our error was a bit different, which is a bit strange, so it would be great if you can test this (see https://docs.vaex.io/en/latest/installing.html#for-developers for dev installs)

**Comment by xdssio** [comment]
Can we close this? @maartenbreddels

**Comment by nextgenmetrics** [comment]
yes, please. this was indeed fixed with #530. apologies for not informing earlier - our developers didn't take time to update this thread. thanks for all the help!
