### ISSUE TITLE
pls share an example for xgboost evals-IndexError: list index out of range

### ISSUE THREAD

**Issue by hanwsf** [vaexio/vaex#535]
I used vaex dataframe df_test from: df_train, df_test = df[:10000000].ml.train_test_split(verbose=True), it says error as following; (tried to use pandas dataframe [[test_x, test_y]], also says error).
IndexError                                Traceback (most recent call last)
~/Downloads/ashrae-energy-prediction/asrae-vaex.py in 
     22 xgmodel = vaex.ml.xgboost.XGBoostModel(features=features, num_boost_round=10, params=best_params)
---> 24 xgmodel.fit(df_train, 'meter_reading_log',evals=[[df_test]],early_stopping_rounds=4,verbose_eval=True)
     25 df_predict = xgmodel.transform(df_test)
     26 df_predict

~/.local/lib/python3.6/site-packages/vaex/ml/xgboost.py in fit(self, df, target, evals, early_stopping_rounds, evals_result, verbose_eval, **kwargs)
    117                                      evals_result=evals_result,
    118                                      verbose_eval=verbose_eval,
--> 119                                      **kwargs)
    120 
    121     def predict(self, df, **kwargs):

~/.local/lib/python3.6/site-packages/xgboost/training.py in train(params, dtrain, num_boost_round, evals, obj, feval, maximize, early_stopping_rounds, evals_result, verbose_eval, xgb_model, callbacks, learning_rates)
    214                            evals=evals,
    215                            obj=obj, feval=feval,
--> 216                            xgb_model=xgb_model, callbacks=callbacks)
    217 
    218 

~/.local/lib/python3.6/site-packages/xgboost/training.py in _train_internal(params, dtrain, num_boost_round, evals, obj, feval, xgb_model, callbacks)
     82         # check evaluation result.
     83         if evals:
---> 84             bst_eval_set = bst.eval_set(evals, i, feval)
     85             if isinstance(bst_eval_set, STRING_TYPES):
     86                 msg = bst_eval_set

~/.local/lib/python3.6/site-packages/xgboost/core.py in eval_set(self, evals, iteration, feval)
   1160             if not isinstance(d[0], DMatrix):
   1161                 raise TypeError('expected DMatrix, got {}'.format(type(d[0]).__name__))
-> 1162             if not isinstance(d[1], STRING_TYPES):
   1163                 raise TypeError('expected string, got {}'.format(type(d[1]).__name__))
   1164             self._validate_features(d[0])

IndexError: list index out of range
--------------------
And if don't use evals, it works, but no verbose.
Please help to check its function.

**Comment by JovanVeljanoski** [comment]
Hi @hanwsf,

Keep in mind that the main reason behind `vaex.ml.xgboost.XGBoostModel` (same for lgbm, catboost) is to make the model a vaex _transformer_. The functionality/usage is as close to using vanilla xgboost as we could make it. Thus the answer lies in the xgboost docs:

```
evals: list of pairs (DMatrix, string)
List of items to be evaluated during training, this allows user to watch
    performance on the validation set.
```

In this case, insted of DMatrix one should pass vaex DataFrame:

```
model = XGBoostModel(features=features, num_boost_round=500, params=params)
history = {}
model.fit(df=df_train, 
          target=target, 
          evals=[(df_train, 'train'), (df_val, 'val')], 
          early_stopping_rounds=10, 
          evals_result=history)
```

Hope this helps!

**Comment by hanwsf** [comment]
Thanks a lot! let me try.
