### ISSUE TITLE
Should exporting a frame of only virtual cols with virtual=False throw an error/warning?

### ISSUE THREAD

**Issue by yetyetanotherusername** [vaexio/vaex#544]
I just made the stupid mistake of writing a frame of virtual columns to a hdf5 file. 

This results in a file that can't be opened (`vaex.open()` throws a `TypeError: 'NoneType' object cannot be interpreted as an integer`).

Since the original error is a bit obscure to debug from that, would it be a good idea for `export_hdf5` to throw a warning/error when a dataframe of only virtual columns is being exported with parameter `virtual=False`?

**Comment by maartenbreddels** [comment]
This should be supported actually, could you give me a reproducible example?

**Comment by yetyetanotherusername** [comment]
I cannot reproduce the exact error I got with this minimal example but I think that it is caused by the same issue:

`import numpy as np
import vaex as vx

x = np.arange(1000000)
y = x ** 2
frame = vx.from_arrays(x=x, y=y)

frame['z'] = frame.x + frame.y
frame['zz'] = frame.x - frame.y
frame['z', 'zz'].export('test.hdf5')

frame1 = vx.open('test.hdf5')
frame1`

If I change `frame['z', 'zz'].export('test.hdf5')` to `frame['z', 'zz'].export('test.hdf5', virtual=True)`, it works.

**Comment by JovanVeljanoski** [comment]
This should be fixed by #699 which makes all export functions to also include all virtual columns by default. 

Please re-open if the issue persists or if you encounter a similar one. 
Cheers!
