### ISSUE TITLE
Running multiple selections in one pass of the data

### ISSUE THREAD

**Issue by rroyer-xyz** [vaexio/vaex#560]
Hello - currently, I’m using code similar to below to generate counts from Boolean expressions entered by users. The number of expressions and logic is dynamic.

```
counts = []
df.select((df.col1 == 4) & (df.col2 == 7))
counts.append(df.selected_length())

df.select((df.col3 == 66) | (df.col4 != 1))
counts.append(df.selected_length())

df.select(((df.col5 == 1) & (df.col6 != 1)) | (df.col7 != 1))
counts.append(df.selected_length())
```
This works just fine; however, I wanted to double check that there isn’t a more elegant way I could be doing this. For example, is there a way to genterate the counts in one pass over the data? I was able to do this in pandas with .apply() but it does not perform as well.

**Comment by JovanVeljanoski** [comment]
Hi @rroyer-xyz 

I am not sure I understand your use-case.. Is your question how to calculate the counts for multiple selections with 1 pass over the data? If that so, I would do something like this:

```
import vaex
import vaex.ml

df = vaex.ml.datasets.load_titanic()
df.count(selection=[(df.sex == "male") & (df.pclass == 3),
                    (df.sex == "female") | (df.pclass == 1),
                    (df.age == 31) & (df.survived)])
```
which returns
`array([493, 645,  12])`

Does this help at all?
J.

**Comment by rroyer-xyz** [comment]
This is exactly what I was looking for, many thanks! The only piece I can't figure out is making the selections dynamic. My use case needs to pass in a list of selections that aren't known ahead of time (i.e., they can't be hard-coded). I tried something similar to this ticket with evaluating a string https://github.com/vaexio/vaex/issues/547 but no luck in this scenario. I put more details below of what I'm trying to achieve.
```
my_list = [(df.sex == "male") & (df.pclass == 3),
                    (df.sex == "female") | (df.pclass == 1),
                    (df.age == 31) & (df.survived)])

df.count(selection=my_list)
```

**Comment by rroyer-xyz** [comment]
I got it. The code below should allow me to build the selection string dynamically. This has some awesome performance. thanks again.

```
exp = '''
selection=[
(df_vx.Cell == 1 & df_vx.Age_tracking == 3),
(df_vx.Cell != 1 & df_vx.Age_tracking == 1)
]
'''

eval('df_vx.count(%s)' % (exp))
```

**Comment by maartenbreddels** [comment]
Hi,

I don't think you needs strings, it is not clear to me exactly what you want, but maybe this example helps:
```python
feature1 = df['Cell']
feature2 = df['Age_tracking']
selections=[(feature1 == 1) & (feature2 == 3), (feature1 != 1) & (feature2 == 1)]
df.count(selection=selections)
```
The 'trick' is that `df[<string>]` allows you to get an expressions, where the string can come from some gui element, or some other input.
Does this make sense?
FYI: I think this question is more stackoverflow material, since I don't think it's vaex specific, more a programming question right? (Not that I mind, but there are more eyes on stackoverflow)

cheers,

Maarten

**Comment by rroyer-xyz** [comment]
This is perfect! And I'll post to stackoverflow in the future.... thanks
