### ISSUE TITLE
Slow execution of numpy

### ISSUE THREAD

**Issue by xdssio** [vaexio/vaex#561]
```
import vaex
import numpy as np
ds = vaex.example()
train, test = ds.ml.train_test_split(verbose=False)
np.sqrt(train.x ** 2 + train.y ** 2 + train.z ** 2) # this get stuck
```

While this:
```
np.sqrt(train.x.values ** 2 + train.y.values ** 2 + train.z.values ** 2)
```
works normally

**Comment by maartenbreddels** [comment]
Thanks for the report. I cannot reproduce it, it works normally here. Which version are you using, and you say 'slow' in the title, but 'stuck' in the comment, can you be more specific what happens?

**Comment by JovanVeljanoski** [comment]
I can not reproduce any issues either (running latest master, and latest conda-forge release).
Seems "normally fast" to me?

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/18574951/72966794-0b404d00-3dc0-11ea-8273-6164a224c4fe.png">

**Comment by maartenbreddels** [comment]
Stale, assuming solved, feel free to reopen if not.
