### ISSUE TITLE
Concatenate dataframe with manipulated column

### ISSUE THREAD

**Issue by MayaStr** [vaexio/vaex#564]
Dear vaex team,

I would like to concatenate dataframes with a column that was converted to datetime64. However, I cannot access the column after concatenating. 

`import vaex`
`import numpy as np`
`x = np.arange(5) `
`y = ['2020-01-23','2020-01-24','2020-01-25','2020-01-26','2020-01-27']`
`df = vaex.from_arrays(x=x, y=y)`

Manipulation, e.g.
`df['y'] = df['y'].astype('datetime64[ms]')`
or
`df['y'] = df['y']+df['y']`

Concatenation:
`concatenated = df.concat(df)`

The original dataframe is fine:
`df.get_column_names`
`df['y']`

while the concatenated dataframe produces errors:
`concatenated.get_column_names`
KeyError: "Unknown variables or column: 'str_cat(__y, __y)'"
`concatenated['y']`
NameError: name '__y' is not defined

Is there a problem in how I use the concatenation or is it a bug?
Kind regards,
Maya

**Comment by JovanVeljanoski** [comment]
Hi @MayaStr 

Thank you for reporting this, and providing such a nice and reproducible example. We will try to attend to this.

Cheers, 
Jovan.

**Comment by maartenbreddels** [comment]
Thanks indeed for the example, this is now fixed in master, and should be in the next release (vaex v3)
