### ISSUE TITLE
DateTime readings, conversions, and selections

### ISSUE THREAD

**Issue by jhjhagen** [vaexio/vaex#565]
Hi,

As suggested in a different issue I would like to convert/read datetime strings to e.g. datetime64 format using vaex. It would also be nice to be able to set or even change/reset the timezone of the column and to compute the local time in a different time zone.

Subsequently, it would be useful to be able to make selections in vaex based on datetime data, e.g. something like:
`ds.select('DatetimeUTC > 2020')` or `ds.select('DatetimeUTC > "2020-01-01"')`

Such features would be similar to those in Pandas, e.g.:
https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html

**Comment by maartenbreddels** [comment]
Great to hear from you again Jorrit!

We now rely fully on numpy for datetime64, which is not aware of timezones. When we move to use Apache Arrow #517, we can add timezone metadata.

But we do support selections/filtering on time:
```python
import vaex
import numpy as np
x = np.array(['2019-01-04T21:23:00', '2019-02-04T05:00:10', '2019-03-04T15:15:15', '2019-06-21T10:31:15'],
             dtype=np.datetime64)
y = np.array(['2018-06-14T12:11:00', '2019-02-02T22:19:00', '2017-11-18T10:11:19', '2019-07-12T11:00:00'],
             dtype=np.datetime64)

df = vaex.from_arrays(x=x, y=y)
df['diff'] = df.x-df.y
df['diff_dev_hours'] = df.diff / np.timedelta64(1, 'h')
df['diff_add_days'] = df.diff + np.timedelta64(5, 'D')

some_date = np.datetime64('2019-02-04T05:00:10')
df[df.x > some_date]
```
Gives:
![image](https://user-images.githubusercontent.com/1765949/73284652-2dd5ca00-41f5-11ea-8850-02e7fd44069b.png)

**Comment by ramadhiantoagung** [comment]
Hi, just want to ask similar item. Does datetime field not supported in groupby?

For now im relying in dask to do initial formating and flooring of datetime format during file read (most of my file input are in excel), and read it as string in vaex. Converting dask/pandas dataframe to vaex one took quite an overhead though.

**Comment by maartenbreddels** [comment]
Can you be more specific about what you want? And maybe it is better to open an new issue, I don't think this is related to the initial issue.

**Comment by JovanVeljanoski** [comment]
@ramadhiantoagung 

Please check out #914 for an example.  I believe that is what you were referring to.
