### ISSUE TITLE
Convert multiple big csv file into a single HDF5 file.

### ISSUE THREAD

**Issue by ridlo** [vaexio/vaex#566]
Hi,

I have several big .csv file that I want to merge into single HDF5 file using vaex. Is there any 'append' method for Vaex-DataFrame when exporting it to hdf5? I can't find it.
The solutions I found that I think should work are:
1. https://vaex.readthedocs.io/en/latest/faq.html#I-have-a-massive-CSV-file-which-I-can-not-fit-all-into-memory-at-one-time.-How-do-I-convert-it-to-HDF5?
2. or modyfing this 'manual' code in
https://vaex.readthedocs.io/en/latest/getting_data_in_vaex.html#getting-your-data-in-and-out-of-vaex

Is it correct? :)

**Comment by JovanVeljanoski** [comment]
Hi @ridlo 

Yes, both 1, 2 that you linked in your post are what we recommend at least for now. 

Cheers, 
Jovan.
