### ISSUE TITLE
Failing to open many files

### ISSUE THREAD

**Issue by fprada** [vaexio/vaex#577]
Hi,

 due to the huge size of our files we had to split them in many. So far we split a single Rockstar output (converted to HDF5) in 8000 files. This makes vaex.open to fail when I try to read more than 1000 or so. I get the error,
OSError: [Errno 24] Too many open files:

If I use vaex.open_many for some reason I get this error regardless the number of files I am reading,

OSError: Could not open file: /, did you install vaex-hdf5? Is the format supported?

Is there a way around such that I can read with vaex so many files? 

Thanks!
Francisco.

**Comment by JovanVeljanoski** [comment]
Hi @fprada 

This is an OS error, not a vaex error. I guess you are likely using a Mac (although a linux machine will also show the same at some point). Anyway, these OSes (no idea about windows) have a limit of how many files you can open at one time. 

You can modify this by running:
`ulimit -n 9999`  (as admin)
to make the limit 9999. 

If you run things in a Jupyter environment, make sure you start the server from the same session (terminal) on which you've executed the above command. 

While the thing above should work, a more brute-force approach is to only open and merge like 1/4 of the files and do that 4 times, and then merge those 4 files. But 8k files should not be that many. 

I hope this helps

P.S. I do not know much about this, but people encounter the same issue from time to time, so you can google around to see more options regarding `ulimit` and so on.

**Comment by fprada** [comment]
Thanks for your fast reply!
Indeed it must be an OS error due to 'ulimit' setting (Btw. I am using linux in my server). 
It doesn't sound too practical to use this option if one needs root access even when using Jupiter. I am thinking in the case where the user will run the jobs in a big computer that she / he is not root.

The option of merging different DataFrames sounds probably better. Would you recommend to use  vaex.concat([df1, df2, df3, ...]) or is there any other way for this brute-force approach.

Thanks.

**Comment by JovanVeljanoski** [comment]
Yeah it is for sure an OS thing.. nothing we can do about it. I am not completely sure if you must have sudo access for the `ulimit` thing..  maybe I is not necessary. (Perhaps @maartenbreddels knows more about this?).

As for iterative approach, yeah `vaex.concat` is the way to go. Perhaps one can do a loop, open/concat bunch of files, export, close those files (`df.close()`), get another batch etc.

**Comment by fprada** [comment]
Thanks!
I am curious. Why does one need 'export'? is it not enough to open and concat only?

**Comment by JovanVeljanoski** [comment]
Hi, 

Right now there are some issues around the concatenated DataFrames. You can see there are bunch of open issues on this topic. 

We plan to improve matters, hopefully to the point at which one indeed does not have to export to a single file. Right now, it is best to export to a single file.

Cheers, 
J.

**Comment by fprada** [comment]
Got it. Thank you!

Cheers,
 Francisco.

**Comment by yetyetanotherusername** [comment]
I'm actually trying to work around this by using chunks, but I can't get vaex to free up the file handles (after opening them with .open_many()). Is there anything else one needs to do except run close_files() on the mapped frame?

**Comment by maartenbreddels** [comment]
Which OS are you using?

**Comment by yetyetanotherusername** [comment]
I'm on Linux (Fedora 31).

**Comment by maartenbreddels** [comment]
could you open a new issue for this? that makes tracking easier
