### ISSUE TITLE
plot() takes 0 positional arguments but 2 were given

### ISSUE THREAD

**Issue by masoodimran** [vaexio/vaex#588]
I am trying to run the below code from the tutorial documentation

df.select(df.x > 0)
@vaex.jupyter.interactive_selection(df)
def plot():
    print("Mean x for the selection is:", df.mean(df.x, selection=True))
    df.plot(df.x, df.y, what=np.log(vaex.stat.count()+1), selection=[None, True])
    plt.show()

I get the following error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/Documents/ml/python-vaex/.venv/lib/python3.7/site-packages/vaex/jupyter/utils.py in _selection_changed(df, selection_name)
     59                 with output:
     60                     clear_output(wait=True)
---> 61                     f_interact(df, selection_name)
     62             hook = df.signal_selection_changed.connect(_selection_changed)
     63             _selection_hooks.append((df, hook))

TypeError: plot() takes 0 positional arguments but 2 were given

**Comment by JovanVeljanoski** [comment]
Hi @masoodimran 

Please check the [this discussion](https://github.com/vaexio/vaex/issues/541#issuecomment-570361877).

I hope this helps.
Jovan

**Comment by maartenbreddels** [comment]
> @vaex.jupyter.interactive_selection(df)
> def plot():

I think you missed two arguments here, the df and selection name!
I initially thought it was the df.plot call, and maybe you did too?

cheers,

Maarten

**Comment by masoodimran** [comment]
@maartenbreddels Sorry, I did not understand. I am not passing any arguments to plot(), so from where is it getting 2 arguments?

Can you please correct the code I need to use to make this work?

Regards,
Masood

**Comment by masoodimran** [comment]
@JovanVeljanoski 

It worked for that code. But, when I tried this one, it is giving error.

df.select(df.x > 0)
df.plot_widget(df.x, df.y, f='np.log(vaex.stat.count()+1)', selection=[None, True])

ValueError: do not understand f = np.log(vaex.stat.count()+1), should be a function, string 'identity' or a function from numpy such as 'log', 'log1p'

Regards,
Masood

**Comment by maartenbreddels** [comment]
> Sorry, I did not understand. I am not passing any arguments to plot(), so from where is it getting 2 arguments?

You function is being called with 2 argument, but your function did not take 2 parameters, so it should be sth like


> @vaex.jupyter.interactive_selection(df)
> def plot(df, selection):

Just like the examples.

**Comment by maartenbreddels** [comment]
> do not understand f = np.log(vaex.stat.count()+1), should be a function, string 'identity' or a function from numpy such as 'log', 'log1p'

exactly what it says, it cannot be any strings, 'log', 'log1p', you are confusing it with the what argument, please take a better look at the examples.

**Comment by masoodimran** [comment]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/30685384/74257557-03b6f880-4d1b-11ea-9658-0ba15d988f8b.png">

@maartenbreddels This is what the example has. It works after passing the parameters you mentioned.

Thanks,
Masood

**Comment by maartenbreddels** [comment]
Ah, you are right, the example is not up to date. @JovanVeljanoski we should try putting the example notebook in CI as well, maybe we should put the example dataset on s3?

**Comment by JovanVeljanoski** [comment]
This has been since reworked, and the docs are part of the CI. Please reopen if the issue re-appears. Thanks!
