### ISSUE TITLE
!= not supported as string comparison operand

### ISSUE THREAD

**Issue by ramadhiantoagung** [vaexio/vaex#601]
Hi, trying to exclude some string from list of string, when using != as operand, return this:

`ValueError: operand '!=' not supported for string comparison`

for the alternative, <> also not supported :

`SyntaxError: invalid syntax`

Let say i have a column with 3 rows : 

`['A','B','C']`

How to exclude B?

**Comment by JovanVeljanoski** [comment]
Like this

```
import vaex
df = vaex.from_arrays(x=['A','B','C'])
df[~(df.x == 'B')]
```

**Comment by ramadhiantoagung** [comment]
Ah thank you, i dont know it could be done that way.

Cheers, Dhito
