### ISSUE TITLE
vaex.open(<folder*.hdf5") takes very long just to open 5 files

### ISSUE THREAD

**Issue by ashmpatel** [vaexio/vaex#604]
Opening multiple hdf5 files takes a very long time where as opening a single one takes milliseconds.
I had 7 files , each with 500k rows of data in hdf5. Opening one took 26ms, opening multiple ones using a wildcard took 7 mins !

**Comment by JovanVeljanoski** [comment]
hi @ashmpatel 

Thanks for the report. I can not reproduce this issue.. can you help me out a bit more please?
Can you tell me the contents of the file (data types, number of columns, missing values etc..)

Do all files have the same column names, data types, etc?

**Comment by ashmpatel** [comment]
The files have 658 columns. All files have the same columns and types. They come from the same data source.some colmns have null values but this is the same for all files.

**Comment by maartenbreddels** [comment]
Does vaex.open_many give you the same result?

**Comment by ashmpatel** [comment]
I'll try it tmrw and report back. 
Thx for looking into this.

**Comment by ashmpatel** [comment]
This happend when using open_many as well. I tried it with 2 files and it took very long - in the order of minutes. The files themselves are 3gig giles with 1/2millrows of data , 600+ columns

**Comment by JovanVeljanoski** [comment]
@ashmpatel 

Thanks for the report.  I will try to reproduce this issue locally and report back. 

Can I ask if the majority your data is numeric or otherwise? Also have you installed vaex via pip/conda-forge or from source?

Cheers

**Comment by ashmpatel** [comment]
The majority is numeric. I installed from conda-forge. Are there any instructions to run Vaex from source i.e not an installed version from conda-forge. So I can clone the repo and then use Vaex from the source code. I can then profile the app to see where it's taking a long time.

**Comment by JovanVeljanoski** [comment]
Hi @ashmpatel 

I was able to reproduce your issues. We will try to look into this. 
Thank you for the report.

Jovan

**Comment by ashmpatel** [comment]
Thank you for looking into it.

**Comment by maartenbreddels** [comment]
@JovanVeljanoski can you tell me how you reproduced this? This is instant for me for instance:
```
import vaex
fn1 = '/Users/maartenbreddels/datasets/nytaxi/nyc_taxi2015.hdf5'
fn2  = '/Users/maartenbreddels/datasets/nytaxi/nyc_taxi_all.hdf5'
df = vaex.open_many([fn1, fn2])
```

**Comment by JovanVeljanoski** [comment]
I think it may have to do with the large number of columns.. I've not tested this extensively. But creating similar data as described in the issue does cause a slowdown.. here is a reproducible example (@maartenbreddels ):

```
import vaex
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm
from sklearn.datasets import make_classification

# Create data
n_samples = 500_000
n_features = 650
n_files = 5

features = ['feat_' + str(i) for i in range(n_features)]
for i in tqdm(range(n_files)):

    X, y = make_classification(n_samples=n_samples, 
                               n_features=n_features, 
                               n_informative=50, 
                               n_redundant=30, 
                               n_repeated=20, 
                               n_classes=55,
                               scale=10_000)
    pdf = pd.DataFrame(data=X, columns=features)
    pdf['label'] = y
    df = vaex.from_pandas(pdf, copy_index=False)
    
    df.export_hdf5('/Users/jovan/Desktop/tmp-test-data/file_'+str(i)+'.hdf5', virtual=True)
    
    del df, pdf, X, y
```

After that you can try to open the data with `veax.open` or `vaex.open_many`, and you will experience the slowdown. Also, i noticed if you do this you get the slowdown:

```
df0 = vaex.open('/Users/jovan/Desktop/tmp-test-data/file_0.hdf5')   # This is instant
df1 = vaex.open('/Users/jovan/Desktop/tmp-test-data/file_1.hdf5')     # This is instant

df = vaex.concat([df0, df1])  # this takes minutes
```

I hope this helps.

**Comment by maartenbreddels** [comment]
Thanks all, it actually doesn't matter what the number of rows is, vaex is doing an inefficient comparison between all columns of 1 dataframe to all columns of the other dataframes, N*N scaling, which is bad.
We don't use vaex so often with many columns, but we should improve that!

**Comment by ashmpatel** [comment]
We use these tools for big data in an environment where we have lots of columns. Please let me know if/when this will be fixed. Thanks.

**Comment by maartenbreddels** [comment]
It will not be fixed very soon (as in a few days) but will be part of the next release for sure. We will keep this issue open till then, so you should get notified when we close/fix this.
