### ISSUE TITLE
csv file without header not supported

### ISSUE THREAD

**Issue by argenisleon** [vaexio/vaex#608]
Hi,
I am trying to load a CSV with no header  using

```
df = vaex.open('data/star0000-1.csv',sep=",", header=None, error_bad_lines=False)
```

but I get

```
could not convert column 0, error: TypeError('getattr(): attribute name must be string'), will try to convert it to string
Giving up column 0, error: TypeError('getattr(): attribute name must be string')
could not convert column 1, error: TypeError('getattr(): attribute name must be string'), will try to convert it to string
Giving up column 1, error: TypeError('getattr(): attribute name must be string')
could not convert column 2, error: TypeError('getattr(): attribute name must be string'), will try to convert it to string
Giving up column 2, error: TypeError('getattr(): attribute name must be string')
could not convert column 3, error: TypeError('getattr(): attribute name must be string'), will try to convert it to string
Giving up column 3, error: TypeError('getattr(): attribute name must be string')
could not convert column 4, error: TypeError('getattr(): attribute name must be string'), will try to convert it to string
Giving up column 4, error: TypeError('getattr(): attribute name must be string')
could not convert column 5, error: TypeError('getattr(): attribute name must be string'), will try to convert it to string
Giving up column 5, error: TypeError('getattr(): attribute name must be string')
could not convert column 6, error: TypeError('getattr(): attribute name must be string'), will try to convert it to string
Giving up column 6, error: TypeError('getattr(): attribute name must be string')
could not convert column 7, error: TypeError('getattr(): attribute name must be string'), will try to convert it to string
Giving up column 7, error: TypeError('getattr(): attribute name must be string')
could not convert column 8, error: TypeError('getattr(): attribute name must be string'), will try to convert it to string
Giving up column 8, error: TypeError('getattr(): attribute name must be string')
could not convert column 9, error: TypeError('getattr(): attribute name must be string'), will try to convert it to string
Giving up column 9, error: TypeError('getattr(): attribute name must be string')
could not convert column 10, error: TypeError('getattr(): attribute name must be string'), will try to convert it to string
Giving up column 10, error: TypeError('getattr(): attribute name must be string')
could not convert column 11, error: TypeError('getattr(): attribute name must be string'), will try to convert it to string
Giving up column 11, error: TypeError('getattr(): attribute name must be string')

```

Also it takes like 20x  the time to do nothing, any help?

**Comment by JovanVeljanoski** [comment]
Hi @argenisleon 

Can you read the same file with `pandas`? If so, can you try doing the same with `vaex` using
df = `vaex.read_csv(..)`. 

Cheers

**Comment by argenisleon** [comment]
I got the same error using ```vaex.read(...)```

The problem seems that pandas create integer column names 0,1,2,3...(not a string) when header= None.

I load the file using pandas, change the columns type to string and load the file to vaex.
```
pdf = pd.read_csv('data/HIGGS.csv',sep=",", header=None)
pdf.columns = list_columns_in_string_formar
df =vaex.from_pandas(pdf)
```


Maybe it should be elegant to accept header= None as a param?

**Comment by maartenbreddels** [comment]
Hi Argenis,

You can pass the argument `names`, which is passed down to pandas (I don't like that argument name though). Vaex indeed should take only string argument names.
I think we can do better with the error messages, lets keep this open till we fix this.


cheers,

Maarten

**Comment by raunaqjain** [comment]
May I try my hands on solving the issue? I would appreciate help along the way.

**Comment by maartenbreddels** [comment]
Yeah, you're very much welcome. I think the only thing that needs to happen is to cast the header values to strings, a test would be appreciated. If you have trouble setting up a dev env, let us know!

**Comment by raunaqjain** [comment]
It's my first time contributing to open source, so I don't know the "rules". I hope you can guide me on this.

1. Is this a good place for discussion or do you have a slack group?
2. Setting up a dev environment - Fork the repo, create a virtualenv, run setup.py
3. Issue a pull request (with work in progress). Sync the forked repo constantly and make my changes in a local branch.

Let me know if there's anything wrong in the process. Looking forward!

**Comment by maartenbreddels** [comment]
> It's my first time contributing to open source

Welcome :) feel free to make 'mistakes', nothing you do is irreversible, so no worries.

> * Is this a good place for discussion or do you have a slack group?

Yes, I prefer as much as possible github, or for quick chats https://gitter.im/maartenbreddels/vaex



> * Setting up a dev environment - Fork the repo, create a virtualenv, run setup.py

See for some info:
https://docs.vaex.io/en/latest/installing.html




> 3\. Issue a pull request

👍 

The workflow that I prefer regarding PR's is that you start with a unittest (I suggest adding something to `tests/csv_test.py`) and first make it fail. You can already push that and start with the PR, since that already communicates what you want to do.

You can then start working on the solution, and if you fail, you just push and ask for a review. We iterate till it works, we merge, and be happy :).

Dont worry about having a messy PR's with a lot of commits, I can clean that up for you, but if you are interested in that, I try to follow https://www.conventionalcommits.org/ . I usually end up with 1 commit per PR.

cheers,

Maarten

**Comment by JovanVeljanoski** [comment]
Hi @raunaqjain 

I just wanna add: once you finish with the dev install, it is a good practice to run the tests:

```
# From the vaex directory on your terminal/console run:
pytest tests/
```

That will tell you if everything is set up correctly.

**Comment by raunaqjain** [comment]
Oh, thanks. Didn't do that. 
However, now that I see, `pytest` was not installed in my virtualenv after I ran `pip install -e .` I did skip the `conda install -c conda-forge pcre` since I have pip as the package manager.

**Comment by maartenbreddels** [comment]
Yeah, it would be good to have `pip install -e ".[test]"` also install all test packages required, that's now undocumented.

**Comment by raunaqjain** [comment]
I tried that but it says 

>   WARNING: vaex-meta 0.1.0 does not provide the extra 'test'

Should I manually install the dependencies for pytest?

**Comment by maartenbreddels** [comment]
Sorry I wasn't more clear, I meant to say that we *should* do this.
`pip install pytest pytest-asyncio` should be enough I think (@JovanVeljanoski ?)

**Comment by JovanVeljanoski** [comment]
Yup that's it. If you don't install `pytest-asyncio` few tests will be skipped so no big deal for this PR. But better if you have everything just in case :)

**Comment by raunaqjain** [comment]
Got it. But now when I run `pytest tests/` it says I don't have vaex which seems logical. Do I have to build to install vaex or `pip install vaex` itself (this seems stupid?) 

Thanks for so much help guys

**Comment by JovanVeljanoski** [comment]
Hey @raunaqjain 

Just wondering how you are doing and if you've made any progress on this. 
For installation / and best practices you can always refer to the docs
https://docs.vaex.io/en/latest/installing.html#for-developers
(sorry for not sending you this earlier)

Note that you need to clone the repo and also get the submodules recursively (explained in the docs).

After that `pip install -e .` that should be it!

**Comment by raunaqjain** [comment]
I followed the steps and triple checked them. Running `pip install -e .`  executes the following:

```
Obtaining file:///Users/raunaq/Documents/repos/vaex
Requirement already satisfied: pip in ./venv/lib/python3.7/site-packages (from vaex-meta==0.1.0) (20.0.2)
Installing collected packages: vaex-meta
Running setup.py develop for vaex-meta
Successfully installed vaex-meta
```
When I run `pytest tests/` after install `pytest and pytest-asyncio`, I get the following error - 
```
ImportError while loading conftest '/Users/raunaq/Documents/repos/vaex/tests/conftest.py'.
tests/conftest.py:1: in <module>
    from common import *
tests/common.py:2: in <module>
    import vaex
E   ModuleNotFoundError: No module named 'vaex'
```

So, yeah I haven't made much progress.

**Comment by JovanVeljanoski** [comment]
Which OS are you running on?

**Comment by raunaqjain** [comment]
MacOs Catalina (version 10.15.3)

**Comment by mkst** [comment]
Is it good enough to simply `str()` the name if it's an int:

```py
def find_valid_name(name, used=[]):
    if isinstance(name, int):
        name = str(name)
    .. etc
```

Given the following csv:
```sh
$ cat headerless.csv 
John,3,
Tom,10,30.5
Kate,34,55.5
Ann,25,70
Lisa,40,50
```

```py
>>> import vaex
>>> df = vaex.read_csv('headerless.csv', sep=',', header=None)
>>> df
  #  0       1      2
  0  John    3  nan
  1  Tom    10   30.5
  2  Kate   34   55.5
  3  Ann    25   70
  4  Lisa   40   50
>>> df.columns
{'col_0': array(['John', 'Tom', 'Kate', 'Ann', 'Lisa'], dtype=object), 'col_1': array([ 3, 10, 34, 25, 40]), 'col_2': array([ nan, 30.5, 55.5, 70. , 50. ])}
```

which is what you'd get with a header'd csv with numeric columns:

```sh
$ cat headered.csv
1,2,3
John,3,
Tom,10,30.5
Kate,34,55.5
Ann,25,70
Lisa,40,50
```

```
>>> import vaex
>>> df = vaex.read_csv('headered.csv', sep=',')
>>> df
  #  1       2      3
  0  John    3  nan
  1  Tom    10   30.5
  2  Kate   34   55.5
  3  Ann    25   70
  4  Lisa   40   50
>>> df.columns
{'col_1': array(['John', 'Tom', 'Kate', 'Ann', 'Lisa'], dtype=object), 'col_2': array([ 3, 10, 34, 25, 40]), 'col_3': array([ nan, 30.5, 55.5, 70. , 50. ])}
```

If so I'll attempt a PR... I too am finding it a struggle to get a dev environment up and running though!
