### ISSUE TITLE
Vaex use GPUs?

### ISSUE THREAD

**Issue by argenisleon** [vaexio/vaex#613]
Hi,

it's not clear in the docs if vaex use GPUs for core functions.  It seems that I can write UDF and use ```jit_cuda()``` to use NVIDIA GPUs. But is it vaex using or can use GPUs?

**Comment by maartenbreddels** [comment]
Hi Argenis,

yes, good question. Vaex currently only has support for UDFs/virtual columns using the GPU, via jit_cuda. If this function call succeeds, it will do it all on the GPU, of there are missing functions (like the string functions are not implemented on the GPU), you will get an error.
Does this answer your question?
@JovanVeljanoski something for the FAQ?
Note that Jovan recently tweeted about this: https://twitter.com/JovanVaex/status/1228015803292934144

Regards,

Maarten

**Comment by argenisleon** [comment]
yes @maartenbreddels, Thanks

**Comment by KestutisMa** [comment]
Maybe support of Vulkan compute shaders could make GPU support more general?

**Comment by maartenbreddels** [comment]
See also https://github.com/vaexio/vaex/pull/584
