### ISSUE TITLE
Reading the Fannie Mae CSV is really slow with Vaex

### ISSUE THREAD

**Issue by xiaodaigh** [vaexio/vaex#619]
I tried to read the CSV from https://rapidsai.github.io/demos/datasets/mortgage-data.

I only download the 1 year data, and it took 10 mins to read, but pandas only takes about 16s.

I have prepared the docker here

https://github.com/xiaodaigh/disk.frame-vs

Just navigate to `notebooks/vaex.ipynb` once you have started the jupyter notebook and run to replicate.

**Comment by JovanVeljanoski** [comment]
Hi @xiaodaigh 

Thank you for bringing this up, and for the nice reproducible example. 
We are aware of such issues and work was already started at #612 . 

We hope to have this resolved soon.

**Comment by JovanVeljanoski** [comment]
Hi @xiaodaigh 

#612 was merged to master, which handled the issue you are describing, so I will close this. Please feel free to test if you can install vaex from source. Our benchmarks showed significant improvement.  Otherwise it will be part of the next release!

Cheers!

**Comment by maartenbreddels** [comment]
@byaminov might be able to squeeze a bit more out of it.

**Comment by byaminov** [comment]
squeezed a little bit more: #623
