### ISSUE TITLE
vaex-ui not working

### ISSUE THREAD

**Issue by mfouesneau** [vaexio/vaex#624]
from a fresh installation running only a demo dataset, the UI breaks with class attribute errors and/or key error (the latter when reading a file from disk)

**Comment by maartenbreddels** [comment]
I'm afraid from v3 we will deprecate vaex-ui, since we are focussing more on the web based (widget) part for the interactive part, so I'm not surprised master will not work, but we should update the docs etc on this.

Unless you, or some other party wants to help to maintain that. I'm open to ideas.

**Comment by mfouesneau** [comment]
Can you point me towards the selection features etc from the widget? I was not able to run the widget properly so far and one feature that I cannot reproduce is having multiple panels and the lasso selection

**Comment by maartenbreddels** [comment]
I've been wanting that for ages actually (well, before I left astronomy). It is still on my wish list, and I think I can get this in bqplot fairly soon.

**Comment by mfouesneau** [comment]
This kind of selection was the big advantage of the UI. I have to admit that it is sad to not have any replacement.

**Comment by maartenbreddels** [comment]
It will happen, that's what I am saying.

**Comment by mfouesneau** [comment]
A minimal update made it work again. I made the pull request https://github.com/vaexio/vaex/pull/643

which seems to hang on the last test, but works on my mac.

**Comment by JovanVeljanoski** [comment]
# Closed via #643
