### ISSUE TITLE
show DLL load failed: 找不到指定的模块。

### ISSUE THREAD

**Issue by zhangao4833** [vaexio/vaex#630]
from .superstrings import *

ImportError: DLL load failed: 找不到指定的模块。

**Comment by maartenbreddels** [comment]
Hi,

thanks for the report. Could you try putting the attached dll's to the directory:
```
c:\Python36\lib\site-packages\vaex\
```
Or where your directory is containing superstrings.pyd / superstrings.cp36-win_amd64.pyd
[pcre-dlls.zip](https://github.com/vaexio/vaex/files/4292442/pcre-dlls.zip)
You might be able to place them in the directory where you run the Python code from as well.

Regards,

Maarten

**Comment by zhangao4833** [comment]
Thanks,  Try your way for python 3.6 ENV, show Import Error numpy.core.xxxx, but update python for 3.7 and numpy 1.16.5, It's normal after you use it in your way , 
I hope that the specific version of the running environment can be provided in the future update

**Comment by maartenbreddels** [comment]
That's good to hear, yes, I just noticed that myself, some older numpy versions don't work. We'll create a new release including these dll's.

**Comment by ziliangok** [comment]
> Hi,
> 
> thanks for the report. Could you try putting the attached dll's to the directory:
> 
> ```
> c:\Python36\lib\site-packages\vaex\
> ```
> 
> Or where your directory is containing superstrings.pyd / superstrings.cp36-win_amd64.pyd
> [pcre-dlls.zip](https://github.com/vaexio/vaex/files/4292442/pcre-dlls.zip)
> You might be able to place them in the directory where you run the Python code from as well.
> 
> Regards,
> 
> Maarten

Great

**Comment by Code4SAFrankie** [comment]
After putting the dlls in the specified directory the error changed to:

```
>>> import vaex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\vaex\__init__.py", line 39, in <module>
    import vaex.dataframe
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\vaex\dataframe.py", line 28, in <module>
    import vaex.promise
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\vaex\promise.py", line 5, in <module>
    import aplus
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\aplus\__init__.py", line 452, in <module>
    import gevent
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\gevent\__init__.py", line 86, in <module>
    from gevent._config import config
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\gevent\_config.py", line 699, in <module>
    Loop().get()
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\gevent\_config.py", line 146, in get
    self.value = self.validate(self._default())
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\gevent\_config.py", line 248, in validate
    return self._import_one_of([self.shortname_map.get(x, x) for x in value])
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\gevent\_config.py", line 219, in _import_one_of
    return self._import_one(item)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\gevent\_config.py", line 237, in _import_one
    module = importlib.import_module(module)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\gevent\libuv\loop.py", line 51, in <module>
    ('python_queue_callback', None)])
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\gevent\_ffi\loop.py", line 297, in assign_standard_callbacks
    callback = ffi.def_extern(onerror=error_func)(func)
MemoryError
>>>             
```

I am on Windows 10 running WinPython 3.7.1 64 bit. I have 32Gb of memory of which only 38% is used. I only did an `import vaex`

**Comment by Gil-Frenkel** [comment]
Thank @maartenbreddels ,

Copied the .DLL files to the Vaex directory and it worked for me on Windows 10, Python 3.7.6 and NumPy 1.18.1.

Thanks!

**Comment by xfzhu** [comment]
> Hi,
> 
> thanks for the report. Could you try putting the attached dll's to the directory:
> 
> ```
> c:\Python36\lib\site-packages\vaex\
> ```
> 
> Or where your directory is containing superstrings.pyd / superstrings.cp36-win_amd64.pyd
> [pcre-dlls.zip](https://github.com/vaexio/vaex/files/4292442/pcre-dlls.zip)
> You might be able to place them in the directory where you run the Python code from as well.
> 
> Regards,
> 
> Maarten

It works for me on Windows 10, Python 3.6.0, vaex 2.6.1 and Numpy 1.18.1. Thank you so much!

**Comment by ouening** [comment]
> Hi,
> 
> thanks for the report. Could you try putting the attached dll's to the directory:
> 
> ```
> c:\Python36\lib\site-packages\vaex\
> ```
> 
> Or where your directory is containing superstrings.pyd / superstrings.cp36-win_amd64.pyd
> [pcre-dlls.zip](https://github.com/vaexio/vaex/files/4292442/pcre-dlls.zip)
> You might be able to place them in the directory where you run the Python code from as well.
> 
> Regards,
> 
> Maarten

It works for me in Win10, python3.7.4, vaex:'1.0.0-beta.6' , numpy1.18.1

**Comment by SaidSultani** [comment]
> 
> 
> Hi,
> 
> thanks for the report. Could you try putting the attached dll's to the directory:
> 
> ```
> c:\Python36\lib\site-packages\vaex\
> ```
> 
> Or where your directory is containing superstrings.pyd / superstrings.cp36-win_amd64.pyd
> [pcre-dlls.zip](https://github.com/vaexio/vaex/files/4292442/pcre-dlls.zip)
> You might be able to place them in the directory where you run the Python code from as well.
> 
> Regards,
> 
> Maarten

FIXED, thank you very much!
I will experiment with your awesome VAEX now :)

**Comment by saharsh93** [comment]
Hi,
I am getting the error even after pasting the DLL files. I have the following:

superstrings.cp37-win_amd64
python 3.7.7
Vaex 2.6.1
Numpy 1.18.2

Thanks for your help.
Saharsh

**Comment by maartenbreddels** [comment]
Which error, and what did you do exactly?

(from mobile phone)

**Comment by saharsh93** [comment]
Sorry, I mean the same error which is the topic of this thread:

import vaex 

leads to

 from .superstrings import *
ImportError: DLL load failed: The specified module could not be found.

Thanks for your help!

**Comment by maartenbreddels** [comment]
The latest release vaex==3 or vaex-core==2 should work 🎉 if not, please reopen. cheers, and thanks for you patience.
