### ISSUE TITLE
readme: machine learning link does not work

### ISSUE THREAD

**Issue by arm2arm** [vaexio/vaex#635]
If you follow https://github.com/vaexio/vaex in the vaex-ml part of the text the Machine  Learning link does not exist or moved.

**Comment by JovanVeljanoski** [comment]
Hi @arm2arm 

Indeed, the link has changed. Thank you for catching that, we will try to update it shortly. 
In the meantime, [this is the correct link](https://docs.vaex.io/en/latest/tutorial_ml.html).

Cheers!

**Comment by JovanVeljanoski** [comment]
It should be working now. Thanks!
