### ISSUE TITLE
AttributeError: 'TextFileReader' object has no attribute 'columns'

### ISSUE THREAD

**Issue by fjibj** [vaexio/vaex#641]
my code as:
for i, chunk in enumerate(vaex.read_csv('data_V1.csv', chunksize=100_000)):
    df_chunk = vaex.from_pandas(chunk, copy_index=False)
    export_path = f'part_{i}.hdf5'
    df_chunk.export_hdf5(export_path)

and get errors:
INFO:MainThread:matplotlib.font_manager:generated new fontManager
Traceback (most recent call last):
  File "csv2hdf5.py", line 3, in <module>
    for i, chunk in enumerate(vaex.read_csv('train/data_V1.csv', chunksize=100_000)):
  File "/opt/conda/envs/py3/lib/python3.6/site-packages/vaex/__init__.py", line 491, in read_csv
    return from_csv(filepath_or_buffer, **kwargs)
  File "/opt/conda/envs/py3/lib/python3.6/site-packages/vaex/__init__.py", line 486, in from_csv
    return from_pandas(pd.read_csv(filename_or_buffer, **kwargs), copy_index=copy_index)
  File "/opt/conda/envs/py3/lib/python3.6/site-packages/vaex/__init__.py", line 412, in from_pandas
    for name in df.columns:
AttributeError: 'TextFileReader' object has no attribute 'columns'

**Comment by JovanVeljanoski** [comment]
Hi @fjibj 

Normally the `.read_csv` method returns a pandas DataFrame, but when `chunksize` is set, a `TextFileReader` object is returned which is iterated over. So you can not (for now) use it in the way you suggest above. 

The fix is simple, just use 
```
for i, chunk in enumerate(pd.read_csv('data_V1.csv', chunksize=100_000)):
```
the rest of the code is unchanged. 

Note that `vaex.read_csv` is simply `vaex.from_pandas(pd.read_csv(file, **kwargs), copy_index=copy_index)`. 

I hope this helps!
J.

**Comment by heyuqi1970** [comment]
THX, I have solved problem with  pd.read_csv

**Comment by Sebastiaan-Alvarez-Rodriguez** [comment]
Hi, I experience the same problems as described in this issue.
If I decide to use:
```python
for i, df in enumerate(vaex.from_csv('h.csv_small', chunk_size=100_000)):
    pass
```
(note the equivalence with the official `vaex` documentation [here](https://vaex.readthedocs.io/en/latest/api.html#vaex.from_csv))
I get a 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/no_u/.local/lib/python3.6/site-packages/vaex/__init__.py", line 486, in from_csv
    return from_pandas(pd.read_csv(filename_or_buffer, **kwargs), copy_index=copy_index)
TypeError: parser_f() got an unexpected keyword argument 'chunk_size'
```
When checking out `pandas.read_csv()` [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html), we see there is indeed no argument `chunk_size`. There is, however, a `chunksize`. When using that, we get the AttributeError described in this post.

I'd like to note here that I installed `vaex` using `pip3 install vaex --user`.

So, either `vaex` cannot handle reading from csv's in a chunk by chunk manner, or I did something wrong here.

Any ideas what the problem might be?

For now, I guess I will just not read in in chunks and consume large amounts of memory on my university cluster.

**Comment by JovanVeljanoski** [comment]
Hi @Sebastiaan-Alvarez-Rodriguez 

While vaex uses pandas for reading CSV files, the `vaex.read_csv` and `pandas.read_csv` are a bit different. So you are reading pandas docs, but using vaex.. 

I suspect what you want is:
```
df = vaex.read_csv('some_big_file.csv', chunk_size=5_000_000, convert=True)
```
This will read the CSV in chunks, export each chunk into an hdf5 file, than merge all the hdf5 files into a single file and clean up. That why you work with all your data in an out-of-core manner. 

If you do not specify `convert=True`,  than `vaex.read_csv('some_file.csv', chunk_size=100_000)` will be a generator, yielding a portion of the dataframe.  

This is all in master, and not yet released however. It should be released over the next 1-2 weeks at latest. 

In the meantime, you can look at the [FAQ section where this is addressed](https://docs.vaex.io/en/latest/faq.html)
