### ISSUE TITLE
Subset of Data Ingested with Partitioned Parquet Files via Arrow

### ISSUE THREAD

**Issue by iainwo** [vaexio/vaex#645]
## Source
https://github.com/vaexio/vaex/blob/d500e903b92c572123e95b310267647d32482a63/packages/vaex-arrow/vaex_arrow/dataset.py#L45

## Problem
Only a subset of the Arrow table data is ingested into vaex dataframes when calling `vaex.from_arrow_table(table)`

## Description
When converting a PyArrow ParquetDataset to a PyArrow table, the table will be comprised of chunks. When importing the chunked PyArrow table into vaex only a subset of data will be imported into the vaex dataframe. This will break the vaex dataframe object because it makes assertions between the arrow metadata and imported subset of vaex data; which yields contradictions because the arrow metadata references the entirety of the arrow tables chunks.

## Solution
Arrow chunks should be concatenated on import.

## Temporary Workaround
For now you can unify all the partition parquet files (parquet dataset) into a single parquet which forms a single arrow chunk.

**Comment by maartenbreddels** [comment]
Thanks for the clear report!

This should be solved once https://github.com/vaexio/vaex/pull/517 gets in, but it may take a while to be honest.

**Comment by iainwo** [comment]
@maartenbreddels awesome sauce

**Comment by majidaldo** [comment]
@iainwo , how did you join the chunks? 
also #834

**Comment by maartenbreddels** [comment]
This should now work, to install:
```
$ pip install "vaex-core>=4.0.0a11"
# or for the while kitchsink:
$ pip install "vaex>=4.0.0a6"
```
