### ISSUE TITLE
Failed import : ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by gopel** [vaexio/vaex#647]
Hi,   
I recently downloaded vaex using pip, but I stumble upon an error when I try to import it : `ImportError: numpy.core.multiarray failed to import` (see details below). I have no such problem when I try to import numpy, which is why I post here.  
So far, I tried to upgrade pip, upgrade numpy, downgrade numpy, uninstall all instances of numpy and reinstall it, but with no luck. I have the last version of vaex and numpy installed. I saw workarounds with conda virtual environments on the Internet, but I don't have access to Anaconda on the machine (or at least the command "conda" does not work). I work on a remote server on which I have no sudo right.  
Could you help me please?

ModuleNotFoundError                       Traceback (most recent call last)
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-29-d77a49405cf5> in <module>
     15 # Object
     16 import pandas as pd
---> 17 import vaex
     18 import collections
     19 from collections import defaultdict

~/.local/lib64/python3.6/site-packages/vaex/__init__.py in <module>
     37 import six
     38 
---> 39 import vaex.dataframe
     40 import vaex.dataset
     41 from vaex.functions import register_function

~/.local/lib64/python3.6/site-packages/vaex/dataframe.py in <module>
     24 import vaex.events
     25 # import vaex.ui.undo
---> 26 import vaex.grids
     27 import vaex.multithreading
     28 import vaex.promise

~/.local/lib64/python3.6/site-packages/vaex/grids.py in <module>
      1 __author__ = 'maartenbreddels'
      2 import numpy as np
----> 3 import vaex.vaexfast
      4 from vaex.utils import filesize_format
      5 import logging

ImportError: numpy.core.multiarray failed to import

**Comment by anubhav-nd** [comment]
Hi @gopel 

I was also getting this error once but upgrading to `numpy 1.17.4` resolved it. I have had no problems even with` numpy 1.18.x series`.

Could you try with `virtualenv`. Maybe it is picking some old version of numpy.

**Comment by gopel** [comment]
Hi,   
Thank you for your help.  
I typed `python -c "import numpy;print(numpy.__version__);print(numpy.__file__)"; ` and received 1.18.2.  
Is it `virtualenv` ?

**Comment by anubhav-nd** [comment]
`virtualenv` is a way to have a completely independent environment for running python on our system. That way we can be sure that some package is not being referenced from some unintended location. 

You can find more information here: `https://docs.python-guide.org/dev/virtualenvs/`

**Comment by gopel** [comment]
Hi,

Due to the Covid19 outbreak, I had to change the computer I used to connect to the server, and the problem disappeared.
If I can access the old computer (after the crisis), I can try to get more info ?

Best regards,

**Comment by JovanVeljanoski** [comment]
I will close this as stale - please open if needed.

**Comment by maartenbreddels** [comment]
> I was also getting this error once but upgrading to `numpy 1.17.4`

I think indeed we should specify a minimum version for numpy, I've had to upgrade numpy when running vaex on google colab as well.
