### ISSUE TITLE
Inner with zero intersection set throws value error

### ISSUE THREAD

**Issue by hewa55** [vaexio/vaex#649]
Hello,

first of all, thanks a lot for creating vaex, it has helped me a lot so far and really increased speed of my projects. 

I came across the following - which might be known, but I couldn't find anything online: 
When performing an inner join on two vaex dataframes when they do not have an intersection, I get a `ValueError: zero-size array to reduction operation maximum which has no identity`.

A minimum example is below:
```
import vaex
import pandas as pd

t1 = pd.DataFrame({"a":[1,2],"c":["one","two"]})
t2 = pd.DataFrame({"b":[1,5],"d":[3,5]})

t1 =vaex.from_pandas(t1, copy_index=False)
t2= vaex.from_pandas(t2, copy_index=False)

print(t1.join(t2, left_on="a",right_on="b", how="inner"))
print(t1.join(t2, left_on="a",right_on="d", how="inner"))
```

The full traceback is:

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    print(t1.join(t2, left_on="a",right_on="d", how="inner"))
  File "/home/me/venv/lib64/python3.7/site-packages/vaex/dataframe.py", line 5518, in join
    left = left.take(left_indices_matched, filtered=False, dropfilter=False)
  File "/home/me/venv/lib64/python3.7/site-packages/vaex/dataframe.py", line 3852, in take
    df.columns[name] = ColumnIndexed.index(df_trimmed, column, name, indices, direct_indices_map)
  File "/home/me/venv/lib64/python3.7/site-packages/vaex/column.py", line 102, in index
    return ColumnIndexed(df, indices, name)
  File "/home/me/venv/lib64/python3.7/site-packages/vaex/column.py", line 76, in __init__
    max_index = self.indices.max()
  File "/home/me/venv/lib64/python3.7/site-packages/numpy/core/_methods.py", line 30, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity

I have the feeling a more natural response would be to return an empty dataframe. 
Let me know what you think. 
Thanks

**Comment by JovanVeljanoski** [comment]
Hi @hewa55 

Thanks for the issue.

This is actually fixed in master, and will be available in the next release. 

Cheers, 
J.
