### ISSUE TITLE
get_column_names(regex → df.get_column_names(prefix

### ISSUE THREAD

**Issue by xdssio** [vaexio/vaex#650]
in the _get_column_names_ function, the argument "regex" act only as a prefix.

Options 1: make it works like regex.
Option 2: rename it to prefix

**Comment by JovanVeljanoski** [comment]
Hey, 

Maybe you are confusing "regex" with "glob" expressions, I do that a lot also. 
The "regex" keyword in `get_column_names` acts as true regex, not as prefix. For example:

```
import vaex
df = vaex.from_arrays(aa_x = [1, 2, 3], bb_x=[10, 20, 30], cc_z=['a', 'b', 'cc'])
df.get_column_names(regex='.*x$')
```
returns
`['aa_x', 'bb_x']`

Cheers, 
J.

**Comment by JovanVeljanoski** [comment]
I will close this, please re-open if you can find a reproducible issues with the regex.
