### ISSUE TITLE
Cant plot lineplot

### ISSUE THREAD

**Issue by Alsen57** [vaexio/vaex#653]
Hi i have the problem that i cannot plot a line. I dont know if that is implemented. 
I would like to achieve something like that here: 

[https://matplotlib.org/3.1.0/gallery/lines_bars_and_markers/simple_plot.html#sphx-glr-gallery-lines-bars-and-markers-simple-plot-py](url)

I have a pandas dataframe which i am turning into a vaex dataframe through the from_pandas function.
Then  i tried  df.plot1d("A") to acces the A column. but when i plot it, it plots a histogram instead of a line. which should contain 100mio datapoints at the x axis and the value at the y axis.

**Comment by JovanVeljanoski** [comment]
Hi @Alsen57 

Indeed, we do not have a wrapper for making a line plot straight from the DataFrame object. The main idea behind vaex is to use to anayse and visualise 100s of millions of sample (or more!). Plotting 100s of millions of points (in a scatter or line plots) is not really practical, and might be quite slow. Maybe you have a good reason for asking this, can you please share your usecase?

Instead you can just use matplotlib in the usual way to plot anything you want, for instance:
```
import vaex
import numpy as np
import pylab as plt

x = np.arange(0, 100)
y = np.random.random_sample(size=100)

df = vaex.from_arrays(x=x, y=y)

plt.plot(df.x.values, df.y.values)
plt.show()
```

Note that the above example will require putting `df.x` and `df.y` in memory (which should not be a problem since you stated that your data is already in memory).

In the near future `df.plot` and `df.plot1d` will be renamed to `heatmap` and `histogram` to alleviate any confusion. 

I hope this helps.

**Comment by Alsen57** [comment]
Hi @JovanVeljanoski 

thanks for the fast response.  I am working in the area of data science for manufacturing industries. There we have a lot of sensor data for with sensor having a samplerate sometimes of several MHz, for the purpose of getting knowledge of the underlying process for example in production when a failure accures but the machine is still running it could be possible to see the failure in the sensor data and compare it to well run processes. For this case it is necessary to plot 1d data over time and see the impact of the circumstances in the data. Dont you think there could be any possibility to enable that in vaex? It seems to run quiet fast.

**Comment by DougRzz** [comment]
@Alsen57 Vaex can be very quick as a calculation engine for time-series data processing which could then be visualised interactively in your own custom plotting application. You could easily interactively visualise 30 minutes worth of 1MHz data.!  You would need to downsample the data using the mean/min/max aggregators. I did an example notebook showing simple time-series processing using Vaex.   https://github.com/DougRzz/Vaex-demo-notebook .  It might give you some clues on how to do it.  

Its also might be worth looking into Jupyter-Glue to plot your Vaex processed data. That tool would potentially be useful for visually comparing good vs bad machines.     

However, I'm not sure how you would do live streaming data in Vaex.   Vaex is not the tool really suited to do that.    But perhaps, you could use Vaex to interactively explore your historical data and then use that to help you develop algorithms to flag sensor failure.

**Comment by JovanVeljanoski** [comment]
Hi @Alsen57 

Thanks for the clarification. Your usecase makes sense. Although when you say "enable that in vaex", there is nothing really to enable.. let me explain:

Vaex is (primarily) geared towards analysis, exploration, viz of big-ish data. This is often done by looking at various aggregate statistics: 0d (mean, std, mean, min, max, etc.),  1d (histograms), 2d(heatmap), or N-d if needed. Vaex is super fast when computing that. Not only fast, but the data is super-compressed after that. Image you have 1 billion points, and from that you calculate 512 x 512 heatmap. Vaex can do that in the second, and the resulting heatmap would take less than peanuts in memory. 

So once you have a histogram or heatmap computed , we send that data to be drawn by matplotlib (and provide convenience) methods to do that. Note that this is a bit different to doing for example, `plt.hist` or `plt.imshow`. In those cases, the raw data is aggregated by numpy, and than drawn by matplotlib. While numpy is fast in its own right, vaex is just on another level, and can do out-of-core computations. 

Ok, so when you do a scatter or a line plot, no prior calculations/transformations are taking place, so there is nothing for vaex to do, other than to pass the data to matplotlib "as is".  Hence the above code that I posted in my previous reply.

Having said that, if you are looking for just a shortcut, or a convenience method to speed up your exploration, and reduce the coding you have to do, I would suggest writing you own Vaex extension for this. You can [look at the example here](https://docs.vaex.io/en/latest/tutorial.html#Adding-DataFrame-accessors)

It would look like something like this. 
(assume you work for a company called.. "axon", and you wanna build a set of methods are just for you, and just for your field).

In the following example, we will just wrap `plt.plot` so you can use it straight from vaex. Again, vaex does nothing here, just passes the data to matplotlib...

```
@vaex.register_dataframe_accessor('axon', override=True)
class AxonStuff(object):
    def __init__(self, df):
        self.df = df

    def lineplot(self, x, y, selection=None, xlabel=None, ylabel=None, title=None, **kwargs):
        x = vaex.utils._ensure_strings_from_expressions(x)
        y = vaex.utils._ensure_strings_from_expressions(y)
        x_values = self.evaluate(x, selection=selection)
        y_values = self.evaluate(y, selection=selection)
        
        plt.xlabel(xlabel or self.label(x))
        plt.ylabel(ylabel or self.label(y))
        plt.title(title)

        return plt.plot(x_values, y_values,  xerr=xerr_values, **kwargs)

# Than use this like
df.axon.lineplot('x', 'y', selection='x>5')
```

I have not tested the above code, but should be some like that.
The reason I am spending time explaining this, is that often we all have specific uses, or want different convenience methods that may not be a good idea to enter into the main product. But this way you can write as many functions/methods that are specific to your needs and use-cases, while taking full advantage of vaex. 

I hope this helps!

P.S.: @DougRzz While what you say is technically correct, it is possible that downsampling may not always be recommended, as it might smooth over some aspect of the signal that they want to investigate. I guess it depends on the nature of the signal, etc.. So sometimes, just line plots are the way to go..

**Comment by maartenbreddels** [comment]
@DougRzz I was thinking of your work as well, I think you should advertise it more, or vaex should have support for what you are making :)

![](https://raw.githubusercontent.com/DougRzz/Vaex-demo-notebook/master/demo.gif)

I think it can be useful to plot things like mean/min/max/std for timeseries, to get an idea about the distribution and outliers etc.

**Comment by DougRzz** [comment]
Screencast of Vaex, BQplot & Voila.....
![timeseriesVaexExample](https://user-images.githubusercontent.com/3510318/77767266-b677b780-7038-11ea-8e01-bc6f516174c9.gif)

So I use Vaex to downsample points 'on-the-fly'. It is not possible to plot 500 million data points on a line plot so it has to be aggregated somehow.  If I plot the mean, min and max binned against time, I can see trends and outliers.  Also, I can interactively zoom into the data (with a fixed number of bins).  Eventually, with enough 'zooming-in',  you can visualise the original raw data.  At the same time, I can create histograms and 2D heatmaps.  When I couple this to the Vaex filtering/selection capabilities, this is really powerful.  IMO, Big time series interactive analysis is potentially Vaex's biggest potential use cases/market.  And yes, I should publicise this work.   A poster (or talk:fearful:) at JupyterCon 2020 in Berlin would be nice.

**Comment by JovanVeljanoski** [comment]
@DougRzz Wow that is incredible. Fantastic work!

Do you know what is happening to JupyterCon, is it going forward given the situation? Bunch of other events are push postponed for next year, given the global situation we are in.

As for time-series analysis, I agree, vaex can be an excellent tool for it. We are a bit weak in that point I must admit, but it would be great if we can offer more features in that domain (cumulative functions, rolling window functions, the works).

Really cool stuff!

**Comment by JovanVeljanoski** [comment]
@DougRzz btw if JupyterCon does go forward, and you give vaex-centric talk there (or elsewhere for the matter), and you need some help/advice in the preparation, please reach out :)

**Comment by Alsen57** [comment]
@JovanVeljanoski 
So for example for time series data which is quite long for example 100mio. I could calculate the mean in bins of two datapoints and could plot this against the time doing the same procedure for the time data?
So the data would be used by vaex to bin it and therefore the plotting would be much faster or i am misunderstanding it?

i will check the provided code above.

@DougRzz 
Thanks for the code i will check it and try to adapt it to my use case.
Cool work you did there! Very impressive. May i ask in which branch you are working.

**Comment by JovanVeljanoski** [comment]
@Alsen57 
Yes, you can calculate the mean (or other statistic of interest, std, max etc..) for some resolution interval, and plot that. That is where vaex shines and what it was made for, and that is indeed what @DougRzz has been suggesting.

**Comment by DougRzz** [comment]
@JovanVeljanoski  Thanks.  But all the clever stuff is done by you guys.  I just piece it together for my use-case.   

If it is still lockdown in August, then there won't be many of us in paid work.  Best to assume JupyterCon is going ahead.

@Alsen57 Use Vaex as the calculation engine (and maybe the plotting tools too if you want to).  It is very fast at aggregating big tabular data. So fast, it enables you to aggregate big data on the fly.  You don't have to preempt what you think you will want to visualise and no storing processed data is required.  
My branch .....Industrial diesel engines development.  Emission compliance means the time series data analysis is quite a challenge.

**Comment by Alsen57** [comment]
@JovanVeljanoski 
Would it still be possible if the remaining data is still very long like when i have raw dataset of 100mio. and do the mean calculation of two datapoints through vaex and binning it so that i have 50mio data points in each column/array and plot that?

@DougRzz  
Sounds cool, so you are working in mechanical engineering area. Im student in that field and i am currently writing my master thesis in predictive maintenance for production chains.

**Comment by DougRzz** [comment]
@Alsen57 Plotting 50 million data points is not possible.  Even if you had an amazing graphics card to do that, it won't be useful because your monitor or retina will not be able render it.   Instead, if you find the mean, min and max (plot three lines) with each bin consisting of 100,000 sample chunks, then you would have 500 points for each of 3 lines to plot.  Much more manageable and easier to interpret.

**Comment by Alsen57** [comment]
@DougRzz 
what is the restriction of the length of the bins? Would it be possible to have many bins with small sample chunks for getting the highest possible resolution?

**Comment by maartenbreddels** [comment]
There isn't really a restriction I guess, you could easily do 10.000 bins, but given a resolution of a few thousand pixels, it doesn't make sense to go much about 1000 or 2000 right?
