### ISSUE TITLE
Jupyter with Vaex index column with css

### ISSUE THREAD

**Issue by willsilvano** [vaexio/vaex#656]
When I print vaex dataframe the index colomun # show CSS style:

![image](https://user-images.githubusercontent.com/7406991/77865763-677f7d00-7206-11ea-8df6-9f31dd653575.png)

Is it a Jupyter bug?

**Comment by maartenbreddels** [comment]
That is super weird, can you give me the version number of notebook or lab?

**Comment by limo1213** [comment]
I had the same problem. Jupyterlab version is 1.2.7.

**Comment by willsilvano** [comment]
The version of the notebook server is: 6.0.3
