### ISSUE TITLE
Dataframe subset with zero eligible rows throws error

### ISSUE THREAD

**Issue by gkovaig** [vaexio/vaex#657]
df_negative = df[df.x < 0] works fine if df.x < 0 has one or more eligible rows
If there are no rows that qualify, then get "RuntimeError: end index should be larger or equal to start index"

**Comment by JovanVeljanoski** [comment]
Hi @gkovaig 

Thanks for the report. This is actually fixed in master, and it will be available in the next release.

Cheers
