### ISSUE TITLE
Trouble following this tutorial https://nbviewer.jupyter.org/github/vaexio/vaex-examples/blob/master/medium-airline-data-eda/airline-original-data-conversion.ipynb

### ISSUE THREAD

**Issue by GoFast94** [vaexio/vaex#658]
(The link in the title : https://nbviewer.jupyter.org/github/vaexio/vaex-examples/blob/master/medium-airline-data-eda/airline-original-data-conversion.ipynb )

Hi,

I have a large dataset and was very glad to stumble upon vaex to help me work on it, as I am still new to python and it seemed very efficient and relatively close to pandas.

My dataset is about 1945 csv files, each comprise of 5-6 columns and from a few rows to more than 1million rows. It is about 23Go compressed (.gz) and about 70Go once it is extracted. The link I posted explains how to work with files that are in the .zip format but not with the .gz. I was wondering if it was possible or if I had to convert them all. 

Anyways I extracted them all and tried to work with the csv files directly, so I skipped a bit of the code but I encountered other problems. 

Here is the tutorial code

```
# Set up the list of zip files to be opened and converted
zip_list = np.sort(np.array(glob.glob('./airlines-us-original/raw/*.zip')))[::-1]

# The output directory
output_dir = './airlines-us-original/hdf5/'
```

And here is what I did 

```
# Set up the list of zip files to be opened and converted
zip_list = np.sort(np.array(glob.glob('E:/Data/Trades/*')))[::-1]

# The output directory
output_dir = 'C:/Users/Sam/Desktop/Data/Stocks/hdf5/'
```

It is not really explained what the output_dir variable does, so I am not sure what to put there. Shall I create a hdf5 folder or is it going to create one by running this code ?

Then I ran this code : 

```
# The magic happens here:
for file in tqdm(zip_list, leave=False, desc='Converting to hdf5...'):
    # Setting up the files, and directories
    zip_file = ZipFile(file)
    output_file = file.split('/')[-1][:-3]+'hdf5'
    output = output_dir + output_file
    
    # Check if a converted file already exists: if it does skip it, otherwise read in the raw csv and convert it
    if (os.path.exists(output) and os.path.isfile(output)):
        pass
    else:
        # Importing the data into pandas 
        pandas_df = [pd.read_csv(zip_file.open(text_file.filename), 
                                 encoding='latin',
                                 usecols=columns,
                                 dtype=dtypes,)
                     for text_file in zip_file.infolist()
                     if text_file.filename.endswith('.csv')][0]
        # Rename some columns to match the more well known dataset from 
        # http://stat-computing.org/dataexpo/2009/the-data.html
        pandas_df.rename(columns=rename_dict, inplace=True)

        # Importing the data from pandas to vaex
        vaex_df = vaex.from_pandas(pandas_df, copy_index=False)
        
        # Export the data with vaex to hdf5
        vaex_df.export_hdf5(path=output, progress=False)
```

I didn't understand everything it does, again I am not sure I am suppose to run it like this when working with csv and not .zip files but I worked without an error.

Finally when I ran this : 

```
# This is an important step
master_df = vaex.open_many(hdf5_list)

# exporting
master_df.export_hdf5(path='./airline_data_1988_2018.hd5', progress=True)
```

I got an error "IndexError: list index out of range".
I uncommented the assert line in the previous snippet and it told me that the number of files was not 1945, so I guess there is an issue here as well (I replaced the 372 with 1945).

Sorry for this long post but I feel I am very close to making vaex work so anyone who will take the time to help a pour soul I would be forever grateful !

Cheers

**Comment by maartenbreddels** [comment]
Hi there,

> It is not really explained what the output_dir variable does, so I am not sure what to put there.

It is in the cell below, this is where the temporary hdf5 files go.

> I got an error "IndexError: list index out of range".

you have two lines with one error, I don't know which line gave that error. Please give a full tracktrace, or find out yourself which gave the error.

I cannot help you now, since I don't have enough information.

Regards,

Maarten

**Comment by GoFast94** [comment]
Hi Maarten,
Thanks for the reply. For some reason when I came back to the code I now have an error with the zip conversion cell. I don't remember how I went around it last time.

So I tried to completely rewrite it without the unzipping part and I made this : 

```
dataframes = []

for f in csv_list:
    dataframes.append(pd.read_csv(f))
    
pandas_df.rename(columns=rename_dict, inplace=True)

        # Importing the data from pandas to vaex
vaex_df = vaex.from_pandas(pandas_df, copy_index=False)
        
        # Export the data with vaex to hdf5
vaex_df.export_hdf5(path=output, progress=False)
```

I'm not sure that it is correct, but what I am sure of is that it takes way too long to run and it is not what vaex is supposed to do, so I know I made something wrong.

**Comment by GoFast94** [comment]
![screen vaex](https://user-images.githubusercontent.com/58434377/78835127-eedfa400-79ef-11ea-8edd-4e9342946276.PNG)
Screenshot for details

**Comment by JovanVeljanoski** [comment]
Hi @GoFast94 

Can you please provide the the error you get, and on which line exactly does it happen in your case. We can not help otherwise.

Cheers, 
J.

**Comment by GoFast94** [comment]
Hi Jovan,

On the cell I put above I don't get an error really, just that it takes too long to compute so I think I did something wrong because in the demo it takes only a few seconds. My computer starts lagging so I have to interrupt it
![vaex2](https://user-images.githubusercontent.com/58434377/79086038-fded8b80-7d3a-11ea-991b-96ee9a43c3a4.PNG)

**Comment by JovanVeljanoski** [comment]
I guess it is slow.. because you are reading compressed text files. Try reading one, and how long it takes. Note that now you are reading everything in memory, do you have enough for that?

You might need to open a few 100 csv at a time, save them, then continue.

Which demo takes a few seconds? How do you know that?

Besides, I am not sure the code you are showing is doing what you want to do. 

Since there is no issue here.. maybe this is more of a stackoverflow question?

**Comment by GoFast94** [comment]
Hi,

After a break from coding I came back to this issue and found some solutions online. I can now convert the files to pandas dataframe, then to vaex dataframes and then to hdf5 files. The problem when I do the last part, is that it somehow converts only one file from the directory, I'm not sure if my loops is messy or if I miss a part. Here is my code
![vaex1](https://user-images.githubusercontent.com/58434377/80295305-254c4b80-8772-11ea-9705-f8b1c846268a.PNG)

I tried putting the cells 4 and 5 with cell number 3 so that all happens in the same time, but it didn't do the trick. do you have any ideas ?

![Inkedvaex2_LI](https://user-images.githubusercontent.com/58434377/80295441-f1bdf100-8772-11ea-98fa-3b42911c6f58.jpg)


Thanks

**Comment by JovanVeljanoski** [comment]
I guess in the `vaex_df.export_hdf5()` line,  `path` should be `y` ? Otherwise you are just overwriting the same `output` test file?

**Comment by GoFast94** [comment]
Yes that was it thank you very much !!

**Comment by GoFast94** [comment]
Hello,

Just reopening this issue to see if everything is normal, I did the conversion with the entire folder, and I got this as a result : 
![vaex screen](https://user-images.githubusercontent.com/58434377/80421343-9c055800-88dc-11ea-8ef4-4b5422ab12d4.PNG)

I didn't stay in front of the screen the whole time because it was quite long, but I'm not sure why there are 3 progress bars, and why the first one stopped at 60%... Is there a way to know that all the data was properly converted ?
The first and last lines of the dataframe are from the first and last csv but can't really check manually each of the 1900 files in between

Thanks

**Comment by maartenbreddels** [comment]
Yes, all the data is exported. I have seen this behaviour before, seeing the progress bar twice, not three times though. But it is the same progress bar, but apparently I print a newline (so it does to the new line) in some rare cases, and then updating the progress bar again, causing it to print on the next line.

I opened an issue to track this at https://github.com/vaexio/vaex/issues/703

**Comment by GoFast94** [comment]
Ok Thank you very much !

Cheers
