### ISSUE TITLE
Unable to convert multiple hdf5 file to a single hd5 file. It is giving me the following error. Any help would be great. I am stuck. 

### ISSUE THREAD

**Issue by Tanay0510** [vaexio/vaex#664]
MY CODE
```
import re
import glob
import vaex
import numpy as np

def tryint(s):
    try:
        return int(s)
    except:
        return s

def alphanum_key(s):
    """ Turn a string into a list of string and number chunks.
        "z23a" -> ["z", 23, "a"]
    """
    return [ tryint(c) for c in re.split('([0-9]+)', s) ]

hdf5_list = glob.glob('/Volumes/HD-E1/HDF5/*.hdf5')
hdf5_list.sort(key=alphanum_key)
hdf5_list = np.array(hdf5_list)
master_df = vaex.open_many(hdf5_list)
master_df.export_hdf5(path='/Volumes/HD-E1/FinalHDF5/NycTaxiData.hd5', progress=True)
```

ERROR 

```
ERROR:MainThread:vaex.execution:error in task, flush task queue. 

raise KeyError("Unknown variables or column: %r" % (variable,))
KeyError: "Unknown variables or column: 'str_byte_length(tpep_dropoff_datetime)'"
```

**Comment by JovanVeljanoski** [comment]
Hey @Tanay0510 

Are the two functions you mention (tryints, and alphanum_key) relevant to this error? If not, can you please remove anything that is not strictly related since it makes it more confusing from our side.

Can you try the opening the hdf5 files individually, and inspect them ? Does that work? Do they have the same number (and name) of columns?

Cheers, 
J.

**Comment by Tanay0510** [comment]
Hey @JovanVeljanoski 

I removed the tryints and alphanum_key. I run all the file hdf5 files individually and it runs fine.

 I think the problem has to be with number of columns. I downloaded the yellow taxi dataset from 2015 to 2019. And I think they changed the columns names somewhere in mid 2016. I will have to make it streamlined and then try merging it. But this library is insanely fast. I love it.

Thank You

**Comment by JovanVeljanoski** [comment]
Ah indeed.. if you want to play with the taxi dataset, best to use data prior to 2016. After that the exact locations are removed and changed with area codes, so one can not make nice maps as we have in the past.. 

Also note that the original data is a bit dirty.. one needs to do a lot of manual work to make it readable.. 

I am sure you know this, but the original data is [here](https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page), and they also have some docs, on the contents etc..

Cheers

**Comment by Tanay0510** [comment]
I wanted to do time series analysis for the dataset from 2015 to 2019 for one of my stats class. Thought it would be a good learning curve for me using hundred gb's of data. 

I guess I will have to do it using data from 2009 to 2015. Can you suggest me some other dataset which is like the NYC taxi dataset?

**Comment by JovanVeljanoski** [comment]
Hi, 

I don't know another large numerical dataset that is similar to the taxi one..
I have been looking in the past, especially for vaex demo etc, but have not been able to find anything nearly as large as the taxi dataset, at least when it comes to primarily numerical data.

If you do find something please let us know :).

( I will close this for now, please reopen if needed).
