### ISSUE TITLE
Reading Excel Files

### ISSUE THREAD

**Issue by anarchy89** [vaexio/vaex#666]
Hi, I tried looking at the documentation and I don't see any methods for opening up excel files. Is there a way?

**Comment by JovanVeljanoski** [comment]
Can pandas read excel files? If so, open with pandas, than use `vaex.from_pandas` to pass the data to vaex.

**Comment by anarchy89** [comment]
So I have to load it into a pandas dataframe first then convert correct?

**Comment by JovanVeljanoski** [comment]
Yes. That is what we currently do for all non-memory mappable file formats.
