### ISSUE TITLE
The html tag escapes for Vaex index column in jupyterlab 

### ISSUE THREAD

**Issue by limo1213** [vaexio/vaex#675]
I install vaex 2.6.1 in jupyterlab 1.2.7. When I print vaex dataframe, the index column # show html tag.
![image](https://user-images.githubusercontent.com/34529711/79339972-45069700-7f5c-11ea-8840-d8779f587902.png)

I inspect the index element. It looks like the "<" and ">" been encode to "&lt;" and "&gt;"
![image](https://user-images.githubusercontent.com/34529711/79340322-b5151d00-7f5c-11ea-9845-3a38370919d5.png)

Can you help to check it or avoid htmlEscapes for index column #?

**Comment by maartenbreddels** [comment]
Appearently tabulate 0.8.7 broke html escaping https://github.com/astanin/python-tabulate/issues/48
I suggest you downgrade it to 0.8.6, and once 0.8.8 is out we can apply a workaround.

**Comment by Xemnas0** [comment]
Version 0.8.9 is now out. Would it be possible to fix it?

**Comment by maartenbreddels** [comment]
Yeah, this is fixed again (it used to be fixed), but the next release should have it.
