### ISSUE TITLE
Lasso tool without GUI

### ISSUE THREAD

**Issue by balbinot** [vaexio/vaex#677]
Is there a way of using the lasso tool outside of the GUI interface? The idea would be to provide a list of vertices of a polygon.

**Comment by maartenbreddels** [comment]
Hi Eduardo,

The tests can be a great resource for this:
https://github.com/vaexio/vaex/blob/master/tests/selection_test.py#L181
Does this help you out?
We only support using the lasso with selection, no filtering though.

cheers,

Maarten

**Comment by balbinot** [comment]
Works perfectly! Thanks
