### ISSUE TITLE
Combine data from different files

### ISSUE THREAD

**Issue by rieder** [vaexio/vaex#68]
Can vaex combine data from multiple files, e.g. a snapshot from a simulation that is split up across processes? Combining these into one big file may not really be feasible...

**Comment by maartenbreddels** [comment]
Yes, vaex.open (https://docs.vaex.io/en/latest/api.html#vaex.open) should now take glob arguments, so:
```python
ds = vaex.open('sim*.hdf5')
```
Otherwise you can do it manually
```python
ds1 = vaex.open('sim1.hdf5')
ds2 = vaex.open('sim2.hdf5')
ds = ds1.concat(ds2)
```
Use the convert=True argument only if you have enough disk space :)
