### ISSUE TITLE
KeyError on using nunique as an aggregation function

### ISSUE THREAD

**Issue by jplauri** [vaexio/vaex#680]
The docs tell me that `nunique` is [supported as an aggregation function](https://vaex.readthedocs.io/en/latest/api.html#vaex.agg.nunique), but consider now the following:

```
import pandas as pd
import vaex

dates = pd.date_range("01-01-2020", "14-04-2020", freq="20H")[0:7]
vdf = vaex.from_arrays(date=dates, item=[1,1,1,2,3,3,4], amount=[10,20,30,40,50,60,70])
q = vdf.groupby(vaex.BinnerTime.per_day(vdf.date)).agg({"item": "count"})
```

This is fine, but changing `"count"` to `"nunique"` results in `KeyError: 'nunique'`. 

Am I misunderstanding the documentation, simply not understanding the syntax, or why is that?

I saw [PR 412](https://github.com/vaexio/vaex/pull/412) which says only strings are supported at the moment, but even constructing the dataframe as 

`vdf = vaex.from_arrays(date=dates, item=["1","1","1","2","3","3","4"], amount=[10,20,30,40,50,60,70])`

gives me the same key error for the group-by.

**Comment by JovanVeljanoski** [comment]
Hi @jplauri 

Yeah, i think it is just a syntax thing. For groupby vaex does not match pandas exactly. Look at this example:

```
import vaex
import pandas as pd

dates = pd.date_range("01-01-2020", "14-04-2020", freq="20H")[0:7]
df = vaex.from_arrays(date=dates, item=[1,2,1,2,3,3,4], amount=[10,20,30,40,50,60,70])

df.groupby(by=vaex.BinnerTime.per_day(df.date)).agg({'item_count': vaex.agg.count(),
                                                     'item_nunique': vaex.agg.nunique(expression='item')
                                                    })
```

Note that I modified your data a bit, so the aggregation would not yield only ones for the nunique column.

Some of the common aggregation function have "shortcuts". But in vaex, aggregation functions in vaex have multiple options, for e.g. they support selections, and in the case of nunique you get to choose how to treat missing values or nans. 

But this is a good point, I hope to update the docs and the tutorial on the docs page to better reflect this.

I hope this helps.

**Comment by maartenbreddels** [comment]
> This is fine, but changing `"count"` to `"nunique"` results in `KeyError: 'nunique'`.

This should work, maybe this is not released yet Jovan?

In any case, we could have a better error msg here, and give a list of possible names like in https://github.com/vaexio/vaex/pull/299 ? Or just list all options?

**Comment by JovanVeljanoski** [comment]
I tried on master and I get the same error message, but using the aggregation function explicitly works just fine. 

>In any case, we could have a better error msg here, and give a list of possible names like in #299 ? Or just list all options?

Either is a good idea.

**Comment by maartenbreddels** [comment]
I tried it, and it works on master, can you try again, maybe this was fixed by accident recently?

**Comment by maartenbreddels** [comment]
![image](https://user-images.githubusercontent.com/1765949/80026837-12701780-84e3-11ea-85f1-f16c926f767f.png)

**Comment by JovanVeljanoski** [comment]
Closing as stale, please reopen if needed.
