### ISSUE TITLE
Aliases for column names

### ISSUE THREAD

**Issue by heyuqi1970** [vaexio/vaex#693]
For display, reporting or some other purposes, sometime we need to have user friendly fieldnames.  
But rather than changing the original fieldnames, I prefer to set alias for fieldnames.  However, I can’t find any function to setup or modify alias for fieldnames.  Would you please advise how to do it?  If there is no such function, I suggest to add in.

**Comment by maartenbreddels** [comment]
Hi,

thanks for opening this issue. This should be fixed in https://github.com/vaexio/vaex/pull/617
But this is not released yet, https://docs.vaex.io/en/latest/installing.html should help with a dev install.
Let me know if this solves it for you.

Regards,

Maarten

**Comment by heyuqi1970** [comment]
HI,

Thanks for your patience, #691 is my misoperation.

Regards, 

Heyuqi

**Comment by heyuqi1970** [comment]
HI，

I tested it , but I get the same column name after I rename.

How can I set alias name?

> df = vx.read_csv('test5.csv', warn_bad_lines=True, error_bad_lines=False)
> df.get_column_names()
> Out:['ACC_NAME', 'MATCHED_TIME', 'index']
> df.rename('ACC_NAME', '姓名')
> Out:'姓名'
> df.get_column_names(alias=False)
> Out: ['姓名', 'MATCHED_TIME', 'index']
> df.get_column_names(alias=True)
> Out: ['姓名', 'MATCHED_TIME', 'index']

**Comment by JovanVeljanoski** [comment]
Hi, 

Is there a reason behind not simply using
```
df['name_name']  = df['old_name']
```

This will not result in a memory copy.

**Comment by heyuqi1970** [comment]
Hi， 

As my file have over 40 column , Will the size of the file double  if I using command `df['name_name']  = df['old_name']`.

**Comment by JovanVeljanoski** [comment]
The data is immutable (does not change).

When you do:
`df['name_name'] = df['old_name']` 
you are creating a virtual column, takes no memory.

Only if you export to disk all the new columns to disk, will the file size change.

**Comment by heyuqi1970** [comment]
Thank you , I got it.
