### ISSUE TITLE
Using large lists in vaex.from_arrays results in MemoryError

### ISSUE THREAD

**Issue by fabero** [vaexio/vaex#706]
Good afternoon!

While I have worked with vaex before and am very happy with it, I ran into an issue when trying to convert large lists into a vaex dataframe:

`Traceback (most recent call last):
  File "create_vaex_dataframe.py", line 26, in <module>
    df = vaex.from_arrays(**test)
  File "$DIR$/python3.6/site-packages/vaex/__init__.py", line 356, in from_arrays
    array = np.asanyarray(array)
  File "$DIR$/python3.6/site-packages/numpy/core/numeric.py", line 591, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
MemoryError`

Is there any way to circumvent this? Would it maybe be possible to load parts of the list and concatenate the dataframes?

Thanks in advance.

**Comment by JovanVeljanoski** [comment]
Hi @fabero 

Can you please the code that causes this issue?

**Comment by fabero** [comment]
> Hi @fabero
> 
> Can you please the code that causes this issue?

I used this tiny script to convert a jsonl file to hdf5:


`
import jsonlines
import vaex
from tqdm import tqdm

FILENAME = 'testfile'

ids = []
textsA = []
textsB = []

with jsonlines.open(FILENAME+'.jsonl') as reader:
	for obj in tqdm(reader):
		ids.append(obj['id'])
		textsA.append(obj['pair'][0])
		textsB.append(obj['pair'][1])

df = vaex.from_arrays(id=ids, text1=textsA, text2=textsB)

df.export_hdf5(FILENAME+'.hdf5', progress=True)
`

**Comment by JovanVeljanoski** [comment]
Hi @fabero ,

Few points:
 - Can you please be more clear: which line is the one causing the problem? Is it the `vaex.from_arrays(...)` or `df.export(...)` ?
 - Have you tried using `vaex.from_json` ? Does that give you problems?
 - How big (i.e. how many elements) does the lists have?
 - If it is the export line giving problems, can you try running it without the `progress` kwarg being set, or at least set to `False`?

We have tested `vaex.from_arrays` with at least 1e8 number of elements, perhaps more. I am not 100% sure (cc @maartenbreddels ), I am not sure if there is any difference between passing python lists and numpy array to `vaex.from_arrays`. I vaguely remember a discussion in the past the conclusion of which was that numpy arrays were recommended.

**Comment by fabero** [comment]
> Hi @fabero ,
> 
> Few points:
> 
> * Can you please be more clear: which line is the one causing the problem? Is it the `vaex.from_arrays(...)` or `df.export(...)` ?
> * Have you tried using `vaex.from_json` ? Does that give you problems?
> * How big (i.e. how many elements) does the lists have?
> * If it is the export line giving problems, can you try running it without the `progress` kwarg being set, or at least set to `False`?
> 
> We have tested `vaex.from_arrays` with at least 1e8 number of elements, perhaps more. I am not 100% sure (cc @maartenbreddels ), if there is any difference between passing python lists and numpy array to `vaex.from_arrays`. I vaguely remember a discussion in the past the conclusion of which was that numpy arrays were recommended.

Sorry for being unclear. The problem is caused by `vaex.from_arrays(...)` . I tried using `vaex.from_json(..., lines=True)` but this returns another error: `AttributeError: module 'pandas.core.arrays' has no attribute 'integer'` .

 The list consists of 727.000 elements. The elements are texts, which can be quite long (the longest consists of 17.000 characters).

**Comment by JovanVeljanoski** [comment]
Hi @fabero,

I understand now, than you for the explanation. What happens is, you reach your memory limit before the data is ingested into vaex. This is what happens: in your example, you read the data as lists. When you pass it to vaex, vaex will convert those lists to numpy arrays. Since you have such a large strings, numpy arrays take much more memory than lists, so this is why the error occurs. 

You can try this by casting those `textsA`, `textsB` lists into numpy arrays.

Good news is that it should be possible to get your data into vaex relatively easily. You need to get the data in chunks. Something like this:

```
# Generate data for example
size = 1_000_000
x = np.random.randint(0, 9, size=size)
y = np.random.randn(size)

# Here we go
chunk_size = 100_000   # Set as appropriate for your system

list_x = []
list_y = []

counter = 0
for i, obj in enumerate(tqdm(zip(x, y))):
    
    # Export each chunk to an hdf5 file
    if (np.mod(i, chunk_size) == 0) & (i != 0):
        df_chunk = vaex.from_arrays(x=list_x, y=list_y)
        print(df_chunk.head(3))
        output_file = f'tmp_{counter}.hdf5'
        print(output_file)
        df_chunk.export_hdf5(output_file)
        
        # re-instantiate the lists and increase the counter (that designates each chunk)
        list_x = []
        list_y = []
        counter += 1

    # Add data to lists
    list_x.append(obj[0])
    list_y.append(obj[1])

# Final loop
print(df_chunk.head(3))
output_file = f'tmp_{counter}.hdf5'
print(output_file)
    

# Now all of your data is converted to HDF5, but in different chunks/files. To get it all in the same place:
df = vaex.open('tmp_*.hdf5')
df.export_hdf5('my_full_data.hdf5')
# All done
```

The above example is just to illustrate the idea, it is not the clean/efficient code you would probably want. The idea is: read a chunk of data (that can fit into memory). Export that chunk to disk in hdf5 (or arrow if you prefer that). Go to the next chunk etc.. When all done: 
`vaex.open(tmp*.hdf5)` will read all the data as a single dataframe (now they are all memory mapped so no memory issues any more), and you can export that as a single file if you want. 

Reading data in chunks is the standard strategy to get your data in. 

I hope this helps.

**Comment by fabero** [comment]
> Hi @fabero,
> 
> I understand now, than you for the explanation. What happens is, you reach your memory limit before the data is ingested into vaex. This is what happens: in your example, you read the data as lists. When you pass it to vaex, vaex will convert those lists to numpy arrays. Since you have such a large strings, numpy arrays take much more memory than lists, so this is why the error occurs.
> 
> You can try this by casting those `textsA`, `textsB` lists into numpy arrays.
> 
> Good news is that it should be possible to get your data into vaex relatively easily. You need to get the data in chunks. Something like this:
> 
> ```
> # Generate data for example
> size = 1_000_000
> x = np.random.randint(0, 9, size=size)
> y = np.random.randn(size)
> 
> # Here we go
> chunk_size = 100_000   # Set as appropriate for your system
> 
> list_x = []
> list_y = []
> 
> counter = 0
> for i, obj in enumerate(tqdm(zip(x, y))):
>     
>     # Export each chunk to an hdf5 file
>     if (np.mod(i, chunk_size) == 0) & (i != 0):
>         df_chunk = vaex.from_arrays(x=list_x, y=list_y)
>         print(df_chunk.head(3))
>         output_file = f'tmp_{counter}.hdf5'
>         print(output_file)
>         df_chunk.export_hdf5(output_file)
>         
>         # re-instantiate the lists and increase the counter (that designates each chunk)
>         list_x = []
>         list_y = []
>         counter += 1
> 
>     # Add data to lists
>     list_x.append(obj[0])
>     list_y.append(obj[1])
> 
> # Final loop
> print(df_chunk.head(3))
> output_file = f'tmp_{counter}.hdf5'
> print(output_file)
>     
> 
> # Now all of your data is converted to HDF5, but in different chunks/files. To get it all in the same place:
> df = vaex.open('tmp_*.hdf5')
> df.export_hdf5('my_full_data.hdf5')
> # All done
> ```
> 
> The above example is just to illustrate the idea, it is not the clean/efficient code you would probably want. The idea is: read a chunk of data (that can fit into memory). Export that chunk to disk in hdf5 (or arrow if you prefer that). Go to the next chunk etc.. When all done:
> `vaex.open(tmp*.hdf5)` will read all the data as a single dataframe (now they are all memory mapped so no memory issues any more), and you can export that as a single file if you want.
> 
> Reading data in chunks is the standard strategy to get your data in.
> 
> I hope this helps.

Your suggestion worked like a charm. Thank you very much for your help!

**Comment by JovanVeljanoski** [comment]
You are very welcome.
