### ISSUE TITLE
Difficulty with reading a CSV without header 

### ISSUE THREAD

**Issue by xiaodaigh** [vaexio/vaex#707]
See https://github.com/xiaodaigh/disk.frame-vs

Just build the docker and go to `vaex.ipynb` which has code to 

* read the CSV using pandas (which reads it fine) and 
`%time pd.read_csv("../fm-data/perf/Performance_2000Q1.txt", sep="|", header = None)`
![image](https://user-images.githubusercontent.com/4497189/80704342-bda64f80-8b27-11ea-9e46-25f8e4c080ef.png)

* using vaex which reads it wrongly. 
```
%%time
a = vaex.from_csv("../fm-data/perf/Performance_2000Q1.txt", sep="|", header=None)
```
![image](https://user-images.githubusercontent.com/4497189/80704375-cc8d0200-8b27-11ea-9501-53420ef8f0d7.png)

**Comment by JovanVeljanoski** [comment]
Hi @xiaodaigh 

Thanks for your report. This is a known issue and is discussed here: #608

**Comment by JovanVeljanoski** [comment]
Will close as duplicate. Please use #608 for any discussions regarding this issue. Cheers!
