### ISSUE TITLE
figure (box) size in interactive plots

### ISSUE THREAD

**Issue by sevamoo** [vaexio/vaex#71]
Thanks a lot for the really amazing library. 
I was wondering what would be the best way to change the figure size in the plots such as ds.plot_widget()? 
I see the effect of shape, but "figsize" is not effective and always I have the same box size.
Thanks a lot.

**Comment by maartenbreddels** [comment]
Hi Vahid,

thanks! The (default) underlying library is bqplot. What you can do, is get a hold of the underlying [bqplot figure](http://bqplot.readthedocs.io/en/stable/_modules/bqplot/figure.html#Figure) using
```
p = ds.plot_widget('x', 'y')
# and since it is a DOMWidget (see ipywidgets for this)
# we can change the layout for instance.
p.backend.figure.layout.width = '300px'
```
Hope that helps!

cheers,

Maarten

**Comment by sevamoo** [comment]
Thanks a lot. 
It works very well with "min_width" and "min_height", but strangely not with "height" and "width".
Best
Vahid

**Comment by maartenbreddels** [comment]
Ok, it is general css, so it's always a bit tricky. Do you set it to '300px', not 300?

**Comment by sevamoo** [comment]
Yes, sure, "300px". 300 gives an error as expected.
But in my case this didn't work. Only with min_hight and min_width I get the expected result.
