### ISSUE TITLE
vaex.example() fails

### ISSUE THREAD

**Issue by akotlar** [vaexio/vaex#727]
Url missing http://vaex.astro.rug.nl/data/ does not exist, and neither does https://...

**Comment by JovanVeljanoski** [comment]
Hi @akotlar 

This is a duplicate of #169. Please refer to that issue. The links are updated in master, and will be available in the next release.

**Comment by akotlar** [comment]
Ah sorry about that, had done a quick search missed the existing issue. Thanks!
