### ISSUE TITLE
Equivalent of loc and iloc in vaex ?

### ISSUE THREAD

**Issue by BustaRams** [vaexio/vaex#728]
Hi,

I tried using loc and iloc like in pandas in a vaex dataframe but it didn't work, and I couldn't find what you use in the docs... I tried using this part 
![vaex screen](https://user-images.githubusercontent.com/24378381/81359905-b8727300-90da-11ea-81c2-6feae231820a.PNG)

I used these syntaxes, but those two cells run forever and make my computer crash
![Capture2](https://user-images.githubusercontent.com/24378381/81360077-30409d80-90db-11ea-9ef7-7af364d91bbd.PNG)

**Comment by JovanVeljanoski** [comment]
Hi @BustaRams ,

First of, vaex does not have `iloc` and `loc` methods, as it does not have a dedicated index column like pandas. Can you share what is it that you are trying to accomplish? 

As for your issues, I am afraid I can not reproduce them. Can you try for example:
```
import vaex.ml

df = vaex.ml.datasets.load_titanic()

df.select(df.sex == 'female')
print(df.evaluate(df.sex, selection=True))

df = df[df.sex == 'female']
print(df)
```
See if that works. 

Can you share the actual error (stacktrace) that you get. Perhaps some info on the data (dtype of the columns), how is the data created (are you reading it from an hdf5 file?), and version of vaex and OS. 

Cheers,

**Comment by BustaRams** [comment]
Hi @JovanVeljanoski , 

Thanks for the reply. I tried the example code and it works fine. What I am trying to do is filter the vaex dataframe so that I have only the lines that have the label 'XYZ' under the column 'symbol'.

The screenshot from the doc I shared seem to do that, but I'm not 100% sure. I am reading the data from a hdf5 file. I'm on windows 10 and vaex version I'm not sure. Here is the message I got when I interrupt the node (It's quite long I'm sorry).
The line just above dfsorted is "dfsorted = df[df.symbol == 'XYZ']"
and df is df=vaex.open(file.hd5)

![vaex1](https://user-images.githubusercontent.com/24378381/81410548-39645580-9141-11ea-817b-9a087acc62a9.PNG)
![vaex2](https://user-images.githubusercontent.com/24378381/81410561-3d907300-9141-11ea-91e0-95a966a9f664.PNG)
![vaex3](https://user-images.githubusercontent.com/24378381/81410577-42552700-9141-11ea-8651-dcde3b7b90a5.PNG)
![vaex4](https://user-images.githubusercontent.com/24378381/81410585-45e8ae00-9141-11ea-904b-37f5b4e24028.PNG)

The dtype of the columns is as follows
![vaex5](https://user-images.githubusercontent.com/24378381/81411081-22723300-9142-11ea-962f-2de4d3da57d8.PNG)
the column symbol is a string

**Comment by BustaRams** [comment]
Just tried a bunch of tests and I can confirm that the problem is occurring anytime I try to make a new dataset. For example df.describe( ) also takes a long time (longer than displaying the original dataframe) and I have to manually interrupt the process.

**Comment by JovanVeljanoski** [comment]
Hi, 

Ok, couple of more questions (you need to be as descriptive as possible so we can understand what is going wrong exactly to be able to help):

- how did you get/make the hdf5 file? Did you make it yourself, or used another tool?
- how big is the dataset (rows/columns)?
- how long did you wait before interrupting the process (either during filtering or during describe)?
- what are the specs of your machine (CPU, RAM, hard-disk)?

Did you read through vaex documentation tutorial or examples? When you print/display a dataframe vaex gives you a preview. When you do filtering (i.e. `df_filter = df[df.x > 5]`) and then trying to display the `df_filter` , or something like a `df.describe()`, vaex will need to actually do the computations, and this will take time depending on your machine specs and size of dataset. 

Also, earlier I asked for an error traceback (i.e. the error that is displayed when a process crashes), but you've posted what is displayed when you manually interrupt the process which is not useful in this case.

**Comment by BustaRams** [comment]
I see thank you for the clarification. I thought that it was going to be faster as the dataframe would be reduced. I did try to read the documentation but did not understand that part. All good now, thank you ! I'm just going to wait and do nothin on the side (probably what was crashing my computer). I just was afraid the code was wrong.

**Comment by JovanVeljanoski** [comment]
@BustaRams Sure not problem! It might be possible that you have indeed uncovered an issue we are not aware of, but they way you presented the case was not clear to me what the issue was. 

If you do encounter the problem, of it things properly crash, please re-open or create a new issue. 
Thanks!
