### ISSUE TITLE
Online demo

### ISSUE THREAD

**Issue by sevamoo** [vaexio/vaex#73]
I appreciate it a lot if you could give me a hint on how to use vaex in an online setup, like the NYC taxi case: https://vaex.io/
Best

**Comment by maartenbreddels** [comment]
It is quite hackish, I think a better way would be to use https://github.com/pbugnion/ipywidgets_server or https://github.com/maartenbreddels/flask-ipywidgets (really beta!). 
For instance, if you get `ds.plot_widget('x', 'y')` working in the notebook, or should also work with these libraries/
Does that help you?

**Comment by sevamoo** [comment]
Thanks a lot. I am pretty familiar with the set ups such as of flask with python backend/, JS front end, but not sure how would be the communications between two sides in this case. 
I will check it out and update here.
Thanks.

**Comment by sevamoo** [comment]
sorry, but not yet, unfortunately. I was pushing it a bit as it was before one of my presentations. I couldn't find a way and then I was off for a week.
It is on my list. I will update here.
Thanks for the follow up.
