### ISSUE TITLE
OSError: Unknown error opening: s3://vaex/taxi/yellow_taxi_2009_2015_f32.hdf5?anon=true

### ISSUE THREAD

**Issue by qiruoqiqi77** [vaexio/vaex#738]
I am trying vaex open as follows:
nyctaxi = vaex.open('s3://vaex/taxi/yellow_taxi_2009_2015_f32.hdf5?anon=true')
but I am receveing the following errors:
before I copy the error message here, I can successfully open this data:
df = vaex.open('s3://vaex/taxi/yellow_taxi_2015_f32s.hdf5?anon=true')
 I am in urgent need of taxi travel data for 2009-2016. I hope to ask you how to open or repair it.
thanks in advance.

![image](https://user-images.githubusercontent.com/65230725/81688936-7bb4cc00-948c-11ea-86c9-33d0056214af.png)
ERROR:MainThread:vaex.file:could not read 4 bytes from 's3://vaex/taxi/yellow_taxi_2009_2015_f32.hdf5?anon=true'
Traceback (most recent call last):
  File "D:\anaconda3\envs\tf\lib\site-packages\vaex\hdf5\dataset.py", line 152, in can_open
    with s3.open(path, "rb") as f:
  File "D:\anaconda3\envs\tf\lib\site-packages\vaex\file\s3.py", line 47, in open
    fp = vaex.file.cache.CachedFile(fp, naked_path)
  File "D:\anaconda3\envs\tf\lib\site-packages\vaex\file\cache.py", line 96, in __init__
    self.data_file = MMappedFile(self.data_path, self.length)
  File "D:\anaconda3\envs\tf\lib\site-packages\vaex\file\cache.py", line 36, in __init__
    self.mmap = mmap.mmap(self.fp.fileno(), self.length)
ValueError: cannot mmap an empty file
ERROR:MainThread:vaex:error opening 's3://vaex/taxi/yellow_taxi_2009_2015_f32.hdf5?anon=true'

OSError                                   Traceback (most recent call last)
<ipython-input-30-b9691d83751b> in <module>
----> 1 nyctaxi = vaex.open('s3://vaex/taxi/yellow_taxi_2009_2015_f32.hdf5?anon=true')

D:\anaconda3\envs\tf\lib\site-packages\vaex\__init__.py in open(path, convert, shuffle, copy_index, *args, **kwargs)
    235 
    236         if ds is None:
--> 237             raise IOError('Unknown error opening: {}'.format(path))
    238         return ds
    239     except:

OSError: Unknown error opening: s3://vaex/taxi/yellow_taxi_2009_2015_f32.hdf5?anon=true

**Comment by maartenbreddels** [comment]
> ValueError: cannot mmap an empty file

I believe this is triggered when you do not have enough diskspace. Try removing the files from ~/.vaex/file-cache, and make sure you have plenty of disk space (130GB orso).

**Comment by qiruoqiqi77** [comment]
D have  plenty of  disk space (409GB), 
and  I can successful opens3://vaex/taxi/yellow_taxi_2015_f32s.hdf5, but other single taxi data can't  be opened such as green taxi 2015,yellow taxi 2014/2013/2012.

**Comment by maartenbreddels** [comment]
> such as green taxi 2015,yellow taxi 2014/2013/2012.

As far as I know, none of those files exist. Did you try removing the files and try again?

**Comment by qiruoqiqi77** [comment]
I found the file-cache on Disk C and C have only  25.7GB.
Do you know the download path of other taxis.hdf5?
I would appreciate your help.

**Comment by JovanVeljanoski** [comment]
Hi @qiruoqiqi77 

> As far as I know, none of those files exist. 

As @maartenbreddels said, there are no such files. We have downloaded and converted all of the yellow taxi data from 2009-2015 from the [official website](https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page). That is the link that you tried and is working. 

For any other portions of data (other years, or the other taxi companies), you should download and convert the data yourself.

**Comment by qiruoqiqi77** [comment]
Thank you for your answer. I try again~
