### ISSUE TITLE
vaex group by date

### ISSUE THREAD

**Issue by qiruoqiqi77** [vaexio/vaex#740]
We want to group by date. The same date is a group. How can we achieve the goal?
Note that we only need to group without computation and aggregation.
We have tried the following mistakes:
df1.groupby(by='date1')
vaex dataframe is 
![image](https://user-images.githubusercontent.com/65230725/82034917-6da3bd00-96d1-11ea-8e77-9658fe59f1e9.png)

**Comment by JovanVeljanoski** [comment]
Hi, 

Looks at this example:

```
import vaex
import numpy as np

t = np.array(['2015-01-01', '2015-02-01', '2015-02-01', '2015-02-01', '2015-01-01'], dtype=np.datetime64)
y = np.arange(len(t))

df = vaex.from_arrays(t=t, y=y)

# Now do groupby per date, you need to specify "resolution" like this:
dfg = df.groupby(vaex.BinnerTime(df.t, resolution='M'), agg={'y': 'sum'})

# Alternatively, you can also use this shortcut
dfg = df.groupby(vaex.BinnerTime.per_month(df.t), agg={'y': 'sum'})
```

If you do not want to aggregations, you can simply not specify the `agg` keyword. 

We hope to add this to the tutorial soon.

I hope this helps.
J.

**Comment by JovanVeljanoski** [comment]
Naively it sounds just like you want to do filtering? But if you have many dates, that might get tedious..  If you want do filtering, you can 

If you have a single month for example:
```
for day in np.arange(1, 32):
    df_filter = df[df.date_col.dt.day == day]
    # now do stuff with df_filter
```
but this seems like a bad solution to me. 

If this does not expose any actual problem with vaex, maybe it is better suited to be posted to stackoverflow?
