### ISSUE TITLE
Virtual columns don't convert pd.dataframe 

### ISSUE THREAD

**Issue by qiruoqiqi77** [vaexio/vaex#741]
we add a virual columns for  vaex.df,
then, df1=df1.extract()
df1.to_pandas_df()
But the resulting dataframe still has no virtual columns

**Comment by qiruoqiqi77** [comment]
`df1.select(df1.date1)
df1.evaluate(df1.date1, selection=True)`

ValueError: invalid literal for int() with base 10: '2017-12-26'
![image](https://user-images.githubusercontent.com/65230725/82089098-863dc280-9725-11ea-830b-7c0c89f4dcf0.png)

**Comment by JovanVeljanoski** [comment]
> we add a virual columns for vaex.df,
> then, df1=df1.extract()
> df1.to_pandas_df()
> But the resulting dataframe still has no virtual columns

Look at the keyword arguments of all functions please.  The docstrings explain a lot.
in this case, if you want to export virtual columns you need to do 👍 
`df.to_pandas_df(virtual=True)`.

Note that this will now consume memory. 
Also in the future release of vaex, the default behaviour will change, that `virtual=True` will be set by default.

**Comment by JovanVeljanoski** [comment]
> `df1.select(df1.date1) df1.evaluate(df1.date1, selection=True)`
> 
> ValueError: invalid literal for int() with base 10: '2017-12-26'
> ![image](https://user-images.githubusercontent.com/65230725/82089098-863dc280-9725-11ea-830b-7c0c89f4dcf0.png)

please provide a full working example. We can't help unless we can reproduce your issue. 
For example, i do not know what df1.date1 is. Of course, you do not need to use the real data, you can just create small fake data to show an example.
