### ISSUE TITLE
to_pandas_df not support chunk_size

### ISSUE THREAD

**Issue by qiruoqiqi77** [vaexio/vaex#744]
TypeError: to_pandas_df() got an unexpected keyword argument 'chunk_size'

![image](https://user-images.githubusercontent.com/65230725/82156629-d300d500-98ae-11ea-95c0-d05504b93961.png)

**Comment by qiruoqiqi77** [comment]
df1 = df1.to_pandas_df(["PULocationID", "DOLocationID", "date"],parallel=True, virtual=True,chunk_size=5000)

TypeError: to_pandas_df() got an unexpected keyword argument 'chunk_size'

**Comment by JovanVeljanoski** [comment]
Just remove `chunk_size` completely. If you saw that from the docs, the docs are built on master, so unless you have installed vaex from source you will not have that option yet. But we hope to make a release very soon.

**Comment by maartenbreddels** [comment]
You can try pip installing some alphas to try to this right now:
```
pip install vaex-core==2.0.0a5
pip install vaex-hdf5==0.6.0a1
```

**Comment by JovanVeljanoski** [comment]
This is included in the latest standard release now.
