### ISSUE TITLE
vaex.example() returns broken link

### ISSUE THREAD

**Issue by arkanoid87** [vaexio/vaex#751]
```
Downloading http://vaex.astro.rug.nl/data/helmi-dezeeuw-2000-10p.hdf5 to /home/jovyan/.vaex/data/helmi-dezeeuw-2000-10p.hdf5
wget failed, using urlretrieve
```

**Comment by inti** [comment]
same thing here, i tried a couple of the datasets in here, https://vaex.readthedocs.io/en/latest/datasets.html, and it seems at least those i tried are not working :/

**Comment by maartenbreddels** [comment]
See https://github.com/vaexio/vaex/issues/169 for the helmi dataset fix. This is already in the alpha release of vaex-core https://pypi.org/project/vaex-core/2.0.0a5/ 
The page with the datasets are indeed now out of data, my previous university closed my google drive account.

As a replacement for that, we'll have a remote dataframe server up soon, so you don't even need to download the data. Also I think we should have some example notebooks hows to convert for instance the taxi dataset when downloaded from the original source (right @JovanVeljanoski ).

I think we should fix this before or when we do the next release, looks sloppy.

**Comment by JovanVeljanoski** [comment]
New release made, and this issue is resolved.
