### ISSUE TITLE
[FEA] Configurable build to find libraries

### ISSUE THREAD

**Issue by ccoulombe** [vaexio/vaex#755]
Allow users and developers building from source to configure the build to find system libraries such as PCRE or BOOST and particularly Arrow, installed in different location.

This could be easily be done through environment variable or using CMake.

**Comment by maartenbreddels** [comment]
Hi Charles,

I like it, if you have some example, or want to open a PR, I'm more than happy to accept that. Can you explain why you need this, what issue do you run into?

cheers,

Maarten

**Comment by ccoulombe** [comment]
Hi Maarten,

On many system such as HPC clusters, many libraries may not be installed in standard locations (e.g. /usr/). It is then rather useful to be able to point where are the librairies and include directory located.

One quick and easy is way is to document the different options to configure the build and then use environment variables in `setup.py` to set the path for the include directory in https://github.com/vaexio/vaex/blob/28d60207e1303d35744239d9115c9ec6ecf5aa49/packages/vaex-core/setup.py#L77 by adding :
```
os.environ.get('PCRE_INC', '')
```
One important part of this is documenting what is possible to configure or not.

This also allows to avoid shipping boost as part of the repo and rely on the system one.

**Comment by ccoulombe** [comment]
Actually, I screwed up my environment and that was the real reason why PCRE was not found.

Still, the idea of being able to configure the build might be relevant.

I'll let you close or not this issue.

**Comment by maartenbreddels** [comment]
I'll close it for now, if anyone sees a reason to add this, you're welcome. Thanks for letting us know.
