### ISSUE TITLE
Aggregate strings on a groupby operation

### ISSUE THREAD

**Issue by melovv** [vaexio/vaex#763]
Hi.

I need to group a dataframe and aggregate the strings as a list or a set. I have many string columns in the dataframe. How can I do that in vaex?
This is the functionality I'm looking for:

```
d
   A       B
0  1    This
1  2      is
2  3       a
3  4  random
4  1  string
5  2       !

 d.groupby('A')['B'].apply(list)
A
1    [This, string]
2           [is, !]
3               [a]
4          [random]
dtype: object

```

Thanks!

**Comment by SultanOrazbayev** [comment]
I'm just exploring vaex, so this is not a solution. It seems that `df.groupby` allows for custom aggregation function, one could try to develop a custom solution based on https://vaex.readthedocs.io/en/latest/_modules/vaex/agg.html#AggregatorDescriptorMulti.

As a quick hack, if you can reshape your data (so that each row corresponds to specific A value), then the following code might work (and can be expanded for more columns):

```
import vaex

def tolist(x,y):
   return list([x,y])

data = {'A':[1,2,1],'B':['a','b','c'], 'C':['d', 'e', 'f']}
df = vaex.from_dict(data)
df['list'] = df.apply(tolist, arguments=[df.A, df.B])
df['list2'] = df.apply(tolist, arguments=[df.B, df.C])
print(df)
```

**Comment by SultanOrazbayev** [comment]
And if you are not looking for a vaex-specific solution, then also consider `dask` (bags and dataframe). Specifically, dask supports pandas syntax and your `d.groupby('A')['B'].apply(list)` will probably work there.

**Comment by kylegilde** [comment]
Is this use case supported at this point? I don't really see how to use AggregatorDescriptorMulti to do this task.

**Comment by maartenbreddels** [comment]
Been thinking about this lately, and I think we should implement this for all primitives and strings in the C++ layer, not supported yet.

**Comment by jeschultz12** [comment]
This is related to #752

**Comment by Ben-Epstein** [comment]
@maartenbreddels any updates on this one?

**Comment by vikalfc** [comment]
Any updates now?

**Comment by JovanVeljanoski** [comment]
Hi, 

Yeah this has been available for a while. Here is an example:

```python
import vaex

df = vaex.datasets.titanic()

df_grouped = df.groupby('pclass').agg({
    'name': 'list',
    'origin': vaex.agg.list('embarked'),
    })

print(df_grouped)
```

**Comment by JovanVeljanoski** [comment]
I think this is safe to close now. Please re-open if needed.

**Comment by vikalfc** [comment]
This is great! But if we have something like this I'm getting error:
```python
def custom_f(x,y):
    return {"name": x,"cabin": y}

df["content"]=df.apply(custom_f,
    arguments=[df["name"], df["cabin"]])

df_grouped = df.groupby(by=['pclass', 'survived']).agg({
    'content': 'list'})



ValueError: Could not find a class (AggList_object_int64), seems int64 is not supported
```
or 

```python
df_grouped = df.groupby(by=['pclass', 'survived']).agg({
    'cabin': 'list'})


RuntimeError: [
  [
    "C22 C26",
    "C22 C26",
    "C22 C26",
    "A36",
    null,
    "C62 C64",
    null,
    "B58 B60",
    "C6",
    null,
    ...
    "D37",
    null,
    "D26",
    "D26",
    null,
    "C80",
    "C82",
    null,
    "C128",
    null
  ],
  [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    ...
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null
  ],
  ...
  [],
  []
] cabin has shape (20,) while we expected (5, 4)
```

**Comment by JovanVeljanoski** [comment]
Can you open a separate issue for this please? Easier to track and if it is a bug it is a separate thing. Thanks!

**Comment by JovanVeljanoski** [comment]
After a quick look, i see that after doing `df.dtypes`,  is see that `content` is of `dtype` object which is not supported.

**Comment by vikalfc** [comment]
Thanks, I can open Feature Request for this, it would be pretty useful! 😄

**Comment by JovanVeljanoski** [comment]
I assume you need this kind of feature?
https://github.com/vaexio/vaex/issues/2032

**Comment by vikalfc** [comment]
I actually need aggregation on the `dict` object, basically this is how we manage it in Pandas

```python
import vaex

df = vaex.datasets.titanic()

def custom_f(x,y):
    return {"name": x,"cabin": y}

df["content"]=df.apply(custom_f,
    arguments=[df["name"], df["cabin"]])
df_pandas=df.to_pandas_df()

df_pandas.groupby(by=['pclass', 'survived']).agg({
    'content': list}).reset_index()

```
<img width="528" alt="Screenshot 2022-11-18 at 12 06 42" src="https://user-images.githubusercontent.com/23177147/202691465-c21fa01b-7903-4f69-bc88-5d6fca323b59.png">

**Comment by JovanVeljanoski** [comment]
I understand but first step is creating the "dict" object right? Then the aggregation begins. 
Unless you already have data in that form (via [pyarrow structs](https://arrow.apache.org/docs/python/generated/pyarrow.struct.html)).

But please create a new issue on this, since it is going away from the original topic of this thread.

**Comment by vikalfc** [comment]
Sure, tnx for support
