### ISSUE TITLE
Performance issues with parquet files vs HDF5 equivalent

### ISSUE THREAD

**Issue by dazzag24** [vaexio/vaex#765]
Hi,

I have the same data set in two formats (the hdf5 was generated using vaex.open() on the parquet and then exporting as hdf5).

  28G  2020_01_09T_PT1H.hdf5
 3.7G  2020_01_09T_PT1H.parquet

Calling vaex.open on the parquet file takes 3 min 58 secs and uses a lot of memory.

Calling vaex.open on the hdf5 file takes only around 250ms.

Is this disparity expected?

Thanks

Darren

**Comment by JovanVeljanoski** [comment]
Hi @dazzag24 thanks for reaching out.

Yeah that is expected for now. For now we support reading in parquet files in memory only, and we hope to provide a proper memory-mappable support for it soon (@byaminov). 

So for now at least, we would recommend HDF5 or Arrow format.

Cheers

**Comment by dazzag24** [comment]
Thanks for the quick response.  I look forward to the new memory mappable support.  In the mean time perhaps the docs could clarify this performance distinction.  

Thanks
Darren

**Comment by maartenbreddels** [comment]
Fair point, lets keep this open as a reminder.

**Comment by yohplala** [comment]
Hi there,
Is this shortcoming still expected?
I have performance issue in a workflow where (all with vaex):
- I open about 20 parquet files - this is supposed to be a test case that I am using to debug my code as well, so these 20 parquet files ~5 columns x 6 rows each of random data.
- I join all Dataframes on a key (timestamp column)
- I scale row per row (with code I already shared patrially in #1547 and in #1550 I am most notably using decorator `@vx.register_function()`  )

It takes more than 10mn with so few data.
I have to work out a minimal reproducible example to share, I will try to do this this evening.
But from what I say, do you think the reading from 20 different parquet files could be the root cause?

Thanks in advance for your feedbacks, Bests

**Comment by yohplala** [comment]
> Hi there,
> Is this shortcoming still to be expected?
> I have performance issue in a workflow where (all with vaex):
> 
> * I open about 20 parquet files - this is supposed to be a test case that I am using to debug my code as well, so these 20 parquet files ~5 columns x 6 rows each of random data.
> * I join all Dataframes on a key (timestamp column)
> * I scale row per row (with code I already shared patrially in [[FEATURE-REQUEST] How to apply same MinMaxScaling to a set of columns? #1547](https://github.com/vaexio/vaex/issues/1547) and in [Understanding ?weird? running behavior with `@vaex.register_func()` / min row wise #1550](https://github.com/vaexio/vaex/discussions/1550) I am most notably using decorator `@vx.register_function()`  )
> 
> It takes more than 10mn with so few data.
> I have to work out a minimal reproducible example to share, I will try to do this this evening.
> But from what I say, do you think the reading from 20 different parquet files could be the root cause?
> 
> Thanks in advance for your feedbacks, Bests

**Comment by maartenbreddels** [comment]
Hi,

this is already an older issue, and things have changed for parquet, and now we actually lazily read it, which means we can support larger than memory datasets, at the cost of performance.
While profiling a larger application, I did see some possible performance issues, which I may solve in https://github.com/vaexio/vaex/pull/1594 (or another PR, which I'll reference there).
What we probably want now, is an option to eagerly read everything in memory, see #1595. you can easily do this manually:
```
import pyarrow.parquet as pq
import vaex
table = pq.read_table('/data/issue-1237.parquet')
df = vaex.from_arrow_table(table)
```
Please let me know if that gives you better performance.

Regards,

Maarten

**Comment by yohplala** [comment]
> Please let me know if that gives you better performance.

Hi @maartenbreddels 
Thanks a lot for the follow-up.
As I indicated, I worked out a 'minimal reproducible' example, and posted in ticket #1591.
This example 'outperforms' expectation in the sense that vaex is actually not ending the calculation (seems to be undefinitely working?)

**Comment by mfouesneau** [comment]
Sorry to comment on a closed ticket, but I still get terrible performance on parquet files. Is there a place where I should look to make it faster?
