### ISSUE TITLE
Iterate over the groupby object?

### ISSUE THREAD

**Issue by stokhos** [vaexio/vaex#773]
Dear vaex team:

I have a huge time series data, that I have it groupby month, and I'd like to iterate each group. Is there a way of doing that?

like in pandas:
```python
grouped = df.groupby(pd.Grouper(key='Datetime', freq='M'))
for name, group in grouped:
    print(name)
```
and access the group by:

```python
print(grouped[name])
```
best

**Comment by maartenbreddels** [comment]
Hi,

thanks for opening the issue. I think this is not a good pattern in terms of efficiency, so I'm collecting use cases to see how we can provide the right tools to attack these problems efficiently (with aggregators). What problem do you want to attack, why do you need the whole dataframe, and can't you use aggregators?

Regards,

Maarten

**Comment by stokhos** [comment]
Hi, 

actually, it's a workaround for my actual problem.
I have a huge time series dataset, I group it by month, and the count the observations in each group.
I want to add the number of observation in each group back to the original dataset.

```python
import vaex
data = vaex.read_csv(file)
data['Datetime'] = data.Datetime.astype('datatime64[s]')
data['Date'] = data.Date.astype('datatime64[D]')
data['Month'] = data.Date.astype('datatime64[M]').astype(str)

count = grouped = data.groupby(by='Month').agg({'Price':'count'})

group_count = gp_count.loc[data.Month] # if data was a pandas dataframe or cudf dataframe, this would work
data['group_count'] = group_count
```

best

**Comment by stokhos** [comment]
got it!
Thanks a lot!
