### ISSUE TITLE
Open s3 kwargs no longer function

### ISSUE THREAD

**Issue by erikakert** [vaexio/vaex#774]
The documentation states that when opening an s3 file, kwargs are passed through to the s3 file system.
This does not appear to work anymore, as the following:

`df_from_s3 = vaex.open('s3://vaex/testing/xys.hdf5?anon=True', profile_name='jf-dev')`

Provides the following error:
`ERROR:MainThread:vaex:error opening 's3://vaex/testing/xys.hdf5?anon=True'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-49-26b36d159aea> in <module>
----> 1 df_from_s3 = vaex.open('s3://vaex/testing/xys.hdf5?anon=True', profile_name='jf-dev')
      2 df_from_s3

/usr/local/lib/python3.7/site-packages/vaex/__init__.py in open(path, convert, shuffle, copy_index, *args, **kwargs)
    196                         ds = from_csv(path, copy_index=copy_index, convert=csv_convert, **kwargs)
    197                     else:
--> 198                         ds = vaex.file.open(path, *args, **kwargs)
    199                         if convert and ds:
    200                             ds.export_hdf5(filename_hdf5, shuffle=shuffle)

/usr/local/lib/python3.7/site-packages/vaex/file/__init__.py in open(path, *args, **kwargs)
     39             break
     40     if dataset_class:
---> 41         dataset = dataset_class(path, *args, **kwargs)
     42         return dataset
     43 

TypeError: __init__() got an unexpected keyword argument 'profile_name'`

We want to use vaex to work with our large s3 parquet files in our datalake, but haven't been able to read a single file from there when needing to pass credentials or profiles.

I should note that even another example, the following also fails stating that anon is an unexpected keyword argument.
`df_from_s3 = vaex.open('s3://vaex/testing/xys.hdf5', anon=True)
df_from_s3`

**Comment by maartenbreddels** [comment]
Hi,

thanks for opening this issue, we found out in https://github.com/vaexio/vaex/issues/733 indeed. I'll close this issue to you can follow that one.

Regards,

Maarten
