### ISSUE TITLE
Unable to use convert option in vaex.from_csv()

### ISSUE THREAD

**Issue by rajathjain** [vaexio/vaex#783]
Hi,

I am trying to read a large csv file in chunks and convert it to .hdf5 file internally as per the api documentation. But while doing so I encounter the following problem

df=vaex.from_csv("data.csv",copy_index=False,chunk_size=5_000_000,convert=True)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/anaconda3/envs/vaex/lib/python3.8/site-packages/vaex/__init__.py", line 486, in from_csv
    return from_pandas(pd.read_csv(filename_or_buffer, **kwargs), copy_index=copy_index)
TypeError: parser_f() got an unexpected keyword argument 'chunk_size'

**Comment by JovanVeljanoski** [comment]
Hi @rajathjain 

Can you please share which version of vaex you are using?

Also I see that you are using python 3.8. Is that on windows or another OS? 

Cheers.

**Comment by rajathjain** [comment]
Hi @JovanVeljanoski 

I am using python3.8 on a Linux machine.
![image](https://user-images.githubusercontent.com/28035823/83557653-a942e180-a52f-11ea-9c35-aa622fdfa8c9.png)

**Comment by JovanVeljanoski** [comment]
Hi, 

you are getting that error because you are running an older version of vaex.
Please try to update. Once you do that, checking the version should show that:
vaex -> 3.0.
vaex-core -> 2.0

Then your example above should work. Hope this helps

**Comment by rajathjain** [comment]
Hi,

It works fine after updating.
Thanks for the quick reply

Cheers
