### ISSUE TITLE
Supporting delimiters in vaex.open()

### ISSUE THREAD

**Issue by prakharrathi25** [vaexio/vaex#784]
Hi, does vaex not support other delimiters. This is the code that I ran : 
`vaex.open('ap_final.CSV', delimiter='|')`

and I got the following error: 

OSError: Could not open file: ap_final.CSV, did you install vaex-hdf5? Is the format supported?

Even when I removed the delimiter argument, I got the same error. Please help. Urgent.

**Comment by JovanVeljanoski** [comment]
Hi, 

If you are reading CSV files, might be better to use
`vaex.read_csv()...`

which basically uses pandas to read the csv, and you can use the same arguments as you would use in `pandas.read_csv`.

Also please check that you are using the latest version of vaex.

**Comment by prakharrathi25** [comment]
Hi, I downloaded vaex today so I am using the latest version. The read_csv() solution worked. Where can I find complete documentation for this? Also, is there no to_csv() function. I got this error when I was trying to save the dataframe as a csv file. 

`AttributeError: 'DataFrameArrays' object has no attribute 'to_csv'`

**Comment by JovanVeljanoski** [comment]
Hi, 

I don't understand why exactly, but in some (rare) cases it used to happen that pip would not install the latest version, so it does not hurt to check.

Sure, please check out the documentation pages at:
https://github.com/vaexio/dash-117million-taxi-app/blob/master/app.py

Also, if you are primarily interested in I/O, there is an example page just for that:
https://docs.vaex.io/en/latest/example_io.html

Note that while vaex tries to keep close to the pandas API as much as possible, some method may be different (or have slightly different name). 

So if you want to export data to CSV, the method is 
`df.export_csv()`.

Note that vaex is optimal when using arrow or hdf5 files.

**Comment by JovanVeljanoski** [comment]
Is it ok to close this?

**Comment by prakharrathi25** [comment]
Hi, 

Thank you for the prompt response. This was helpful. This library is really useful and I am still learning. Could you just point me to a resource where I could find a method to convert DataFrameArray to pandas DataFrame ?

**Comment by JovanVeljanoski** [comment]
Hi, I already did:

> Also, if you are primarily interested in I/O, there is an example page just for that:
> https://docs.vaex.io/en/latest/example_io.html

Please read through the tutorial and examples to see to best use vaex.

**Comment by prakharrathi25** [comment]
Alright, thank you.
