### ISSUE TITLE
NameError using export_csv

### ISSUE THREAD

**Issue by BssMsi** [vaexio/vaex#790]
Hi,
I'm getting NameError, not sure why.
I have columns "Sub-Region" and "Global-Region", which I'm guessing is implicitly aliased to "Sub_Region", since I can access the column in both ways.
Even if I just read the file and export it in the next line, I get the error, that is,
oneDF = vaex.from_csv(inputFile)
oneDF.export_csv("test.csv")

NameError: Column or variable 'Region' does not exist. Did you mean: 'Sub-Region' or 'Global-Region'

My guess would be it might be some issue handling the hyphenated column while exporting.

Thanks

**Comment by JovanVeljanoski** [comment]
Thank you for the report, we'll try to look into this soon.

**Comment by maartenbreddels** [comment]
This should be fixed when #793 is merged/released, but I do recommend not using csv. Use hdf5, arrow or parquet, especially when exporting large amounts of data.

**Comment by BssMsi** [comment]
Oh, that might be the issue, I had pip installed it, I'll clone the repo and set it up again and check.

Thanks

**Comment by maartenbreddels** [comment]
Vaex 2.0.2 is almost released https://github.com/vaexio/vaex/actions/runs/124999191 :)

**Comment by maartenbreddels** [comment]
This is released now, you can try it out with `$ pip install "vaex-core>=2.0.2"`

**Comment by BssMsi** [comment]
Yeah, it's working now, thanks
Excited to get started with vaex

Cheers

**Comment by maartenbreddels** [comment]
Great, thanks for letting us know, good luck!
