### ISSUE TITLE
Efficient way to convert pandas hdf5 to vaex hdf5

### ISSUE THREAD

**Issue by 08walkersj** [vaexio/vaex#798]
I have recently come across this package, so far it looks very good. I have a large hdf5 file created using pandas, to give you an idea it is just over 60GB. I have been testing out some methods to convert to a vaex hdf file: https://stackoverflow.com/questions/59264275/convert-large-hdf5-dataset-written-via-pandas-pytables-to-vaex. But I wanted to know if their is a more efficient way as I find the export_hdf5 function can be a little slow some times.
So far my only idea is to chunk through the pandas hdf5 and turn the chunks into vaex hdf5 and then join them together after but this will be very time consuming.

This is the code I'm testing to convert chunks, I have had to use the sleep function because the console seems to freeze between iterations and getting it to stop for a second seemed to fix it.:
```
for i, start in enumerate(pd.date_range(start= pd.Timestamp('1999-01-01T01:00:00'), end= pd.Timestamp('1999-04-01T00:00:00'), freq='30d')):
   print(100*i/len(pd.date_range(start= pd.Timestamp('1999-01-01T01:00:00'), end= 
   pd.Timestamp('1999-04-01T00:00:00'), freq='M')))
   end= start + pd.Timedelta(value=30, unit='day')
   tmp_df= pd.read_hdf('pandas.hdf5', mode='r', where="index>= start & index<end")
   dfvx=vaex.from_pandas(tmp_df, copy_index=True)
   dfvx.export_hdf5("batch"+str(i)+".hdf5")
   time.sleep(1)
```

**Comment by maartenbreddels** [comment]
Wouldn't it be faster to use the chunk_size, sth like:
```
for tmp_df in pd.read_hdf('pandas.hdf5', mode='r', chunk_size=5_000_000):
   dfvx=vaex.from_pandas(tmp_df, copy_index=True)
```
so do it 5 million at a time. export_hdf5 can be a bit slow if you filter the vaex dataframe, I think otherwise it should be fast.

**Comment by JovanVeljanoski** [comment]
Will close this as stale. Please reopen if needed.
