### ISSUE TITLE
Feature: Initialize column to a fixed value

### ISSUE THREAD

**Issue by maartenbreddels** [vaexio/vaex#802]
`df['x'] = scalar_value`
Would be helpfull.

What you can do now is:

```
df['test'] = vaex.vrange(0, len(df))  # add a 'virtual range' column, which takes no memory
df['test'] = df['test']* 0 + 111  # multiply by zero, and add the initial value
```

**Comment by norlandrhagen** [comment]
This would be a great addition. However, the temporary solution doesn't seem to work with differant dtypes. For example:

df['test'] = vaex.vrange(0, len(df))  
df['test'] = df['test']* 0 + 'string'  

Resuts in:
"TypeError: bad operand type for unary +: 'str'"

Do you know of any ways of initializing a column with a string?

**Comment by JovanVeljanoski** [comment]
Hi, 

Actually your way does work, but you are trying to add float to string, hence the error. If you do:
```
df['test'] = vaex.vrange(0, len(df))
df['test'] = (df['test']* 0).astype('str') + 'text'
```
it will work as you might expect.

Although, I agree, there probably should be a nice/convenient way to add a virtual column with a fixed string value. 

Thanks!

**Comment by kmcentush** [comment]
+1 to this issue

**Comment by kmcentush** [comment]
I would also ask for the ability to initialize a column with a mask. For example, I would initialize a string column where by default all values are masked.

**Comment by mkst** [comment]
If I filter my dataframe I need to add a column with the same number of entries as the original, *unfiltered* dataframe.

Is this deliberate? Is there a way to 'commit' my filters so I can work with the current `len(df)` rather than needing to track the original length? I was going to raise a separate issue, but think it fits well enough under this one (but let me know!)

```
ValueError: Array is of length 8993, while the length of the DataFrame is 8993 due to the filtering, the (unfiltered) length is 33782.
```

**Comment by JovanVeljanoski** [comment]
This is explained in the FAQ, so [please check it out](https://vaex.io/docs/faq.html#Why-can't-I-add-a-new-column-after-filtering-a-vaex-DataFrame?).

**Comment by mkst** [comment]
Sorry Jovan! That's exactly what I needed.

**Comment by JovanVeljanoski** [comment]
No problem at all, i hope this helps!
