### ISSUE TITLE
Very slow exporting to CSV

### ISSUE THREAD

**Issue by Ralimar** [vaexio/vaex#803]
In Jupyter notebook, I used Vaex to import a 6M row dataset from a CSV.  Cleaned data, merged cells and used TextBlob to run sentiment analysis.  I had a finished Vaex dataframe with 2 columns and 63K rows.   Trying to export to CSV took 3+ hours, never finished(restarted kernel), only exported 50K rows.

**Comment by JovanVeljanoski** [comment]
Hmm that is odd.. so i guess there is no error message?

If you are using the latest version of vaex, can you try to adjust the `chunk_size` parameter in `.export_csv()`

If you have a ~70K dataframe, perhaps set it to that or even smaller? So something like 

`df.export_csv(path=myfile.csv, chunk_size=70_000)`
or  perhaps
`df.export_csv(path=myfile.csv, chunk_size=10_000)`

Would that help?

**Comment by Ralimar** [comment]
I was already having issues, so the described attempt had chunk_size=10_000

**Comment by JovanVeljanoski** [comment]
Vaex is using pandas `read_csv`  / `to_csv()` under the hood for CSV IO. 

You could try converting your vaex df (or part of it) to pandas with df.to_pandas_df() and try export it like that. If you get the same performance.. there is little we can do about that. If you get much faster performance, we can try to investigate this further. 

Thanks!

**Comment by maartenbreddels** [comment]
An alternative would be to try:
`df.extract().export_csv(...)` would be very useful if you could let us know if any of these methods give you a speedup?

In any case, I would recommend not using csv, but export to hdf5 or arrow.

**Comment by JovanVeljanoski** [comment]
Will close this as stale. 

For more info please visit our guide for exporting data: https://vaex.io/docs/example_io.html#Data-export
Also note the `df.export_many` method. Sometimes can speed things up!
