### ISSUE TITLE
vaex.ml.PCA returns nan values

### ISSUE THREAD

**Issue by psmgeelen** [vaexio/vaex#805]
Hi there, 
To begin with, I love vaex! I have an issue with the PCA method, as it returns only nan values on my dataset for all components. I also noticed that in the class, the eigenvectors were also described as being a list of nans. The data is to big to test vanilla scikit-learn unfortunately. 

Regrads
Pieter

**Comment by JovanVeljanoski** [comment]
Hi @psmgeelen 
Thanks for reaching out. Can you please check if your columns contain nans, i mean in the data itself?  That is the likely cause of this.

**Comment by psmgeelen** [comment]
Thats it! Thank you sooo much!

**Comment by JovanVeljanoski** [comment]
You are very welcome.
