### ISSUE TITLE
Unnamed index while reading csv file causes issues

### ISSUE THREAD

**Issue by GlorifiedStatistics** [vaexio/vaex#807]
Reading a csv file with unnnamed columns (for example, reading in a csv file created by pandas with 'index=True') creates a column with the name 'Unnamed__0'. Calling some other functions like .drop('Unnamed__0') throws an error.

This code throws an error:

```python
import pandas as pd 
import vaex 

pd.DataFrame({'a':[1,2,3]}).to_csv('test_csv.csv', index=True)

df = vaex.open('test_csv.csv')
df = df.drop('a')
```

While this code does not:

```python
import pandas as pd 
import vaex 

pd.DataFrame({'a':[1,2,3]}).to_csv('test_csv.csv', index=False)

df = vaex.open('test_csv.csv')
df = df.drop('a')
```

I believe this is due to the 'Unnamed__0' column that is generated when loading in the csv with 'index=True'.

**Comment by GlorifiedStatistics** [comment]
And it gives the error:


---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
 in 
      5 
      6 df = vaex.open('test_csv.csv')
----> 7 df = df.drop('Unnamed__0')

~/venv/lib64/python3.6/site-packages/vaex/dataframe.py in drop(self, columns, inplace, check)
   4666         columns = _ensure_strings_from_expressions(columns)
   4667         df = self if inplace else self.copy()
-> 4668         depending_columns = df._depending_columns(columns_exclude=columns)
   4669         for column in columns:
   4670             if check and column in depending_columns:

~/venv/lib64/python3.6/site-packages/vaex/dataframe.py in _depending_columns(self, columns, columns_exclude, check_filter)
   4693         for column in columns:
   4694             expression = self._expr(column)
-> 4695             depending_columns |= expression.variables()
   4696         depending_columns -= set(columns)
   4697         if check_filter:

~/venv/lib64/python3.6/site-packages/vaex/expression.py in variables(self, ourself, expand_virtual, include_virtual)
    390                 variables.add(varname)
    391 
--> 392         expresso.translate(self.ast, record)
    393         return variables
    394 

~/venv/lib64/python3.6/site-packages/vaex/expression.py in ast(self)
    223         """Returns the abstract syntax tree (AST) of the expression"""
    224         if self._ast is None:
--> 225             self._ast = expresso.parse_expression(self.expression)
    226         return self._ast
    227 

~/venv/lib64/python3.6/site-packages/vaex/expresso.py in parse_expression(expression_string)
    554 def parse_expression(expression_string):
    555     expr = ast.parse(expression_string).body[0]
--> 556     assert isinstance(expr, ast.Expr), "not an expression"
    557     return expr.value
    558 

AssertionError: not an expression

**Comment by JovanVeljanoski** [comment]
Hi @GlorifiedStatistics 

Thanks for the report, and for the nice reproducible example.

 This is not really related reading a csv file per se, but how vaex handles "non standard" column names (column names with special characters like spaces etc..). In this case 'Unnamed: 0' is added by pandas when one attempts to read a csv file without a header. 

The same behaviour can be reproduced like so:

```
pandas_df = pd.DataFrame({'a':[1,2,3], 'Unnamed: 0': [10, 20, 30]})
df = vaex.from_pandas(pandas_df)
df.drop(columns=['a'])
.
.
AssertionError: not an expression
```

I hope we can fix this soon. 
Thanks!

**Comment by JovanVeljanoski** [comment]
This has been fixed. Thank you!
