### ISSUE TITLE
s3 + parquet support

### ISSUE THREAD

**Issue by zkchong** [vaexio/vaex#810]
Hi All, 
I try to read a parquet file from s3 with the following code.
`vaex.open('s3://adc-ds-dev//data/xxx/subscribers/201907/part-00076-0b85f844-aecb-4183-8265-a375173bf0af-c000.snappy.parquet')`

And it showed me the following error: 
~/anaconda3/envs/py37/lib/python3.7/site-packages/pyarrow/parquet.py in _make_manifest(path_or_paths, fs, pathsep, metadata_nthreads, open_file_func)
   1366             if not fs.isfile(path):
   1367                 raise OSError('Passed non-file path: {}'
-> 1368                               .format(path))
   1369             piece = ParquetDatasetPiece(path, open_file_func=open_file_func)
   1370             pieces.append(piece)

OSError: Passed non-file path: s3://adc-ds-dev//data/xxx/subscribers/201907/part-00076-0b85f844-aecb-4183-8265-a375173bf0af-c000.snappy.parquet

I can use aws s3 ls to see my file. I guess I have configured the aws correctly. 

Any idea what has gone wrong here?

**Comment by maartenbreddels** [comment]
Hi,

there is no support yet for using vaex with s3 and parquet yet. This will happen though, I think we first need to get #517 in. Parquet support isn't great at the moment (it will not work out of code, as it will read it into memory). You could copy, and then locally convert to hdf5, or store as hdf5 in AWS.

I hope that helps.

Regards,

Maarten

**Comment by adilosa** [comment]
Not sure if this would be in the same issue, but S3 support for Arrow files would be great as well!

**Comment by maartenbreddels** [comment]
This is now supported, to install:
```
$ pip install "vaex-core>=4.0.0a11"
# or for the while kitchsink:
$ pip install "vaex>=4.0.0a6"
```
