### ISSUE TITLE
give split random a defualt value

### ISSUE THREAD

**Issue by datascienceit** [vaexio/vaex#82]
`split_random() missing 1 required positional argument: 'frac' shouldn't occur. 
Should have 0.8 or something

**Comment by maartenbreddels** [comment]
What about sklearn's default value? http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

**Comment by maartenbreddels** [comment]
Note that split_random is not ML specific, a default does not make sense.
