### ISSUE TITLE
How to add a new row in existing vaex dataframe.

### ISSUE THREAD

**Issue by neikhil** [vaexio/vaex#820]
I am trying to transpose a data frame but I am not able to do it,
so I decide I will convert it to an array and transpose it and then add to an empty data frame with some vaex function.
but I am unable to find a function which could append rows nor could I find a function which could create an empty data frame with predefined index and columns name.

**Comment by scollay** [comment]
I think concat might work for you.
https://docs.vaex.io/en/latest/api.html#vaex.dataframe.DataFrameLocal.concat

**Comment by JovanVeljanoski** [comment]
Veax does not have a dedicated index column (like pandas for example). And a dataframe always refers to some data, there is little use for having an empty object in the vaex framework (although such things are support, for example if you filter out all the data in a given dataframe). 

You can always do a "hack" like `vaex.from_arrays(x=[], y=[])` but we do not recommend doing this. 

For appending rows, indeed, the concat method is the way to go!
