### ISSUE TITLE
Receiving ContextualVersionConflict error 

### ISSUE THREAD

**Issue by neikhil** [vaexio/vaex#825]
> ContextualVersionConflict: (pyarrow 0.14.1 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('pyarrow>=0.15'), {'vaex-arrow'})

This is something which has started appearing on my colab from today.

Just to give you reference initially I used to run vaex by executing these two lines on colab.

```
!pip install --upgrade python 
!pip install --upgrade vaex
```

Tried upgrading pyarrow from pip got the following error

`!pip install --upgrade pyarrow`

> Requirement already up-to-date: pyarrow in /usr/local/lib/python3.6/dist-packages (0.17.1)
Requirement already satisfied, skipping upgrade: numpy>=1.14 in /usr/local/lib/python3.6/dist-packages (from pyarrow) (1.18.5)

**Comment by JovanVeljanoski** [comment]
Hi @neikhil 

I tried vaex on collab today. 

(At least) for me, running
```
!pip install --upgrade python
```
leads to this soft error
```
ERROR: Could not find a version that satisfies the requirement python (from versions: none)
ERROR: No matching distribution found for python
```

Next up, vaex is not install on collab by default, so no need to run the `--upgrade` flag, just 
```
!pip install vaex
```
Finally, collab seems to run a rather old version of IPython, so I needed to upgrade that
```
!pip install --upgrade ipython
```

So if I start the notebook with this cell:
```
!pip install vaex
!pip install --upgrade ipython
```
Then things seem to work. Also (you probably know this already), but you need to restart the runtime after installing vaex and updating ipython for the changes to take effect (the notebooks tells you this anyway).

Can you try if this helps? Are you pip installing other packages along with vaex btw?

**Comment by neikhil** [comment]
Yup it worked.

thanks for the help.

**Comment by rsjain1978** [comment]
Thank you for your suggestion @JovanVeljanoski , worked for me as well.

**Comment by MANUTH-V** [comment]
Hi everyone i am having a problem when I tried to import the APICLient from IBM it's said : 
ContextualVersionConflict: (docutils 0.17 (/Users/manuthvann/opt/anaconda3/lib/python3.8/site-packages), Requirement.parse('docutils<0.16,>=0.10'), {'ibm-cos-sdk-core'})

Has anyone encountered this problem before? Looking forward to hearing back from you thanks
