### ISSUE TITLE
Selection with plot_widget

### ISSUE THREAD

**Issue by andersdot** [vaexio/vaex#83]
I'm getting an error when using `ds.plot_widget` with a `selection`, that I sometimes see with `ds.plot` but I'm struggling to reproduce again. 

This is my selection:
`selectionGaia = (ds.pm < 10**0.6) & (ds.phot_g_mean_mag < 18.5) & (ds.phot_g_mean_mag>14) & (ds.parallax < 1)`

This code works fine:
```
ds.plot(ds.ra*1, ds.dec, f='log1p', limits=[[360, 0], [-90, 90]], selection=selectionGaia, figsize=(15,5))
ds.plot(ds.ra+360, ds.dec, f='log1p', limits=[[360+360, 360], [-90, 90]], colorbar=False, selection=selectionGaia, figsize=(15,5))
plt.xlim(360+360, 180) 
```

This code:
`ds.plot_widget(ds.ra*1, ds.dec, f='log1p', selection=selectionGaia)`

gives this error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/anaconda3/lib/python3.6/site-packages/vaex/jupyter/plot.py in _update_grid(self)
    216             result = self.dataset._stat(binby=self.get_binby(), what=self.what, limits=self.limits,
    217                                         shape=self.get_shape(), progress=pb,
--> 218                                         selection=self.active_selections(), delay=True)
    219             if delay:
    220                 promises.append(result)

/anaconda3/lib/python3.6/site-packages/vaex/jupyter/plot.py in active_selections(self)
    149             return selection
    150         selections = map(translate, selections)
--> 151         selections = list([s for s in selections if self.dataset.has_selection(s) or s in [False, None]])
    152         if not selections:
    153             selections = [False]

/anaconda3/lib/python3.6/site-packages/vaex/jupyter/plot.py in <listcomp>(.0)
    149             return selection
    150         selections = map(translate, selections)
--> 151         selections = list([s for s in selections if self.dataset.has_selection(s) or s in [False, None]])
    152         if not selections:
    153             selections = [False]

/anaconda3/lib/python3.6/site-packages/vaex/dataset.py in has_selection(self, name)
   4494     def has_selection(self, name="default"):
   4495         """Returns True of there is a selection"""
-> 4496         return self.get_selection(name) is not None
   4497 
   4498     def __setitem__(self, name, value):

/anaconda3/lib/python3.6/site-packages/vaex/dataset.py in get_selection(self, name)
   4232         """Get the current selection object (mostly for internal use atm)"""
   4233         name = _normalize_selection_name(name)
-> 4234         selection_history = self.selection_histories[name]
   4235         index = self.selection_history_indices[name]
   4236         if index == -1:

TypeError: unhashable type: 'Expression'

**Comment by maartenbreddels** [comment]
Ok thanks for the report. This is a leftover of moving to pure strings, to expressions. A workaround is this:
```python
ds.plot_widget(ds.ra*1, ds.dec, f='log1p', selection=selectionGaia.expression)
or 
ds.plot_widget(ds.ra*1, ds.dec, f='log1p', selection=str(selectionGaia))
```
I'll keep this open until fixed, thanks for all the feedback!

**Comment by andersdot** [comment]
(Thanks for writing an awesome viz package!)

The workaround gets rid of the error but doesn't do the selection in the widget

**Comment by maartenbreddels** [comment]
Thank you for the positive feedback :)
Btw, you're better off using the following pattern:
```python
ds.select(selectionGaia, name='gaia')
ds.plot_widget(.... selection='gaia')
```
These are what I called named selection, and in a future version you can modify this in the notebook gui, have a history etc.
I think that also explains why it doesn't work.. it actually checks if it is a named selection..., i should support or check that!

**Comment by maartenbreddels** [comment]
Fixed in master
