### ISSUE TITLE
Vertical and horizontal rays in data visualization of taxi dataset

### ISSUE THREAD

**Issue by hughsheehy** [vaexio/vaex#830]
When I run the taxi dataset and do a wide heatmap of the whole dataset, there are horizontal and vertical rays "shining" out from the main centers of the heatmap. 

As you zoom in they fade, but they're quite visible at intermediate zoom and are not in the actual data. 

![Annotation 2020-06-13 163331](https://user-images.githubusercontent.com/9504388/84574925-b074b580-ada1-11ea-9aac-688a0d116da0.jpg)

![Annotation 2020-06-13 095422](https://user-images.githubusercontent.com/9504388/84574912-9dfa7c00-ada1-11ea-8f55-221cccae58e2.jpg)

![Annotation 2020-06-13 163351](https://user-images.githubusercontent.com/9504388/84574903-920eba00-ada1-11ea-97b0-5fe491471202.jpg)

**Comment by JovanVeljanoski** [comment]
Hi, 

Yeah the data has some extreme outliers..  so when you zoom in enough, the outliers are excluded in the heatmap viz. 

Also when you zoom (in/out), the axes ranges change, and the grid is being recomputed each time. So while the number of bins stays the same, the "area" they cover also varies, which is the whole point, right?

There is nothing wrong with vaex here, you are just looking and weird data. 
You can verify that this is the case by doing filtering yourself..
