### ISSUE TITLE
Support dropping non-finite values efficiently?

### ISSUE THREAD

**Issue by ag-tcm** [vaexio/vaex#831]
Awesome library! Would you be able to add support for dropping/selecting only finite values? I know that currently you support dropna, dropnan, and dropmissing but sometimes we're working with datasets with inf and haven't found an efficient way to remove them without having to load all the data in memory. Computations like PCA will throw errors with inf values which is the main reason it would be nice to have this feature.
(Please see [this SO question](https://stackoverflow.com/questions/62295994/how-can-i-efficiently-remove-non-finite-values-from-a-vaex-dataframe-with-many-c) for reference.)
Thanks!

**Comment by JovanVeljanoski** [comment]
Hey @ag-tcm 

We are actually aware of that SO question, and the implementation for dropinf is basically done here #821, just pending review. You can try it out if you comfortable with a dev install, otherwise we hope to have this merged and released very soon.

**Comment by ag-tcm** [comment]
@JovanVeljanoski I hadn't seen that issue. Thanks for adding it!

**Comment by JovanVeljanoski** [comment]
This is now merged in master
