### ISSUE TITLE
Error while joining 2 dataframes: ZeroDivisionError

### ISSUE THREAD

**Issue by rivo50** [vaexio/vaex#835]
Hi,

I get the following error while trying to join 2 dataframes. One of the dataframes is in-memory(80k Lines) and the other is from a hdf5 file (over 1Mil lines). 

Thank you

5627                 lookup_left = np.concatenate([k[0] for k in lookup_extra_chunks])
   5628                 lookup_right = np.concatenate([k[1] for k in lookup_extra_chunks])
-> 5629                 left = left.concat(left.take(lookup_left))
   5630                 lookup = np.concatenate([lookup, lookup_right])
   5631 

D:\MyInstalls\anaconda3\envs\PYSOD\lib\site-packages\vaex\dataframe.py in concat(self, other)
   5217         else:
   5218             dfs.extend([other])
-> 5219         return DataFrameConcatenated(dfs)
   5220 
   5221     def _invalidate_caches(self):

D:\MyInstalls\anaconda3\envs\PYSOD\lib\site-packages\vaex\dataframe.py in __init__(self, dfs, name)
   5952         self.columns = {}
   5953         for column_name in self.get_column_names(virtual=False, hidden=True):
-> 5954             self.columns[column_name] = ColumnConcatenatedLazy([df[column_name] for df in dfs])
   5955             self._save_assign_expression(column_name)
   5956 

D:\MyInstalls\anaconda3\envs\PYSOD\lib\site-packages\vaex\column.py in __init__(self, expressions, dtype)
    195         for i in range(1, len(self.expressions)):
    196             expression = self.expressions[i]
--> 197             shape_i = (len(self), ) + expressions[i][0:1].to_numpy().shape[1:]
    198             if self.shape != shape_i:
    199                 raise ValueError("shape of of expression %s, array index 0, is %r and is incompatible with the shape of the same column of array index %d, %r" % (self.expressions[0], self.shape, i, shape_i))

D:\MyInstalls\anaconda3\envs\PYSOD\lib\site-packages\vaex\expression.py in __getitem__(self, slice)
    316 
    317     def __getitem__(self, slice):
--> 318         return self.ds[slice][self.expression]
    319 
    320     def __abs__(self):

D:\MyInstalls\anaconda3\envs\PYSOD\lib\site-packages\vaex\dataframe.py in __getitem__(self, item)
   4603                 stop = stop+1  # +1 to make it inclusive
   4604             df = self.trim()
-> 4605             df.set_active_range(start, stop)
   4606             return df.trim()
   4607 

D:\MyInstalls\anaconda3\envs\PYSOD\lib\site-packages\vaex\dataframe.py in set_active_range(self, i1, i2)
   3816         """
   3817         logger.debug("set active range to: %r", (i1, i2))
-> 3818         self._active_fraction = (i2 - i1) / float(self.length_original())
   3819         # self._fraction_length = int(self._length * self._active_fraction)
   3820         self._index_start = i1

ZeroDivisionError: float division by zero

**Comment by JovanVeljanoski** [comment]
Hey @rivo50 

Thanks for the report. I tried, but in the simplest (naive) case I could not reproduce the issue.

Can you please share a code example? Also maybe the code leading up to the join, so we can see what kind of transformations you are doing to the expressions or the dataframe that lead up to the error. 

Also, on what kind of dtypes are you doing the joining?

Thanks!

**Comment by rivo50** [comment]
Hi Jovan,

That was fast, thank you. Please find below few more details about my code.

df_APPLY_RULES2ROLES = df_RISK_RULES_vx.join(df_ROLES_W, left_on="FUNC_1", right_on="LOW", how="left",allow_duplication=True) => Had to use a pandas dataframe as I could not find a way to build a cartesian product using vaex. Is there a way similat to pandas multindex? 

**df_RISK_RULES_vx = vx.from_pandas(df_RISK_RULES)**

{'FUNC_1': array(['TREXADMIN', 'TREXADMIN', 'TREXADMIN', ..., 'VORA', 'VLAL', 'F.34'],
       dtype=object),
 'FUNC_2': array(['WORKINGAREA', 'WBDEMO', 'SWRK', ..., nan, nan, nan], dtype=object),
 'FUNC_3': array([nan, nan, nan, ..., nan, nan, nan], dtype=object),
 'FUNC_4': array([nan, nan, nan, ..., nan, nan, nan]),
 'FUNC_5': array([nan, nan, nan, ..., nan, nan, nan]),
 'RISK_ID': array(['B001', 'B001', 'B001', ..., 'SDAC', 'SDAC', 'SDMD'], dtype=object)}

**df_ROLES = vx.open(os.path.join(ERP_ROLES,"MyFile.csv.txt.hdf5"))**

{'AGR_NAME': <vaex.column.ColumnStringArrow at 0x2229728a1d0>,
 'OBJECT': <vaex.column.ColumnStringArrow at 0x2229728f710>,
 'AUTH': <vaex.column.ColumnStringArrow at 0x2229728ac88>,
 'FIELD': <vaex.column.ColumnStringArrow at 0x2229728f470>,
 'LOW': <vaex.column.ColumnStringArrow at 0x2229728fe48>,
 'HIGH': <vaex.column.ColumnStringArrow at 0x2229728f518>,
 'DELETED': <vaex.column.ColumnStringArrow at 0x2229728f080>}

**Comment by JovanVeljanoski** [comment]
Hmm.. I still can't reproduce it?

In your join example, the right table is "df_ROLES_W", but below you give a description for "df_ROLES". Can I assume that those are the same?

Can you check that perhaps you don't have any exotic entries in the joining columns, like empty strings, or something like that? 

Also, if you try to use a considerable smaller samples (like if you slice one or both of the dataframes), do you get the same (or a different) issue?

Aside:
I don't want to talk about this in this thread, to keep it focused, but for cartesian product can you do just `np.dot(df1, df2)`  (where df1 and df2 are vaex dataframes)?

**Comment by rivo50** [comment]
Hi Jovan,

It should have been df_ROLES_W, did a mistake while pasting. 

I did few tests using smaller datasets with the same result. I will test & debug further and I'll come back to you if needed. I will close this issue for now.

Thank you for your support and responsivness. 

Aside+:
I beleive that np.dot will work only if all fields are numeric, correct? 

Wishing you all the best.

**Comment by JovanVeljanoski** [comment]
Hi @rivo50, 

Let's keep this open until we figure it out.

If possible, can you maybe attach very small portions of the data that cause the issue? Or use similar but made up entries just to expose what is going wrong?

Aside:
Yes the np.dot will work only for numeric columns.. but you can do 
```
np.dot(df1[['x', 'y', 'z']], df2[['x', 'y', 'z']] )
```

**Comment by rivo50** [comment]
Hi Jovan,

I found the problem, as you assumed it was related to my data source. It seems that for certain lines there were additional trailing "spaces" included for the column I used in the join. I have done a quick test with a properly formated file and the join worked fine.

Thank you one more time for your support and the great library you guys have built.

Best regards

**Comment by JovanVeljanoski** [comment]
Glad you figured it out!
Good luck!
