### ISSUE TITLE
adding new column error

### ISSUE THREAD

**Issue by pisonir** [vaexio/vaex#837]
Hi,

I want to add a new column to my dataset after filtering it but I encounter the following error:

```
dict_dummy = {
    'x':['A','B','C'],
    'y':[0,1,2]
}

df_dummy = vaex.from_dict(dict_dummy)
df_dummy = df_dummy[df_dummy.y < 2]
df_dummy
```
![image](https://user-images.githubusercontent.com/30863615/84768752-08473280-afd5-11ea-91c8-5feca25444aa.png)

```
df_dummy['z'] = np.array(['C','D'])
```
```
ValueError: Array is of length 2, while the length of the DataFrame is 2 due to the filtering, the (unfiltered) length is 3.
```

Thank you,
Riccardo

**Comment by JovanVeljanoski** [comment]
Hi @pisonir 

Thanks for reaching out. 

Let me give a short explanation:
Vaex not copy or modify the data at all. So when you do an operation such as filtering for example
```
df2 = df[df.x > 5]
```
then `df2` actually contains all of the data of `df` (it is a shallow copy), the part of the data that is filtered out is masked/hidden. This means that in principle you can "undo" a filter. Or turn filters on/off at will.

If you want to actually modify the dataframe after some transformations done to it, like filtering, 
you need to do:
```
df2 = df2.extract()
```
That will modify some internals of the dataframe, so it can be more "independent" from the parent `df`.  However, you can't get access to the filtered out data in this case.

This is a good question btw, we will add it to the [FAQ](https://docs.vaex.io/en/latest/faq.html).

**Comment by pisonir** [comment]
Thank you @JovanVeljanoski, that's a very clear explanation!
