### ISSUE TITLE
exporting slow (evaluate as well)

### ISSUE THREAD

**Issue by maartenbreddels** [vaexio/vaex#84]
As discussed with Stephan Jordan, exporting can be quite slow, the code below took ~15h:
```python
import vaex
from pylab import *
ds = vaex.open("gaia-dr2-minimal-sort-by-source_id.hdf5“)
ds.select(".....“)
ds.add_virtual_columns_eq2gal(long_in='ra', lat_in='dec', long_out='l', lat_out='b', input=None, output=None, name_prefix='__celestial_eq2gal', radians=False)
ds.export_fits("/output.fits",selection=True,virtual=True,progress=True)
```
This is a bit long, see if we can optimize this, evaluate can be slow as well, since it is not yet multithreaded.

**Comment by JovanVeljanoski** [comment]
Will closed as @maartenbreddels has done may improvements in this area since.
