### ISSUE TITLE
Drop a row by index

### ISSUE THREAD

**Issue by druzmieres** [vaexio/vaex#841]
Is this implemented in Vaex? I couldn't find it in the docs. I also tried to do it as I would in Pandas, but it didn't work either.

Then I tried to create an empty dataframe and add the rows I need instead, but I couldn't. I tried creating an empty dataframe like this `df = vaex.dataframe.DataFrame(columns=columns)`, but it seems to need another parameter called `name` which is not clearly defined in the docs (or at least I couldn't find the definition). And anyway, the dataframes I create from files are of type `<class 'vaex.dataframe.DataFrameArrays'>` and not just dataframes, so I'm not sure which type I need to use.

About the problem:

What I have is a dataframe with "rules":
```
DataFrame A
start  | end   | number   | string
------------------------------------
 0     |   1   |    5     |   'AB'
 0     |   2   |    3     |   'CD'
``` 

And another dataframe with rows I need to filter based on `DataFrame A`.
```
DataFrame B
value  | number | string
-------------------------
 0.5   |   3    |  'CD'
```

For example, if column `value` of the first row of `DataFrame B` is between `start` and `end` of the first row of `DataFrame A` (i.e. between 0 and 1), and the `number` and `string` of that row also match, then I want to remove that column of `DataFrame B`.

In this case, the row in `DataFrame B` is first compared to the first row in `DataFrame A`. The column `value` is 0.5 and is between `start` and `end` in the first row of `DataFrame A`, but `number` and `string` don't match (3 !=5 and 'CD' != 'AB'). Then the row in `DataFrame B` is compared to the values in the second row of `DataFrame A`. This time, `value` is also in the range of `start` and `end` (between 0 and 2) and `number` and `string` match, therefore, the row in `DataFrame B` needs to be removed.

**Comment by JovanVeljanoski** [comment]
Hi @druzmieres 

Very interesting question. These kind of problems are something we have been actively thinking about. Not trivial to solve as far as I understand. 

In principle, vaex dataframes are "islands". You can do many things with them, but they are self-contained, and it is (to the best of my knowledge) not possible to reference one dataframe from the other. So I do not know a good way of handling this I am afraid..  but..

**Disclaimer**
The following is a very very bad idea. It is way too slow to be of any practical use. I am only writing it in hope it will spark a better idea on your side, and that I thought this was a relevant problem that I wanted to try. I hope @maartenbreddels will still speak to me after reading this..

```
# Create example dataframes
df1 = vaex.from_dict({'start': [0, 0],
                      'end': [1, 2],
                      'number': [5, 3],
                      'string': ['AB', 'CD']
                     })
df2 = vaex.from_dict({'value': [0.5, 3, 8, 10, 0.2, 0.3],
                      'number': [5, 10, 3, 3, 5, 3],
                      'string': ['AB', 'AA', 'EE', 'DD', 'FF', 'CD']
                     })

def decision_function(value, number, string):
    # The following line is very slow - it was not meant to be abused like this..
    count = df1.count(selection=(df1.end>value) & (value>df1.start) & (number==df1.number) & (df1.string==string))
    # Will not work if called via apply from df2 - external dataframes are not allowed.
    if count > 0:
        return 1
    else:
        return 0

# placeholder for the result - this is in memory
index = np.zeros(len(df2), dtype=np.int8)

# Iterate over the df2 dataframe in chunks, so it will not go out of memory at any point
generator = df2.to_pandas_df(chunk_size=3)
for i1, i2, chunk in tqdm(generator):
    index[i1:i2] = chunk.apply(lambda row: decision_function(row['value'], row['number'], row['string']), axis=1).values

# Finally, add the result to the dataframe
df2.add_column('index', index)
print(df2)

# now one can filter based on the newly added index column:
df3 = df2[df2['index'] == 0)  # for example
```

As I said, the above example is for inspiration only (or for great desperation). I tested it with`df1` and `df2` both having 10_000 rows, and `chunk_size~1_000` and this took ~7 minutes on my laptop.  You likely have much larger dataframes, so I don't see this being useful in practice.

How would you do it with `pandas` btw? 

Aside: regarding creation of DataFrames, [check out this guide](https://docs.vaex.io/en/latest/example_io.html#). I find the `vaex.from_arrays(x=np_array1, y=np_array2)`  and `vaex.from_dict({'x': np_array1, 'y': np_array2}` methods most convenient. 

The `vaex.dataframe.DataFrame` and the like are for internal use. If you are curious you can look for example at the `vaex.from_csv()` implementation on how it is used. The `name` argument is part of the metadata associated with each dataframe, allowing you to give "name"s or titles to each dataframe if needed.

**Comment by JovanVeljanoski** [comment]
Closing this as stale. Please reopen if needed.
