### ISSUE TITLE
Creating new column based on conditions on other columns: how to use where

### ISSUE THREAD

**Issue by alrz199** [vaexio/vaex#845]
hi
how can i create a new column in vaex baesd on conditions on other columns?. in sql i can use when-otherwise. vaex has "where" and based on documents it is a Lazy wrapper around numpy.where but i couldn't find example of use.

**Comment by maartenbreddels** [comment]
Hi,

thanks for you question:
Yes, it's current use is a bit funny:
```
df['q'] = (df.x > 0).where(df.y, df.z)
```

does that help?

cheers,

Maarten

**Comment by alrz199** [comment]
hi
thank you for example.
