### ISSUE TITLE
Joining dataframes on datetime column

### ISSUE THREAD

**Issue by mrogojanu** [vaexio/vaex#848]
Hello,

I am looking forward to optimize my project and replace Pandas with Vaex for the time series dataframes manipulation. Below is an example where I get issues: 

```
import vaex
import numpy as np
x = np.arange(5)
y = x**2
z = x**3
t1 = np.array(['2020-04-27T00:00:00.000000000', '2020-04-28T00:00:00.000000000',
              '2020-04-29T00:00:00.000000000', '2020-04-29T00:00:00.000000000',
              '2020-04-29T00:00:00.000000000'], dtype='datetime64[ns]')

t2 = np.array(['2020-04-27T00:00:00.000000000', '2020-04-28T00:00:00.000000000',
              '2020-04-29T00:00:00.000000000', '2020-04-29T00:00:00.000000000',
              '2020-04-29T00:00:00.000000000'], dtype='datetime64[ns]')

df1 = vaex.from_arrays(x=x, y=y, Date=t1)
df2 = vaex.from_arrays(z=z, Date=t2)

df = df1.join(df2, left_on='Date', right_on='Date')
df
```

Above code results in  `KeyError: 'index_hash_datetime64[ns]' ` .   

Thank you,

**Comment by JovanVeljanoski** [comment]
Hi, 

It seems like a good feature to have indeed. We started working on this in #849 , I hope we will figure it out soon.

Cheers!

**Comment by mrogojanu** [comment]
Thanks a lot, great news! 
Actually my code project is a little bit more complicated than given example.  I successful do groupby days  in Vaex which transform my datetime column from datetime64[ns] to datetime64[D] type.  After I have an operation of joinining  two dataframes, where one column is datetime64[ns] and second one is datetime64[D] type.  Normally this should  match on midnight time for the [ns] column.  This just to explain that would be great to have the functionality to take into account all  datetime options [ns, s, m, h, D, W, M, Y, etc]. This to avoid additional code lines to get equivalent units of measure for the joined dataframes , as by  `df1.Date.astype('datetime64[ns]')` on every new join.
