### ISSUE TITLE
[BUG-REPORT] Installation issue at azure/databricks platform

### ISSUE THREAD

**Issue by igorpereirabr1** [vaexio/vaex#895]
**Description**
Hey guys, i´m to try install vaex at a databricks cluster, the installation process works, but I´ve an error during the import process. Any idea about how to proceed?

**Software information**
 - Vaex version:vaex 3.0.0 
 - Vaex was installed via: pip 
 - OS: 4.15.0-1050-azure
![image](https://user-images.githubusercontent.com/29541571/87090819-f725c600-c20e-11ea-8726-5c34ff7459f9.png)

**Additional information**
![image](https://user-images.githubusercontent.com/29541571/87091297-d0b45a80-c20f-11ea-9719-713c52e7153c.png)

**Comment by igorpereirabr1** [comment]
Hey Guys, maybe we can use the databricks function dbutils.fs.ls(ptah) to confirm if the path exists,if not, use the dbutils.fs.mkdir to create them.

**Comment by mkst** [comment]
> Hey Guys, maybe we can use the databricks function dbutils.fs.ls(ptah) to confirm if the path exists,if not, use the dbutils.fs.mkdir to create them.

It looks like the process doesn't have permission to create `/root/.vaex` - it *is* trying to create that path. What user is the process running as?

**Comment by igorpereirabr1** [comment]
Hey @mkst , you are right, it's a persmission error. But also we have a different sintax to create a new path in databricks, we need to use :`dbutils.fs.mkdir()`

I'm to try test the bellow option:

```
def get_private_dir(subdir=None, *extra):
    #Custom databricks test
    try:
        dbutils.fs.ls("dbfs:/tmp/vaex")
    except:
        dbutils.fs.mkdirs("/tmp/vaex/")
    path = os.path.expanduser('/tmp/vaex')
    if subdir:
        path = os.path.join(path, subdir, *extra)
    try:
        dbutils.fs.ls(path)
    except:
        dbutils.fs.mkdirs(path)
        #os.makedirs(path)
    return path
```

**Comment by maartenbreddels** [comment]
Could you try editing $HOME ?

**Comment by igorpereirabr1** [comment]
Hey @maartenbreddels , based on your sugestion I've found a way...

`
#Change the $Home path

import os
os.environ["HOME"] = "/local_disk0/tmp/"
print(os.getenv("HOME"))`

#Install vaex
dbutils.library.installPyPI("vaex")

#remove log messages

import logging
logger = spark._jvm.org.apache.log4j
logging.getLogger("py4j").setLevel(logging.ERROR)

#remove log messages

import vaex.core as vx`

The next step it's  read the tables stored in the DBFS with delta lake format. Or maybe convert a pyspark dataframe in a vaex dataframe...

I know that I can convert to pandas and then to vaex, but in my case it's some huge tables.. so I need to investigate a bether way to do it..

Thanks all for your support!

**Comment by maartenbreddels** [comment]
Did you consider using Apache Arrow as a common format. The next version of Vaex will have even more support for Arrow.
