### ISSUE TITLE
[BUG-REPORT] Unable to read s3 file using vaex which is in snappy parquet

### ISSUE THREAD

**Issue by divyadaka** [vaexio/vaex#900]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your problem may already be discussed or addressed.

**Description**
Please provide a clear and concise description of the problem. This should contain all the steps needed to reproduce the problem. A minimal code example that exposes the problem is very appreciated.

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
 - Vaex was installed via: pip / conda-forge / from source 
 - OS:

**Additional information**
Please state any supplementary information or provide additional context for the problem (e.g. screenshots, data, etc..).

**Comment by divyadaka** [comment]
ERROR:MainThread:vaex:error opening  s3 path. 

Installed in virtual env able to import pandas
import s3fs
import numpy
import vaex

Also how to pass the profile_name ?

**Comment by JovanVeljanoski** [comment]
Hi @divyadaka 

For now, it is only possible to stream hdf5 files directly from S3.

As for specifying profile name, please check the docstring of `vaex.open()`, it is explained there.

**Comment by maartenbreddels** [comment]
This is now supported, to install:
```
$ pip install "vaex-core>=4.0.0a11"
# or for the while kitchsink:
$ pip install "vaex>=4.0.0a6"
```
