### ISSUE TITLE
drop duplicates rows 

### ISSUE THREAD

**Issue by plavallen** [vaexio/vaex#906]
Hi everyone, i am work with vaex and i don't know how i can drop duplicates row in a dataframe, pandas has a function drop_duplicates to do this. are there in vaex something like that?

**Comment by JovanVeljanoski** [comment]
Hi, 

This is a non trivial problem actually and we do not have a official implementation of this yet. 
There was a discussion here #746 , maybe you can read through and see if that works for you right now.

Cheers, 
J.

**Comment by plavallen** [comment]
Hi Jovan, thanks for your quick response!!. I saw that discussion and
I'm working on it now

Cheers,

**Comment by JovanVeljanoski** [comment]
Cool. I will close this. If you have any questions or concerns on this topic, let's use the other issue so all the discussion is in one place. 

Thanks!
