### ISSUE TITLE
[FEATURE-REQUEST] Make some dependencies optional (e.g. as part of extras)

### ISSUE THREAD

**Issue by hmonteiro** [vaexio/vaex#907]
**Description**
At the moment, installing `vaex` brings along quite a few dependencies (around 100, taking around 183MB in total). A few of these are related to visualization or working within a jupyter environment, which is not always going to be used if, for example, one is only interested in using it for the performance increase in data processing.

It would be great if some of these dependencies could be split to the extras part and be installed only on demand. For example if one wanted the vizualisation features, we would install with `pip install vaex[viz]`, or we could use `vaex[ml]` or `vaex[jupyter]` if one wanted to use the machine learning capabilities or the jupyter helpers.

Having this type of optional dependencies makes using this package in production a lot easier as we could control exactly what features are turned on, thus controlling the dependencies that are installed, which allows saving both space, startup time in microservices architectures, and compliance headaches (having to justify having frontend javascript in a backend service for example).

**Comment by JovanVeljanoski** [comment]
Hi, 

Actually, this is already possible.  If you read[ the documentation](https://docs.vaex.io/en/latest/), you will see that vaex is already separated in various packages that cover the functionality. 

Installing vaex, you install the meta-package, which installs all packages. You can choose to install, vaex-core only, to get only the dataframe capabilities for example, or vaex-core and vaex-hdf5, if you want to read from hdf5 and so on. 

This is possible both via pip and conda (conda-forge). 
I hope this helps!

**Comment by hmonteiro** [comment]
Ah, great, thanks for that (I should RTFM :) ). I would then suggest you add README files to each of those projects so that it is more visible that they can be used on their own (and what they functionality they contain) when you visit for example https://pypi.org/project/vaex-core/ 

Thanks again for pointing me in the right direction!

**Comment by JovanVeljanoski** [comment]
I agree, we should definitely improve the documentation there, and perhaps on our doc pages at all.
Cheers.
