### ISSUE TITLE
Question: Does Vaex support the regular python slice notation? 

### ISSUE THREAD

**Issue by betolink** [vaexio/vaex#911]
This is most likely a dummy question but I want to "decimate" a big data frame and I couldn't find a native function for this or how to use the simpler slice notation i.e. 
```python
df.column[::1000]
```
but I got this
```bash
AssertionError                            Traceback (most recent call last)
<timed exec> in <module>
   4616                 stop = len(self)+stop
   4617             stop = min(stop, len(self))
-> 4618             assert step in [None, 1]
   4619             if self.filtered:
   4620                 count_check = self.count()  # fill caches and masks
```
thanks.

**Comment by JovanVeljanoski** [comment]
Hi, 

Yeah this is not yet supported. Can you please give us some info of your use-case and what you are trying to achieve? 

For now, this is a possible work around:
```
import vaex

df = vaex.example()

df.add_column('index', vaex.vrange(0, len(df)))   # vaex.vrange() is like numpy.arange but uses 0-memory no matter the length.
df_decimated = df[(df.index % 100 == 0)]
```
It is a bit over the top, but at least it is something until we figure this out. 
Thanks!

**Comment by betolink** [comment]
Thanks for the quick response, I'm working with lidar data loaded from HDF5 files, each file is like 1GB or 7 million rows and the resolution is high so I want to downsample the data frame to plot "the big picture" faster.

**Comment by maartenbreddels** [comment]
Yeah, we don't implement the step, because it will lead to bad performance. Maybe we should have a better msg for that, since I'd rather not support it.
An alternative would be for instance:
```
df.export('shuffled.hdf5', shuffle=True)
dfs = open('shuffled.hdf5')[:1_000_000]
```
And work with the a random set of 1 million rows. In this way the random sample is a contiguous array, and performance will be good.

**Comment by JovanVeljanoski** [comment]
I guess the usecase is downsampling, so random shuffling is not the same. 

Is there a way we could implement a "take every nth sample" method that would be performant @maartenbreddels ?  This can be useful for certain time series stuff.

**Comment by maartenbreddels** [comment]
Hmm, that does make sense, I'm not sure though if we want to implement that using the slice notation since that gives the impression that it's a cheap operation.

**Comment by JovanVeljanoski** [comment]
Yeah indeed, does not have to be a slice operation, but an appropriately named method. We can think about it at least.
