### ISSUE TITLE
Feature for groupby on datetime or similar to pd.resample(timedelta) [FEATURE-REQUEST]

### ISSUE THREAD

**Issue by paramrajpura** [vaexio/vaex#914]
I am thankful to Vaex community for the help and support!

**Description**
Allow data to be grouped by a column of type "Datetime" to the extent of hours, minutes, seconds and millliseconds.
I could find BinnerTime (df.groupby(vaex.BinnerTime.per_day(df.DateTime)).agg({'Total observations': 'sum'})) to use it for day however the other resolutions will be very helpful.

**Additional context**
Posting this after trying to find something similar to [pd.df.resample](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html).
Also discussed about in #421 .

**Comment by JovanVeljanoski** [comment]
Hi @paramrajpura 

Grouping per datetime interval is already possible. Check out the example below:

```
import vaex
import pandas as pd
import numpy as np

# Create example data
dt = np.array(pd.bdate_range(start='2015-01-01', end='2015-05-25', freq='5min'))
x = np.random.normal(size=len(dt))
df = vaex.from_arrays(dt=dt, x=x)

# Groupby
# Per month
group_per_month = df.groupby(by=vaex.BinnerTime(df.dt, resolution='M'), agg={'count': 'count',
                                                                             'mean_x': vaex.agg.mean(df.x)})

# Per week
group_per_week = df.groupby(by=vaex.BinnerTime(df.dt, resolution='W'), agg={'count': 'count',
                                                                            'mean_x': vaex.agg.mean(df.x)})

# Per hour
group_per_hour = df.groupby(by=vaex.BinnerTime(df.dt, resolution='h'), agg={'count': 'count',
                                                                            'mean_x': vaex.agg.mean(df.x)})

# Per minute
group_per_minute = df.groupby(by=vaex.BinnerTime(df.dt, resolution='m'), agg={'count': 'count',
                                                                              'mean_x': vaex.agg.mean(df.x)})
```

Is this something you had in mind? 
Please re-open the issue if you encounter problems or you had something else in mind.
