### ISSUE TITLE
memory strangeness with multi-column groupby

### ISSUE THREAD

**Issue by matt-erhart** [vaexio/vaex#919]
```python
#arrows is df with 38 million rows, col1 & col2 are strings, amount is float
#running this has my memory usage increase from 1gb to 100gb in activity monitor, eventual kernel shutdown
arrows = vaex.open('./*.arrow') # 38 files
df1 = arrows.groupby(['col1', 'col2'] , agg=[vaex.agg.sum(arrows.Amount)]) # 2 cols memory increases until crash
```

```python
# one column nice and fast, no problem
arrows = vaex.open('./*.arrow') # 38 files
df1 = arrows.groupby('col1' , agg=[vaex.agg.sum(arrows.Amount)]) #works
```

 - Vaex version {'vaex-core': '2.0.3',
 'vaex-viz': '0.4.0',
 'vaex-hdf5': '0.6.0',
 'vaex-server': '0.3.1',
 'vaex-astro': '0.7.0',
 'vaex-jupyter': '0.5.2',
 'vaex-ml': '0.9.0',
 'vaex-arrow': '0.5.1',
 'vaex-graphql': '0.1.0'}
 - Vaex was installed via: conda-forge
 - OS: macos catalina

**Comment by JovanVeljanoski** [comment]
Hi, 

How many unique values do you have in `col1` and `col2`? Can you check this please?
The result of the groupby operation is an in-memory DataFrame, so you need to make sure that you can hold the output.

Cheers, 
J.

**Comment by matt-erhart** [comment]
~500k in col1, and ~2k in the other.

**Comment by JovanVeljanoski** [comment]
So that means the resulting dataframe will have 3 columns and 1_000_000_000 rows (billion!). Do you have enough RAM to handle that?

**Comment by matt-erhart** [comment]
32gb, so seems not. Would be great to have a bit more in the docs on how vaex differs from pandas or dask for groupbys. I personally do a ton of groupbys and was hoping vaex could handle larger datasets with low memory use. Just trying out, I wasn't sure if I wasn't using vaex right, e.g. via some setting/parameter, or I wasn't applying it to the right problem, and I'd bet other new testers will run into the same situation.

**Comment by JovanVeljanoski** [comment]
In the future we might be able to solve this issue by writing the grouped dataframe to disk directly, so one will not need as much RAM as now. Perhaps @maartenbreddels can comment on that.

**Comment by matt-erhart** [comment]
https://towardsdatascience.com/faster-pandas-with-parallel-processing-cudf-vs-modin-f2318c594084

Rapids/cudf might have a trick up its sleeve for dealing with small amounts of GPU memory, but I'm just learning the ecosystem and when to use what. 

Just out of curiosity, could something like itertools.product(unique(col1),unique(col2)) (but a c++ equivalent) help or would that break down when running the aggregate function and/or be crazy slow.

**Comment by JovanVeljanoski** [comment]
It is not about running, vaex is fully out of core. It is about storing the output result.

**Comment by matt-erhart** [comment]
Aha, makes sense. Thanks.
