### ISSUE TITLE
How to use vaex to work like this SQL?

### ISSUE THREAD

**Issue by qinglok** [vaexio/vaex#926]
select c1, c2, count(*), count(DISTINCT c3) 
from t1
group by c1, c2

**Comment by JovanVeljanoski** [comment]
Hi, 

Please refer to the [documentation](https://vaex.readthedocs.io/en/latest/) (the [tutorial](https://docs.vaex.io/en/latest/tutorial.html) is a good way to start) to learn how to use vaex.

For other questions on how to use vaex, perhaps StackOverflow is a better resource, as we try to keep GitHub for technical issues and the like.
