### ISSUE TITLE
Groupby on multiple columns 

### ISSUE THREAD

**Issue by abaradia1978** [vaexio/vaex#929]
Hi,

I am trying to use groupby on a dataset with 200mn rows (13GB of data). It's a HDF5 file and has 20 columns. It works fine if I perform groupby on 3-4 columns. But if I try to perform groupby on 8-10 columns and aggregate (sum) on one column, it triggers a very high CPU and Memory usage and finally exists the process. I am using Jupyter notebook to do this activity on a server with 8 cores and 100GB of RAM. 

I don't consider this to be a very large dataset and server size should have ideally managed this load. Or am I missing something?

I even tried to split the vaex dataframe in 4 equal size and perform the same operation on one split dataframe. Still it would break because of high CPU/Memory requirement.

The command is as under:

`df.groupby(by=['product_code','product_category','product','sub_product','business_segment','region','state','city','c_year','c_quarter','c_month'],agg={ 'cnt' : vaex.agg.count() } )`

**Comment by JovanVeljanoski** [comment]
Hi, 

Perhaps can you are hitting the case discussed here: https://github.com/vaexio/vaex/issues/919

Can you check that you can hold the output dataframe (the grouped dataframe) in memory?

Cheers, 
J.

**Comment by abaradia1978** [comment]
Unique values in my dataset are not more than 50 in each column on which groupby is performed. And also data does not exists for all combinations of values across these columns. I ran below code to see uniqueness across all these columns.

```
def combine(a,b,c,d,e,f,g,h,i,j,k):
    return a + '_' + b + '_' + c + '_' + d + '_' + e + '_' + f + '_' + g + '_' + h + '_' + i + '_' + j + '_' + k

df['combined'] = combine(df.product_code,df.product_category,df.product,df.sub_product,df.business_segment,df.region,df.state,df.city,df.c_year,df.c_quarter,df.c_month)

df.combined.nunique()
```
The count was only 48896. The granular data is 13GB and RAM available is 100GB. Isn't this enough to group data?

I also noticed very high CPU usage which at times reaches 90% and then it crashes.

**Comment by JovanVeljanoski** [comment]
Hi, 

I am not sure I am correct about this.. but say you are doing a groupby on  just two columns, where column "a" has 2 unique values and column "b" has 3 unique values. Say you do just one aggregation on top of that groupby. The output would be a dataframe with 6 rows (2 * 3), and 3 columns (one for the aggregation specified and 2 for the columns you are grouping by). 

In your case, you are using 11 columns to do the groupby on. Say each of those columns has 10 unique values. That means that the number of output rows will be 10**11 -> 100 billion rows! And you are having 12 columns. You can't keep that into memory, hence it is crashing. 

It does not matter if some of those combinations have no values. Those combinations will be made, and if there are no values, there will be nan or something there. 

Does this make sense?

**Comment by abaradia1978** [comment]
Thanks @JovanVeljanoski for your reply.

column "a" with 2 unique values and column "b" with 3 unique values may not necessarily result in 6 rows. It depends on the underlying data. The raw data may not have all combination of unique values of column a and column b. 

Also why should we populate a NAN row if some of those combinations have no values - in my mind, this seems to be incorrect at least in my use case. May be there can be a flag in groupby function if any user needs a NAN row for combinations with no values.

In my case as mentioned above, I added a new virtual column - joining values of all 11 columns separated by "_". The nuinque function on that new virtual column resulted in only 48896 rows - so it is not 100 billion rows. 

Further, I did group by on that new virtual column and it worked. It worked on the same system, same CPU and same RAM. It took 9mins though - But now I have an additional step to again split the combined column into 11 columns in grouped dataframe. My code for this is as under:
```
def combine(a,b,c,d,e,f,g,h,i,j,k):
    return  a + '_' + b + '_' + c + '_' + d + '_' + e + '_' + f + '_' + g + '_' + h + '_' + i + '_' + j + '_' + k

df['combined'] = combine(df.product_code.astype(str),df.product_category,df.product,df.sub_product,df.business_segment,df.region,df.state,df.city,df.c_year.astype(str),df.c_quarter,df.c_month)

df_cg = df.groupby(by=['combined'],agg={ 'cnt' : vaex.agg.count() } )
df_cg_p = df_cg.to_pandas_df(['combined','cnt']) #converted to pandas to make next 2 lines work - it didn't work on vaex dataframe
colnames = ['product_code','product_category','product','sub_product','business_segment','region','state','city','c_year','c_quarter','c_month']
df_cg_p[colnames] = df_cg_p.combined.str.split("_")[0]
dd = vaex.from_pandas(df_cg_p) #to convert it back to vaex
 ```

So it just indicates that vaex group by function has some overhead which can be avoided. I looked into the code and narrowed down on line which would break the groupby on 11 columns. Line 256 in vaex\groupby.py which I guess does lazy execution of aggregation promise.

`self.df.execute()`

I also noticed some comments which seems there is some TODO planned to better it and I guess non existing pairs is being taken care of as per the comment - isn't it?
```
# TODO: this basically forms a cartesian product, we can do better, use a
# 'multistage' hashmap
arrays = super(GroupBy, self)._agg(actions)
# we don't want non-existing pairs (e.g. Amsterdam in France does not exist)
```

**Comment by JovanVeljanoski** [comment]
Hi,

Yes you are right -  the non-existent combinations are ignored. But as you have seen in the code, vaex currently does the cartesian product, so it takes all combinations into account initially, even the non existent ones, which is where the problem with memory happens. 

We plan to improve on this in the future, but I can not speculate as to when it will happen. 

But if you have found a work-around, at least temporarily, that is great!

**Comment by maartenbreddels** [comment]
Great workaround, and we indeed want to improve this. Now with better Arrow support, this should be easier to do, keeping this open to track this.

**Comment by 99snowleopards** [comment]
thank you for releasing this amazing library! I have a follow-up question on groupby with vaex, so I'm continuing the open thread here, please let me know if you'd like me to open a new Issue.

w.r.t the comment by @JovanVeljanoski about holding the output of a grouped dataframe in memory, and also the comment here:

https://github.com/vaexio/vaex/issues/919

"In the future we might be able to solve this issue by writing the grouped dataframe to disk directly, so one will not need as much RAM as now. Perhaps @maartenbreddels can comment on that."

what would your advice be to deal with a grouped df that cannot be held in memory

the groupby is an unavoidable intermediate step that is blocking me from using Vaex - Vaex is very efficient in all of the steps before and after the groupby!

would greatly appreciate your feedback here, thanks,

**Comment by maartenbreddels** [comment]
Just an update: I think we can do this efficiently, i have some good ideas. Let's say we try to attach this for version 4.1.

**Comment by 99snowleopards** [comment]
that's great to hear @maartenbreddels !!! thanks for the update - eagerly looking forward to the updates on efficient groupby!

**Comment by JovanVeljanoski** [comment]
This topic is now being worked on: please check https://github.com/vaexio/vaex/pull/1381 for updates.
