### ISSUE TITLE
AttributeError: module 'vaex.ml' has no attribute 'KBinsDiscretizer

### ISSUE THREAD

**Issue by rishabh2408** [vaexio/vaex#930]
Hi,

As per documentation(https://vaex.readthedocs.io/en/latest/tutorial_ml.html#KBinsDiscretizer). 

I am trying to use the KBinsDiscretizer for binning my data, but it shows the error:
```AttributeError: module 'vaex.ml' has no attribute 'KBinsDiscretizer'```
when I try to run
```kbdisc = vaex.ml.KBinsDiscretizer(features=['y_train_column'],n_bins=10,strategy='quantile')```

**Comment by JovanVeljanoski** [comment]
Hi,

That feature is merged in master, but it is not released yet. Should be part of the next release.
If you would like to try it out, you will need to install vaex from source. 

Let me know if you need help on how to do this.

**Comment by rishabh2408** [comment]
Hi Jovan,

Thanks for the quick reply, I'll try with source for now.

Is there a schedule for the release where I can track the feature?

**Comment by JovanVeljanoski** [comment]
It should happen "soon" :) but I don't think there is a firm date. I hope by the end of September, or earlier hopefully.

**Comment by rishabh2408** [comment]
Ok, Thank you for the update and the note 😄
