### ISSUE TITLE
Pycharm is not printing vaex dataframe column

### ISSUE THREAD

**Issue by salwaen** [vaexio/vaex#931]
when I run this code  in Pycharm 

````
x = np.arange(5)
y = x ** 2
df = vaex.from_arrays(x=x, y=y)
print(df.x)

````
### I get only this
    x
### and in Python Console

````
>>> import vaex, numpy as np
>>> x = np.arange(5)
>>> y = x ** 2
>>>df =  vaex.from_arrays(x=x, y=y)
>>>df.x
>>> Expression = x
Length: 5 dtype: int32 (column)

0  0
1  1
2  2
3  3
4  4
````
I am using Python 3.6

**Comment by maartenbreddels** [comment]
```
> print(df.x)
```

this means print the expression, and will call `df.x.__str__()`,. which will print the string expression, so that's correct.

```
>>> df.x
```

This will call `df.x.__repr__()`, which explains the difference.
Use `print(repr(df.x))` is you need to use print.

**Comment by salwaen** [comment]
it works.

Thanks all for your support!
