### ISSUE TITLE
MemoryError bad_alloc when doing groupby and agg

### ISSUE THREAD

**Issue by suchiek** [vaexio/vaex#933]
**I was able to successfully execute this query on the first 5,000,000 million records of my data frame:**
```
test = dv.head(5_000_000)
test.groupby(test[‘col1’], agg={'sum_data':vaex.agg.sum(test[‘col2’]), 
                                ’count_usid':vaex.agg.nunique(test[‘col3’]),
                                ’count_pdate':vaex.agg.nunique(test[‘col4’])})

```

**But then when I try to execute the query on the first 10,000,000 million records of my data frame:**
```
test = dv.head(10_000_000)
test.groupby(test[‘col1’], agg={'sum_data':vaex.agg.sum(test[‘col2’]),
                                ’count_usid':vaex.agg.nunique(test[‘col3’]),
                                ’count_pdate':vaex.agg.nunique(test[‘col4’])})
```

**I am getting this error:**
ERROR:MainThread:vaex.execution:error in task, flush task queue
…..
….
  File "/home/…/…/lib/python3.7/site-packages/vaex/agg.py", line 138, in _create_operation
    agg_op = agg_op_type(grid, self.dropmissing, self.dropnan)
MemoryError: std::bad_alloc

**After getting this error, I tried again with the first 5,000,000 million records, and I am now getting a MemoryError trying to execute even that.**

**Any ideas as to why this is happening?**

**Comment by JovanVeljanoski** [comment]
Hi, 

Can you tell us how you installed vaex, which version and  on which platform/OS.

Also, can you provide more info on the data, for instance dtype for each of the columns you are using?

Something to try: 
 - can you do `nunique`on all those columns individually without the group-by operation, and tell us what those numbers are?
 - can you try leaving out of the 3 aggregation functions and do just 1 or 2 at a time and see if that works?

Thanks for the report!

**Comment by abaradia1978** [comment]
@suchiek - try to manually clear the memory before next run of group by

```
import gc
gc.collect()
```

Also, you may use below function to keep checking the memory used by your process. I picked up this function from one of the stackoverflow issues - it helps me to see what's happening after each step. It will only work on Linux.

```
def getCurrentMemoryUsage():
    ''' Memory usage in kB '''

    with open('/proc/self/status') as f:
        memusage = f.read().split('VmRSS:')[1].split('\n')[0][:-3]

    return int(memusage.strip())

print(((getCurrentMemoryUsage()/1024)/1024))
```

**Comment by maartenbreddels** [comment]
Closing this is stale / needs more information.
