### ISSUE TITLE
[BUG-REPORT] Multi column groupby operations failing causing kernel error 

### ISSUE THREAD

**Issue by gaganmalhotra** [vaexio/vaex#934]
**Description**
While doing a group by aggregation on multiple columns i see a kernel died error due to segmentation fault.

**Software information**
- Package installation {'vaex': '3.0.0', 'vaex-core': '2.0.3', 'vaex-viz': '0.4.0', 'vaex-hdf5': '0.6.0', 'vaex-server': '0.3.1', 'vaex-astro': '0.7.0', 'vaex-jupyter': '0.5.2', 'vaex-ml': '0.9.0', 'vaex-arrow': '0.5.1'}

 - OS: Linux <ip-xx-xx-xx-xxx> <x.xx.xxx-xxx.xxx.amzn1.x86_64> #1 SMP Tue Jul 14 02:57:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Additional information**
Please find the code i tried below - 
```
import vaex
dd = vaex.example()
dd.groupby([dd.x, dd.y]).agg('mean')

```
![Screen Shot 2020-08-14 at 5 51 43 PM](https://user-images.githubusercontent.com/10791093/90301800-db898d00-de56-11ea-8fa2-7216a98b46e5.png)

**Comment by gaganmalhotra** [comment]
@JovanVeljanoski

**Comment by JovanVeljanoski** [comment]
This is not a bug. You simply do not have enough resources to store the output of this operation. 
Look at this issue for more details: https://github.com/vaexio/vaex/issues/919

The output of the operation you suggest will be 3 (columns) x 100 billion (samples). You probably can't hold that in memory, hence it kernel dies.

```
import vaex
df = vaex.example()
df.x.nunique() * df.y.nunique()
# outputs 108509630463
```
