### ISSUE TITLE
Does Vaex have a logo?

### ISSUE THREAD

**Issue by rgommers** [vaexio/vaex#935]
Hi, I was looking for a Vaex logo to include in an overview of dataframe libraries, and as far as I can tell there is no logo. So opening an issue as a "feature request", or in case I'm missing something.

**Comment by JovanVeljanoski** [comment]
There is in fact a logo.  I will attach it here for convenience. I hope this helps. 


![vaex-logo](https://user-images.githubusercontent.com/18574951/90343540-a1181f80-e011-11ea-8ff5-bb21e5fdc71c.png)

![logo](https://user-images.githubusercontent.com/18574951/90343543-a2e1e300-e011-11ea-8a69-9c12baf07f8e.png)

**Comment by rgommers** [comment]
Awesome, thank you. I'll use the bottom one for now, because it has a transparent background. If you have the top one with a transparent background as well, that'd be even better.
