### ISSUE TITLE
[BUG-REPORT] Columns disappearing after shallow copy

### ISSUE THREAD

**Issue by kkontoudi-dd** [vaexio/vaex#938]
**Description**
Hello,

I noticed that performing a shallow copy of columns causes the rest of the columns to disappear. I think this behaviour is not expected. Am I missing something?

Here is a minimal reproducing example:
```
import pandas as pd
import vaex as vx

a = pd.DataFrame({'col1': [1], 'col2': [2]})
df = vx.from_pandas(a)
df[["col1"]]
df.materialize('col2')
```

This snippet causes:
```
KeyError: "Virtual column not found: 'col2'"
```

**Software information**
 - Vaex version: 3.0.0
 - Vaex was installed via: pip
 - OS: Ubuntu 18.04.4 LTS

**Comment by JovanVeljanoski** [comment]
Hi, 

This is not a bug. 'col2' is not a virtual column, you created it via pandas, so it is an in-memory column. 

If you do `df["col3"] = df.col1 + df.col2`, "col3" would be a virtual column, and you can materialize that.

I hoe this helps, 
J.
