### ISSUE TITLE
select random Rows in Vaex dataframe

### ISSUE THREAD

**Issue by salwaen** [vaexio/vaex#942]
###  in panda
````
x = np.arange(6)
y = np.array([10, 20, 30, 40, 50, 60])
z = np.array(['x', 'y', 'z', 'f', 'b', 's'])
df_panda = pd.DataFrame({'x':x, 'y':y, 'z':z})

df_panda = df_panda.loc[df_panda.index.isin([1,3,5])]

````
### Output

````
     x   y  z
1  b  20  y
3  d  40  f
5  f  60  s
````
### in vaex I can only select nonrandom rows 

````
df_vaex = vaex.from_arrays(x=x, y=y, z=z)
df_vaex[:3]

````
### Output
````
#  x      y  z
  0  a     10  x
  1  b     20  y
  2  c     30  z

````
is there another solution or idee? 
thanks

**Comment by JovanVeljanoski** [comment]
Yes, check out the  `df_vaex.sample(...)` method

**Comment by salwaen** [comment]
thanks for reply, sorry  i want specific row as in my example above . rows (1,3,5)

**Comment by maartenbreddels** [comment]
http://docs.vaex.io/en/latest/api.html#vaex.dataframe.DataFrame.take

(from mobile phone)
