### ISSUE TITLE
Convert data types of a Vaex dataframe to  another data types

### ISSUE THREAD

**Issue by salwaen** [vaexio/vaex#944]
Hi, 

### I tried theis solution But it didn't really solve my problem

````
x = ['a', 'b', 'c', 'd', 'e', 'f']
y = np.array(['10', '20', '30', '40', '50', '60'])
z = np.array(['x', 'y', 'z', 'f', 'b', 's'])
df_vaex = vaex.from_arrays(x=x, y=y, z=z)

df_vaex.y = df_vaex.y.astype('float64')
print(df_vaex.dtypes) 

`````
### Output

````
x    <class 'str'>
y    <class 'str'>
z    <class 'str'>
dtype: object

````

it's a bug or is there another function for convert i haven't found?  
thanks all for your support.

**Comment by JovanVeljanoski** [comment]
Not sure it is a bug.. `df.y` is more like a shirtcut to get stuff, you can't assign stuff to it.

This is how you would do it
```
df_vaex['y'] = df_vaex.y.astype('float64')

```

**Comment by salwaen** [comment]
Super, Thanks

**Comment by krkakade** [comment]
Hi I am trying to convert object data types to str
df_vaex['y'] = df_vaex.y.astype('str') 
gives error
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

I tried below but still same error
df_vaex['y'] = df_vaex.y.fillna(value='M').astype('str') 
df_vaex['y'] = df_vaex.y.fillnan(value='M').astype('str') 

I am stuck from morning on this.. can anyone help please..

**Comment by salwaen** [comment]
This error appears if column has type string and would like to convert it to string again
you can use replace
````
df_vaex['y'] = df_vaex['y'].str.replace('NaN', 'm')

''''

**Comment by krkakade** [comment]
thank you so much :)
It worked.

**Comment by krkakade** [comment]
Hi .. sorry I just checked dtype yesterday.
It is keeping it in the string format but not changing the NA values..

I tried below code
df_vaex['y'] = df_vaex['y'].str.replace(None, 'm')
but it gives error : 

  replace(): incompatible function arguments. The following argument types are supported:
    1. (self: vaex.superstrings.StringSequenceBase, arg0: str, arg1: str, arg2: int, arg3: int, arg4: bool) -> vaex.superstrings.StringSequenceBase

Invoked with: <vaex.superstrings.StringList64 object at 0x000001928C92ED30>, None, 'm', -1, 0, False



If I use fillna then it gives object. But I want string. 
Can you please help.

**Comment by salwaen** [comment]
Hi,
i use this code to fill None with blank values(white space) in column with type string
````
vaex_df = vaex_df.fillna(value='', column_names=['Name'])

````
does it help you?

**Comment by dharik-arsath** [comment]
Hi how  to change the data type of a column from string to category in vaex

**Comment by NickCrews** [comment]
People, if you want help then you'll need to file new issues. This issue is closed so the maintainers aren't seeing these questions.
