### ISSUE TITLE
[BUG-REPORT] Segmentation Fault

### ISSUE THREAD

**Issue by amir-abdi** [vaexio/vaex#945]
**Description**
After applying `groupby`, and when running aggregation (`agg`), a segmentation fault is thrown and the process is killed. My understanding is that vaex is taking more memory that is was allowed by the operating system and this is causing the issue. However, I could not find any way to "limit" the memory available to Vaex. If there is a way, that would be a valuable addition to the documentation.

**Software information**
 - Vaex version: 3.0.0 (`import vaex; vaex.__version__)`:
 - Vaex was installed via: conda
 - OS: Red Hat linux 

**Additional information**
- I'm loading a very huge file. Smaller files are working fine.

**Comment by JovanVeljanoski** [comment]
Hi, 

Can you please read through #929 and/or #919. 
Is this also what you are experiencing? 

Cheers, 
J.

**Comment by JovanVeljanoski** [comment]
Will close this as duplicate. Let's follow the issues mentioned above, so anyone interested can find all info in one place.

Thanks!
