### ISSUE TITLE
[BUG-REPORT] IncrementalPredictor prediction raises KeyError

### ISSUE THREAD

**Issue by crimsonmote** [vaexio/vaex#951]
**Description**
IncrementalPredictor can fit but to predict produces the following error:

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`:
{'vaex': '3.0.0',
 'vaex-core': '2.0.3',
 'vaex-viz': '0.4.0',
 'vaex-hdf5': '0.6.0',
 'vaex-server': '0.3.1',
 'vaex-astro': '0.7.0',
 'vaex-jupyter': '0.5.2',
 'vaex-ml': '0.9.0',
 'vaex-arrow': '0.5.1'}
 - Vaex was installed via: pip 
 - OS: Arch Linux (Kernel 5.8.1)

**Additional information**
IncrementalPredictor can fit but to predict produces the following error:

Traceback (most recent call last):

  File "/home/***/venv38/lib/python3.8/site-packages/vaex/scopes.py", line 97, in evaluate
    result = self[expression]

  File "/home/***/venv38/lib/python3.8/site-packages/vaex/scopes.py", line 144, in __getitem__
    raise KeyError("Unknown variables or column: %r" % (variable,))

KeyError: "Unknown variables or column: 'incremental_prediction_function(dummy_awarding_agency_code_3, ......

relevant code:
`import vaex.ml`
`from vaex.ml.sklearn import Predictor, IncrementalPredictor`
`from sklearn.linear_model import SGDRegresso`

`dfm_train, dfm_test = dfm.ml.train_test_split()`
`sgd=SGDRegressor(loss="epsilon_insensitive", penalty="elasticnet")`
`svr_elasticnet = IncrementalPredictor(model=sgd, features=fcols, target="some_target", prediction_name='pred',num_epochs=1,batch_size=500000, shuffle=True)`
`svr_elasticnet.fit(dfm_train, progress="widget")`

then 

`dfm_train = svr_elasticnet.transform(dfm_train)`
`dfm_train.pred`

produces the above

**Comment by JovanVeljanoski** [comment]
Hey @crimsonmote 

Thanks for trying out vaex (and vaex-ml). 

I can't reproduce the error with my sample datasets. However, looking at the stacktrace, the problem seems to be related to the input features. 

To narrow down the problem, can you please start with a couple of features, and iteratively add more until you encounter the problem? 

Potentially problematic features may be those that are over-written at some point.  Although I am surprised this is exposed at prediction, not at training time. 

Any extra information you can share about the data and how it is created would be useful in tracking the issue here.

As a sanity check, can you please run the following block and make sure it works for you?
```
import vaex
import vaex.ml
from vaex.ml.sklearn import Predictor, IncrementalPredictor
from sklearn.linear_model import SGDRegressor

# Get data
df = vaex.ml.datasets.load_iris_1e5()
df_train, df_test = df.ml.train_test_split(verbose=False)

features = df_train.column_names[:3]
target = df_train.column_names[3]

# Define model
sgd=SGDRegressor(loss="epsilon_insensitive", penalty="elasticnet")
svr_elasticnet = IncrementalPredictor(model=sgd, 
                                   features=features, target=target, 
                                   prediction_name='pred',
                                   num_epochs=1,
                                   batch_size=10_000, 
                                   shuffle=True)
svr_elasticnet.fit(df_train, progress="widget")

# get predictions
df_train = svr_elasticnet.transform(df_train)
df_train.pred
```

Thanks!

**Comment by crimsonmote** [comment]
Thank you for the prompt reply!

For more information, this is a large dataset with around 2000 columns and 15 million rows.
The columns are mostly generated with vaex.ml.OneHotEncoder from an original dataset with many categorical string columns.
The onehot columns are quite sparse.

I ran the sanity check and it worked instantly without any issue. "pred" is outputed.

**Comment by JovanVeljanoski** [comment]
Hi, 

That should not matter.. as long as you can fit 1-2 batches into memory, it should not matter. Maybe check if there are any collisions in the feature names? See if maybe there are some "weird" column names (e.g. containing special characters) Maybe you can try smaller batch sizes as well. 

Maybe try with one-2 of transformer original features at a time (I mean 1-2 original features converted to encoded features).

**Comment by JovanVeljanoski** [comment]
Hi, 

I tried to recreate a an example based on your description, and for me this works. Can you check on your end please?

```
import vaex
import vaex.ml
from vaex.ml.sklearn import Predictor, IncrementalPredictor
from sklearn.linear_model import SGDRegressor
import numpy as np


size = 500_000
data = {'x0': np.random.choice(a=range(100), size=size, replace=True),
        'x1': np.random.choice(a=range(100), size=size, replace=True),
        'x2': np.random.choice(a=range(100), size=size, replace=True),
        'x3': np.random.choice(a=range(100), size=size, replace=True),
        'x4': np.random.choice(a=range(100), size=size, replace=True),
        'x5': np.random.choice(a=range(100), size=size, replace=True),
        'x6': np.random.choice(a=range(100), size=size, replace=True),
        'x8': np.random.choice(a=range(100), size=size, replace=True),
        'x9': np.random.choice(a=range(100), size=size, replace=True),
        'x10': np.random.choice(a=range(100), size=size, replace=True),
        'x11': np.random.choice(a=range(100), size=size, replace=True),
        'x12': np.random.choice(a=range(100), size=size, replace=True),
        'x13': np.random.choice(a=range(100), size=size, replace=True),
        'y': np.random.normal(size=size)
        
       }

df = vaex.from_dict(data)
df_train, df_test = df.ml.train_test_split(verbose=False)

# Features to encode
features = df_train.get_column_names(regex='x')
target = 'y'

encoder = vaex.ml.OneHotEncoder(features=features)
df_train = encoder.fit_transform(df_train)

# Features to train on
features = df_train.column_names[9:]

# Train a model
sgd=SGDRegressor(loss="epsilon_insensitive", penalty="elasticnet")
svr_elasticnet = IncrementalPredictor(model=sgd, 
                                   features=features, target=target, 
                                   prediction_name='pred',
                                   num_epochs=1,
                                   batch_size=10_000, 
                                   shuffle=True)
svr_elasticnet.fit(df_train, progress="widget")

df_train = svr_elasticnet.transform(df_train)
df_train.pred
```

**Comment by crimsonmote** [comment]
> Hi,
> 
> I tried to recreate a an example based on your description, and for me this works. Can you check on your end please?
> 
> Feel free to modify the example below to better match the data you have at your end.
> 
> ```
> import vaex
> import vaex.ml
> from vaex.ml.sklearn import Predictor, IncrementalPredictor
> from sklearn.linear_model import SGDRegressor
> import numpy as np
> 
> 
> size = 500_000
> data = {'x0': np.random.choice(a=range(100), size=size, replace=True),
>         'x1': np.random.choice(a=range(100), size=size, replace=True),
>         'x2': np.random.choice(a=range(100), size=size, replace=True),
>         'x3': np.random.choice(a=range(100), size=size, replace=True),
>         'x4': np.random.choice(a=range(100), size=size, replace=True),
>         'x5': np.random.choice(a=range(100), size=size, replace=True),
>         'x6': np.random.choice(a=range(100), size=size, replace=True),
>         'x8': np.random.choice(a=range(100), size=size, replace=True),
>         'x9': np.random.choice(a=range(100), size=size, replace=True),
>         'x10': np.random.choice(a=range(100), size=size, replace=True),
>         'x11': np.random.choice(a=range(100), size=size, replace=True),
>         'x12': np.random.choice(a=range(100), size=size, replace=True),
>         'x13': np.random.choice(a=range(100), size=size, replace=True),
>         'y': np.random.normal(size=size)
>         
>        }
> 
> df = vaex.from_dict(data)
> df_train, df_test = df.ml.train_test_split(verbose=False)
> 
> # Features to encode
> features = df_train.get_column_names(regex='x')
> target = 'y'
> 
> encoder = vaex.ml.OneHotEncoder(features=features)
> df_train = encoder.fit_transform(df_train)
> 
> # Features to train on
> features = df_train.column_names[9:]
> 
> # Train a model
> sgd=SGDRegressor(loss="epsilon_insensitive", penalty="elasticnet")
> svr_elasticnet = IncrementalPredictor(model=sgd, 
>                                    features=features, target=target, 
>                                    prediction_name='pred',
>                                    num_epochs=1,
>                                    batch_size=10_000, 
>                                    shuffle=True)
> svr_elasticnet.fit(df_train, progress="widget")
> 
> df_train = svr_elasticnet.transform(df_train)
> df_train.pred
> ```

Thank you for following up.
The above example works well.

As you said, I think it is most likely due to special characters or dots or "weird" column names. I'm still troubleshooting now, and will post updates.

**Comment by maartenbreddels** [comment]
I'm assuming this is solved, if you find the specific problem, please let us know. You can also see if the latest alpha solved it: https://pypi.org/project/vaex-core/4.0.0a2/

Thanks for the report!
