### ISSUE TITLE
[FEATURE-REQUEST] Does vaex support dropping duplicates records like pandas.

### ISSUE THREAD

**Issue by vijaybabupalli** [vaexio/vaex#954]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your request may already be discussed or addressed.

**Description**
Please provide a clear description of the functionality that you propose. A (pseudo)-code example showing the use-case, desired behaviour and API is a great way to communicate ideas.

**Is your feature request related to a problem? Please describe.**
Please describe the type of use-cases the proposed feature will address.

**Additional context**
Please state any supplementary information or provide additional context for the proposed functionality (e.g. workarounds, alternatives you have considered, etc..).

**Comment by vijaybabupalli** [comment]
Could you please help me with vaex alternative for df.drop_duplicates(subset ="col1")

**Comment by JovanVeljanoski** [comment]
Hi, 

Dropping duplicates is not yet implemented, but it is discussed in #746, where also an example is provided. Please use that thread for any further discussions so the content is all in once place.

Also: please search the issues before posting a new one - your problem may have already been discussed or solved. Also please use the template provided.

(Closing this as duplicate).

https://github.com/vaexio/vaex/issues/746
