### ISSUE TITLE
Does vaex support df.diff(). What is the alternative?

### ISSUE THREAD

**Issue by vijaybabupalli** [vaexio/vaex#955]
Thank you for reaching out and helping us improve Vaex!

Before you submit a new Issue, please read through the [documentation](https://docs.vaex.io/en/latest/). Also, make sure you search through the Open and Closed Issues - your request may already be discussed or addressed.

**Description**
Please provide a clear description of the functionality that you propose. A (pseudo)-code example showing the use-case, desired behaviour and API is a great way to communicate ideas.

**Is your feature request related to a problem? Please describe.**
Please describe the type of use-cases the proposed feature will address.

**Additional context**
Please state any supplementary information or provide additional context for the proposed functionality (e.g. workarounds, alternatives you have considered, etc..).

**Comment by vijaybabupalli** [comment]
Vaex alternative for df['col1'].diff()

**Comment by JovanVeljanoski** [comment]
Hi,

This is not implemented yet, but we hope to start working on it soon.

I will close this and open a proper feature request with explanations and examples (as the template requires) so that @maartenbreddels has a better idea of the implementation. 

Cheers.

**Comment by vijaybabupalli** [comment]
Thank you and vaex is amazing.

Regards,
Vijay Palli.

**Comment by pjgao** [comment]
is any updates about 'diff' feature? or any way can do this now?

**Comment by LuchiLucs** [comment]
What is the alternative at the moment? Convert the dataframe to Pandas/Dask?

**Comment by JovanVeljanoski** [comment]
`diff` is now available as a dataframe method. So you can use it like

`df.diff(periods=2, column='x')`

Please open a separate issue (hopefully with a reproducible example) if you encounter any problems or have feedback. Thanks!
