### ISSUE TITLE
[BUG-REPORT] Concat into an empty vaex dataframe gives error

### ISSUE THREAD

**Issue by chitochat** [vaexio/vaex#964]
Hello:

**Description**
concat api issue

When I try to concat into an empty dataframe, I get an error message.

emtpy_vx = empty_vx.concat(temporary_vx)

The data frames were created from panda dataframes.

Confirmation that dataframe is emtpy:
Empty DataFrame
Columns: [material_made, material_used, material_made_forecasted_sales_current_month, traversal_ind]
Index: []

**Software information**
Running on OS: Windows 10
IDE: PyCharm 2019.3.2
vaex: 3.0.0
Python: 3.8.5
Installed via conda

**Additional information**
I have a workaround by making the first entry to dataframe via assignment and then use concat going forward.
empty_vx = temporary_vx

Thanks a lot!
Abhi

**Comment by JovanVeljanoski** [comment]
Hi,

Vaex is not (yet) officially supported for Python 3.8.x on Windows. Please try using python 3.7.x if possible.

It is possible that this is a bug nonetheless. Can you maybe give me a small reproducible example so I can test it out locally?

Cheers.

**Comment by chitochat** [comment]
I´m sorry Jovan,

correction:
Python: 3.7

To reproduce it, please use the code below:
# initiatize the df
findings_df = pd.DataFrame(pairs_df.iloc[[0]])
# empty the df
findings_df = findings_df[0:0]
# convert to vaex
findings_vx = vx.from_pandas(findings_df)
# load data into emtpy dataframe
findings_vx = findings_vx.concat(pairs_vx_forecast_filter)

above statement drives the error.

**Comment by JovanVeljanoski** [comment]
I meant can you give me a reproducible example, something that I can copy paste and run locally. 
Can be with fake data, just to expose the problem you are having.

Thanks

**Comment by chitochat** [comment]
Here is an example:

import vaex
import pandas as pd
df = pd.DataFrame([[1, 2], [3, 4]], columns=list('AB'))
df_empty = pd.DataFrame(df.iloc[[0]])
df_empty = df_empty[0:0]

df_empty_vx = vaex.from_pandas(df_empty)
df_vx = vaex.from_pandas(df)

df_empty_vx = df_empty_vx.concat(df)

**Comment by JovanVeljanoski** [comment]
Hi, 

Thanks for that!
You have a small bug, maybe type, so I fixed that in your post (last line).

While this for sure look like a bug.. not sure if it is. I think maybe this is an abuse of a vaex dataframe :)
(maybe @maartenbreddels can check it out and disagree here)

I guess you are trying to build up vaex dataframe here somehow? This should be a separate process. 
Perhaps work with pandas until you reach the relevant size of your dataframe, then pass it to vaex if you want to get the benefit of speed and so on.

Remember, the current philosophy of vaex is that data is immutable, and lives on disk. 

But I would be curious to learn of your usecase. If you are dealing with streaming data (or batch jobs), we can solve it another way.

**Comment by chitochat** [comment]
Thanks Jovan,

Quite likely I am not using it correctly, but here is the broad approach:

1. Using pandas to get data from DB via SQL into a dataframe. There are two large datasets that are being brought into two dataframes.
2. I need to perform a large genealogy chain build using pairs, pandas was too slow for the data size, hence trying vaex.
3. Need an empty dataframe to start building the genealogy chain into it.

Hope this helps evaluate it better.
