### ISSUE TITLE
get a list from column of type datetime64[ns] of vaex dataframe don't working correct

### ISSUE THREAD

**Issue by salwaen** [vaexio/vaex#978]
Hi,

I want a list from column of type datatime64[ns]
````
date = np.array(['2009-10-12T03:31:00', '2016-02-11T10:17:34', '2015-11-12T11:34:22'], dtype='datetime64[ns]')
df = vaex.from_arrays(date=date)
print(df.date.tolist())

````
Output

````
[1255318260000000000, 1455185854000000000, 1447328062000000000]

````
is it a bug? 
thanks for all your support

**Comment by maartenbreddels** [comment]
Hi Salwaen,

it seems like numpy behaviour, `date.tolist()` does the same. It's the int64 backing the date.

cheers,

Maarten

**Comment by salwaen** [comment]
Thanks for the response @maartenbreddels .
actually i used panda to convert int64 to datetime
````
pd.to_datetime(df.date.tolist())

````

Regards
