### ISSUE TITLE
vaex install issues on Mac laptop. Install is not seamless.

### ISSUE THREAD

**Issue by gauravdhiman** [vaexio/vaex#981]
I faced few challenges while installing Vaex 3.0.0 on my office Mac laptop in enterprise setup. I would like to highlight the same here so that vaex installation can be seamless at least on Mac.

1. On local Mac, when vaex is installed without xcode command line tools, few dependent packages does not compile. In my case, three packages could not compile when I don't have command line tools - vaex-core and two others.

2. After installing xcode command line tools, the two packages got compiled (wheel built) but `vaex-core` throws an error at https://github.com/vaexio/vaex/blob/master/packages/vaex-core/src/strings.cpp#L28. It could not find the required `pcrecpp.h` file. Error says:
```
src/strings.cpp:28:10: fatal error: 'prcecpp.h' file non found
#include <pcrecpp.h>
1 error generated.
error: command 'clang'  failed with exit status 1
----------------------------------------------
``` 

3. When tried to install using Jenkins on Linux servers, I got the issue while building `vaex-core`. In this case, while installing `vaex-core`, it first tries to download dependent packages and fails to download numpy from pypi public repo. Jenkin server in most of the enterprises won't have direct access to public repos on internet, they are exposed to repos maintained in enterprise. I think, there should be some mechanism to download dependent packages from other repos (non-pulic repos). Here is some info on how to build with dependencies from non-public repos: https://setuptools.readthedocs.io/en/latest/setuptools.html#dependencies-that-aren-t-in-pypi. It will be good to make vaex build with any repo.

**Comment by JovanVeljanoski** [comment]
Hi, 

Just to make this clear - in this issue you are talking about installing from source, is that right?

The recommended installation process for users is via pip/conda. 

Regarding installation instructions for developers/contributors, did you check out the [instructions](https://docs.vaex.io/en/latest/installing.html#for-developers)?

**Comment by maartenbreddels** [comment]
Hi,

in case you are not installing from source:

> 1. On local Mac, when vaex is installed without xcode command line tools, few dependent packages does not compile. In my case, three packages could not compile when I don't have command line tools - vaex-core and two others.

Yeah, very frustrating, but out of our control. I really recommend using anaconda or miniconda to avoid those issues. 

You may also be missing out the binary wheel if you have an old pip, try upgrading pip (`pip install -U pip`). Otherwise you need to install pcre dev libraries, or get it from conda-forge if you want to install from source.




> 2\. After installing xcode command line tools, the two packages got compiled (wheel built) but `vaex-core` throws an error at https://github.com/vaexio/vaex/blob/master/packages/vaex-core/src/strings.cpp#L28. It could not find the required `pcrecpp.h` file. Error says:

You've need to install pcrecpp dev, if you use brew, you can try:
https://formulae.brew.sh/formula/pcre++#default

But again, make sure you have a modern pip, or use conda.



> 3. When tried to install using Jenkins on Linux servers, I got the issue while building `vaex-core`. In this case, while installing `vaex-core`, it first tries to download dependent packages and fails to download numpy from pypi public repo. Jenkin server in most of the enterprises won't have direct access to public repos on internet, they are exposed to repos maintained in enterprise. I think, there should be some mechanism to download dependent packages from other repos (non-pulic repos).

It's not a vaex problem, but we can provide some hints. You can create a full conda environment, and package that up using:
https://github.com/conda/conda-pack

Let us know which solution worked for you, that would be useful feedback.

Regards,

Maarten

**Comment by gauravdhiman** [comment]
> Hi,
> 
> in case you are not installing from source:
> 
> > 1. On local Mac, when vaex is installed without xcode command line tools, few dependent packages does not compile. In my case, three packages could not compile when I don't have command line tools - vaex-core and two others.
> 
> Yeah, very frustrating, but out of our control. I really recommend using anaconda or miniconda to avoid those issues.
> 
> You may also be missing out the binary wheel if you have an old pip, try upgrading pip (`pip install -U pip`). Otherwise you need to install pcre dev libraries, or get it from conda-forge if you want to install from source.

Surely I will try this on local Mac, it may work, but this still wont be a solution for conda-forge production-able build on Jenkins.

> 
> > 2. After installing xcode command line tools, the two packages got compiled (wheel built) but `vaex-core` throws an error at https://github.com/vaexio/vaex/blob/master/packages/vaex-core/src/strings.cpp#L28. It could not find the required `pcrecpp.h` file. Error says:
> 
> You've need to install pcrecpp dev, if you use brew, you can try:
> https://formulae.brew.sh/formula/pcre++#default
> 
> But again, make sure you have a modern pip, or use conda.
> 
> > 1. When tried to install using Jenkins on Linux servers, I got the issue while building `vaex-core`. In this case, while installing `vaex-core`, it first tries to download dependent packages and fails to download numpy from pypi public repo. Jenkin server in most of the enterprises won't have direct access to public repos on internet, they are exposed to repos maintained in enterprise. I think, there should be some mechanism to download dependent packages from other repos (non-pulic repos).
> 
> It's not a vaex problem, but we can provide some hints. You can create a full conda environment, and package that up using:
> https://github.com/conda/conda-pack

We are not using `conda`, but using `venv` for environment setup and within `venv` when we try to install `vaex` using `pip install vaex`, it fails with errors I gave. Updating pip on Jenkins server is not a possible solution as those servers are enterprise server where app teams do not normally have control to make changes.

We would like to try `vaex` for our big-data processing usecase, but all these hurdles to just install and build is a big blocker to use `vaex` in our existing enterprise setup.

Can you make installation of dependent packages possible from non-public repos. That may help. If you are open to this idea, I can raise a PR for the same: https://setuptools.readthedocs.io/en/latest/setuptools.html#dependencies-that-aren-t-in-pypi

> 
> Let us know which solution worked for you, that would be useful feedback.
> 
> Regards,
> 
> Maarten

**Comment by maartenbreddels** [comment]
Ok, so problem 1 and 2 are potentially solved, that leaves us with problem 3 right?

I don't think you have a problem with vaex, but a Python/pip problem, would you agree? Not that I'm not willing to help, but just to confirm we're on the same page. There is nothing special about vaex compared to other Python packages that I am aware of.

I see two solutions:
 * Prepackage the virtual environment, but for venv https://pypi.org/project/venv-pack/
 * Make sure that all dependencies of vaex are available from your private pypi server, or pre-installed in a different way.

A final recommendation I can give is not to install the `vaex` metapackage (with all batteries included), but limit yourself to vaex-core and vaex-hdf5 first, to cut down on the number of dependencies.

**Comment by JovanVeljanoski** [comment]
Will close this as stale - please re-open if needed.

**Comment by MaiHoangViet1809** [comment]
Guy, I meet the same issue, it look like some typo when pip install package:
`g++ -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -g -L/opt/homebrew/Cellar/unixodbc/2.3.11/lib -I/opt/homebrew/Cellar/unixodbc/2.3.11/include build/temp.macosx-11-universal2-cpython-38/src/string_utils.o build/temp.macosx-11-universal2-cpython-38/src/strings.o -L/Users/****/Projects/****/.venv3.8/lib -L/Users/****/Projects/****/.venv3.8/Library/lib -Lvendor/pcre/Library/lib -lpcre -lpcrecpp -o build/lib.macosx-11-universal2-cpython-38/vaex/superstrings.cpython-38-darwin.so
      ld: warning: directory not found for option '-L/Users/****/Projects/****/.venv3.8/Library/lib'
      ld: warning: directory not found for option '-Lvendor/pcre/Library/lib'
      ld: library not found for -lpcrecpp
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      error: command '/usr/bin/g++' failed with exit code 1
      [end of output]
`
someone forgot to include space between argument and value... or perhaps I'm wrong about syntax ?
 example:
 "-L/opt/homebrew[...]" should be "-L /opt/homebrew[...]" right ?
 
 I'm using Mac M1.

**Comment by js-ojus** [comment]
After losing my morning to this issue, I have resolved this on my **Intel Mac** by **downgrading to Python 3.8** from Python 3.10.

Just for posterity!

**Comment by JovanVeljanoski** [comment]
Indeed - python 3.10 is not supported. Currently 3.6 - 3.9 are supported.
