### ISSUE TITLE
Can't convert to Pandas DataFrame after applying a state with model predictions

### ISSUE THREAD

**Issue by ntoxeg** [vaexio/vaex#987]
**Description**
I tried to apply a trained XGBoost model, wrapped in `vaex.ml.sklearn.Predictor`.
As per the tutorial, I used `model.transform` followed by `state_get` and `state_set`.

There are two problems:
- When looking into a view that shows a subset of the test data there is `RecursionError: maximum recursion depth exceeded while calling a Python object` - you can still inspect the data though.
- When trying to get the Pandas representation (`to_pandas_df`) I get the same error for the view and for the whole data frame `NameError: name 'random_index' is not defined` - the `random_index` column is present in the Vaex frame and full of "error" values.

The training data frame can still be successfully converted.

**Software information**
 - Vaex version:
```
{'vaex-core': '2.0.3',
 'vaex-viz': '0.4.0',
 'vaex-hdf5': '0.6.0',
 'vaex-jupyter': '0.5.2',
 'vaex-ml': '0.10.0',
 'vaex-arrow': '0.5.1'}
```
 - Vaex was installed via: conga-forge
 - OS: Ubuntu 18.04

**Comment by JovanVeljanoski** [comment]
Hey!

Thanks you for reaching out. 

I have seen this problem before (first bullet point), not sure why exactly it happens. I'm afraid you will have to narrow it down a bit more. Here are some ideas on how to do this:
- for the column you are getting the error values - please check the definition of it, also if any other method or transformation is using it or modifying it in some way. Some treatment of this `random_index` column is likely causing the problem. Does this column exist in the training data? 

- check if you are overwriting columns/expressions somewhere in your script / notebook. I have experienced this myself whenever I achieved a "circular" expression (the new definition is leading into another one, and that goes forever until it breaks). 

-  I remember us fixing issue such as you describe.. not sure if it was part of the release you are using, or will be part of the upcoming release (@maartenbreddels do you remember this?).

Also, the problem in the 2nd bullet point is a direct consequence of the 1st point. 

I hope this helps a bit,
J.

**Comment by ntoxeg** [comment]
Ah, there is indeed that `random_index` present in the data - it actually stems from exporting the training data with `shuffle=True`. The test data is not exported like that, maybe that's the problem, do I have to shuffle the test set too?

Also I am not clear on how `random_index` is used - it seems that to get data in random order you have to use it as the index, I assume Vaex `Predictor`s do that automatically?

**Comment by JovanVeljanoski** [comment]
Hi, 

The `random_index` column is an artefact of the shuffling. It can be used to go back to the original order of the rows if that is needed, but it is a bit complicated (an artefact of a different age..). Once the data is exported with shuffle=True, the data is already shuffled.

I guess the problem happens because you are likely using random_index as an input feature to the model, you are using a column that does not exist in the test set, and no way to re-create it. 

I would suggest to not use random_index in your modelling and things should work.

The Predictor does not do much for the modelling: it materializes the data and feeds it into the model scikit-learn style. However, it does handle the serialization part (to make the models part of the state) and making them into transformers.

Let me know how it does!

**Comment by ntoxeg** [comment]
It seems that shuffling the test set helped - I don't use `random_index` in any way, I guess I will have to drop it from the frame.

I guess transferring state from one frame to another requires all columns that are present a priori in the former to be present in the latter.

**Comment by JovanVeljanoski** [comment]
It requires that all columns used in the training set be present in the test set.

the state is a dictionary, you can inspect it before applying to the test set.

**Comment by ntoxeg** [comment]
Well, that solves the issue for me - `random_index` which was added by shuffling is to be dropped.
