### ISSUE TITLE
Vaex taking very long time to read arrow/hdf5 files

### ISSUE THREAD

**Issue by revathik1991** [vaexio/vaex#990]
I am trying to read 40GB hdf5/arrow file through vaex which takes 4 minutes for the reading.  I have 14 columns which  are all numeric.
How to reduce this to seconds?
Is this a normal behavior with Vaex?

**Comment by maartenbreddels** [comment]
Hi,

this depends on your machine, this seems like it is reading at 166mb/s. I guess you have a spinner harddrive. Is that the case?

cheers,

Maarten
