### ISSUE TITLE
Apply Simple Transformations on Filtered/Selected Data

### ISSUE THREAD

**Issue by kmcentush** [vaexio/vaex#991]
**Description**
I would like the ability to apply simple operations to filtered column. Ex:

```
data = vx.from_arrays(val=np.array([0, 1, 1, 0, 1]))
to_transform = data['val'] == 1

# ex: multiplication
data[valid, field] *= 0.5
# result should be:
#   x
# 0
# 0.5
# 0.5
# 0
# 0.5

# ex: addition
data[valid, field] += 0.5
# result should be:
#   x
# 0
# 1.5
# 1.5
# 0
# 1.5
```

**Is your feature request related to a problem? Please describe.**
I only need to transform a select number of rows in the dataframe, so I've been using a filter to apply the selection. I've been getting "TypeError: unhashable type: 'Expression'" whenever I try the above.

**Comment by JovanVeljanoski** [comment]
Hi, 

You can do this with the `where` function, just like you would do in numpy. Here is an example:

```
import vaex
df = vaex.from_arrays(x=np.array([0, 1, 1, 0, 1]))
df['new_x'] = df.func.where(df.x==1, 1.5, df.x)
print(df)
  #    x    new_x
  0    0      0
  1    1      1.5
  2    1      1.5
  3    0      0
  4    1      1.5
```

you don't over-write the same column, since vaex does not make memory copies, the new column would be virtual in any case (whether you overwrite or not). 

I hope this helps!

**Comment by kmcentush** [comment]
Hi @JovanVeljanoski,

Thanks for your reply. I was able to adapt your code to not only set static values, but actually apply the transformation in a more convenient way:

```
import vaex
df = vaex.from_arrays(x=np.array([0, 1, 2, 0, 1]))
df['new_x'] = df.func.where(df.x!=0, df.x * 1.5, df.x)
print(df)
  #    x    new_x
  0    0      0
  1    1      1.5
  2    2      3
  3    0      0
  4    1      1.5
```
