### ISSUE TITLE
Issue with opening a parquet file from GCS

### ISSUE THREAD

**Issue by laniakea** [vaexio/vaex#992]
Here is what I get trying to use vaex:
`OSError                                   Traceback (most recent call last)
<ipython-input-5-ee9b32d56a12> in <module> ----> 9 df = vaex.open('gs://path_to.parquet')

/opt/conda/lib/python3.8/site-packages/vaex/__init__.py in open(path, convert, shuffle, copy_index, *args, **kwargs)
    180             ds = None
    181             if len(filenames) == 0:
--> 182                 raise IOError('Could not open file: {}, it does not exist'.format(path))
    183             filename_hdf5 = _convert_name(filenames, shuffle=shuffle)
    184             filename_hdf5_noshuffle = _convert_name(filenames, shuffle=False)

OSError: Could not open file: gs://path_to.parquet, it does not exist`

I have also tried to add the token in the following formats:`
df = vaex.open('gs://path_to.parquet?token="/path_to_credentials.json"')
df = vaex.open('gs://path_to.parquet?token=/path_to_credentials.json')
df = vaex.open('gs://path_to.parquet', token='/path_to_credentials.json')
` 
I get the same error

**Comment by maartenbreddels** [comment]
Hi  Abdolreza,

This is not supported yet. Only hdf5 via s3/gs is supported. But the next version (version 4) is likely to have support for this.

Regards,

Maarten

**Comment by maartenbreddels** [comment]
Note that I'm just work on this *now*, https://github.com/vaexio/vaex/pull/993/

**Comment by laniakea** [comment]
I assume VAEX only is capable of reading parquet files locally then as in the documentation there is an example that opens a parquet file locally.

Thanks for your clarification.

**Comment by maartenbreddels** [comment]
This is now supported, and released, to install:
```
$ pip install "vaex-core>=4.0.0a11"
# or for the while kitchsink:
$ pip install "vaex>=4.0.0a6"
```
