### ISSUE TITLE
Error Converting String/Object Column to String During Concatenation

### ISSUE THREAD

**Issue by kmcentush** [vaexio/vaex#998]
**Description**
In trying to create a single column that is the concatenation of many, I found this weird bug that occurs whenever a column that is a "string" type or "object" type tries to be converted to a "string" type mid-concatenation. The root of the issue is here:
```
File "C:\Users\Imprint\Miniconda3\envs\dev\lib\site-packages\vaex\functions.py", line 2175, in _astype
    mask = np.isnan(x)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

It appears that the `_astype()` function will try to remove NaNs prior to converting to string. However, this fails because numpy's native `np.isnan()` does not support these objects (I'm still not sure if the object it's seeing is of type "object", "string", or even a Vaex Expression). The solution would be to have an if statement that applies this normal route if the incoming data is numeric, and another route (TBD) if it's not.

**Software information**
 - Vaex version (`import vaex; vaex.__version__)`: {'vaex': '3.0.0', 'vaex-core': '2.0.3', 'vaex-viz': '0.4.0', 'vaex-hdf5': '0.6.0', 'vaex-server': '0.3.1', 'vaex-astro': '0.7.0', 'vaex-jupyter': '0.5.2', 'vaex-ml': '0.9.0', 'vaex-arrow': '0.5.1'}
 - Vaex was installed via: pip
 - OS: Windows 10

**Additional information**
I attached a notebook that has a few example snippets: [vaex_bug.zip](https://github.com/vaexio/vaex/files/5322644/vaex_bug.zip). The traceback is pretty long, but here are the same examples w/o any output shown.

```
import numpy as np
import vaex as vx
```
```
# Works
dt = vx.from_arrays(a=[1, 2, 3, 4], b=[5, 6, 7, 8])
print(dt.dtypes)
dt['join_col'] = dt['a'].astype(str)
dt['join_col'] = dt['join_col'] + '|' + dt['b'].astype(str)

dt
```
```
# Doesn't Work
dt = vx.from_arrays(a=[1, 2, 3, 4], b=['5', '6', '7', '8'])
print(dt.dtypes)
dt['join_col'] = dt['a'].astype(str)
dt['join_col'] = dt['join_col'] + '|' + dt['b'].astype(str)

dt
```

```
# Doesn't Work
dt = vx.from_arrays(a=[1, 2, 3, 4], b=['5', '6', '7', '8'])
dt['b'] = dt['b'].astype('O')
print(dt.dtypes)
dt['join_col'] = dt['a'].astype(str)
dt['join_col'] = dt['join_col'] + '|' + dt['b'].astype(str)

dt
```

**Comment by JovanVeljanoski** [comment]
Hi @kmcentush 

Thanks for reaching out. I was unable to reproduce the issues you are describing, and your notebook run without any problems on my end. I checked this with the current master however. We have been working hard on the next release, so it is possible that the problems you are describing are solved (next release is expected to happen quite soon). 

I also tried this example that worked without any problems:
```
a = np.array([1, np.nan, '3', None])
df = vaex.from_arrays(a=a, b=['5', '6', '7', '8'])
print(df.dtypes)
df['join_col'] = df['a'].astype(str)
df['join_col'] = df['join_col'] + '|' + df['b'].astype(str)

df
```

You can try installing the alpha perhaps, see if this issue goes away `pip install vaex-core=4.0.0a3`. The next stable release should be out soon.

Some pointers:
 - As time goes on vaex is quite likely to move away from dtype object. We primarily have this for pandas compatibility. But it is introducing all kinds of performance and other penalties. The issue you are describing does sound familiar and some version of it I have experienced in the past (although can't reproduce now). Our general advice is that, to get top performance of vaex, the data should be of a single primitive type, kind of like a database in a sense. One can use other tools to iteratively go over the data and decide what the common type should be. Vaex will try to smartly convert a dtype object to a common type if possible, but if nothing works, the data will be cast to string. 

- please use `import vaex`. It is not such a long name to be abbreviated, and it does not pop up that often in the code anyway, unlike `numpy` for example. 


I hope this helps.

**Comment by kmcentush** [comment]
Hi @JovanVeljanoski,

Looks like upgrading to core v4 fixed the issue (I just have to ignore all of the warnings for incompatibilities with the other vaex libraries). Looking forward to that v4 release!

I think enforcing a single primitive type on columns would be great, as long as they're nullable.

**Comment by JovanVeljanoski** [comment]
Hi again, 

Yeah, all column type are indeed nullable (and will continue to be like that!)

Cheers!
